### ISSUE TITLE
Design Specs List

### ISSUE THREAD

**Issue by Mec-iS** [bigchaindb/bigchaindb#1]
It would be great to have a file in which design principles and specifications are listed. Just to understand the basic assumptions on which the project is built.
For example: 
- How is it supposed querying to be implemented?
- about [transaction-validation](https://github.com/BigchainDB/bigchaindb/blob/develop/docs/source/transaction-validation.md): Do you want to use the blockchain design to leverage the distributed content or to let multiple owners of data to share/modify it safely? Basically, is it meant to be a p2p service among clients or a p2p among servers beyond a service?
- It is not clearly stated anywhere: the idea is to represent a blockchain using a JSON/NoSql storage/datastore?

I can be helpful with wiki and documentation.

Great idea guys!

**Comment by r-marques** [comment]
Thanks for the interest @Mec-iS 

We are currently finalizing everything and by the end of the day we will have the code, contributing guidelines, better documentation and a withepaper online to better explain what we are trying to achieve.

After that any comments, suggestions, contributions will be highly appreciated.

cheers
