### ISSUE TITLE
Figure out how to interoperate with IPFS

### ISSUE THREAD

**Issue by ttmc** [bigchaindb/bigchaindb#100]
It would be nice for BigchainDB to interoperate with [IPFS](http://ipfs.io/) by @jbenet et al.

For example, it would be great if we both use the same standard way of referencing "objects" in the world (e.g. files or BigchainDB transactions).

IPFS references objects using [IPLD](https://github.com/ipfs/specs/blob/master/merkledag/ipld.md) (including [multihash](https://github.com/jbenet/multihash) for all hashes).

We could start by changing our hashes (which currently _assume_ sha3-256 always) to multihash.

There are probably other things we could do as well. It would be great to iterate with @jbenet on this.

**Comment by TimDaub** [comment]
Linking this with ipfs/notes#133

**Comment by TimDaub** [comment]
@ttmc I'll close this ticket in favor of #485.

> Figure out how to interoperate with IPFS

The answer is IPLD.
