### ISSUE TITLE
Avoid the need to hardcode table names

### ISSUE THREAD

**Issue by sbellem** [bigchaindb/bigchaindb#1004]
We currently hardcode the "three standard" table names in various places in the code.

These table names could be set as constants in a relevant place.

One important question:

- [x] Are the table names going to be the same no matter what the underlying database engine is?

**Comment by r-marques** [comment]
Yes to your question. I see no reason why it shouldn't be

**Comment by sbellem** [comment]
> Yes to your question. I see no reason why it shouldn't be

thanks!
