### ISSUE TITLE
Document required header ffi.h

### ISSUE THREAD

**Issue by sbellem** [bigchaindb/bigchaindb#1007]
see https://gitter.im/bigchaindb/bigchaindb?at=58619101e7bdfe4e299ec663

**Comment by Shalsh23** [comment]
Trying to install bigchaindb on redhat os 6.8, and I am getting the following error in the final step of install: 

`<Command "/usr/bin/python3.4 -u -c "import setuptools, tokenize;file='/tmp/pip-build-vzw9fsht/PyNaCl/setup.py';f=getattr(tokenize, 'open', open)(file);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, file, 'exec'))" install --record /tmp/pip-ilkp37tx-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-vzw9fsht/PyNaCl/ >`

Following the instructions of: https://linuxctl.com/bigchaindb-on-centos-7-2/

**Comment by Shalsh23** [comment]
Detailed error logs:

`**[root@coul openssl-1.0.1s]$ CFLAGS='-I /opt/openssl-1.0.1s/src/include' LDFLAGS='-L /opt/openssl-1.0.1s/build/lib -Wl, -rpath=/opt/openssl-1.0.1s/build/lib' pip --no-cache-dir install bigchaindb**
Collecting bigchaindb
  Downloading BigchainDB-0.8.0.tar.gz (46kB)
    100% |████████████████████████████████| 51kB 615kB/s
Requirement already satisfied: rethinkdb~=2.3 in /usr/lib/python3.4/site-packages (from bigchaindb)
Requirement already satisfied: pysha3>=0.3 in /usr/lib64/python3.4/site-packages (from bigchaindb)
Collecting cryptoconditions>=0.5.0 (from bigchaindb)
  Downloading cryptoconditions-0.5.1.tar.gz
Collecting statsd>=3.2.1 (from bigchaindb)
  Downloading statsd-3.2.1-py2.py3-none-any.whl
Collecting python-rapidjson>=0.0.6 (from bigchaindb)
  Downloading python-rapidjson-0.0.8.tar.gz (124kB)
    100% |████████████████████████████████| 133kB 2.3MB/s
Collecting logstats>=0.2.1 (from bigchaindb)
  Downloading logstats-0.2.1.tar.gz
Collecting flask>=0.10.1 (from bigchaindb)
  Downloading Flask-0.12-py2.py3-none-any.whl (82kB)
    100% |████████████████████████████████| 92kB 3.8MB/s
Collecting flask-restful~=0.3.0 (from bigchaindb)
  Downloading Flask_RESTful-0.3.5-py2.py3-none-any.whl
Collecting requests~=2.9 (from bigchaindb)
  Downloading requests-2.12.4-py2.py3-none-any.whl (576kB)
    100% |████████████████████████████████| 583kB 4.2MB/s
Collecting gunicorn~=19.0 (from bigchaindb)
  Downloading gunicorn-19.6.0-py2.py3-none-any.whl (114kB)
    100% |████████████████████████████████| 122kB 5.1MB/s
Collecting multipipes~=0.1.0 (from bigchaindb)
  Downloading multipipes-0.1.0.tar.gz
Collecting jsonschema~=2.5.1 (from bigchaindb)
  Downloading jsonschema-2.5.1-py2.py3-none-any.whl
Collecting pyyaml~=3.12 (from bigchaindb)
  Downloading PyYAML-3.12.tar.gz (253kB)
    100% |████████████████████████████████| 256kB 4.4MB/s
Requirement already satisfied: base58~=0.2.2 in /usr/lib/python3.4/site-packages (from cryptoconditions>=0.5.0->bigchaindb)
Collecting PyNaCl~=1.0.1 (from cryptoconditions>=0.5.0->bigchaindb)
  Downloading PyNaCl-1.0.1.tar.gz (2.7MB)
    100% |████████████████████████████████| 2.7MB 8.1MB/s
Collecting Werkzeug>=0.7 (from flask>=0.10.1->bigchaindb)
  Downloading Werkzeug-0.11.14-py2.py3-none-any.whl (307kB)
    100% |████████████████████████████████| 317kB 6.3MB/s
Collecting Jinja2>=2.4 (from flask>=0.10.1->bigchaindb)
  Downloading Jinja2-2.8.1-py2.py3-none-any.whl (264kB)
    100% |████████████████████████████████| 266kB 9.1MB/s
Collecting click>=2.0 (from flask>=0.10.1->bigchaindb)
  Downloading click-6.6-py2.py3-none-any.whl (71kB)
    100% |████████████████████████████████| 71kB 14.6MB/s
Collecting itsdangerous>=0.21 (from flask>=0.10.1->bigchaindb)
  Downloading itsdangerous-0.24.tar.gz (46kB)
    100% |████████████████████████████████| 51kB 14.2MB/s
Requirement already satisfied: six>=1.3.0 in /usr/lib/python3.4/site-packages (from flask-restful~=0.3.0->bigchaindb)
Collecting pytz (from flask-restful~=0.3.0->bigchaindb)
  Downloading pytz-2016.10-py2.py3-none-any.whl (483kB)
    100% |████████████████████████████████| 491kB 9.8MB/s
Collecting aniso8601>=0.82 (from flask-restful~=0.3.0->bigchaindb)
  Downloading aniso8601-1.2.0.tar.gz (59kB)
    100% |████████████████████████████████| 61kB 21.2MB/s
Requirement already satisfied: cffi>=1.1.0 in /usr/lib64/python3.4/site-packages (from PyNaCl~=1.0.1->cryptoconditions>=0.5.0->bigchaindb)
Collecting MarkupSafe (from Jinja2>=2.4->flask>=0.10.1->bigchaindb)
  Downloading MarkupSafe-0.23.tar.gz
Collecting python-dateutil (from aniso8601>=0.82->flask-restful~=0.3.0->bigchaindb)
  Downloading python_dateutil-2.6.0-py2.py3-none-any.whl (194kB)
    100% |████████████████████████████████| 194kB 9.4MB/s
Requirement already satisfied: pycparser in /usr/lib/python3.4/site-packages (from cffi>=1.1.0->PyNaCl~=1.0.1->cryptoconditions>=0.5.0->bigchaindb)
Installing collected packages: PyNaCl, cryptoconditions, statsd, python-rapidjson, logstats, Werkzeug, MarkupSafe, Jinja2, click, itsdangerous, flask, pytz, python-dateutil, aniso8601, flask-restful, requests, gunicorn, multipipes, jsonschema, pyyaml, bigchaindb
  Running setup.py install for PyNaCl ... error
    Complete output from command /usr/bin/python3.4 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-oi9wb0oh/PyNaCl/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-w845fz_r-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.4
    creating build/lib.linux-x86_64-3.4/nacl
    copying src/nacl/public.py -> build/lib.linux-x86_64-3.4/nacl
    copying src/nacl/encoding.py -> build/lib.linux-x86_64-3.4/nacl
    copying src/nacl/utils.py -> build/lib.linux-x86_64-3.4/nacl
    copying src/nacl/signing.py -> build/lib.linux-x86_64-3.4/nacl
    copying src/nacl/hash.py -> build/lib.linux-x86_64-3.4/nacl
    copying src/nacl/exceptions.py -> build/lib.linux-x86_64-3.4/nacl
    copying src/nacl/__init__.py -> build/lib.linux-x86_64-3.4/nacl
    copying src/nacl/secret.py -> build/lib.linux-x86_64-3.4/nacl
    creating build/lib.linux-x86_64-3.4/nacl/bindings
    copying src/nacl/bindings/sodium_core.py -> build/lib.linux-x86_64-3.4/nacl/bindings
    copying src/nacl/bindings/crypto_sign.py -> build/lib.linux-x86_64-3.4/nacl/bindings
    copying src/nacl/bindings/crypto_scalarmult.py -> build/lib.linux-x86_64-3.4/nacl/bindings
    copying src/nacl/bindings/randombytes.py -> build/lib.linux-x86_64-3.4/nacl/bindings
    copying src/nacl/bindings/crypto_secretbox.py -> build/lib.linux-x86_64-3.4/nacl/bindings
    copying src/nacl/bindings/crypto_box.py -> build/lib.linux-x86_64-3.4/nacl/bindings
    copying src/nacl/bindings/__init__.py -> build/lib.linux-x86_64-3.4/nacl/bindings
    copying src/nacl/bindings/crypto_hash.py -> build/lib.linux-x86_64-3.4/nacl/bindings
    running build_clib
    checking build system type... x86_64-unknown-linux-gnu
    checking host system type... x86_64-unknown-linux-gnu
    checking for a BSD-compatible install... /usr/bin/install -c
    checking whether build environment is sane... yes
    checking for a thread-safe mkdir -p... /bin/mkdir -p
    checking for gawk... gawk
    checking whether make sets $(MAKE)... yes
    checking whether make supports nested variables... yes
    checking whether UID '0' is supported by ustar format... yes
    checking whether GID '0' is supported by ustar format... yes
    checking how to create a ustar tar archive... gnutar
    checking whether make supports nested variables... (cached) yes
    checking whether to enable maintainer-specific portions of Makefiles... no
    checking for style of include used by make... GNU
    checking for gcc... gcc
    checking whether the C compiler works... no
    configure: error: in `/tmp/pip-build-oi9wb0oh/PyNaCl/build/temp.linux-x86_64-3.4':
    configure: error: C compiler cannot create executables
    See `config.log' for more details
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-oi9wb0oh/PyNaCl/setup.py", line 259, in <module>
        "Programming Language :: Python :: 3.5",
      File "/usr/lib64/python3.4/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib64/python3.4/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/lib64/python3.4/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/lib/python3.4/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/lib64/python3.4/distutils/command/install.py", line 539, in run
        self.run_command('build')
      File "/usr/lib64/python3.4/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib64/python3.4/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/lib64/python3.4/distutils/command/build.py", line 126, in run
        self.run_command(cmd_name)
      File "/usr/lib64/python3.4/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib64/python3.4/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/tmp/pip-build-oi9wb0oh/PyNaCl/setup.py", line 186, in run
        cwd=build_temp,
      File "/usr/lib64/python3.4/subprocess.py", line 558, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['/tmp/pip-build-oi9wb0oh/PyNaCl/src/libsodium/configure', '--disable-shared', '--enable-static', '--disable-debug', '--disable-dependency-tracking', '--with-pic', '--prefix', '/tmp/pip-build-oi9wb0oh/PyNaCl/build/temp.linux-x86_64-3.4']' returned non-zero exit status 77
   
    ----------------------------------------
Command "/usr/bin/python3.4 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-oi9wb0oh/PyNaCl/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-w845fz_r-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-oi9wb0oh/PyNaCl/
[root@coul openssl-1.0.1s]$`

**Comment by Shalsh23** [comment]
Update: This error got solved by installing libsodium

**Comment by r-marques** [comment]
The documentation already explains what type of os level dependencies need to be installed for both ubuntu and fedora (should also work with centoOS and redhat) https://docs.bigchaindb.com/projects/server/en/latest/appendices/install-os-level-deps.html

can we close this?
