### ISSUE TITLE
Problem with installation docs

### ISSUE THREAD

**Issue by sbellem** [bigchaindb/bigchaindb#1008]
at https://docs.bigchaindb.com/projects/server/en/latest/nodes/setup-run-node.html

see https://gitter.im/bigchaindb/bigchaindb?at=585ea51dc5a4e0233bc6a406

**Comment by sbellem** [comment]
Most likely an encoding issue with the OS locale, as it must be UTF-8. E.g.:

```bash
$ export LC_ALL=en_US.UTF-8
$ export LANG=en_US.UTF-8
$ export LANGUAGE=en_US.UTF-8
```

**Comment by ttmc** [comment]
We ran into a similar problem when installing on Ubuntu 14.04 on an Azure virtual machine, which is why we added the `export LANG="en_US.UTF-8"` line to the `init.sh` script there:

https://github.com/Azure/azure-quickstart-templates/blob/master/bigchaindb-on-ubuntu/scripts/init.sh#L14

**Comment by r-marques** [comment]
This seems related to #1010 and #1011

**Comment by sohkai** [comment]
#1011 and https://github.com/python-rapidjson/python-rapidjson/pull/52 have both been merged. Do we want to try reverting #1011 and close this? Or just close it?

**Comment by r-marques** [comment]
@sbellem can we close this?

**Comment by sbellem** [comment]
Closing as this was resolved in latest python-rapidjson, which we now use in 0.9.5.
