### ISSUE TITLE
docker build --tag local-bigchaindb . fails

### ISSUE THREAD

**Issue by josephwinston** [bigchaindb/bigchaindb#1010]
[Gist](https://gist.github.com/josephwinston/6a56be07f7f086dc52cc95db3f9faeb7) of failure.

**Comment by josephwinston** [comment]
See https://github.com/bigchaindb/bigchaindb/pull/1011

**Comment by r-marques** [comment]
Hi @josephwinston 

Thanks for spotting this issue.
I will keep this issue open until #1011 is merged

**Comment by sohkai** [comment]
Closing as #1011 was merged.
