### ISSUE TITLE
Need secure connection to RethinkDB

### ISSUE THREAD

**Issue by mgrand** [bigchaindb/bigchaindb#1013]
I need BigchainDB to be able to provide credentials for a secure connection to RethinkDB. In particular, I need to be able to specify a certificate and authorization key.  

The scenario that I want to support is that each blockchain participant will operate their own BigchainDB instance. A non-participant (my organization) will operate the RethinkDB instances. The RethinkDB instances will be on a public cloud. Right now that is expected to by IBM's Bluemix. We will recommend but not require that each participant's BigchainDB instances will run in the same public cloud. 

Running an unsecured RethinkDB admin account will not be acceptable in this environment. We will want RethinkDB to authenticate each connection so that we know where each request is coming from.

**Comment by r-marques** [comment]
That's an interesting approach.

RethinkDB provides two ways for driver authentication:
- User/Pass but these go in plain text through the wire
- Use rethinkdb builtin TLS

**Comment by vrde** [comment]
@mgrand, as @r-marques pointed out there are some "out of the box" solutions with Rethinkdb, take a look to those two links:
 - https://rethinkdb.com/docs/security/
 - https://rethinkdb.com/api/python/connect/

If you need `user/pass` or `ssl` support when connecting to RethinkDB, we can add those options to the configuration, shouldn't be a lot of work.

**Comment by mgrand** [comment]
The RethinkDB ssl support is what I want.   I just need to be able to specify the information in the BigchainDB configurtion.

**Comment by ttmc** [comment]
As of BigchainDB 2.0, which is coming out very soon, we're no longer supporting RethinkDB, therefore I am closing this issue.
