### ISSUE TITLE
Duplicate transaction ID into asset for CREATE transactions

### ISSUE THREAD

**Issue by libscott** [bigchaindb/bigchaindb#1033]
When serializing a CREATE transaction, it's ID should be duplicated into `tx.asset.id`. 

This is to simplify database queries. It has the added benefit that the whole issue surrounding "tx id as asset ID" becomes a little easier to understand.

Like signatures, it needs to be removed again before hashing ie: `tx.asset.pop('id', None)`.

**Comment by sohkai** [comment]
This change is a bit of a cop-out, but perhaps another option to throw out there: what if the transaction data stored in the underlying database automatically includes the tx ID in the asset (to make the querying easier) but the http responses / querying mechanisms remove it (and don't require it) so the user doesn't have to deal with it?

**Comment by diminator** [comment]
I think @libscott is saying that he wants it to be there explicitly so that the user can see the relation between assets more easily

Cleaning up a transaction before signing is always a bit of a PITB from a driver/client point of view

**Comment by libscott** [comment]
> what if the transaction data stored in the underlying database automatically includes the tx ID in the asset (to make the querying easier) but the http responses / querying mechanisms remove it (and don't require it) so the user doesn't have to deal with it?

Not a bad idea. So the tx is transformed before it goes into the database. Or, rather, the transactions in the block.

What i dont like is that now there needs to be function applied everywhere that a tx is read from the DB.

**Comment by sohkai** [comment]
> What i dont like is that now there needs to be function applied everywhere that a tx is read from the DB

This could be applied transparently (we more or less already do this, by creating `Transaction` instances).

> he wants it to be there explicitly so that the user can see the relation between assets more easily

This is a good point; if we agree this is more clear for the user, let's add it (@TimDaub).

**Comment by libscott** [comment]
> This could be applied transparently (we more or less already do this, by creating Transaction instances).

Good point.

**Comment by libscott** [comment]
How about this, we duplicate the ID into asset.id, as a published change, and then if we end up needing to do more transformations to store data in the database (like #992) then we can think about duplicating the ID as a further transformation. Make sense?

**Comment by sohkai** [comment]
👍
