### ISSUE TITLE
Write systemd init script for bigchaindb

### ISSUE THREAD

**Issue by ttmc** [bigchaindb/bigchaindb#1049]
This is needed if we want `bigchaindb` to start on boot, as we may on testnet & production machines (e.g. virtual machines on Azure, launched from the Azure Marketplace).

Note: Using systemd rather than Upstart or System V init scripts assumes a recent version of Ubuntu, but that's probably okay since Ubuntu 16.04 is an LTS version and it uses systemd init scripts.

This will also help with graceful shutdown and restart of BigchainDB Server: see issue #662

**Comment by r-marques** [comment]
You could also consider using [Supervisor](http://supervisord.org/) in my experience its a much more user friendly alternative.

**Comment by krish7919** [comment]
systemd is a superset of supervisor.
As in the run supervisor, we will need a systemd config.

**Comment by krish7919** [comment]
Digged into this a little bit. So far I have:
```
[Unit]
Description="bigchaindb server"
Documentation="https://docs.bigchaindb.com"
#Requires=network-online.target mongod.service?
#After=
[Service]
#User=bigchaindb
User=krish
#EnvironmentFile=/etc/environment PYTHONPATH?
TimeoutSec=30
#ExecStartPre=-/xxx/bigchaindb-pre-start.bash
ExecStart=/xxx/bin/bigchaindb -c /etc/bigchaindb/.bigchaindb start
#ExecStop=/xxx/bigchaindb-stop.bash flush and cleanup here
Restart=always
RestartSec=5

#[Install]
#WantedBy=multi-user.target
```
and 
```
diff --git a/setup.py b/setup.py
index 9dd050b..491bbe4 100644
--- a/setup.py
+++ b/setup.py
@@ -127,4 +127,5 @@ setup(
         'docs': docs_require,
     },
     package_data={'bigchaindb.common.schema': ['*.yaml']},
+    data_files=[('/etc/systemd/system', ['bigchaindb.service'])]
 )
```

The workflow should be more like:
1.  Create the user and group during pip install, OR create the user group as an exec-pre-start script.
2.  Create and configure a .bigchaindb conf file in /etc/bigchaindb/.
3.  Point python to be python3.

Will get back to this later.

**Comment by ttmc** [comment]
We're going to stop working on this for now because internally we're going to be using Docker to start/restart BigchainDB inside containers.

If you, dear reader, need a systemd init script for your own BigchainDB deployment, then comment below to let us know.
