### ISSUE TITLE
Deployment scripts for MongoDB

### ISSUE THREAD

**Issue by r-marques** [bigchaindb/bigchaindb#1058]
Deployment scripts for mongodb test clusters in aws/azure.
Dockerfiles for local development.

##### References:
- [Install MongoDB Community Edition on Ubuntu](https://docs.mongodb.com/manual/tutorial/install-mongodb-on-ubuntu/)
- [Deploy a replica set Mongo Docs](https://docs.mongodb.com/manual/tutorial/deploy-replica-set/)
- [Replica sets PyMongo Docs](http://api.mongodb.com/python/current/examples/high_availability.html)
- Example config file:
```bash
# mongod.conf

# for documentation of all options, see:
#   http://docs.mongodb.org/manual/reference/configuration-options/

# where to write logging data.
systemLog:
  destination: file
  logAppend: true
  path: /var/log/mongodb/mongod.log

# Where and how to store data.
storage:
  dbPath: /data
  journal:
    enabled: true
#  engine:
#  mmapv1:
#  wiredTiger:

# how the process runs
processManagement:
  fork: true  # fork and run in background
  pidFilePath: /var/run/mongodb/mongod.pid  # location of pidfile

# network interfaces
net:
  port: 27017
  bindIp: 127.0.0.1  # Listen to local interface only, comment to listen on all interfaces.

#security:

#operationProfiling:

replication:
  replSetName: bigchain-rs

#sharding:

## Enterprise-Only Options

#auditLog:

#snmp:
```
This is an example of the MongoDB configuration file stored by default in `/etc/mongod.conf`.
The important options for the dev environment are `dbPath: /data` - the location of the database data and `replSetName: bigchain-rs` the name of the replica set (BigchainDB uses `bigchaindb-rs` by default).
I think that we will need to comment `bindIp` so that the driver can connect to any node on the cluster.

Another thing to note is that we require MongoDB v3.4.X. Travis is currently using v3.4.1 to run the unit tests.

**Comment by ttmc** [comment]
We had a meeting about this today. Decisions:
- Rodolphe will do some simple internal scripts for deploying MongoDB cluster tests on AWS.
- Krish and I will figure out a more production-worthy process for provisioning on _Azure_, and deploying there (with a MongoDB backend).

Therefore this issue is being closed.
