### ISSUE TITLE
Don't remove asset.id before signing transaction

### ISSUE THREAD

**Issue by sohkai** [bigchaindb/bigchaindb#1089]
common/transaction.py#L959 should be separated out into a different method to avoid popping the asset id during transaction signing.

**Comment by libscott** [comment]
What's the reasoning?

**Comment by sohkai** [comment]
Shouldn't the `asset.id` be included in the message that is signed in a fulfillment?

**Comment by libscott** [comment]
It is in the case of a transfer. This issue is covered by #970 really.

**Comment by sbellem** [comment]
To put the question in another way:

The asset id used to be part of the transaction payload that was serialized and signed. What was the reasoning to remove it?

**Comment by sohkai** [comment]
Superceded by #1101; we'll remove the `asset.id` from `CREATE` transactions and deal with query optimizations later.
