### ISSUE TITLE
Validate transaction before writing it to the backlog

### ISSUE THREAD

**Issue by r-marques** [bigchaindb/bigchaindb#109]
Right now, `bigchaindb.web.views` only verifies the signature. We should call `validate_transaction` instead so that we can catch double spends and other errors before writing the transaction to the backlog, and send whatever exception back to the client

**Comment by ttmc** [comment]
The current code (`write_transaction()` in the `Bigchain` class; see [core.py](https://github.com/bigchaindb/bigchaindb/blob/master/bigchaindb/core.py)) assigns the transaction to a random node for inclusion in a block. It's possible that it might assign _itself_ to put the transaction in the block. That means it might do _both_ of the initial transaction validations. It seems to me that it would be better for a different node to be assigned to validate and put the transaction in the block, i.e. choose from a list of federation nodes excluding the initial node.

Edge case: If the federation only has one node, then that node must do both of the initial validations.

**Comment by r-marques** [comment]
> The current code (write_transaction() in the Bigchain class; see core.py) assigns the transaction to a random node for inclusion in a block. It's possible that it might assign itself to put the transaction in the block.

This does not happen. A node assigns the transaction to a random federation node excluding itself. `Bigchain.federation_nodes` contains all the federation nodes except itself.

But I agree that its bad for the node receiving the transaction to validate it before putting it into the backlog. If the node is faulty it may reject valid transactions.

I propose that we close this issue and take care of improving resilience against faulty nodes when sending transactions for when we separate the server and client code.

**Comment by ttmc** [comment]
If only one node is responsible for validating a transaction before that transaction gets into a block, then if that one node is faulty, it could allow _invalid_ transactions into its blocks. The other nodes will catch the invalid transactions, of course, but it's a bit late:  the whole block is ruined (invalid), and all the valid transactions in it must be cycled back to the backlog for reconsideration.

That said, it's very easy to detect when some node said a transaction was invalid whereas all the others say it's valid. We already have some issues for that: Issue #351 & Issue #354 . 

This issue could be closed.
