### ISSUE TITLE
Why including the redundant api root "/api/v1/" in the docs?

### ISSUE THREAD

**Issue by sbellem** [bigchaindb/bigchaindb#1093]

**Comment by libscott** [comment]
In what way it it redundant? It provides different info to `/`.

**Comment by sbellem** [comment]
All endpoints are under `/api/v1`, so why repeat that information?

**Comment by ttmc** [comment]
It's true that the documentation of many REST APIs doesn't include the `/api/v1` (or similar) in the heading for each endpoint, but there are exceptions, e.g.

https://docs.atlassian.com/confluence/REST/latest/

It doesn't matter that much to me. We already show a full HTTP request example for each endpoint, so there's no ambiguity. It's nice how the first line in those examples matches up with the heading for the endpoint.
