### ISSUE TITLE
[http api] Why using case sensitive values for query parameters?

### ISSUE THREAD

**Issue by sbellem** [bigchaindb/bigchaindb#1096]
Isn't this overly restrictive?

What difference does it make if an API consumer passes "yes" or "YES", or "Yes"? Why bother?

**Comment by diminator** [comment]
of course it's over restrictive... should be case insensitive
If you found that in the docs, remove it

**Comment by libscott** [comment]
It could be overly restrictive, my idea was to reduce the number of duplicate URLs for the same resource (for caching), but that's probably a premature optimisation. One question, should this apply to CREATE and TRANSFER too? Should "OPERation=CREate" be valid?

**Comment by diminator** [comment]
It's only important when providing secrets or encoded IDs as query params

**Comment by sbellem** [comment]
> of course it's over restrictive... should be case insensitive
> If you found that in the docs, remove it

Ok, well, it is not so much about the docs. The implementation for some endpoint(s) is currently strict with respect to the case. If I am not mistaken, it is so for values such as "true", "false", "CREATE", and "TRANSFER". Basically, endpoints depending on the parameters [`valid_bool`](https://github.com/bigchaindb/bigchaindb/blob/master/bigchaindb/web/views/parameters.py#L10-L15) and [`valid_operation`](https://github.com/bigchaindb/bigchaindb/blob/master/bigchaindb/web/views/parameters.py#L25-L30), and perhaps others as well.

As an aside `flask-restful` has an option to specify an argument as being case insensitive.

**Comment by libscott** [comment]
Cool I'll take this one.
