### ISSUE TITLE
[tx gen protocol] Document the protocol for forming transaction payloads

### ISSUE THREAD

**Issue by sbellem** [bigchaindb/bigchaindb#1122]
Transaction payloads submitted to BigchainDB must be formed according to multiple criteria (schema, serialization, hashing, crypto-conditions). The knowledge on how to form the payload needs to be documented in a programming language agnostic way as a reference for implementers.

Some things that can be done towards the goal of this ticket:

- [ ] Move [python driver handcrafting transactions](https://github.com/bigchaindb/bigchaindb-driver/blob/v0.2.1/docs/handcraft.rst)
 docs under server docs, and remove references to Python driver (replace with `requests`).
- [x] Write a clear specification that outlines the steps that need to be followed to form a valid transaction payload. This specification would serve three main purposes, roughly:
    1. Contract binding server nodes with clients with respect to correct transaction payloads.
    2. Specification for all clients to follow when implementing code to form transaction payloads.
    3. Specification to follow when implementing server side validation logic to validate transaction payloads.
- [x] Details about the (json) serialization step for the transaction hash and message to sign. (Documented in https://docs.bigchaindb.com/projects/server/en/latest/appendices/json-serialization.html?highlight=json)
- [ ] Provide a set of test vectors against which implementations can be tested.

The second point is really what this ticket is concerned with.

**Comment by r-marques** [comment]
This is done in the [python driver documentation](https://github.com/bigchaindb/bigchaindb-driver/blob/v0.2.1/docs/handcraft.rst)

@sbellem is there anything else we need to do to close this issue?

**Comment by r-marques** [comment]
Also this seems related to #1137

**Comment by sbellem** [comment]
> is there anything else we need to do to close this issue?

@r-marques Yes, this ticket is meant to continue what was started under the python driver. I will add the tasks that need to be done in the description.

**Comment by sbellem** [comment]
> Also this seems related to #1137

It is yes, but much less general, and strictly focused on the transaction payload formation part,

**Comment by addywaddy** [comment]
This is a great aid in helping me build transactions without having to dig through e.g. bigchaindb-common. Thanks!

As an addition, it would be great if there were a set of versioned test vectors (similar to those for cryptoconditions) against which clients written in other languages could test.

**Comment by ttmc** [comment]
Some of these things are done now, as part of writing the [IPDB Transaction Spec](https://the-ipdb-transaction-spec.readthedocs.io/en/latest/), so I will check the associated boxes after I submit this comment.

* [How to Construct a Transaction](https://the-ipdb-transaction-spec.readthedocs.io/en/latest/construct-a-tx.html)
* [Common Operations](https://the-ipdb-transaction-spec.readthedocs.io/en/latest/common-operations/index.html)
