### ISSUE TITLE
[http api] Redundant GET: /transactions/txid and /transactions?asset_id=txid&operation=CREATE

### ISSUE THREAD

**Issue by sbellem** [bigchaindb/bigchaindb#1129]
Both calls will return the same exact transaction, except for one being in a list.

The asset id is actually the transaction id of the CREATE transaction in which the asset was created/minted, and consequently calling `GET /transactions?asset_id=some-id&operation=CREATE` will return the CREATE transaction in a list. One may as well use the simpler call `GET /transactions/some-id` and get the transaction directly without the need to extract it out of a list.

**Comment by ttmc** [comment]
I made a comment here: https://github.com/bigchaindb/bigchaindb/pull/1522/files#r120831399

**Comment by TimDaub** [comment]
Closed according to decision in #1522.
