### ISSUE TITLE
[http api] query parameters are "tx_id" meanwhile the payloads are "txid"

### ISSUE THREAD

**Issue by sbellem** [bigchaindb/bigchaindb#1134]
For instance, the query parameter for the transaction id on the statuses endpoint is `tx_id`. Given that we support querying the block id via the parameter `block_id` and that `blockid` would be awkward, then the first question is do we wish to have some kind of consistency between the query parameters and the payloads. If yes, then perhaps we could consider renaming the field `txid` to `tx_id`?

Although this may be viewed as an annoying detail, consistency can help making interfaces simpler and easier to understand.

**Comment by TimDaub** [comment]
#1134 is overwritten by #1531 and is according to what was decided by the team in #1522.

I'll close this issue and we'll handle all changes in #1531. 

@r-marques: OK?

**Comment by r-marques** [comment]
Yes. I was looking for an already open issue but didn't found this one

**Comment by r-marques** [comment]
Yes
