### ISSUE TITLE
DoubleSpend exception occurs when multiple clients submit assets simultaneously

### ISSUE THREAD

**Issue by user758904** [bigchaindb/bigchaindb#1140]
Hi,

I am getting double spend exceptions in certain circumstances and not sure why. Would appreciate any help. Here is what I am doing. I am running the following python script 100 time simultaneously (i.e. 100 independent processes.)

This is the python script:

    #!/usr/bin/env python3
    
    from bigchaindb_driver import BigchainDB
    from bigchaindb_driver.crypto import generate_keypair
    import time
    import uuid
    import sys
    import traceback
    
    alice, bob = generate_keypair(), generate_keypair()
    
    bdb = BigchainDB('http://localhost:9984/api/v1')
    
    
    def createAsset():
        
        bicycle = {
            'data': {
                'bicycle': {
                    'serial_number': 'abcd1234',
                    'manufacturer': 'bkfab',
                    'uuid': str(uuid.uuid4()),
                },
            },
        }
    
        metadata = {'planet': 'earth'}
    
        prepared_creation_tx = bdb.transactions.prepare(
            operation='CREATE',
            owners_before=alice.verifying_key,
            asset=bicycle,
            metadata=metadata,
        )
        
        fulfilled_creation_tx = bdb.transactions.fulfill(
            prepared_creation_tx, private_keys=alice.signing_key)
        
        bdb.transactions.send(fulfilled_creation_tx)
    
        txid = fulfilled_creation_tx['id']
    
        return txid
    
    
    def checkStatus(transactionIds):
        totalTransactions = len(transactionIds)
        totalValidTransactions = 0
    
        for txid in transactionIds:
            while True:
                try:
                    if bdb.transactions.status(txid).get('status') == 'valid':
                        totalValidTransactions += 1
                        break
                except:
                    print("Exception in user code:", flush=True)
                    traceback.print_exc(file=sys.stdout)
                    print("-"*60, flush=True)
                time.sleep(2)
    
        print("Total valid transactions: " + str(totalValidTransactions) + " / " + str(totalTransactions), flush=True)
    
    
    def main():
        while True:
            transactionIds = []
            for _i in range(10):
                txid = createAsset()
                print(str(_i) + " " + txid, flush=True)
                transactionIds.append(txid)
    
    
            print("Submitted 10 assets", flush=True)
            checkStatus(transactionIds)
    
    
    main()

This script is based on the examples in the documentation. It submits 10 assets and then waits until all 10 assets are valid, and then repeats this indefinitely. 

I run this script 100 times simultaneously using the following simple bash script (which assumes the above python script is named test.py):

    #!/bin/bash
    
    for i in {1..100}
    do
        ./test.py &
    done
    
    wait

After running a very short amount of time, I start seeing double spend errors in the output log on the server. I.e. that a transaction is present in more than one valid block. Eventually, the server just hangs and no new assets can be submitted.  This is a typical exception thrown:

    [2017-02-02 11:25:30,008] ERROR in app: Exception on /api/v1/transactions/a0455a4c7e48435c0f8d02c7fe1ed40e3b56d5c5c77d08cd9038759cc1518188/status [GET]
    Traceback (most recent call last):
      File "/home/user/.local/lib/python3.5/site-packages/flask/app.py", line 1612, in full_dispatch_request
        rv = self.dispatch_request()
      File "/home/user/.local/lib/python3.5/site-packages/flask/app.py", line 1598, in dispatch_request
        return self.view_functions[rule.endpoint](**req.view_args)
      File "/home/user/.local/lib/python3.5/site-packages/flask_restful/__init__.py", line 477, in wrapper
        resp = resource(*args, **kwargs)
      File "/home/user/.local/lib/python3.5/site-packages/flask/views.py", line 84, in view
        return self.dispatch_request(*args, **kwargs)
      File "/home/user/.local/lib/python3.5/site-packages/flask_restful/__init__.py", line 587, in dispatch_request
        resp = meth(*args, **kwargs)
      File "/home/user/.local/lib/python3.5/site-packages/bigchaindb/web/views/transactions.py", line 77, in get
        status = bigchain.get_status(tx_id)
      File "/home/user/.local/lib/python3.5/site-packages/bigchaindb/core.py", line 290, in get_status
        _, status = self.get_transaction(txid, include_status=True)
      File "/home/user/.local/lib/python3.5/site-packages/bigchaindb/core.py", line 240, in get_transaction
        validity = self.get_blocks_status_containing_tx(txid)
      File "/home/user/.local/lib/python3.5/site-packages/bigchaindb/core.py", line 326, in get_blocks_status_containing_tx
        block_ids=block_ids))
    bigchaindb.common.exceptions.DoubleSpend: Transaction a0455a4c7e48435c0f8d02c7fe1ed40e3b56d5c5c77d08cd9038759cc1518188 is present in multiple valid blocks: ['3d55102a907c193a6a380aedace1e13c2bf52190336bbd0a7c2283f878f4bb3b', '7b6bc95fb475e1c97661081b4cd2090cde4cbd7e3a54f42b48e5302dd8357349']

When the above python script is only run once at a time, I don't see these errors. It's only when many multiple clients are run at the same time do I notice these errors. Just wondering if anyone else is able to reproduce these errors or if you know what might be wrong. I am using bigchain version 0.8.2 and bigchain-driver 0.1.3 on ubuntu 16.04 with python 3.5.2.

Thanks for any help in advance.

**Comment by r-marques** [comment]
@user758904 thanks for pointing out this problem.
We will try to reproduce it and fix the problem

**Comment by libscott** [comment]
Update! I tracked down the issue, and 3 separate issues have been created to fix it.

Thank you @user758904 for your detailed and useful report, which made it easy to diagnose :).
