### ISSUE TITLE
Rename `api_v1` to `api_prefix` in http response.

### ISSUE THREAD

**Issue by krish7919** [bigchaindb/bigchaindb#1143]
Motivation: The `api_v1` gives the prefix for all the htttp requests. And we can change this in the future if we upgrade the api contract.

```
curl -X GET http://localhost:59984/
{
  "_links": {
    "api_v1": "/api/v1/", 
    "docs": "https://docs.bigchaindb.com/projects/server/en/0.9.dev/"
  }, 
  "keyring": [], 
  "public_key": "6F5Bi9HEgaFicPiT1FNDCPJgQBhAr8SJVUX7P2uBKLRY", 
  "software": "BigchainDB", 
  "version": "0.9.0.dev"
}
```

**Comment by TimDaub** [comment]
This ticket is based on: #1141.

Assuming that we make all host+ports freely configurable as described in #1141, defining the value of `_links.api_v1` to `/api/v1` is possible for a node operator.

Calling it `api_prefix` is opinionated, as some node operators might choose to link directly to the node's API  - using a full path like `{"api_v1": "http://example.com:1234/"}`. In that case, calling the key `api_v1` leaves more options open for network operators.

@krish7919 I'll close and have solution being done in #1141. Hope that's OK.
