### ISSUE TITLE
[http api] Remove "third" layer of versioning

### ISSUE THREAD

**Issue by sbellem** [bigchaindb/bigchaindb#1145]
**IMPORTANT**: To avoid misunderstanding: please not that this issue is concerned with a lyer of versioning not versioning altogether. BigchainDB has three layers of versioning as of now,

1. Server layer, the one that appears under [version.py](https://github.com/bigchaindb/bigchaindb/blob/master/bigchaindb/version.py)
2. [Transaction model layer](https://github.com/bigchaindb/bigchaindb/blob/master/bigchaindb/common/schema/transaction.yaml#L57)
3. HTTP API layer, the one that appears in the [URL path](https://github.com/bigchaindb/bigchaindb/blob/master/bigchaindb/web/routes.py#L40), following the hostname and port, e.g.: `http:localhost:9984/api/v1/transactions`

This is a proposal to remove the current versioning **layer** on the HTTP API. Since BigchainDB itself has a version, the HTTP API version is implicit. That is, the HTTP API contract that clients rely on when communicating with a BigchainDB node follows from the version of the server itself, hence rendering a versioning system unnecessary.

If, in the future, we reach a state in which a specific BigchainDB version supports multiple HTTP API contract versions, then we could introduce an additional layer of versioning as needed. 

- [ ] Compare with other db systems that offer an HTTP API (e.g.: couchdb, elasticsearch, voltdb, etc)
- [ ] Address the question of how will requests be routed in an heterogeneous (version-wise) cluster where, for instance,  a load balancer can route to the appropriate version. (E.g.: using headers versus using the url path.)

**Comment by krish7919** [comment]
We will still want HTTP versioning.
If a consortium runs 2 instances of bigchaindb server during migration/upgrade/bugfix patch, which is backed by the same mongodb, we can just have a rule at the load balancer level to forward requests to the appropriate node, rather than having to setup 2 LBs, firewalls, etc.
It also helps in maintaining backward compatibility, where an API change (or BDB version change) will result in nodes of a cluster being upgraded one by one, and not all at once.

**Comment by TimDaub** [comment]
Fully agreed with @krish7919 here.

- HTTP API versioning decouples servers (this means bigchaindb/bigchaindb, but also forked versions) from their respective drivers (HTTP driver and server decoupling)
- Transaction model versioning decouples servers from forked servers (Hard- & softforks in blockchain world)
- Server versioning decouples earlier code from later code (traditional SEMVER via pypi)

Moving forward, I do see harm in removing versioning - as it could constrain us (or others - e.g. users that want to fork BDB), but no harm in leaving versioning as is.

> Compare with other db systems that offer an HTTP API (e.g.: couchdb, elasticsearch, voltdb, etc)

I don't think the given examples are appropriate, as they do not give information on versioning of blockchain systems, where apart from dataconsistency-consensus, there is also logical-order-consensus.

@sbellem I'll hence close this ticket. If there's ever a time where we're forced to remove layers of versioning, we should reopen.
