### ISSUE TITLE
Transaction already in valid block is not checked

### ISSUE THREAD

**Issue by libscott** [bigchaindb/bigchaindb#1150]
Solves #1140 

During the process of creating a block, we do not check if transactions have already been included in a valid block. This is not an issue for TRANSFER transactions because a double spend would be detected, but it is an issue with CREATE transactions because they do not generate double spends.

Edit: It COULD be an issue for transfers, where the same transfer is submitted twice and not identified as a double spend. See #592 

Outstanding question: Should this be part of the `models.Transaction.validate()` method? Should validate() called on an existing, already included transaction check that it has not been included? The description is then incorrect, it would be more correct to then call the method: `is_eligible_for_inclusion`.

**Comment by ttmc** [comment]
The existing check to see if a TRANSFER transaction is spending the same output looks in both valid _and undecided_ blocks (of the bigchain table) for other transactions spending the same output. (It ignores transactions in invalid blocks and doesn't look in the backlog table.)

For consistency, should we check in the same places (valid and undecided blocks) for identical CREATE transactions? Or just vaid blocks?

You make a good point that this check isn't really about checking transaction "validity." Maybe the method could be called (transaction) `not_already_in_a_valid_block()`?

It could be done before or after checking transaction validity, both:
* in the block-building pipeline, and 
* in bigchain block validation.

**Comment by libscott** [comment]
Slight correction, the issue is not when a block is being created, there we DO check that a transaction was not already included, it's when the block is being voted on.

Reproduction: https://github.com/bigchaindb/bigchaindb/commit/5e263f95b31b4120d0312bdac8a0b756f1971a74#diff-7099c087df5ce3458965854f1f64bf1dR29
