### ISSUE TITLE
Decide what Docker containers to create & create them

### ISSUE THREAD

**Issue by ttmc** [bigchaindb/bigchaindb#1153]
We need to decide what Docker containers to create (i.e. what should they contain) for different purposes:
* for people to try out BigchainDB Server on Windows, macOS, or whatever
* for development
* for internal testing
* for production

Ideally, the same containers can be used for many or all of these use cases.

**Comment by krish7919** [comment]
I would suggest having 2 containers:
1.  BigchainDB Server
2.  MongoDB has [released official containers](https://hub.docker.com/r/library/mongo/)
3.  BigchainDB driver.

We can use all of them for dev, internal testing, dev and prod.
Decoupling DB from Bigchain is better as:
1.  Upgrade to bigchaindb does not affect mongodb and vice versa.
2.  BigchainDB crash does not affect mongodb and vice versa.
3.  We can support multiple transaction models with the same db backend in the future. In case our transaction schema changes, we can have a mixture of old + new transaction schema versions running over the same database cluster, before the entire cluster is migrated.

**Comment by ttmc** [comment]
We shouldn't forget RethinkDB.

**Comment by krish7919** [comment]
@ttmc : RethinkDB has official containers too. https://hub.docker.com/_/rethinkdb/
This is what we use as base image for bigchaindb docker container currently.

**Comment by trentmc** [comment]
This is for IPDB right? IPDB is going to be deployed with MongoDB. So why bother with RethinkDB?

**Comment by ttmc** [comment]
Because IPDB isn't our only user? Everyone, up til now, has been using RethinkDB. Some may opt to continue using it.

**Comment by trentmc** [comment]
OK, this isn't just for IPDB then (that was my first question). No problem then:)

**Comment by krish7919** [comment]
We have decided to decouple the backend database from bigchaindb when running in containers.
We will use the official rethinkdb/mongodb container images hosted in dockerhub.

We will also use the docker0 vnic (Ubuntu 16.04, docker 1.13) to connect the backend DB and bigchainDB together.

The general workflow is:

##### Configure BDB:
```
docker run \
  --rm \
  -v "$HOME/bigchaindb_docker:/data" \
  bigchaindb/krish-test \
  -y configure mongodb
```
OR
```
docker run \
  --rm \
  -v "$HOME/bigchaindb_docker:/data" \
  bigchaindb/krish-test \
  -y configure rethinkdb
```

##### Run backend DB:
```
docker run \
  --name=mongodb \
  --publish=172.17.0.1:27017:27017 \
  mongo:3.4.1 --replSet=bigchain-rs
```
OR 
```
docker run \
  --name=rethinkdb \
  --publish=172.17.0.1:28015:28015 \
  rethinkdb:2.3
```

##### Run BDB:
Modify the .bigchaindb configuration file to change the `host` field from `localhost` to `172.17.0.1`.

```
docker run \
  --name=bigchaindb \
  --publish=9984:59984 \
  --volume=$HOME/bigchaindb_docker:/data \
  bigchaindb/krish-test \
  start
```

**Comment by TimDaub** [comment]
> for production

I have a building customer that is also interested in this. If you're iterating on this, his feedback and use cases might be valuable. I can establish a email-link if you want.

**Comment by krish7919** [comment]
@tim:
Always welcome!
