### ISSUE TITLE
Unify database exceptions and unify behavior on reconnects

### ISSUE THREAD

**Issue by vrde** [bigchaindb/bigchaindb#1158]
Specifically:
- [x] riconciliate RethinkDB and MongoDB connection classes: there are some discrepancies on how reconnects are handled between the RethinkDB Connection class and the MongoDB one.
- [x] add `max_retries` and `connection_timeout` to the configuration
- [x] unify database exceptions

**Comment by TimDaub** [comment]
@vrde and @sbellem  Should this ticket be related to the proposal made by @sbellem in #721?

**Comment by vrde** [comment]
@TimDaub it's related, but it doesn't overlap. I'd say that my job is a subset of what @sbellem is proposing, so all good as long as I'm the only one working on that specific branch (the DB one) in the exception tree.
