### ISSUE TITLE
Implement a better web server

### ISSUE THREAD

**Issue by vrde** [bigchaindb/bigchaindb#116]
Right now BigchainDB uses the default Flask single synchronous test server.

An idea is to use gunicorn. Since we are using subprocessing to spawn processes, maybe we can use this guide:
 - http://docs.gunicorn.org/en/latest/custom.html

**Comment by Mec-iS** [comment]
Do you think adding all the complexity of a non-blocking server is worth in this case? In my experience (and seen the "atomicity" of the operations on a blockchain in this particular case) a high-performance blocking server is more advisable. [Falcon framework](http://falconframework.org) has the necessary features for the project to leverage (authentication, input/output sanitation, etc), avoiding the overhead from Flask, and runs with C bindings for performance.

**Comment by vrde** [comment]
> Do you think adding all the complexity of a multiprocess server is worth in this case?

Here I'm just talking on how to spawn the webserver when starting the daemon. Flask apps (and Falcon apps as well) expose a WSGI app that can be run by any WSGI compatible application server. Gunicorn is usually a really good choice, and it's also the [recommended way](http://falcon.readthedocs.org/en/latest/user/tutorial.html#hosting-your-app) to put a Falcon app in production. Right now the `bigchaindb start` command spawns also a Flask development server, you can find the code in the [`Processes` module](https://github.com/bigchaindb/bigchaindb/blob/develop/bigchaindb/processes.py#L86). The scope of this issue is to replace the bootstrap of that server with a more stable and production ready implementation that is, indeed, Gunicorn.

Related to Falcon, I didn't know it, thanks for linking to it. The approach they have is interesting and minimal. As you can see from the code in the [web module](https://github.com/bigchaindb/bigchaindb/tree/develop/bigchaindb/web), the application itself is pretty basic, so if one day we want to change framework to Falcon it should not be that hard.

Related to performance, we can have a synchronous approach (the current one) or an asynchronous approach. RethinkDB supports Tornado (that is async) and, IMO, it can be the right tool for this job since running the API will be more **IO-bound** than **CPU-bound**. We didn't dig too much in it right now because using Tornado means also to change all our queries to be asynchronous, but it's in our roadmap.

**Comment by r-marques** [comment]
It would be ok if the server was threaded and each thread would open a connection to the database. This would allow for parallel requests to the database out of the box

**Comment by Mec-iS** [comment]
@vrde Yeah using an event-loop is an option, but I wouldn't start implementing anything in Tornado at this time, Py3 Twisted is still on the way... (: Have you heard about [hug](https://github.com/timothycrosley/hug)?

> running the API will be more IO-bound than CPU-bound

Yeah but, as far as I understand, other operations on the server (crypto) are highly CPU-bound.

@r-marques yeah using Python threads could be a less overhead solution, avoiding Web frameworks' "heaviness". In this case a smaller framework than Flask could apply.

**Comment by vrde** [comment]
> @vrde Yeah using an event-loop is an option, but I wouldn't start implementing anything in Tornado at this time, Py3 Twisted is still on the way... (: Have you heard about hug?

didn't know about hug, thanks for the link!

I made some progress, check out [my branch](https://github.com/bigchaindb/bigchaindb/tree/feat/116/more-solid-webserver).
