### ISSUE TITLE
MultipleVotesError when there are votes from unknown nodes

### ISSUE THREAD

**Issue by libscott** [bigchaindb/bigchaindb#1166]
See [example](https://github.com/bigchaindb/bigchaindb/commit/89d816055418dcb3c3d3227a03015f8c870df9f7)

Each block contains a list of public keys which are the voting nodes for that block. If there are more votes than voters in the block, an exception is thrown:

> bigchaindb.common.exceptions.MultipleVotesError: Block cfbfb0b125e1f6cba22bf97ecf5ae2c10df76deb525216cbc79137e204347907 has 11 votes cast, but only 1 voters

Well behaved nodes should not vote for a block where they are not part of the voters set. But this is a sybill attack vector which we can protect against.

**Comment by CsterKuroi** [comment]
It might be dangerous if someone falsifies block.voters.
