### ISSUE TITLE
[http api] Include block_id and transaction status in response to GET /transactions

### ISSUE THREAD

**Issue by sbellem** [bigchaindb/bigchaindb#1169]
A transaction has a status (`IN_BACKLOG`, `IN_UNDECIDED_BLOCK`, `IN_VALID_BLOCK`, `IN_INVALID_BLOCK`) and potentially belongs to a block. This information is important and could be returned as part of the response to a `GET /transactions/id` for instance.

This could also save clients from making subsequent calls to get the transaction status and block id, via `GET /statuses` and `GET /blocks` respectively.

We may also wish to consider adding a timestamp, if that makes any sense, and some information about the votes.

**Comment by TimDaub** [comment]
Closed according to decision in #1522

For everyone wondering about this functionality.
We already have a very similar function implemented [here](https://docs.bigchaindb.com/projects/server/en/v0.10.2/http-client-server-api.html#get--api-v1-blocks?tx_id=tx_id&status=UNDECIDED|VALID|INVALID)
