### ISSUE TITLE
[tx gen protocol] Only add "fulfillment" key/value pair after fulfillment

### ISSUE THREAD

**Issue by sbellem** [bigchaindb/bigchaindb#1176]
I wonder why the fulfillment key/value pair is necessary for hashing, and serialization (transaction `id` generation, and fulfillment URI generation). Before hashing and fulfilling (e.g.: signing) the fulfillment value is `None`. So why bother? A simpler approach would be to only add the key/value pair once the fulfillment URI is generated and ready to be inserted. This would be similar to how we handle the transaction `id`. In the case of the transaction `id` we do not add it before hashing with a `None` value. We only add the `id` value along with its key once we have generated it.

This topic is linked (is a subset of) the protocol definition to obtain a valid transaction payload compliant with the server's requirements.

The mindset of this ticket is to make it simpler for users to form payloads, on their own, through their own custom code.

Also as an example, one could think of two main "actors" required to form a payload: a HASHER and a FULFILLER.

The information that is passed to the hasher and fulfiller would be reduced if we do not include the dummy key/value pair ('fulfillment', None), and therefore simpler.

Code implementing the hasher and fulfiller would therefore be simpler.

**Comment by zbo14** [comment]
For me, omitting the fulfillment field would be more natural.. And what about omitting the other null fields (fulfills, condition signature) from the initial payload as well?

**Comment by sbellem** [comment]
> And what about omitting the other null fields (fulfills, condition signature) from the initial payload as well?

I need to double check this, but if it is possible yes!

**Comment by sbellem** [comment]
Adding some feedback from DBH17:

Whatever the approach, be consistent at the very least. Some would prefer all fields to be there ftom the get go, with null values whereever needed.
