### ISSUE TITLE
Logging guidelines

### ISSUE THREAD

**Issue by libscott** [bigchaindb/bigchaindb#1188]
This ticket was rewritten (original content below) since it's no longer a requirement for *correctness* specifically. Original content is below.

As a wishlist though, I can propose the following:

* All database state changes are logged with INFO after they happen (and with DEBUG before they happen, perhaps could be a wrapper for this that also calculates the time they take).
* Logger names are not the __name__ of the module but rather the concern. Module / file names are not the most meaningful thing in log output.

------------------------------------------
-- original content

There are some logging requirements for the async pipeline, so that state changes can be followed accurately:

* All database changes need to be logged to a particular output (backlog, votes, bigchain tables)
* Log entries should happen _after_ the operations, to reflect that they have been completed
* Log entries should contain some extra data passed via the [`extra` parameter](https://docs.python.org/2/library/logging.html#logging.debug):
    * backlog insert: {tx: signed_timestamp}
    * backlog update: {txid: transaction_id, tx: doc}
    * backlog delete: {ids: [transaction_id]}
    * vote insert: {'vote': signed_vote}
    * bigchain insert: {'block': block}
* Loggers need to be identifiable as a group (not just __name__) so that database changes can be collected into one handler

So the object being written is passed into the logging call. This way, if needed, it can be retrieved later for inspection elsewhere by adding logging handlers.

**Comment by krish7919** [comment]
> All database state changes are logged with INFO after they happen (and with DEBUG before they happen, perhaps could be a wrapper for this that also calculates the time they take).

1.  I think we should never log _all_ changes in the system, just the interesting ones.
We will be overwhelmed with logs then. The point should be to get insights on what is happening; TMI is bad. We also need to take into account the perf hit logging will have on the usual functionality and have to be a little careful about logging.

2.  We should also consider a consolidated logging (at the node level for bdb for different pipelines, and maybe at the federation level later in the future if requirements mandate it) rather than logging to multiple files/places and then correlating the logs.

3.  One more proposal is to implement a signal handler/trap mechanism that changes the log levels dynamically, so that we can increase log verbosity (consciously taking a hit on perf) in a running system without restarting it. It affects HA and many a times the problem disappears after a restart.

**Comment by sohkai** [comment]
> Another proposal is to run a logging service as a udp socket on localhost where different modules can send logs. This way the hit on the DB is kept minimal and we get logging easily from different pipelines/processes in the module.

This is interesting; we could add a setting to redirect log output to a service instead of the default of something like a file or stdout. This could also be combined with an instrumentation service, and the node monitor could just pull data from this.

**Comment by domi41** [comment]
We tried running two instances of bigchaindb, each with its own ports and mongod instance, and the logger complains about its socket already being used.

```
Traceback (most recent call last):
  File "/usr/local/bin/bigchaindb", line 9, in <module>
    load_entry_point('BigchainDB==1.2.0.dev0', 'console_scripts', 'bigchaindb')()
  File "/home/code/fork/bigchaindb/bigchaindb/commands/bigchaindb.py", line 348, in main
    utils.start(create_parser(), sys.argv[1:], globals())
  File "/home/code/fork/bigchaindb/bigchaindb/commands/utils.py", line 204, in start
    return func(args)
  File "/home/code/fork/bigchaindb/bigchaindb/commands/utils.py", line 49, in configure
    command(args)
  File "/home/code/fork/bigchaindb/bigchaindb/commands/utils.py", line 75, in start_logging
    setup_logging(user_log_config=config.get('log'))
  File "/home/code/fork/bigchaindb/bigchaindb/log/setup.py", line 50, in setup_logging
    setup_sub_logger(user_log_config=user_log_config)
  File "/home/code/fork/bigchaindb/bigchaindb/log/setup.py", line 39, in setup_sub_logger
    server = LogRecordSocketServer()
  File "/home/code/fork/bigchaindb/bigchaindb/log/setup.py", line 157, in __init__
    super().__init__((host, port), handler)
  File "/usr/lib/python3.5/socketserver.py", line 440, in __init__
    self.server_bind()
  File "/usr/lib/python3.5/socketserver.py", line 454, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use
```

A way to configure it would be brilliant ! We cannot run Docker.
