### ISSUE TITLE
Improved debuggability for BigchainDB Server

### ISSUE THREAD

**Issue by TimDaub** [bigchaindb/bigchaindb#1189]
# Improved debuggability for BigchainDB Server

## Disclaimer

This ticket's scope is currently defined to loosely! In order to execute on it, some time will need to be spend on defining termination conditions for what must be implemented to "finish" this project.

## Definitions

- **BigchainDB:** Is a scalable blockchain database, the *server* software.
- **BigchainDB driver:** Is an application used to construct, send and receive payloads from BigchainDB.
- **BigchainDB SaaS:** Is BigchainDB deployed as a service by a BigchainDB operator for BigchainDB users (e.g. IPDB).
- **BigchainDB GmbH:** Is the company that develops BigchainDB.
- **BigchainDB developer:** Is an individual working for BigchainDB GmbH working on BigchainDB.
- **BigchainDB operator:** Is an individual deploying BigchainDB in an environment (testing, staging, production, etc.).
- **BigchainDB user:** Is an individual either using BigchainDB deployed as a service or BigchainDB the software (deployed themselves).

**NOTE:** The roles of BigchainDB developer, operator and user can intersect or even be equal, meaning all permutations of roles can be the case (e.g. a BigchainDB developer that is neither a BigchainDB user or BigchainDB operator or a BigchainDB operator that is also a BigchainDB user, but not a BigchainDB developer, etc.)

## Problem statement

Soon, BigchainDB will be deployed in testing, staging and production environments (many of them located on remote machines). For any operators of nodes or federations we'd like to enable them giving BigchainDB developers precise feedback in case of anomalous behavior in their deployments so that
BigchainDB GmbH (BigchainDB developers and BigchainDB operators) can fix these issues effectively.
The overarching theme of this project is **to make firefighting on IPDB as efficient as possible in the time given to complete the project.**

## Distinction

This project is only concerned with improving the debuggability of BigchainDB, not e.g. BigchainDB driver.

## Use cases

This section outlines use cases as user stories ordered by priority, grouped by their stakeholders. They're ordered by priority (actually not yet, but they will be). If you know from users that are interested in a specific aspect, feel free to update this list without changing the prioritization. If you're a user and you're currently reading this ticket, feel free to comment below to let us know what's important to you.

### Business use cases

- As BigchainDB GmbH I want BigchainDB to be efficiently debuggable so that I can efficiently fix issues of BigchainDB SaaS instances (most importantly on IPDB).
- As BigchainDB GmbH I want BigchainDB to be efficiently debuggable so that BigchainDB users and BigchainDB operators can submit high quality issue reports to BigchainDB developers.
- As a BigchainDB GmbH I want to process BigchainDB's logs so that I can use this information to build a node dashboard [(for some of the metrics involved, see this gdrive doc - only circulated internally currently](https://docs.google.com/document/d/1u9eyezFGxcdKVgn5gJ75ch0gT1jNM1V7d5M9THa5x7c/edit#heading=h.p3xjnrw0k0ys), NOTE: "health" is undefined currently!).
- (*if there are more, please feel free to add them here or in the comments*)

### External user use cases

- As a BigchainDB user I want to read BigchainDB's logs so that I can determined why a transaction I sent was labeled invalid by consensus or refused by BigchainDB's HTTP API server (e.g. in schema validation).
- As a user I want to determine exactly when an error occurred (e.g. exact timestamp, atomic counter) so that a developer or operator looking at my error report can easily find what happened in the logs
- (*if there are more, please feel free to add them here or in the comments*)

### Technical use cases

- [As a BigchainDB developer and user I want exceptions thrown by BigchainDB to be categorized hierarchically so that I can semantically catch specific groups of exceptions.](https://github.com/bigchaindb/bigchaindb/issues/723)
- [As a BigchainDB developer I want to read logs of BigchainDB so that I can troubleshoot BigchainDB and BigchainDB SaaS](https://github.com/bigchaindb/bigchaindb/issues/663).
    - As a BigchainDB developer I want to easily filter logs of BigchainDB so that I can efficiently troubleshoot BigchainDB and BigchainDB SaaS
- [As a BigchainDB developer I want to read and process logs of BigchainDB so that I can proof and debug the correctness of asynchronously executing processes in BigchainDB](https://github.com/bigchaindb/bigchaindb/issues/1188)
- As a BigchainDB developer I want visibility on the performance of queries so that I can troubleshoot and debug performance problems on a running BigchainDB instance
- As a BigchainDB developer I want visibility on the state of a running BigchainDB node's pipelines so that I can reconstruct a similar state during testing and troubleshooting
- As a BigchainDB developer I want time control over a running BigchainDB pipeline so I can time travel and replay certain events to help me understand an error
- As a BigchainDB operator I want to persist logs of BigchainDB so that I can run BigchainDB as a daemon (NOTE: Running BigchainDB is a precondition here).
- As a BigchainDB operator I want BigchainDB's logs to be timestamped so that [... motivation missing].
- As a BigchainDB operator I want BigchainDB's logs to include errors, warnings and infos of BigchainDB's data base back end (e.g. RethinkDB, MongoDB, etc.)
- As a BigchainDB operator I want to aggregate logs from all nodes in a federation so I can understand and troubleshoot an entire running federation (as well as the effects of a single node on the federation)
- As a BigchainDB operator I want to increase or decrease log levels of running nodes so I don't have to restart a running system (and potentially lose important state related to an error)
- (*if there are more, please feel free to add them here or in the comments*)

## Actionables and Deliverables

- [x] Have a kick-off meeting for this project (@TimDaub will call it)
- [x] Review use cases and potentially add complementary use cases if necessary
- [x] A list of tasks defining the implementation part of this project
    - [x] Call a review meeting on changes planned to implement (review the
      task list) with the various stakeholders (Team lead calls meeting)
- [x] Implement planned changes

## Kick-off meeting notes

- A BigchainDB daemon mode might be useful
    - this means that logs would then be written to a file
- Is this ticket is only about BigchainDB (the server)
- How do we distinguish between errors, warnings and infos? What should we log?
    - Answer: Whatever it takes to make IPDB firefighting more efficient.
- What's meant by "operator"
    - Tim: I'll fix that in the ticket
    - Is operator someone that can fix a bug: answer, maybe...
- Do logs need to be tracked in wall-clock-time or logical-time?
    - TDB?
- What's "health"?
    - Yeah, we need to define what "health" means first.
- We should call certain failures by there name. A failure might involve specific lines in the log.  Their sum equal a greater failure. It would be nice to give the failure a name and log that.

## Existing technical problems on BigchainDB Server

In this section we list tickets related to this project. If you have any
tickets to add, please feel free to do so.

- [Proposal for BigchainDB Exception Hierarchy](https://github.com/bigchaindb/bigchaindb/issues/721)
- [Log more](https://github.com/bigchaindb/bigchaindb/issues/663)
- [Logging requirements for pipeline correctness](https://github.com/bigchaindb/bigchaindb/issues/1188)
- [Add debugging mode](https://github.com/bigchaindb/bigchaindb/issues/866)
- [In HTTP API, consider using custom error handlers](https://github.com/bigchaindb/bigchaindb/issues/1073)
- Maybe: [Unify database exceptions and unify behavior on reconnects](https://github.com/bigchaindb/bigchaindb/issues/1158)
- Maybe: [Remove unnecessary exceptions](https://github.com/bigchaindb/bigchaindb/issues/723)
- (*if there are more, please feel free to add them here or in the comments*)

**Comment by sohkai** [comment]
> * [Add debugging mode](#866)

This may fall somewhat outside the scope of this project, but this is a use-case that's solely targeted at developers:

> As a BigchainDB developer I want to be able to set deterministic breakpoints across all running pipelines so that I can understand what's going on internally and fix bugs and errors in BigchainDB efficiently.

**Comment by sohkai** [comment]
Some links on logging that may be interesting:

* https://dave.cheney.net/2015/11/05/lets-talk-about-logging
* https://peter.bourgon.org/blog/2016/02/07/logging-v-instrumentation.html

**Comment by TimDaub** [comment]
> As a BigchainDB developer I want to be able to set deterministic breakpoints across all running pipelines so that I can understand what's going on internally and fix bugs and errors in BigchainDB efficiently.

I framed it like this @sohkai. I hope that's fine. If not, I'll just replace it with your framing.


> As a BigchainDB developer I want to read and process logs of BigchainDB so that I can proof and debug the correctness of asynchronously executing processes in BigchainDB

**Comment by sohkai** [comment]
Some added use cases (diff overview from the changes to the issue; `+` is an addition):

```
### External use cases

+ As a user I want to determine exactly when an error occurred (e.g. exact timestamp, atomic counter) so that a developer or operator looking at my error report can easily find what happened in the logs

### Technical use cases

- [As a BigchainDB developer I want to read logs of BigchainDB so that I can troubleshoot BigchainDB and BigchainDB SaaS](https://github.com/bigchaindb/bigchaindb/issues/663).
    + As a BigchainDB developer I want to easily filter logs of BigchainDB so that I can efficiently
+ As a BigchainDB developer I want visibility on the performance of queries so that I can troubleshoot and debug performance problems on a running BigchainDB instance
+ As a BigchainDB developer I want visibility on the state of a running BigchainDB node's pipelines so that I can reconstruct a similar state during testing and troubleshooting
+ As a BigchainDB developer I want time control over a running BigchainDB pipeline so I can time travel and replay certain events to help me understand an error
+ As a BigchainDB operator I want to aggregate logs from all nodes in a federation so I can understand and troubleshoot an entire running federation (as well as the effects of a single node on the federation)
+ As a BigchainDB operator I want to increase or decrease log levels of running nodes so I don't have to restart a running system (and potentially lose important state related to an error)
```

**Comment by ttmc** [comment]
I'm removing the "when: in progress" label on this issue because I'm pretty sure it's not in progress.
