### ISSUE TITLE
Document guarantees for 1.0

### ISSUE THREAD

**Issue by libscott** [bigchaindb/bigchaindb#1194]
This is related to the work on Security, Stability and Correctness that is being done for 1.0.

The deliverable is a document ready to be published (as part of docs.bigchaindb.com) about what guarantees are provided.

This can also be delivered as a work in progress where guarantees are listed as they are added. It's also important to start to qualify what we mean by "guarantee" as there will be some basic assumptions.

Once we have this in place we can close some old issues that pertain to guarantees we are not providing or not going to provide in the near term (#336 for example).

**Comment by TimDaub** [comment]
I just noticed that this duplicates #595.

I'll close this ticket and reference in #595 to here.
