### ISSUE TITLE
[logging] setup basic configuration for logging

### ISSUE THREAD

**Issue by sbellem** [bigchaindb/bigchaindb#1202]
*loosely defined for now*

may include:

- [x] log to file #1204 
* log levels configurable *per component*
* log formatting

### Actions

- [x] **[main]** setup logging for main process (config, tests, etc)
- [ ] **[http api]** Integrate logging with flask/gunicorn
- [x] **[pipelines]** Tackle `multipipes` logging -- see [celery](http://docs.celeryproject.org/en/3.0/history/whatsnew-3.0.html#logging-improvements) as an example
- [x] **small detail**: use `logging.DEBUG` and so on to refer to logging levels rather than the integer or string representation
- [x] Decide on default log level. Note that:

> The default level is `WARNING`, which means that only events of this level and above will be tracked, unless the logging package is configured to do otherwise. [(ref)](https://docs.python.org/3.6/howto/logging.html#when-to-use-logging)

#### About threads when using `logging.basicConfig(**kwargs)`
If using  [`logging.basicConfig(**kwargs)`](https://docs.python.org/3.6/library/logging.html#logging.basicConfig):

 > This function should be called from the main thread before other threads are started. In versions of Python prior to 2.7.1 and 3.2, if this function is called from multiple threads, it is possible (in rare circumstances) that a handler will be added to the root logger more than once, leading to unexpected results such as messages being duplicated in the log. 

#### Integration with the warnings module: ` logging.captureWarnings(capture)`
See https://docs.python.org/3.6/library/logging.html#integration-with-the-warnings-module

#### Multiprocessing & Logging
* https://mail.python.org/pipermail/python-list/2012-April/622522.html
* http://plumberjack.blogspot.de/2010/09/using-logging-with-multiprocessing.html
* http://plumberjack.blogspot.de/2010/09/improved-queuehandler-queuelistener.html
* http://stackoverflow.com/questions/641420/how-should-i-log-while-using-multiprocessing-in-python#894284
* https://github.com/jruere/multiprocessing-logging
* [Eliot: Logging for Complex & Distributed Systems](https://github.com/ScatterHQ/eliot)
* https://docs.python.org/3.6/library/multiprocessing.html#logging (thanks @r-marques)
* http://stackoverflow.com/questions/14643568/is-a-logger-accessible-to-both-parent-and-child-processes

#### Unit testing and logging
* http://plumberjack.blogspot.de/2010/09/unit-testing-and-logging.html

#### Alternatives to stdlib `logging`?
* http://logbook.readthedocs.io/ (see post http://plumberjack.blogspot.de/2010/09/python-logging-functionality-facts-vs.html)

**Comment by sohkai** [comment]
Notes for log formatting:

* We can specify process and thread id via `%(process)d and %(thread)d`

**Comment by sbellem** [comment]
> We can specify process and thread id via %(process)d and %(thread)d

indeed, and much more :smile: : https://docs.python.org/3.6/library/logging.html#logrecord-attributes

**Comment by trentmc** [comment]
Of course, please careful not to swamp the line with too much info, it gets out of control very quickly.
