### ISSUE TITLE
[logging] add rotating file handler

### ISSUE THREAD

**Issue by sbellem** [bigchaindb/bigchaindb#1204]
- [ ] See https://docs.python.org/3.6/library/logging.handlers.html#logging.handlers.RotatingFileHandler and https://docs.python.org/3.6/howto/logging-cookbook.html#using-file-rotation

see https://docs.python.org/3.6/howto/logging.html#useful-handlers for other possible file handlers

### Aggregating logs generated from different processes
- [ ] See [Logging to a single file from multiple processes](https://docs.python.org/3.6/howto/logging-cookbook.html#logging-to-a-single-file-from-multiple-processes) and [A more elaborate multiprocessing example](https://docs.python.org/3.6/howto/logging-cookbook.html#using-file-rotation)

**Comment by libscott** [comment]
Couldn't we use supervisord?

**Comment by sbellem** [comment]
> Couldn't we use supervisord?

We are just kicking off this project, and we can look into alternatives later.  The first cut is meant to be as simple as possible, and limiting ourselves to the standard library can help us to keep things simple for now.

**Comment by krish7919** [comment]
I would recommend using the logging.handlers  RotatingFileHandler for now when we instantiate the logger. Keep it to a fixed 200MB size with 5 backups.
That should be enough.
I am still rooting for the UDP socket idea though. I feel it keeps things simple and becomes less of a perf bottleneck for us. And we can do richer log processing outside the DB.

**Comment by libscott** [comment]
* UDP is a lossy, unordered socket.
* It would be better at this point to prioritize event replayability IE of the HTTP interface
* We don't really need an opinionated solution to log output right now, we just need the outputs to work...

**Comment by krish7919** [comment]
@libscott:
> UDP is a lossy, unordered socket

Hence the localhost and the UDP.

> It would be better at this point to prioritize event replayability IE of the HTTP interface

Are you sure that increasing log verbosity in the system will not hurt performance? Json marshalling and unmarshalling, handling network events for _logging_ affecting  core functionality. Logging is a fine line between capturing all interesting events without hurting performance.
I have faced scenarios where increasing debug levels have actually made the problem worse, or directed at different pain-points than the real issue.

> We don't really need an opinionated solution to log output right now, we just need the outputs to work...

I honestly think I have a much stronger proposal that can last long term without affecting DB functionality.
Please let me know if you need clarifications and I will be happy to elaborate and listen to inputs.

**Comment by libscott** [comment]
Ok, true, it's a separate concern; replayable logs can be obtained using an intermediary such as nginx.
