### ISSUE TITLE
Consensus cleanup

### ISSUE THREAD

**Issue by libscott** [bigchaindb/bigchaindb#1206]
Cleanup of calls to concensus / validate methods

- [x] `Bigchain.is_new_transaction` method, called from Block and Vote pipelines 
- [x] Merge tymelez concensus PR
- [x] Remove access of `consensus` object in pipeline/*
- [x] ~Load `consensus` plugins only once~
- [x] ~All validation exceptions derive from "ValidationError"~
- [x] #1149

Related to #1108, #1222

**Comment by ttmc** [comment]
I think the `@lru_cache()` on the line before `def load_consensus_plugin(name=None):` makes it load only once.

@vrde did that originally, so he knows more.
