### ISSUE TITLE
Validate block voters list

### ISSUE THREAD

**Issue by libscott** [bigchaindb/bigchaindb#1224]
Validate that block voters list matches server keyring (possibly up to some threshold) when voting

@ttmc from #1168:

> I had some more thoughts about the problem of a malicious node writing a baloney voters list into a block it creates. There are at least two bad things a malicious node can do to the voters list in blocks it creates:
> 
> * remove legit public keys of the other federation nodes, preventing them from voting on the block
> * add fake "sybil" public keys of imaginary federation nodes, for which it has all the corresponding private keys, so it can produce valid votes
> 
> While checking the voters list against the "federation keyring" is one way to prevent those problems, there are other options. In particular, each node could have a rule something like:
> 
> "One condition for this block to get a vote-of-valid from me is that its voters list must differ from mine by at most one public key."
> 
> (The list lengths can differ, but so can the list values.)
> 
> It can't be 100% because we need to allow for nodes to come and go from the federation from time to time, but it will take time for all federation nodes to update their local keyrings.
> 
> If we take this approach, we need to re-evaluate how many votes are needed on a block to switch it from undecided to valid/invalid. 50% is probably too low. 66.7% seems like it would suffice. It's not like block validity is a matter of opinion: the usual outcome is that all nodes will agree that a block is valid/invalid. Any disagreement from any node should be a red flag to investigate further.

**Comment by ttmc** [comment]
BigchainDB 2.0 is coming out soon and it doesn't care about the "voter list" (list of current validators). It now leaves those concerns to separate consensus software. Therefore this is no longer an issue for BigchainDB, and I am closing it.
