### ISSUE TITLE
Outputs endpoint needs more information

### ISSUE THREAD

**Issue by libscott** [bigchaindb/bigchaindb#1227]
See example from @jmduque on Gitter: https://files.gitter.im/bigchaindb/bigchaindb/amnB/blob

Use case is to provide "all required information to do next transactions".

https://gitter.im/bigchaindb/bigchaindb?at=58b69b8bf1a33b627564e38e

**Comment by TimDaub** [comment]
Note that this is in contrast to the discussion [here](https://github.com/bigchaindb/bigchaindb/issues/835#issuecomment-261484854)

**Comment by jmduque** [comment]
@TimDaub Hi Tim, the missing point for us to do transactions is:

 - We don't know which output holds which asset
 - For divisible assets, we don't know how much amount each output holds

So, this becomes a problem when:
 - We want to transfer an specific asset from user A to B, impossible to know which output holds the asset without doing a one-by-one request of all transactions for valid outputs, OR
 - We want to transfer an X amount from Asset C from user A to B, even if we assume all transactions to be same asset, we don't know which are the best outputs to transfer from user A to B (i.e., user A has outputs with amount 100, 200 and 300 and we want to transfer 300 to user B, somehow is best to only request the transaction that holds the 300 amount output to minimize requests and data transfers, but we have no way to know that)

**Comment by TimDaub** [comment]
Hey @jmduque, in #1545 we've updated the `/outputs` endpoint to return objects now.
For the exact changes see this [tentative document](https://github.com/bigchaindb/bigchaindb/blob/babe5311a46684ef7679ec843b1f600a7bceed38/docs/upgrade-guides/v0.10--%3Ev1.0.md#get-apiv1outputs).

After releasing our upcoming version, we'll include `asset_id` into the response and offer a `safe=false` status flag that will return the output object as was requested by you. To learn more on what we want to go for, check out this [tentative design](https://github.com/bigchaindb/bigchaindb/blob/99499b1f8783719a082813912ac9a0d363ae278f/bdb-ip.md#proposed-outputs-endpoint-design) and let us know if you have any feedback.
