### ISSUE TITLE
Better handling of timeouts in the block creation

### ISSUE THREAD

**Issue by r-marques** [bigchaindb/bigchaindb#123]
The way that the block creation works is:
- Try to read 1000 transactions
- If less then 1000 transactions are available wait up to 5 seconds and create a block with less then 1000 transactions.

We included this timeout so that if the system is slow we do not create unnecessary small blocks.
The problem is that this timeout is not absolute, its reset everytime a new transaction comes in so for eg if transactions were to come in every 4 sec we would wait up to 4000 sec before creating the block.

We need to make this timeout absolute for a given block so that each block creation will wait at most 5 secs for new transactions before creating the block.

**Comment by ttmc** [comment]
Related issue #427

**Comment by ttmc** [comment]
This is no longer an issue with the release of BigchainDB 2.0, which works differently.
