### ISSUE TITLE
All transactions must be signed 

### ISSUE THREAD

**Issue by libscott** [bigchaindb/bigchaindb#1230]
All transactions must be signed to prevent malleability

**Comment by libscott** [comment]
Currently this is a property of not supporting hashlocks.

**Comment by r-marques** [comment]
For additional discussion about this problem see #339

**Comment by r-marques** [comment]
@sbellem can we close this since we removed support for hashlocks in BigchainDB 1.0?

**Comment by sbellem** [comment]
> can we close this since we removed support for hashlocks in BigchainDB 1.0?

Yes.

**Comment by sbellem** [comment]
Perhaps we should rename the title to something like: 

Hashlock-based transactions must be signed

even though we're closing the issue.
