### ISSUE TITLE
get_outputs: tx_link is referenced before assignment

### ISSUE THREAD

**Issue by TimDaub** [bigchaindb/bigchaindb#1231]
@suceda reported this on Gitter:

> Im using the bigchaindb version 0.9.1.
> The issue is that I’m getting a 500 internal server error when calling the outputs http API: /outputs?public_key=CuG1ejQ6foAyS5dvZicVopWYS3e6ZtNALpEkeVUtN9t5

[Click for the stack trace](https://files.gitter.im/bigchaindb/bigchaindb/2tT5/Screen-Shot-2017-03-02-at-11.47.04-AM.png)

> First I created a CREATE transfer with user A. Then I transfered part of his asset amount to user B. The tx looks like this:

[Click for the tx](https://files.gitter.im/bigchaindb/bigchaindb/moFL/Screen-Shot-2017-03-02-at-11.56.29-AM.png)

> The tx status is valid btw.

If we look at [`get_outputs`](https://github.com/bigchaindb/bigchaindb/blob/master/bigchaindb/core.py#L402), it seems that for `CuG1ejQ6foAyS5dvZicVopWYS3e6ZtNALpEkeVUtN9t5`:

```
for index, output in enumerate(tx['outputs']):
                if len(output['public_keys']) == 1:
                    if output['condition']['details']['public_key'] == owner:
                        tx_link = TransactionLink(tx['id'], index)
                else:
                    if utils.condition_details_has_owner(output['condition']['details'], owner):
                        tx_link = TransactionLink(tx['id'], index)
                links.append(tx_link)
```

None of the statements yield `True`, which apparently can happen but wasn't expected from us.

**Comment by sbellem** [comment]
**perhaps** related to https://github.com/bigchaindb/bigchaindb/pull/1200
