### ISSUE TITLE
Queues are unbounded

### ISSUE THREAD

**Issue by r-marques** [bigchaindb/bigchaindb#124]
The voter and block processes use queues to communicate internally. Right now these queues are unbounded. We need to benchmark the current implementation, understand its memory requirements and put a limit to the size of the queues.

**Comment by r-marques** [comment]
I guess this is still valid although the queues are handled by pipelines

**Comment by wxcsdb88** [comment]
#781 #124
Maybe the  `RethinkDB`\`s `changefeed` can\`t deal the mass change feedback for `backlog` and the total txs in backlog will become more.
If the changes for `backlog` can\`t deal in time, it will increase the memory.
The query `ReQL` for the `backlog` will use more time and memory. Repeat that(continuously write the backlog and query the backlog ), the memory will be run out .
In my opinion, limit the amount of backlog and improve the capacity of the `changefeed` maybe better for that.

**Comment by vrde** [comment]
> I guess this is still valid although the queues are handled by pipelines

yep it is, this might be also one of the reasons why BigchainDB eats up a lot of memory. Adding a size to the `queue`s is straightforward. I'll take some time next week to better documentation, see https://github.com/bigchaindb/multipipes/issues/2
