### ISSUE TITLE
create_transaction not exist

### ISSUE THREAD

**Issue by vincent0330** [bigchaindb/bigchaindb#1245]
def speedtest_validate_transaction():
    # create a transaction
    b = bigchaindb.Bigchain()
    tx = b.create_transaction(b.me, b.me, None, 'CREATE')
    tx_signed = b.sign_transaction(tx, b.me_private)

but:
Why the method "create_transaction " not exist?
Thanks for your replay.

**Comment by vincent0330** [comment]
Or which branch?

**Comment by TimDaub** [comment]
Hi @vincent0330.

the folder you're pointing to hasn't been updated in a while now. `create_transaction` has been replaced with the transaction model in `bigchaindb.common.transaction`. The speed-tests would have to be rewritten with the model to work.
We're planning to update these and other benchmarks in the next 1-2 months.
If you want, I can update you on our progress.

**Comment by r-marques** [comment]
@TimDaub maybe we should just delete that folder.

A lot changed since those tests were written and most of the code and automation scripts are no longer valid.

**Comment by TimDaub** [comment]
Doing benchmarks is on [our roadmap](https://github.com/bigchaindb/org/blob/master/ROADMAP.md) scheduled for a 1.0 release, meaning we'll not forget about it :)

As @r-marques suggested: To close this ticket, we should delete the [speed-tests] folder (https://github.com/bigchaindb/bigchaindb/tree/master/speed-tests).

**Comment by r-marques** [comment]
@TimDaub since we are at it I think the same should be done for the [benchmarking-tests](https://github.com/bigchaindb/bigchaindb/tree/master/benchmarking-tests) folder.

**Comment by vincent0330** [comment]
:)，OK
