### ISSUE TITLE
blockchainDB docker connect failed

### ISSUE THREAD

**Issue by EasonWang01** [bigchaindb/bigchaindb#1256]
requests.exceptions.ConnectionError: HTTPConnectionPool(host='bdb-server', port=9984): Max retries exceeded with url: /api/v1/transactions/ (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x10263d470>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))

```
from bigchaindb_driver import BigchainDB
from bigchaindb_driver.crypto import generate_keypair
bdb = BigchainDB('http://bdb-server:9984')


bicycle = {
  'data': {
    'bicycle': {
      'serial_number': 'abcd1234',
      'manufacturer': 'bkfab',
    },
  },
}

metadata = {'planet': 'earth'}

alice, bob = generate_keypair(), generate_keypair()


prepared_creation_tx = bdb.transactions.prepare(
       operation='CREATE',
       signers=alice.public_key,
       asset=bicycle,
       metadata=metadata,
   )




fulfilled_creation_tx = bdb.transactions.fulfill(prepared_creation_tx, private_keys=alice.private_key)

print(fulfilled_creation_tx)

sent_creation_tx = bdb.transactions.send(fulfilled_creation_tx)
```

<img width="1249" alt="2017-03-07 5 01 00" src="https://cloud.githubusercontent.com/assets/11001914/23648973/b52b58c4-0357-11e7-98a6-09f661a237c0.png">

**Comment by sbellem** [comment]
Hi @EasonWang01 

 could you please tell us which versions you use for the server and driver?

**Comment by EasonWang01** [comment]
I install driver using `pip3 install bigchaindb_driver` and server using this compose file https://github.com/bigchaindb/bigchaindb-driver/blob/master/docker-compose.yml

how to checkout the actual version

**Comment by sbellem** [comment]
the `docker-compose.yml` rely on a Dockerfile: https://github.com/bigchaindb/bigchaindb-driver/blob/master/compose/server/Dockerfile#L12

so the version right now is `0.9.1`

**Comment by EasonWang01** [comment]
So is this version ok?what might cause this problem?

**Comment by sbellem** [comment]
Are you running the driver in a container too, or you are running on your localhost?

**Comment by sbellem** [comment]
> So is this version ok?what might cause this problem?

I think it may be because you are running the driver on your localhost not in a container that is "linked" to the server container. If that would be the case, you would need to set the host to the host of the docker engine. This may depend on how you are running docker. On linux systems that would be `localhost`.

**Comment by EasonWang01** [comment]
It says

```
  raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=9984): Max retries exceeded with url: /api/v1/transactions/ (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x10ef15470>: Failed to establish a new connection: [Errno 61] Connection refused',))
```

**Comment by sbellem** [comment]
Please the following docs, as it may help: https://docs.bigchaindb.com/projects/py-driver/en/latest/connect.html#case-3-docker-container-on-localhost

If that does not help, please let me know.

**Comment by EasonWang01** [comment]
It says 
```
requests.exceptions.ConnectionError: HTTPConnectionPool(host='0.0.0.0', port=32780): Max retries exceeded with url: /api/v1/transactions/ (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x1029f32e8>: Failed to establish a new connection: [Errno 61] Connection refused',))
```

<img width="1067" alt="2017-03-07 7 35 53" src="https://cloud.githubusercontent.com/assets/11001914/23654787/554ed14a-036d-11e7-8992-2b22493e511b.png">

**Comment by EasonWang01** [comment]
I got it,wrong port.

**Comment by sbellem** [comment]
Ok, thanks!

**Comment by EasonWang01** [comment]
do you know which one is better for production now?

1.blockchainDB

2.database with cluster and encrypt data hash.

**Comment by sbellem** [comment]
BigchainDB is not ready for production yet. So if you need a production-ready system right now, the second alternative you list (db clsuter with encryption/hashing), assuming the chosen database is production-ready would be better.

**Comment by EasonWang01** [comment]
thanks

**Comment by TimDaub** [comment]
@EasonWang01 We're currently working closely with some of our lead customers to put their system into production with BigchainDB.

"Production-ready" is not binary and for some scenarios, customers mutually agree with us that BigchainDB can already be deployed in production (specifically: that's scenarios where it's being deployed as a centralized system for now).

We'd be happy to work with you to deploy BigchainDB into production. If you're interested contact us directly at product@bigchaindb.com.
