### ISSUE TITLE
Define how a federation is managed

### ISSUE THREAD

**Issue by r-marques** [bigchaindb/bigchaindb#126]
We need to define:
- [ ] How a federation is created.
- [ ] How it is configured.
- [ ] How nodes join or leave the federation

There are two parts we need to handle when configuring a node:
- Configuring the datastore (RethinkDB). Add the other hosts to be able to join the cluster, sharding, replication, intra cluster TLS
- Configure BigchainDB. Exchange of pub keys between federation nodes.

**Comment by ttmc** [comment]
Issue #135 accidentally covered some of the same ground as this one, so I closed it and said I'd copy the text here for convenience:

**Troy:**

We need some code, tools and instructions to add a node to a BigchainDB cluster (or to remove a node from a cluster).

Remember that BigchainDB is supposed to be decentralized, meaning each node is normally going to be owned and controlled by a different person or organization. The normal way to build a cluster will be for each new member to get permission to join (from the organization governing the cluster, i.e. outside the scope of the software), and then they'll get instructions on how to start up a new BigchainDB node and get it talking to the rest of the cluster.

How will that work? Will the other nodes have to add the new node's public key first? How will they get the public key?

If someone wants to set up a **test cluster** or a **centrally-controlled cluster** (where one entity controls all nodes), then they can do that by repeating the add-one-node instructions over and over again (maybe with a script).

-----------
**Sylvain:**

Just in case this may be helpful: https://docs.saltstack.com/en/latest/topics/tutorials/multimaster.html

**Comment by r-marques** [comment]
@troy is this a duplicate of #388 or #331 ?

**Comment by troy** [comment]
@r-marques: wrong Troy :)

**Comment by r-marques** [comment]
sorry @troy I meant to mention @ttmc

**Comment by ttmc** [comment]
Yeah, issue #331 covers defining how a federation is managed, so I'll close this issue.
