### ISSUE TITLE
Call to has_previous_vote in Vote pipeline shouldn't be there

### ISSUE THREAD

**Issue by libscott** [bigchaindb/bigchaindb#1264]
Since the voting pipeline is reacting to changefeed events on the blocks table, and the blocks table does not experience updates, there should not in theory be a duplicated opportunity to vote on a block. Nodes must vote on the same blocks in the same order, the order dictated by the primary. If there is a previous vote then this is a critical error that requires investigation; the correct behaviour should be a duplicate key exception (given #1258).

@ttmc @roderik

**Comment by ttmc** [comment]
A RethinkDB client might get the same changefeed notification multiple times; see this comment:

https://github.com/rethinkdb/docs/issues/778#issuecomment-105203152

Apparently, a RethinkDB "proxy" can deduplicate the changefeed to clients.

I'm not sure of other scenarios which might cause the same block to appear multiple times in the changefeed. I'm reluctant to say it can never happen.

**Comment by libscott** [comment]
That could represent a small problem running with multiple nodes on RethinkDB then.
