### ISSUE TITLE
Crypto-conditions spec according to ILP

### ISSUE THREAD

**Issue by r-marques** [bigchaindb/bigchaindb#127]
Since we are now starting to use multisig it may make sense to consider switching to `ed25519`.
Slightly faster then ecdsa, efficient threshold signatures, no known signature malleability issues.

We would need to find a good implementation with python bindings.

**Comment by diminator** [comment]
The guys from Ripple have a good standard for these things:

https://github.com/interledger/five-bells-condition/blob/feature/binary-merkle-v2/docs/spec.md
https://www.youtube.com/watch?v=YfBDDWp58po

Basically we only need to convert the JavaScript to Python
