### ISSUE TITLE
bigchaindb.common.exceptions.MultipleVotesError

### ISSUE THREAD

**Issue by vincent0330** [bigchaindb/bigchaindb#1274]
The error:
INFO:bigchaindb.pipelines.block:Write new block 32e642020de94d306f38636063cb057559dafcb3042a9618d2c38b8177c54c38 with 1 transactions
INFO:bigchaindb.pipelines.vote:Voting 'valid' for block e894e82f40ca0aae281346b78ea76d7e073e72bfe956568d1a12ebf7342d15d8
INFO:bigchaindb.pipelines.vote:Voting 'valid' for block 32e642020de94d306f38636063cb057559dafcb3042a9618d2c38b8177c54c38
Process Process-21:
Traceback (most recent call last):
File "/usr/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
self.run()
File "/usr/lib/python3.5/multiprocessing/process.py", line 93, in run
self._target(*self._args, **self._kwargs)
File "/usr/local/lib/python3.5/dist-packages/multipipes/pipeline.py", line 67, in safe_run_forever
self.run_forever()
File "/usr/local/lib/python3.5/dist-packages/multipipes/pipeline.py", line 74, in run_forever
self.run()
File "/usr/local/lib/python3.5/dist-packages/multipipes/pipeline.py", line 106, in run
result = self.target(*args)
File "/usr/local/lib/python3.5/dist-packages/bigchaindb/pipelines/election.py", line 39, in check_for_quorum
next_block['block']['voters'])
File "/usr/local/lib/python3.5/dist-packages/bigchaindb/core.py", line 630, in block_election_status
.format(block_id=block_id, n_votes=str(voter_counts[node]), node_id=node))
bigchaindb.common.exceptions.MultipleVotesError: Block e894e82f40ca0aae281346b78ea76d7e073e72bfe956568d1a12ebf7342d15d8 has multiple votes (2) from voting node DSdxn7V9XLtQR6f1Ua4qiEGYuTfKztyh1dYLkCMTqv2M

My bigchaindb's backend database is MongoDB,the replSet has 3 nodes.
The bigchain-rs :
{
"_id" : "bigchain-rs",
"version" : 4,
"protocolVersion" : NumberLong(1),
"members" : [
{
"_id" : 0,
"host" : "192.168.1.20:27017",
"arbiterOnly" : false,
"buildIndexes" : true,
"hidden" : false,
"priority" : 1,
"tags" : {

		},
		"slaveDelay" : NumberLong(0),
		"votes" : 1
	},
	{
		"_id" : 1,
		"host" : "192.168.1.30:27017",
		"arbiterOnly" : false,
		"buildIndexes" : true,
		"hidden" : false,
		"priority" : 1,
		"tags" : {
			
		},
		"slaveDelay" : NumberLong(0),
		"votes" : 1
	},
	{
		"_id" : 2,
		"host" : "192.168.1.19:27017",
		"arbiterOnly" : false,
		"buildIndexes" : true,
		"hidden" : false,
		"priority" : 1,
		"tags" : {
			
		},
		"slaveDelay" : NumberLong(0),
		"votes" : 1
	}
],
"settings" : {
	"chainingAllowed" : true,
	"heartbeatIntervalMillis" : 2000,
	"heartbeatTimeoutSecs" : 10,
	"electionTimeoutMillis" : 10000,
	"catchUpTimeoutMillis" : 2000,
	"getLastErrorModes" : {
		
	},
	"getLastErrorDefaults" : {
		"w" : 1,
		"wtimeout" : 0
	},
	"replicaSetId" : ObjectId("58c64c6438a038a2d7650fdc")
}
}

**Comment by libscott** [comment]
Hi vincent,

Could you say which version of BigchainDB you are using?

**Comment by vincent0330** [comment]
Hi, libscott:

Version 0.10.0.dev

**Comment by vincent0330** [comment]
It is recommended to use rethinkdb as a backend database? And not MongoDB?

**Comment by libscott** [comment]
No, MongoDB is the recommended database backend.

**Comment by libscott** [comment]
Do each of your nodes have different keys, or did the same config somehow get replicated across all the nodes? By default this config is in `~/.bigchaindb`. If they `keypair` is the same for multiple nodes, that woul d explain the issue.

**Comment by vincent0330** [comment]
No,I deploy the environment in different virtual machines. All of them have different keys and config.
Such as:
1.

{
    "backlog_reassign_delay": 120,
    "keypair": {
        "private": "8FAhMubLe6QUQmzn3WQDpVJqpBaQE1wDtHsEUhEvX3br",
        "public": "5fQ2NQ95XHqK29feCk4HYSc3bkz2TVqpwiDzHgRYF15D"
    },
    "server": {
        "bind": "localhost:9984",
        "workers": null,
        "threads": null
    },
    "database": {
        "port": 27017,
        "backend": "mongodb",
        "host": "localhost",
        "name": "bigchain",
        "replicaset": "bigchain-rs"
    },
    "keyring": []
}

2.
 more ~/.bigchaindb :
{
    "server": {
        "threads": null,
        "bind": "0.0.0.0:9984",
        "workers": null
    },
    "database": {
        "replicaset": "bigchain-rs",
        "host": "127.0.0.1",
        "backend": "mongodb",
        "name": "bigchain",
        "port": 27017
    },
    "keyring": [],
    "keypair": {
        "public": "DSdxn7V9XLtQR6f1Ua4qiEGYuTfKztyh1dYLkCMTqv2M",
        "private": "3ykaEAYd3FDKtGtrwrq5fd6kzzB4CZ2ys2h7NJZHiVAR"
    },
    "backlog_reassign_delay": 120
}

**Comment by vincent0330** [comment]
I probably know:
One of the three BigchainDB,the version is 0.9.3.
I'll try a unified version.

**Comment by vincent0330** [comment]
**All the BigchainDB is 0.9.3, and the same errors:**
Process Process-15:
Traceback (most recent call last):
  File "/usr/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/usr/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.5/dist-packages/multipipes/pipeline.py", line 67, in safe_run_forever
    self.run_forever()
  File "/usr/local/lib/python3.5/dist-packages/multipipes/pipeline.py", line 74, in run_forever
    self.run()
  File "/usr/local/lib/python3.5/dist-packages/multipipes/pipeline.py", line 106, in run
    result = self.target(*args)
  File "/usr/local/lib/python3.5/dist-packages/bigchaindb/pipelines/election.py", line 39, in check_for_quorum
    next_block['block']['voters'])
  File "/usr/local/lib/python3.5/dist-packages/bigchaindb/core.py", line 634, in block_election_status
    n_voters=str(n_voters)))
bigchaindb.common.exceptions.MultipleVotesError: Block 343e272e3d328e365bd218da473265764f37ecfe9abf809401fea79acf3e9af4 has 2 votes cast, but only 1 voters

**Comment by libscott** [comment]
Looking at your config, it appears that the `keyring` is empty? `keyring` should contain the public keys of the other nodes in the federation, ie:

```
"keypair": { public: "foo", private: "..." },
"keyring": ["bar", "baz"]
```

**Comment by vincent0330** [comment]
Thanks, I forgot it.
