### ISSUE TITLE
[shutdown] Error in atexit._run_exitfuncs

### ISSUE THREAD

**Issue by sbellem** [bigchaindb/bigchaindb#1279]
When running bigchaindb with the command `bigchaindb start` and interrupting the process with `CTRL-C`, the following error shows up:

```bash
$ bigchaindb start
# ...
# ...
# ...
# CTRL-C
^CError in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/multiprocessing/popen_fork.py", line 29, in poll
    pid, sts = os.waitpid(self.pid, flag)
KeyboardInterrupt
[2017-03-12 23:29:25 +0000] [34] [INFO] Handling signal: int
```
#### Related links
Listing a few links just in case it may be useful:

* Python docs: [signal](https://docs.python.org/3/library/signal.html#module-signal), [atexit](https://docs.python.org/3/library/atexit.html#module-atexit), [multiprocessing](https://docs.python.org/3/library/multiprocessing.html)
* http://stackoverflow.com/questions/9139127/why-is-my-threading-multiprocessing-python-script-not-exiting-properly#9143486
* http://stackoverflow.com/questions/2546276/python-process-wont-call-atexit#2546397
* http://stackoverflow.com/questions/39884898/large-amount-of-multiprocessing-process-causing-deadlock
* http://stackoverflow.com/questions/19652446/python-program-with-thread-cant-catch-ctrlc
* http://stackoverflow.com/questions/37692262/python-multiprocessing-assertionerror-can-only-join-a-child-process

#### Noteworthy
Quoting Martin Sústrik (original architect and lead developer of ØMQ), in http://aosabook.org/en/zeromq.html (thanks to @krish7919 for the link):

> It turns out that shutting down a fully asynchronous system in a clean way is a dauntingly complex task. Trying to shut down a thousand moving parts, some of them working, some idle, some in the process of being initiated, some of them already shutting down by themselves, is prone to all kinds of race conditions, resource leaks and similar. The shutdown subsystem is definitely the most complex part of ØMQ. A quick check of the bug tracker indicates that some 30--50% of reported bugs are related to shutdown in one way or another.
>
> Lesson learned: When striving for extreme performance and scalability, consider the actor model; it's almost the only game in town in such cases. However, if you are not using a specialised system like Erlang or ØMQ itself, you'll have to write and debug a lot of infrastructure by hand. **Additionally, think, from the very beginning, about the procedure to shut down the system.** It's going to be the most complex part of the codebase and if you have no clear idea how to implement it, you should probably reconsider using the actor model in the first place.

**Comment by r-marques** [comment]
@sbellem can you give a bit more context.
Its hard to know what this issue is about.

**Comment by ttmc** [comment]
I'm not sure if this issue is still relevant but it was part of the old "Shut Down Procedure" project so I reopened it so that we look again.

**Comment by ldmberman** [comment]
Does not seem to be reproducible anymore. Reopen if you reproduce it.
