### ISSUE TITLE
Add MongoDB connection options for SSL and authentication

### ISSUE THREAD

**Issue by tomconte** [bigchaindb/bigchaindb#1281]
I found that requirement while testing with Azure DocumentDB, however I think it can be useful in case anyone needs to use a MongoDB server that requires SSL and/or authentication.

**Comment by krish7919** [comment]
That is the plan. We just got started with a replica set on azure.
We are aiming for whitelisting IP addresses and then TLS connections.

**Comment by r-marques** [comment]
@krish7919 can we close this?

**Comment by krish7919** [comment]
@r-marques : I am unaware how this was tested with a secure MongoDB instance. I would keep it open till we can test and confirm that all works as expected, which will be till the time we add TLS support to MongoDB instance itself, and configure BigchainDB to use secure communication channel.

**Comment by r-marques** [comment]
@krish7919 what about now?

**Comment by krish7919** [comment]
@r-marques Fixed in PRs #1299, #1510, #1552
