### ISSUE TITLE
Where should bigchaindb related files reside?

### ISSUE THREAD

**Issue by sbellem** [bigchaindb/bigchaindb#1289]
Currently, we are mostly concerned with the configuration file which by default is located under the user home directory `~/.bigchaindb`.

Other bigchaindb-related files such as log files, also need a location. Where do we put them?

### Proposal
As a first step to improve the current state of things, at setup/installation time, we could create a `~/.bigchaindb` directory, under which config files, log files, etc, could be stored.

We could use the `console_script` entry point as documented [here](https://packaging.python.org/distributing/#console-scripts) in `setup.py` to create the directory. This should be fairly trivial.

**Comment by ttmc** [comment]
@sbellem Has some decision been made about this, i.e. the default location of a BigchainDB Server log file, if we let BigchainDB Server write a log file?

I gather that it's also an option to pass logs to other software as a stream, and to let that other software decide where to store them. Is that correct?

**Comment by sbellem** [comment]
For now, log files will be stored under `~/` by default, but a user can configure BigchainDB differently. For example, one could store the config file under `/etc/bigchaindb` and the log files under `/var/log/bigchaindb`.
