### ISSUE TITLE
[log] Should we replace pickle in log handling by a more secure alternative?

### ISSUE THREAD

**Issue by sbellem** [bigchaindb/bigchaindb#1296]
As pointed out in Python's logging cookbook section [Sending and receiving logging events across a network](https://docs.python.org/3/howto/logging-cookbook.html#sending-and-receiving-logging-events-across-a-network) (at the end of the section):

> Note that there are some security issues with pickle in some scenarios. If these affect you, you can use an alternative serialization scheme by overriding the `makePickle()` method and implementing your alternative there, as well as adapting the above script to use your alternative serialization.

#### Questions to answer:
* What are the scenarios in which there are security issues with pickle?
* Is the logging infrastructure affected by these scenarios?

In the event that we need to find an alternative:

* What are the alternatives? (e.g.: bson, messagepack, protocol buffers, etc)
* What needs to be changed?
    * Define a class that inherits `logging.handlers.SocketHandler` and overrides `makePickle()` to serialize the log record/message.
    * In `bigchaindb.log.setup.LogRecordStreamHandler` use the alternative serialization scheme to deserialize, instead of `unpickle`.

**Comment by r-marques** [comment]
@sbellem Do we want to proceed further with this?
I think we have bigger things to worry about.

**Comment by sbellem** [comment]
Closing for now. Can be re-opened in the future if necessary.
