### ISSUE TITLE
[shutdown] Make sure the logging subscriber shuts down properly

### ISSUE THREAD

**Issue by sbellem** [bigchaindb/bigchaindb#1302]
The logging subscriber runs in its own process, and when bigchaindb is stopped we need to be sure that the process is properly stopped. For example, we need to be sure that the process completes reading the socket and writing the log records before shutting it down.

**Comment by krish7919** [comment]
This happened today on IPDB Test Net where BigchainDB did not shut down cleanly and was hung after trying to connect to MongoDB thrice.

**Comment by ttmc** [comment]
Resolved by pull request #2304
