### ISSUE TITLE
Transaction size limit / Max cryptoconditions complexity

### ISSUE THREAD

**Issue by r-marques** [bigchaindb/bigchaindb#1303]
This issue addresses both #356 and #805 since they seem to be related.

- __Complexity__:

It may be possible to restrict the cryptoconditions complexity by making use of `maxFulfillmentLength` or `maxMessageLength` but this relates to a single input.

At a transaction level we need to limit the combined complexity of the input fulfillments.

- __Size__:

The size of a transaction is directly related to the max complexity of combined fulfillments and conditions.
Moreover we still need to consider both asset data in CREATE transactions and metadata in all transactions that at this point can be arbitrarily long.

**Comment by libscott** [comment]
Shall we close this one?

**Comment by r-marques** [comment]
Not sure what needs to be done on #805
