### ISSUE TITLE
When validating a transaction, check to ensure it isn't a duplicate

### ISSUE THREAD

**Issue by ttmc** [bigchaindb/bigchaindb#131]
If a transaction is sent by a client (including the timestamp from the client), it's valid, and it's a "create" transaction, then it should eventually end up in a decided_valid block in the bigchain table. It won't be in the backlog table anymore.

If a copy of the same transaction (with the same timestamp and the same hash/id) is sent from the same client a few days later, then the receiver node should check that a transaction with the same hash/id doesn't already exist in a block in the bigchain table. That would be part of the transaction validation logic.

**Comment by ttmc** [comment]
A similar issue may arise once we implement re-assignment of old/stale transactions to new nodes (issue #198 ), so maybe also check-if-duplicate when validating a transaction that has just been read from the backlog... unless we figure out another solution.

**Comment by ttmc** [comment]
When a transaction ends up in an invalid block, it gets copied back to the backlog (see issue #193), so the check for a duplicate transaction in the bigchain table should ignore transactions in invalid blocks.

**Comment by rhsimplex** [comment]
Consolidating discussion under #568
