### ISSUE TITLE
[security] Run bigchaindb as superuser?

### ISSUE THREAD

**Issue by sbellem** [bigchaindb/bigchaindb#1312]
It may make sense to consider requiring superuser privileges to run `bigchaindb`, and/or requiring the definition of a `bigchaindb` user & group.

Some reasons for doing so would be:

* to control more tightly who can run `bgichaindb`
* to control read and write access to config and log files

**Comment by krish7919** [comment]
Some inputs _if_ we are going to take this approach in #1049
1. Create the user and group during pip install, OR create the user group as an exec-pre-start script.
2. Create and configure a .bigchaindb conf file in /etc/bigchaindb/.

**Comment by sbellem** [comment]
@krish7919 thanks for the feedback!
