### ISSUE TITLE
[log] apply formatting configuration to error log file

### ISSUE THREAD

**Issue by sbellem** [bigchaindb/bigchaindb#1313]
The configuration for the error log file can be set the same as it is set for the normal log file.

**Comment by r-marques** [comment]
@sbellem Can you clarify what this means?
Is this something that we want to do right now?

**Comment by r-marques** [comment]
@sbellem Can you clarify what this means?
Is this something that we want to do right now?

This also seems related to #1539 and if so can we consolidate both into a single issue?

**Comment by sbellem** [comment]
This has been done already.

**Comment by sbellem** [comment]
_At some point the config for the error file logs was behind the one for the normal file logs._ 

6d4245dfd91b02382fb229400cc6a6400d341480 and 675d011a76337a105508faaa42a1a29e71ad4cce mostly solved this issue I think.
