### ISSUE TITLE
Remove some powerful `bigchaindb x` commands to increase security

### ISSUE THREAD

**Issue by ttmc** [bigchaindb/bigchaindb#1323]
Right now, there are some BigchainDB command-line commands which exist to make it easier to do some operations on the database backend (RethinkDB or MongoDB):

 * `bigchaindb drop`
* `bigchaindb set-shards` (RethinkDB only)
* `bigchaindb set-replicas` (RethinkDB only)
* `bigchaindb add-replicas` (MongoDB only)
* `bigchaindb remove-replicas` (MongoDB only)

A user doesn't _need_ those commands: they can always do those things by interacting with the database backend directly.

Moreover, the above-listed commands present a security vulnerability: they expose extra attack surface. A user shouldn't be able to do those things unless they are an admin user in the database (or a user with a power-user role).

I realize that removing the above-listed commands would make using BigchainDB a little less easy, but this is a common story: the tradeoff between convenience and security.

We might even revisit the `bigchaindb init` command: maybe some of the things it does should be done first by the backend database admin, not by the `bigchaindb init` command.

If possible, BigchainDB (the Python processes) should only be able to do a limited set of things with the database backend, mostly just CRUD stuff, but no database setup/admin stuff.

**Summary**

Apply the [principle of least privilege](https://en.wikipedia.org/wiki/Principle_of_least_privilege) to BigchainDB. How much should we allow it to do on the database backend? As little as possible.

**Comment by sidhujag** [comment]
Imo this is a showstopper. In a typical blockchain an admin creates the immutable genesis. I would imagine something similae would need to happen.. using a special build or role that when the chain is started it cannot be stopped by malicious users for any reason.

**Comment by krish7919** [comment]
Might be related to #1375
