### ISSUE TITLE
get_unvoted_blocks doesn't reflect changelog order

### ISSUE THREAD

**Issue by libscott** [bigchaindb/bigchaindb#1325]
When the vote pipeline starts up, it calls `get_unvoted_blocks` to get blocks that it missed voting on. This has some issues:

* The order of the blocks that is returned doesn't reflect changefeed order
* This is alot of useless work for a node joining the federation, their votes won't count since they wont be part of block voters list

Possible solutions:

* Remove this; if nodes miss out on changefeed events, they won't vote on blocks they missed
* Have nodes walk existing votes to extrapolate correct changefeed order via `previous_block`.
* Order by block timestamp; won't be 100% the same as changefeed order all the time but it'll be pretty good.

This is non critical really... It's incorrect but it shouldn't result in an invalid state.

cc @vrde @roderik @ttmc

**Comment by ttmc** [comment]
Evey block comes with a list of the voters (nodes) it expects to vote upon it. Those nodes have a responsibility to vote.

Figuring out what order to vote in is not as easy. Currently there are edge cases which would make it impossible to determine the global block ordering based on the existing votes (assuming there _are_ some, which there might not be, yet).

Maybe ordering the votes by block timestamp would be good enough. What about when there are two blocks with the same timestamp (which only has a one second precision)?

Maybe we can defer this question until we have the global, fully-replicated block-order table (which is in the medium-term roadmap).

**Comment by libscott** [comment]
> Maybe ordering the votes by block timestamp would be good enough. What about when there are two blocks with the same timestamp (which only has a one second precision)?

They have to be dependency ordered in this case.

**Comment by CsterKuroi** [comment]
Rethinkdb won't vote on blocks they missed, Mongodb will vote by `last_ts`
