### ISSUE TITLE
Add a new exception to raise when MongoDB Authentication fails

### ISSUE THREAD

**Issue by vrde** [bigchaindb/bigchaindb#1336]
Unfortunately `pymongo` doesn't provide a specific exception when the authentication fails, but a generic `OperationFailure`. This might trigger a retry, but it's not the correct behavior: if credentials are wrong we want BigchainDB to fail and give an explicit error message to the user.

Until [PYTHON-1259](https://jira.mongodb.org/browse/PYTHON-1259) is not resolved, we can do something like:
```python
# in bigchaindb/backend/exceptions.py
class AuthenticationError(ConnectionError): pass

# in bigchaindb/backend/mongodb/connection.py
if str(msg) == 'Authentication failure.':
    raise AuthenticationError
```

**Comment by r-marques** [comment]
resolved by #1357
