### ISSUE TITLE
Initialize timeout when creating a RethinkDB connection

### ISSUE THREAD

**Issue by vrde** [bigchaindb/bigchaindb#1337]
Right now the `connection_timeout` configuration parameter is used only by `MongoDBConnection`. The RethinkDB driver supports a similar option called [`timeout`](https://rethinkdb.com/api/python/connect/), but we are not using it.

**Comment by lavinasachdev3** [comment]
What is the expected timeout ?

**Comment by tdsgit** [comment]
is this right way of testing? 
`py.test -s test_connection.py`
if yes 3 attempts to connect port 28015 fails after 5000ms.

**Comment by vrde** [comment]
@lavinasachdev3: sorry for now replying earlier, I missed the notification on GitHub

@tdsgit: AFAIK we are not testing if the `timeout` parameter is honored by the driver. The time should be cumulative, so if it's `3` tries, the total time is `15000ms`. To run the tests you should do `pytest tests/backend/rethinkdb/test_connection.py`.

**Comment by tdsgit** [comment]
@vrde 
tried testing mongodb connection to see what's going right with mongodb first.
but bigchaindb/backend/connection.py retaining old config values and trying to connect to rethinkdb!
tried clearing tests/__pycache__
the only file which has old keypairs was tests/conftest.py .

**Comment by tdsgit** [comment]
update (april 20):
the mongodb test need to be run as 
`pytest -q tests/backend/mongodb/test_connection.py --database-backend="mongodb"`
and not as
`pytest -q tests/backend/mongodb/test_connection.py`
this snippet assigns tiemout to serverselectiontimeoutms 
`           client = pymongo.MongoClient(self.host,
                                         self.port,
                                         replicaset=self.replicaset,
                                         serverselectiontimeoutms=self.connection_timeout,
                                         ssl=self.ssl)
`
however in rethinkdb the parameter to be passed is timeout ( not connection_timeout)
`r.connect(host=self.host, port=self.port, db=self.dbname, timeout=5000 )`
mock_connect.assert_called_once_with may assert
original_connect also should pass timeout

this concludes the test scripts passing timeout to rethinkdb socket.
