### ISSUE TITLE
Add support for WebHooks

### ISSUE THREAD

**Issue by vrde** [bigchaindb/bigchaindb#1339]
*This issue is a WIP.*

BigchainDB events API (see #862) should support WebHooks to enable third parties to trigger their own business logic on specific events. This would fit well because many businesses and developerss are using cloud services like AWS [Lambda](https://aws.amazon.com/lambda/) and AWS [API Gateway](https://aws.amazon.com/api-gateway/) to build their own applications. A WebHook would be able to trigger custom behaviors on their side, in a """""smart contract""""" fashion.

**Comment by ttmc** [comment]
I copied this issue's idea to https://github.com/bigchaindb/BEPs/issues/86 so I'm going to close this issue here.
