### ISSUE TITLE
Checking if transactions are in a decided_valid block (or otherwise) when necessary

### ISSUE THREAD

**Issue by ttmc** [bigchaindb/bigchaindb#134]
From @thedoctor via the Gitter chatroom:

> I don't see blocks getting marked as decided_valid or decided_invalid anywhere. I know we can determine that on-the-fly based on the votes, but I also don't see us doing that anywhere, e.g. in core.py:get_spent, we don't seem to check whether the spending transaction is in a decided_valid block or not. Couldn't this lead to a situation where a transaction is never included in a block because it's always erroneously considered spent?

**Comment by r-marques** [comment]
moving this to #192
