### ISSUE TITLE
Code, tools & instructions to add a node to a cluster (also remove)

### ISSUE THREAD

**Issue by ttmc** [bigchaindb/bigchaindb#135]
We need some code, tools and instructions to add a node to a BigchainDB cluster (or to remove a node from a cluster).

Remember that BigchainDB is supposed to be decentralized, meaning each node is normally going to be owned and controlled by a different person or organization. The normal way to build a cluster will be for each new member to get permission to join (from the organization governing the cluster, i.e. outside the scope of the software), and then they'll get instructions on how to start up a new BigchainDB node and get it talking to the rest of the cluster.

How will that work? Will the other nodes have to add the new node's public key first? How will they get the public key?

If someone wants to set up a **test cluster** or a **centrally-controlled cluster** (where one entity controls all nodes), then they can do that by repeating the add-one-node instructions over and over again (maybe with a script).

**Comment by sbellem** [comment]
Just in case this may be helpful: https://docs.saltstack.com/en/latest/topics/tutorials/multimaster.html

**Comment by ttmc** [comment]
I just remembered there was already an Issue that had this as a sub-issue: Issue #126 . Therefore, I'll close this issue and copy the above text to that issue for convenience.
