### ISSUE TITLE
 python-rapidjson-0.0.8.tar.gz raises an error in ubuntu

### ISSUE THREAD

**Issue by ferOnti** [bigchaindb/bigchaindb#1350]
when try to install bigchaindb_driver (this also happens with bigchaindb), 
the dependency to python-rapidjson-0.0.8 raises an error, 
as I know this is related to the locale, but I'm not a python programmer and I don't know how can setup the locale to utf8  and make pip to work.

newest versions of python-rapidjson does not have this issue, so probably is better to upgrade this dependency 

pip install bigchaindb_driver
Collecting bigchaindb_driver
  Downloading bigchaindb_driver-0.2.1.tar.gz (481kB)
    100% |################################| 481kB 2.7MB/s 
Collecting requests>=2.11.0 (from bigchaindb_driver)
  Downloading requests-2.13.0-py2.py3-none-any.whl (584kB)
    100% |################################| 593kB 2.3MB/s 
Collecting bigchaindb~=0.9.1 (from bigchaindb_driver)
  Using cached BigchainDB-0.9.4.tar.gz
Collecting rethinkdb~=2.3 (from bigchaindb~=0.9.1->bigchaindb_driver)
  Using cached rethinkdb-2.3.0.post6.tar.gz
Collecting pymongo~=3.4 (from bigchaindb~=0.9.1->bigchaindb_driver)
  Using cached pymongo-3.4.0-cp35-cp35m-manylinux1_x86_64.whl
Collecting pysha3~=1.0.2 (from bigchaindb~=0.9.1->bigchaindb_driver)
  Using cached pysha3-1.0.2.tar.gz
Collecting cryptoconditions>=0.5.0 (from bigchaindb~=0.9.1->bigchaindb_driver)
  Using cached cryptoconditions-0.5.1.tar.gz
Collecting python-rapidjson==0.0.8 (from bigchaindb~=0.9.1->bigchaindb_driver)
  Using cached python-rapidjson-0.0.8.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-f9sj9ef0/python-rapidjson/setup.py", line 27, in <module>
        long_description = f.read()
      File "/usr/lib/python3.5/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 4009: ordinal not in range(128)

**Comment by sbellem** [comment]
Thanks @ferOnti for reporting the issue. A pull request is on the way (#1351) and we should be making a patch release later today. We'll let you know once the patch is released on PyPI.

**Comment by sbellem** [comment]
@ferOnti new patch release 0.9.5 is out on PyPI: https://pypi.python.org/pypi/BigchainDB/0.9.5

**Comment by ferOnti** [comment]
thank you, it works!

**Comment by sbellem** [comment]
> thank you, it works!

Cool! Thanks again for reporting!
