### ISSUE TITLE
drop support for Python 3.4

### ISSUE THREAD

**Issue by sbellem** [bigchaindb/bigchaindb#1353]
In general, at least for as long as we are in active development, and that this does not hinder our users, we could support the last two versions of Python. This would allow us to more easily use new features.

**Comment by TimDaub** [comment]
From internal Slack:

As long as bdb-common is shared with the py-driver and server, we should be tolerant with Python versions to allow more users to on-board (e.g. users that use legacy Python versions in their code base).

This issue is kinda related: https://github.com/bigchaindb/org/issues/24

**Comment by sbellem** [comment]
The driver is Python 3.5+ only.

**Comment by ttmc** [comment]
If we _do_ drop support for Python 3.4, don't forget to update the relevant docs, e.g. [the section on OS Requirements](https://docs.bigchaindb.com/projects/server/en/latest/production-nodes/node-requirements.html#os-requirements). `grep` can help :wink:
