### ISSUE TITLE
Only use utils.condition_details_has_owner and discard utils.output_has_owner?

### ISSUE THREAD

**Issue by sbellem** [bigchaindb/bigchaindb#1367]
It is not clear whether [`utils.output_has_owner()`](https://github.com/bigchaindb/bigchaindb/blob/master/bigchaindb/utils.py#L85) is really needed as [`utils.condition_details_has_owner()`](https://github.com/bigchaindb/bigchaindb/blob/master/bigchaindb/utils.py#L116) maybe sufficient.

See also this [`TODO` note](https://github.com/bigchaindb/bigchaindb/blob/master/bigchaindb/utils.py#L117-L120):

```python
def output_has_owner(output, owner):
    # TODO
    # Check whether it is really necessary to treat the single key case
    # differently from the multiple keys case, and why not just use the same
    # function for both cases.
```

To tackle this issue:

- [ ] First double check what the above `TODO` note asks for.
- [ ] If it is indeed correct to simply use `utils.condition_details_has_owner()` then do so. That should mean changing the [code](https://github.com/bigchaindb/bigchaindb/blob/master/bigchaindb/core.py#L383) in `core.py` under `get_ouputs()`:

```python
    def get_outputs(self, owner):

        # get all transactions in which owner is in the `owners_after` list
        response = backend.query.get_owned_ids(self.connection, owner)
        return [
            TransactionLink(tx['id'], index)
            for tx in response
            if not self.is_tx_strictly_in_invalid_block(tx['id'])
            for index, output in enumerate(tx['outputs'])
            if utils.output_has_owner(output, owner)
]
```

**Comment by r-marques** [comment]
resolved by #1470
