### ISSUE TITLE
Can add a bigchaindb to a bigchaindb federa?

### ISSUE THREAD

**Issue by vincent0330** [bigchaindb/bigchaindb#1370]
I see the error:
bigchaindb.common.exceptions.MultipleVotesError: Block efd83d4a077d4c9ffd7a2dac2084446813a13bdc90f164345499284219124b43 has 4 votes cast, but only 3 voters，

**Comment by ttmc** [comment]
@vincent0330 We would like to be able to reproduce this error, but we need more information:

* What operating system did you install BigchainDB Server on? What version?
* What version of Python? (The output of `python --version`)
* What version of BigchainDB Server? (The output of `bigchaindb --version`)
* Are you using RethinkDB or MongoDB? Maybe just share all your BigchainDB Server config settings, i.e. the output of `bigchaindb show-config`
* What steps should we do to get the above-reported error?

**Comment by vincent0330** [comment]
Firstly,thanks for your reply:

all of them : Ubuntu 14.04
the original server:
server 1:
{
    "backlog_reassign_delay": 120,
    "database": {
        "backend": "mongodb",
        "host": "localhost",
        "name": "bigchain",
        "port": 27017,
        "replicaset": "bigchain-rs"
    },
    "keypair": {
        "private": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
        "public": "BGnb1xf6yVSfyW8J9RASKb2UnhRRnWcAcFWgNGZ25wg8"
    },
    "keyring": [
        "Bn5hQr9eTKa3UA7qU2yoDMH8rzh8YZN1Wg4N1jMPxzZP",
        "6NJdco32qwAdE52pdgYqn28CfM3abxoUS1C9hvUZ86pq",
        "Fyp1ZkH7RDVnnuFyYCp3ugMopu3YNVNWJ8efRqbXHrJQ"
    ],
    "server": {
        "bind": "192.168.1.241:9984",
        "threads": null,
        "workers": null
    }
}

server2:
{
    "backlog_reassign_delay": 120,
    "database": {
        "backend": "mongodb",
        "host": "localhost",
        "name": "bigchain",
        "port": 27017,
        "replicaset": "bigchain-rs"
    },
    "keypair": {
        "private": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
        "public": "Fyp1ZkH7RDVnnuFyYCp3ugMopu3YNVNWJ8efRqbXHrJQ"
    },
    "keyring": [
        "Bn5hQr9eTKa3UA7qU2yoDMH8rzh8YZN1Wg4N1jMPxzZP",
        "6NJdco32qwAdE52pdgYqn28CfM3abxoUS1C9hvUZ86pq",
        "BGnb1xf6yVSfyW8J9RASKb2UnhRRnWcAcFWgNGZ25wg8"
    ],
    "server": {
        "bind": "192.168.1.242:9984",
        "threads": null,
        "workers": null
    }
}

server 3:
{
    "backlog_reassign_delay": 120,
    "database": {
        "backend": "mongodb",
        "host": "localhost",
        "name": "bigchain",
        "port": 27017,
        "replicaset": "bigchain-rs"
    },
    "keypair": {
        "private": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
        "public": "6NJdco32qwAdE52pdgYqn28CfM3abxoUS1C9hvUZ86pq"
    },
    "keyring": [
        "Bn5hQr9eTKa3UA7qU2yoDMH8rzh8YZN1Wg4N1jMPxzZP",
        "BGnb1xf6yVSfyW8J9RASKb2UnhRRnWcAcFWgNGZ25wg8",
        "Fyp1ZkH7RDVnnuFyYCp3ugMopu3YNVNWJ8efRqbXHrJQ"
    ],
    "server": {
        "bind": "192.168.1.251:9984",
        "threads": null,
        "workers": null
    }
}

and the new bigchaindb server config:
{
    "backlog_reassign_delay": 120,
    "database": {
        "backend": "mongodb",
        "host": "localhost",
        "name": "bigchain",
        "port": 27017,
        "replicaset": "bigchain-rs"
    },
    "keypair": {
        "private": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
        "public": "Bn5hQr9eTKa3UA7qU2yoDMH8rzh8YZN1Wg4N1jMPxzZP"
    },
    "keyring": [
        "6NJdco32qwAdE52pdgYqn28CfM3abxoUS1C9hvUZ86pq",
        "BGnb1xf6yVSfyW8J9RASKb2UnhRRnWcAcFWgNGZ25wg8",
        "Fyp1ZkH7RDVnnuFyYCp3ugMopu3YNVNWJ8efRqbXHrJQ"
    ],
    "server": {
        "bind": "localhost:9984",
        "threads": null,
        "workers": null
    }
}

========================
And now, I restarted all of the 4 bigchaindb server,its OK. Bug I don't know why.

**Comment by ttmc** [comment]
Okay, if you get a similar error in the future, please let us know by filing a new issue, along with details so we can reproduce it.
