### ISSUE TITLE
Add support for MongoDB authentication

### ISSUE THREAD

**Issue by vrde** [bigchaindb/bigchaindb#1371]
#1299 introduced SSL & auth support to MongoDB client. Those options has been added to the configuration (see #1348) but hidden to the user. To fully support those options, BigchainDB should:
 - Add [`pymongo[tls]`](http://api.mongodb.com/python/current/examples/tls.html) as a dependency.
   - Eventually add support for a CA file.
 - Create `login` and `password` when the `init` command is run.

**Comment by r-marques** [comment]
@vrde @krish7919 can this be closed or is there something left to do?

**Comment by krish7919** [comment]
This is complete, apart from the `Create login and password when the init command is run.` part.

This is an offline thing and BigchainDB has no role to play in creating users or roles.

I think this can be closed. @vrde, thoughts?

**Comment by vrde** [comment]
> This is an offline thing and BigchainDB has no role to play in creating users or roles.

Agree, it's up to the sysadmin to configure MongoDB correctly.
