### ISSUE TITLE
Document the `server.loglevel` configuration setting?

### ISSUE THREAD

**Issue by ttmc** [bigchaindb/bigchaindb#1373]
Today when I do `bigchaindb -y configure mongodb` and then `bigchaindb show-config`, I get:
```json
{
    "backlog_reassign_delay": 120,
    "database": {
        "backend": "mongodb",
        "connection_timeout": 5000,
        "host": "localhost",
        "login": null,
        "max_tries": 3,
        "name": "bigchain",
        "password": null,
        "port": 27017,
        "replicaset": "bigchain-rs",
        "ssl": false
    },
    "keypair": {
        "private": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
        "public": "HbyLvWy12b3iyMXYwkGjnBgFCytKV28kVfQG7XVXRBr"
    },
    "keyring": [],
    "log": {
        "level_console": "INFO"
    },
    "server": {
        "bind": "localhost:9984",
        "loglevel": "INFO",
        "threads": null,
        "workers": null
    }
}
```

Do we need to add documentation for `server.loglevel`? If so, maybe explain why is it set there rather than in the `log.*` settings. The relevant file to edit is:

`bigchaindb/docs/server/source/server-reference/configuration.md`

(Note: We decided not to document database.login, database.password, and database.ssl for now.)

@sbellem Maybe this is something you can do during our next QA sprint.

**Comment by sbellem** [comment]
I suggest we leave it undocumented for now.

**Comment by sbellem** [comment]
side note, see related issue: https://github.com/bigchaindb/bigchaindb/issues/1379
