### ISSUE TITLE
Better checks during startup: Keys and Keyring

### ISSUE THREAD

**Issue by krish7919** [bigchaindb/bigchaindb#1376]
We should impose certain constraints on keys in the keyring:
* Cannot be empty string
* Should be of definite length
* Should be ':' separated and have no other special characters.

**Comment by ttmc** [comment]
Note: The keyring only needs to be ':' separated when it is being set via an environment variable. One can also edit the bigchaindb config file (JSON) manually, in which case the keyring is a JavaScript array of strings, like `["string1", "string2", "string3"]`

**Comment by krish7919** [comment]
Point to note here is that, for the first node in the cluster, the keyring should be unset.
For example, if using the environment variable BIGCHAINDB_KEYRING is set to a null string `""`, the BigchainDB node tries to wait for a vote from a member with `""` as the public key, and this results in a block never getting into a valid state.

**Comment by ttmc** [comment]
In a BigchainDB config file (JSON), you can have
```json
   "keyring": []
```
and that will work fine. It gets problematic when you try to set an empty keyring using the `BIGCHAINDB_KEYRING` environment variable. Setting it to `""` doesn't work.

One idea: If the environment variable `BIGCHAINDB_KEYRING` is set, and it equals `"EMPTY"` (or some other special value), then internally, inside BigchainDB Server, set the keyring to an empty list. (If its value is "falsy", such as `None` or `""`, then raise an exception?)

**Comment by r-marques** [comment]
There are a lot of issues about things that can go wrong when starting bigchaindb: configuration file, database setup, ...
Maybe we should create a project that would run some pre start routine to check that everything is configured correctly before starting bigchaindb to address all these issues.
