### ISSUE TITLE
Revisit BigchainDB configuration settings for deployment

### ISSUE THREAD

**Issue by krish7919** [bigchaindb/bigchaindb#1427]
Leave the default values and only mention values we need to override.
From PR #1418

**Comment by ttmc** [comment]
Note: This is referring to the Kubernetes "Deployment" YAML file for BigchainDB. The only BigchainDB-related environment variables it needs to set are for the [BigchainDB config settings](https://docs.bigchaindb.com/projects/server/en/latest/server-reference/configuration.html) that must be changed from their default values. For example, the `BIGCHAINDB_BACKLOG_REASSIGN_DELAY` can be left at its default value so it doesn't have to be in the YAML file.
