### ISSUE TITLE
NGINX response to HTTP request when expected an HTTPS request

### ISSUE THREAD

**Issue by ttmc** [bigchaindb/bigchaindb#1429]
This issue is the bigchaindb/bigchaindb analogue of https://github.com/bigchaindb/nginx_3scale/issues/5

The change should be made to `k8s/nginx/container/nginx.conf.template`

**Comment by ttmc** [comment]
@krish7919 For reference, the pull request where you resolved the corresponding issue in the bigchaindb/nginx_3scale repository was:

https://github.com/bigchaindb/nginx_3scale/pull/8

**Comment by krish7919** [comment]
Resolved in bigchaindb/nginx_3scale#8

**Comment by ttmc** [comment]
Note: The reason this issue got resolved was that it was never an issue in the first place: there wasn't any support for HTTPS in the nginx.conf.template (in this repo), so there was no need to tell HTTP requests to upgrade to HTTPS. I suppose it _will_ become an issue if we ever decide to add support for HTTPS.
