### ISSUE TITLE
Upgrade from HDD to SSD in k8s deployment on Azure

### ISSUE THREAD

**Issue by krish7919** [bigchaindb/bigchaindb#1430]
Blocked on this because ACS does not currently support Premium_SKU in k8s Storage Class.

**Comment by muawiakh** [comment]
Azure supports this. Currently we are using only `Standard_D2_v2` and the storage account with `Standard LRS` in our deployment model. However, if we want we can create a `Premium LRS` storage account on Azure and use that for our deployment.

Some references:
[Kubernetes Github](https://github.com/kubernetes/kubernetes/blob/master/pkg/volume/azure_dd/azure_common.go)
[General purpose Linux VM sizes](https://docs.microsoft.com/en-us/azure/virtual-machines/linux/sizes-general)
[High-performance Premium Storage and managed disks for VMs](https://docs.microsoft.com/en-us/azure/storage/storage-premium-storage)
[Recent blog](https://blogs.msdn.microsoft.com/stevelasker/2017/07/25/new-azure-container-registry-skus/)

Do we need to introduce this in our deployment guide now?

**Comment by ttmc** [comment]
@muawiakh I think we can close this issue now. The (optional) use of Premium storage on Azure is documented at:

https://docs.bigchaindb.com/projects/server/en/latest/production-deployment-template/node-on-kubernetes.html?highlight=Premium#step-10-create-kubernetes-storage-classes-for-mongodb
