### ISSUE TITLE
Maintain consistency in specifying bind params

### ISSUE THREAD

**Issue by krish7919** [bigchaindb/bigchaindb#1458]
I just ran into an error when I assumed that the Websocket configs were the same as the HTTP API ones!

We specify a `server.bind` config for the HTTP API port, but `wsserver.host` and `wsserver.port` separately. similar is the case for `database.host` and `database.port`.

```
{
    "server": {
        "bind": "0.0.0.0:9984",
        "loglevel": "info",
        "workers": null,
        "threads": null
    },
    "wsserver": {
        "host": "0.0.0.0",
        "port": 9985
    },
    "database": {
        "backend": "mongodb",
        "connection_timeout": 5000,
        "max_tries": 3,
        "host": "localhost",
        "port": 27017,
```

Should we try to maintain consistency in param specification here?
My personal opinion is the have it similar to the `bind` config where we specify `host:port`.

**Comment by sbellem** [comment]
Good point! I was wondering the same. 

Besides consistency, we should also ask ourselves whether we wish to hide or expose the configuration of the underlying components we use.

For example, `server` is currently for `gunicorn`, which does have a setting [bind](http://docs.gunicorn.org/en/stable/settings.html#bind) in the form of `host:port`.

As for `wsserver` it is currently backed by `aiohttp` and the way we currently use it (via [`aiohttp.web.run_app`](http://aiohttp.readthedocs.io/en/stable/web_reference.html#aiohttp.web.run_app)) requires the host and port to be passed separately.

If we choose to be consistent it is likely that we'll have to hide a bit the underlying required configuration, in some cases, and we'll have to introduce an intermediate step to transform the high level configuration to the required form for the underlying system that the configuration is being targeted at.

Lastly, I think we should ask ourselves who the configuration is for, and we should tailor the configuration for the users who we think the configuration is for.

My opinion is that the configuration is for sys admins, devops, and developers experimenting with the system, and consistency would help to make things simpler for these users.

**Comment by ttmc** [comment]
At least the docs about `wsserver.host` are correct about what it means:

"`wsserver.host` is where to bind the aiohttp server socket and `wsserver.port` is the corresponding port. If you want to allow connections from anyone, on port 9985, set `wsserver.host` to 0.0.0.0 and `wsserver.port` to 9985."

It would be nice if the WebSocket server (aiohttp) configuration parameters were the same as the HTTP server (gunicorn) configuration parameters (in syntax and semantics). For example:

**Proposal**

Replace `wsserver.host` and `wsserver.port` with `wsserver.bind` (which could be, for example, 0.0.0.0:9985) and parse it internally. That way it would be consistent with `server.bind`.

**Comment by ttmc** [comment]
There's a reason those parameters are inconsistent: we're basically passing them along, as is, to third-party APIs. The third-party APIs are inconsistent.

At this point, making a change would just break our users' config files for no good reason.

Therefore I'm closing this issue.
