### ISSUE TITLE
patch release 0.10.2

### ISSUE THREAD

**Issue by sbellem** [bigchaindb/bigchaindb#1467]
This issue is mainly meant to be a way to keep track of small minor fixes that are planned to be included in the patch release 0.10.2.

Currently staged commits for release 0.10.2:

* f3cd43e5a926b2523bcba450ca68871ede41ef0e (Make GET /blocks status arg case insensitive)
* 9d3eb23abf68deabf40ea643c238928022418f31 (Add workaround for hostname of events api link - addresses #1465)

**Comment by ttmc** [comment]
I think @vrde also wants to include the commits associated with the CORS pull request (in 0.10.2):

  https://github.com/bigchaindb/bigchaindb/pull/1311

**Comment by vrde** [comment]
@diminator found and fixed a bug in #1470.

**Comment by ttmc** [comment]
@vrde @diminator Regarding #1470, it's not merged yet, and it seems there are still some TODO items. We want to release 0.10.2 today. Maybe #1470 will have to get bumped to 0.10.3 or later?

**Comment by ttmc** [comment]
Resolved by #1475
