### ISSUE TITLE
Upgrade flask-cors to latest release 3.0.2

### ISSUE THREAD

**Issue by sbellem** [bigchaindb/bigchaindb#1479]

**Comment by r-marques** [comment]
This seems to be already done https://github.com/bigchaindb/bigchaindb/commit/5ae8c8147455eedd22bf5b08ddca056cfce9d38b#diff-2eeaed663bd0d25b7e608891384b7298R74

**Comment by sbellem** [comment]
> This seems to be already done 5ae8c81#diff-2eeaed663bd0d25b7e608891384b7298R74

Yes, closing the issue.
