### ISSUE TITLE
bigchaindb start does not exit when there is a configuration error

### ISSUE THREAD

**Issue by sbellem** [bigchaindb/bigchaindb#1487]
When starting bighcaindb and some configuration is incorrect or missing, the following happens:
```bash
$ bigchaindb start
WARNING:bigchaindb.config_utils:Cannot find config file `/data/.bigchaindb`.
[2017-05-18 16:06:12] [INFO] (bigchaindb.commands.bigchaindb) BigchainDB Version 0.11.0.dev (MainProcess - pid: 39)
Can't start BigchainDB, no keypair found. Did you run `bigchaindb configure`?
```
and then the process is [Just Hangin' Out ](https://youtu.be/cDz29sva4FM)

We should not need to be breaking atoms to fix this Just Hangin' Out problem as the main source of the problem is with logging (#1302) according to @vrde.

**Comment by ttmc** [comment]
- "no keypair found" is not going to happen any more, because the BigchainDB configuration settings no longer include a keypair. All other configuration settings have a default value.
- Issue #1302 has been resolved.

Therefore I will close this issue.
