### ISSUE TITLE
Use XFS filesystem with MongoDB in Production

### ISSUE THREAD

**Issue by ttmc** [bigchaindb/bigchaindb#1489]
From some recent MongoDB startupWarnings:
```text
"2017-05-18T14:06:04.062Z I STORAGE  [initandlisten] ** WARNING: Using the XFS filesystem is strongly recommended with the WiredTiger storage engine",
"2017-05-18T14:06:04.062Z I STORAGE  [initandlisten] **          See http://dochub.mongodb.org/core/prodnotes-filesystem",
```
Here's a clickable link to that URL:

http://dochub.mongodb.org/core/prodnotes-filesystem

**Comment by krish7919** [comment]
Filesystem customization can be taken care of once Azure provides them for Persistent Volume Claims (or is it Storage Classes) on Kubernetes.

**Comment by ttmc** [comment]
This is the responsibility of the node operator / database administrator / MongoDB hosting service. It's not the responsibility of the BigchainDB dev team.
