### ISSUE TITLE
In production, configure 'Transparent Huge Pages' optimally for MongoDB

### ISSUE THREAD

**Issue by ttmc** [bigchaindb/bigchaindb#1490]
From some recent MongoDB startupWarnings:
```text
"2017-05-18T14:06:06.542Z I CONTROL  [initandlisten] ** WARNING: /sys/kernel/mm/transparent_hugepage/enabled is 'always'.",
"2017-05-18T14:06:06.542Z I CONTROL  [initandlisten] **        We suggest setting it to 'never'",
"2017-05-18T14:06:06.542Z I CONTROL  [initandlisten] ",
"2017-05-18T14:06:06.543Z I CONTROL  [initandlisten] ** WARNING: /sys/kernel/mm/transparent_hugepage/defrag is 'always'.",
"2017-05-18T14:06:06.543Z I CONTROL  [initandlisten] **        We suggest setting it to 'never'",
```

What's that about? According to [a page in the MongoDB manual](https://docs.mongodb.com/manual/tutorial/transparent-huge-pages/):

> Transparent Huge Pages (THP) is a Linux memory management system that reduces the overhead of Translation Lookaside Buffer (TLB) lookups on machines with large amounts of memory by using larger memory pages.

**Comment by krish7919** [comment]
AFAIK, this is a host/instance level configuration and cannot be set at a per container level.

**Comment by ttmc** [comment]
This is the responsibility of the node operator / database administrator / MongoDB hosting service. It's not the responsibility of the BigchainDB dev team.
