### ISSUE TITLE
Security: MongoDB <-> BigchainDB TLS connectivity

### ISSUE THREAD

**Issue by krish7919** [bigchaindb/bigchaindb#1505]
* Ensure authentication between BigchainDB and MongoDB instances.
* This is the first step to enable authorization later.

* Implementation details:

- [x] Add configuration options to .bigchaindb. Add a block as:
```
"ssl": {
   "ca":"absolute path to the CA certificate",
   "key":"absolute path the the consolidated public and private key file"
}
```

- [x] Sanity checks: Read only permissions and ownership of the files.

- [x] Add support for TLS in `PyMongo.MongoClient` in `bigchaindb/backend/mongodb/connection.py`.

- [x] Add support for tests with SSL support.
- [x] Add support for Travis CI

**Comment by r-marques** [comment]
For reference can probably reuse some of the work done in this issue to resolve #1013

**Comment by krish7919** [comment]
@r-marques :
The configuration options aren't as described above; I have added them as:
```
"database": {
        "ca_cert": "/ssl/ca.crt",
        "certfile": "/ssl/bdb-instance-0.crt",
        "keyfile": "/ssl/bdb-instance-0.key",
        "keyfile_passphrase": "",
        "crlfile": "/ssl/crl.pem"
}
```
As I thought more about it, we can have a generic `ssl` block proposed above when we support both RethinkDB and MongoDB.

**Comment by r-marques** [comment]
@krish7919 can we close this?

**Comment by krish7919** [comment]
:+1:
