### ISSUE TITLE
Proposal: Remove backlog

### ISSUE THREAD

**Issue by libscott** [bigchaindb/bigchaindb#1506]
Seems to me the backlog isn't pulling it's weight. Given that we don't guarantee anything about transactions in the backlog, and it doesn't provide us with any additional security, it's not clear in what way it's actually providing value at this stage. And if we need a backlog in the future, it's not clear that it would work the way ours currently works.

Proposal is to validate transactions in the HTTP method and pipe them directly to block creation process via IPC. We can then remove:

* Stale transaction monitor (and associated race conditions)
* Transaction recycling in election pipeline
* Transaction validation during block creation

@TimDaub @ttmc @r-marques

**Comment by ttmc** [comment]
The backlog is removed in BigchainDB 2.0, so I'm closing this issue.
