### ISSUE TITLE
Proposal: Blocks are not valid / invalid

### ISSUE THREAD

**Issue by libscott** [bigchaindb/bigchaindb#1507]
Currently we consider a block to be either valid or invalid, as a whole. Given that our blockchain is executed asynchronously, no validity state is considered at ordering time, and therefore it seems a waste to mark an entire block invalid when it's already been included and propagated.

Proposal is to support multiple blockchains:

* Root chain, which simply specifies total order of blocks, pre execution
* Execution chain, wherein the block IDs and execution results are recorded.

An execution chain could contain the result of block execution, which could specify that some transactions were erroneous but the rest were OK.

@ttmc @TimDaub @r-marques

**Comment by ttmc** [comment]
BigchainDB 2.0 doesn't have invalid blocks so this issue is gone. I'm closing it.
