### ISSUE TITLE
Proposal: Separate replication and execution for security and performance

### ISSUE THREAD

**Issue by libscott** [bigchaindb/bigchaindb#1508]
This proposal is about splitting the concerns of secure replication and execution.

## Replication
At mininum, secure replication is achievable using an append only content addressed data store, where all document hashes are verified. There are several candidates, such as Tahoe LAFS, IPFS, Storj, or we can roll our own.

## Execution
What is currrently called validation is termed execution here. Execution involves:

1. Listen to the block order feed.
2. Download the next block from the secure filestore.
3. Execute the block against a mutable data store, containing an indexing of UTXOs (and other indexes necessary for a particular VM).
4. Verify execution result against other nodes.

## Advantages

* Replication is secured. Dynamic sharding can be tackled in the future (perhaps we can re-use internet routing protocols, wouldn't that be nifty?)
* Performance is high; the state store is no longer being used as a blockchain, but as a mutable state store, where all data inside is considered valid. This is more in line with the design of a commercial application database.
* Flexibility of state store is higher, easier to change internal data strucuture and add indexes according to user's needs.
* Nodes may run whichever commercial databases they like to execute assets.

## Implementation

In order to design implementation, transition priorities should be analyzed ie how do we want to get there. I'd suggest that ideally, we could implement the pieces and associated migrations one patch release at a time, to minimise risk.

## Problems

* The block order may include a block that a node can then not locate. To prevent this, the interface for block order submission should validate that the block is accessible. The submitter could include proofs that the block payload was received by storage nodes, or the block ordering agent can verify it themselves by inspecting the database.

@ttmc @TimDaub @r-marques

**Comment by ttmc** [comment]
Can you elaborate on the blockchain feed? How is it generated and communicated?

**Comment by libscott** [comment]
Yes, perhaps it's better communicated as "block order feed"; it's the output of the consensus algorithm that is ordering the blocks (the `consensus` node in the below diagram).

![node](https://cloud.githubusercontent.com/assets/125019/26665424/d46f12a4-4699-11e7-9595-4d230da99dee.png)

**Comment by libscott** [comment]
Superseeded by #1528
