### ISSUE TITLE
Travis docs error makes all the jobs fail

### ISSUE THREAD

**Issue by r-marques** [bigchaindb/bigchaindb#1513]
Travis has a `docsserver` job but this job seems to also be executed in the other database jobs so if the docs job fails all other jobs fail see for instance [Build #5257](https://travis-ci.org/bigchaindb/bigchaindb/builds/238381623)

We should run the docs test only on the `docsserver` job.

@sbellem thoughts?

**Comment by ttmc** [comment]
I'm pretty sure we resolved this issue, so I'm closing it.
