### ISSUE TITLE
On the test net, the HTTP response is sometimes 502 Bad Gateway

### ISSUE THREAD

**Issue by ttmc** [bigchaindb/bigchaindb#1514]
Sometimes, when an HTTP GET https://test.ipdb.io/api/v1 request is sent to the IPDB Test Network (on Kubernetes on Azure), we get an HTTP response status 502, with the following headers and body (copied from an automated test done by Runscope).

```text
HEADERS

Content-Length: 179
Content-Type: text/html
Date: Fri, 02 Jun 2017 03:55:21 GMT
Server: openresty/1.11.2.3

BODY

<html>
  <head>
    <title>502 Bad Gateway</title>
  </head>
  <body bgcolor="white">
    <center>
      <h1>502 Bad Gateway</h1>
    </center>
    <hr>
      <center>openresty/1.11.2.3</center>
    </body>
  </html>
```

**Comment by ttmc** [comment]
Note: the same is sometimes seen in response to HTTP GET requests to https://test.ipdb.io

**Comment by krish7919** [comment]
@ttmc  Does this still occur after bypassing GETs?

**Comment by ttmc** [comment]
@krish7919  I just went to the OMS Portal and did a Log Search over all log messages from the nginx_3scale image in the past 7 days. None contained "502".

That doesn't mean this problem is gone for good, but it is reassuring!

**Comment by krish7919** [comment]
Closing this as this seems to be fixed after bypassing GETs.

**Comment by ttmc** [comment]
This issue is still with us, it seems, albeit intermittently. Some Runscope tests got a "502 Bad Gateway" response this past weekend, e.g.

![screenshot from 2017-07-31 09-42-15](https://user-images.githubusercontent.com/1210951/28767623-b10eb142-75d4-11e7-865d-745cad2a59ac.png)

Ping @krish7919 @muawiakh

**Comment by ttmc** [comment]
Update: I was just talking to @krish7919 and he said it looks like these `502 Bad Gateway` responses happen when MongoDB is crashed, so maybe if we find a better solution to preventing MongoDB crashes, we can also resolve this issue.

**Comment by ttmc** [comment]
We think we understand why this happens now, and it's documented in the "Troubleshooting" page of the docs:

https://docs.bigchaindb.com/projects/server/en/v1.3.0/production-deployment-template/troubleshoot.html

I'm closing this issue.
