### ISSUE TITLE
In production, ensure system clocks used by BDB & MDB properly sync w/ NTP servers

### ISSUE THREAD

**Issue by ttmc** [bigchaindb/bigchaindb#1515]
In production, i.e. when using Docker containers and Kubernetes, we want the BigchainDB instances and MongoDB instances to be using reasonably-accurate time sources. Ideally, we'd like them to be getting the time from some source that's syncing with remote NTP servers.

To do:
- [ ] Look into how time is determined and synced today, when we deploy with Docker containers on k8s
- [ ] Make any necessary changes to our production deployment process, to meet the above-described goals

See also: [Timestamps in BigchainDB](https://docs.bigchaindb.com/en/latest/timestamps.html)

**Comment by krish7919** [comment]
Azure takes care of this for now.
It does also seem to have a bug syncing very aggressively.

```
Jul 24 13:29:41 k8s-master-DA6EDAE7-0 systemd[24922]: Time has been changed
Jul 24 13:29:41 k8s-master-DA6EDAE7-0 systemd[1]: Time has been changed
Jul 24 13:29:41 k8s-master-DA6EDAE7-0 systemd[1]: snapd.refresh.timer: Adding 4h 33.383277s random time.
Jul 24 13:29:41 k8s-master-DA6EDAE7-0 systemd[1]: apt-daily.timer: Adding 5h 55min 14.641048s random time.
Jul 24 13:29:41 k8s-master-DA6EDAE7-0 systemd[24922]: Time has been changed
Jul 24 13:29:41 k8s-master-DA6EDAE7-0 systemd[1]: Time has been changed
Jul 24 13:29:41 k8s-master-DA6EDAE7-0 systemd[1]: snapd.refresh.timer: Adding 10min 26.144518s random time.
Jul 24 13:29:41 k8s-master-DA6EDAE7-0 systemd[1]: apt-daily.timer: Adding 7h 11min 27.908971s random time.
Jul 24 13:29:46 k8s-master-DA6EDAE7-0 systemd[1]: Time has been changed
Jul 24 13:29:46 k8s-master-DA6EDAE7-0 systemd[24922]: Time has been changed
Jul 24 13:29:46 k8s-master-DA6EDAE7-0 systemd[1]: snapd.refresh.timer: Adding 46min 53.508294s random time.
Jul 24 13:29:46 k8s-master-DA6EDAE7-0 systemd[1]: apt-daily.timer: Adding 3h 3min 14.081726s random time.
Jul 24 13:29:46 k8s-master-DA6EDAE7-0 systemd[24922]: Time has been changed
Jul 24 13:29:46 k8s-master-DA6EDAE7-0 systemd[1]: Time has been changed
Jul 24 13:29:46 k8s-master-DA6EDAE7-0 systemd[1]: snapd.refresh.timer: Adding 1h 53min 51.436717s random time.
Jul 24 13:29:46 k8s-master-DA6EDAE7-0 systemd[1]: apt-daily.timer: Adding 10h 48min 30.905630s random time.
Jul 24 13:29:46 k8s-master-DA6EDAE7-0 docker[1622]: I0724 13:29:46.880891    1826 kubelet_node_status.go:433] Using Node Hostname from cloudprovider: "k8s-master-da6edae7-0"
Jul 24 13:29:51 k8s-master-DA6EDAE7-0 systemd[1]: Time has been changed
```

**Comment by muawiakh** [comment]
@ttmc @krish7919 shouldn't we close this ticket, since Azure is taking care of it? Or do we want to look into why this is so aggressive?

**Comment by ttmc** [comment]
It would be nice to know what's up with all those "Time has been changed" events.

Also, I'd like to do a little research into how Azure Container Service sets up NTP (or equivalent) and to add some notes about that to the documentation somewhere, maybe in this page:

https://docs.bigchaindb.com/projects/server/en/latest/appendices/ntp-notes.html

Having "good" timestamps is important for BigchainDB Server, and also for MongoDB, for different reasons.

**Comment by krish7919** [comment]
@muawiakh I would want to look at why is it so aggressive and why does it always say that it is adjusting the time, when it isn't. For the reasons @ttmc outlined above.
Till we have a data point that this is benign, it is a probable cause of failure.
Plus we haven't hit time sync bugs yet with a single node deployment; a multi-node deployment would bring these things to our notice.

**Comment by ttmc** [comment]
This isn't a concern of BigchainDB. It's up to the node operator / system administrator to do standard sysadmin stuff like this.
