### ISSUE TITLE
[transaction validation] Check that outputs contain supported and valid conditions

### ISSUE THREAD

**Issue by sbellem** [bigchaindb/bigchaindb#1516]
Given that BigchainDB supports a subset of cryptoconditions: ed25519 and threshold conditions, the transaction validation step should check whether the included conditions are supported and valid.

Relates to #1122: the transaction generation protocol should document which crypto-conditions are supported.

**Comment by r-marques** [comment]
I guess this also means that we will block/invalidate transactions with hashlock conditions.

If this is the case I don't know if removing support for hashlock conditions is the best solution. They are used heavily in some pocs and I think they are a requirement for the interledger protocol. @diminator thoughts?

To meet the transaction malleability guarantee maybe its enough to guarantee that a valid transaction contains at least on ed25519 fulfillment.

**Comment by ttmc** [comment]
Note: There's an issue that "All transactions must be signed": #1230 (currently open)

**Comment by ttmc** [comment]
Update: We've decided that BigchainDB version 1.0.0 will _not_ support hashlocks (i.e. preimage conditions). The only valid crypto-condition types in 1.0.0 will be ED25519 signature conditions and threshold conditions.

We may add support for hashlocks in a side branch, and in a future release of BigchainDB Server.
