### ISSUE TITLE
/outputs returns threshold conditions?

### ISSUE THREAD

**Issue by TimDaub** [bigchaindb/bigchaindb#1523]
See comment on /outputs endpoint: https://docs.bigchaindb.com/projects/server/en/master/http-client-server-api.html#get--api-v1-outputs?public_key=public_key

```The public_key parameter must be a base58 encoded ed25519 public key associated with transaction output ownership.```

- [x] clarify if our code actually works like this
  - [x] if so, change such that sha256Threshold public keys are also returned
  - [x] if not, adjust documentation

**Comment by TimDaub** [comment]
According to @r-marques, the `/outputs` endpoint indexes `transaction.outputs.public_keys`.

Hence, it will in fact return sha256Threshold conditions, meaning that [the docs](https://docs.bigchaindb.com/projects/server/en/v0.10.2/http-client-server-api.html#get--api-v1-outputs?public_key=public_key) are currently incorrect:

> The public_key parameter must be a base58 encoded ed25519 public key associated with transaction output ownership.

**Comment by r-marques** [comment]
This endpoint also returns threshold conditions.
Here is an example:

```python
pk1 = '9oZqQyAktAZ4Ka1a6iufVyG1mDDLoJ2J2fAZYEz63B6t'
pk2 = 'AqfnNNkRx1gAz6hWt2WqiUDzeCM6QYPHEENLyn96bFQc'
# ed25519
# tx1.id 67afbd0aba6d5c1f9ca7c09eebefe4d6eb80cf6c24abe8eca486e329494f8a84
tx1 = Transaction.create([b.me], [([pk1], 1)]).sign([b.me_private])

# ThresholdSha256
# tx2.id 09585367b302df55d74f6027a1406cd54adfdd1db848fe95df7d0935be158d5d
tx2 = Transaction.create([b.me], [([pk1, pk2], 1)]).sign([b.me_private])
```

```bash
$ $ curl http://localhost:9984/api/v1/outputs?public_key=9oZqQyAktAZ4Ka1a6iufVyG1mDDLoJ2J2fAZYEz63B6t
["../transactions/67afbd0aba6d5c1f9ca7c09eebefe4d6eb80cf6c24abe8eca486e329494f8a84/outputs/0", "../transactions/09585367b302df55d74f6027a1406cd54adfdd1db848fe95df7d0935be158d5d/outputs/0"]
```
