### ISSUE TITLE
Inconsistency in using relative links

### ISSUE THREAD

**Issue by TimDaub** [bigchaindb/bigchaindb#1525]
See [/outputs endpoint](https://docs.bigchaindb.com/projects/server/en/master/http-client-server-api.html#get--api-v1-outputs?public_key=public_key)

```
[
  "../transactions/2d431073e1477f3073a4693ac7ff9be5634751de1b8abaa1f4e19548ef0b4b0e/outputs/0",
"../transactions/2d431073e1477f3073a4693ac7ff9be5634751de1b8abaa1f4e19548ef0b4b0e/outputs/1"
]
```

[/status endpoint](https://docs.bigchaindb.com/projects/server/en/master/http-client-server-api.html#get--api-v1-statuses?tx_id=tx_id)

```
{
  "status": "valid",
  "_links": {
    "tx": "/transactions/38100137cea87fb9bd751e2372abb2c73e7d5bcf39d940a5516a324d9c7fb88d"
  }
}
```

notice `_links` being used here (both blocks and transactions).

This pattern is not repeated in `/assets`, the events API, `/blocks?tx_id`

**Comment by libscott** [comment]
Are links the thing we should be using? I just wonder because it seems like there would be more instances of people parsing links to extract the information than the links being convenient due to conforming to a protocol.
