### ISSUE TITLE
Proposal: Use Tendermint for consensus and replication

### ISSUE THREAD

**Issue by libscott** [bigchaindb/bigchaindb#1528]
This proposal is a revised version of #1508 that is easier to transition to and gives us flexibility for the long term. The proposal is to use Tendermint for replication and consensus.

## Consensus pipeline

(Turn off MongoDB replication)

1. Transaction is POSTed to BigchainDB web frontend
1. Transactions are collected into a block
1. Block is sent to Tendermint for replication
1. Tendermint asks each node to CHECK the block.
1. Node validates block schema and ID and says OK if it's valid
1. Tendermint asks each node to DELIVER the block.
1. Node writes block to bigchain table
1. Voting pipeline votes on block validity [using only information it has locally, not checking with any other node]

## Async fault tolerance

The above consensus pipeline does not form consensus on block results. One possible approach:

1. Each node writes vote result to Tendermint
1. Tendermint asks node to CHECK the vote result
1. Each node responds with OK, if they already have the result AND it is the same
1. Each node responds with NOT OK, if they do not have the result OR it is not the same
1. Eventually, someone will broadcast the block result and enough nodes will agree and Tendermint will commit it into the blockchain.

The same blockchain that communicates the block order could also contain the block results (see below), or they could be different ones.

![screenshot from 2017-06-09 15-13-21](https://user-images.githubusercontent.com/125019/26976911-395544b2-4d26-11e7-852c-eebf9d15c9ed.png)

@r-marques @ttmc @TimDaub

**Comment by ttmc** [comment]
I discussed this with @libscott and would like to add a few notes:

- The proposal in issue #1508 used a separate system to store the blocks and to replicate them around the network. That was removed in this proposal because it adds extra complexity. It could be added back in the future.
- In this proposal, each node has its own independent database, which it consults for most of its information.
- Each node would have to have some way to recover if it notices that it has gone off track (i.e. its latest block result disagreed with what Tendermint committed).

**Comment by libscott** [comment]
A few more points:

* All disagreements should be considered to be faults and requiring manual intervention. In the case of a fault, all information required to reproduce should be saved and an alert sent out. The fault will then need to be fixed and the replication log replayed to catch up. 
* Once the machine state is large enough, a bootstrapping procedure will be required in order to join or re-join the network, since it will be unfeasable to catch up via log replay. This could be achieved using backfill over a trusted replication protocol ie MongoDB. 
* From what i can see, Tendermint serializes the blockchain data so that it can be replayed. This includes all of the block data, so it may grow large. Elastic storage would be ideal. If at some point, replication is done separately, the blockchain will once again be lightweight.

**Comment by ttmc** [comment]
We _are_ integrating Tendermint now, but not in the way outlined in this issue.
