### ISSUE TITLE
JavaScript driver on live docs

### ISSUE THREAD

**Issue by kremalicious** [bigchaindb/bigchaindb#1534]
On _Drivers & Clients_ page, the current [live state](https://docs.bigchaindb.com/projects/server/en/latest/drivers-clients/index.html) doesn't reflect the [current `master` version](https://github.com/bigchaindb/bigchaindb/blob/master/docs/server/source/drivers-clients/index.rst). To the outside world, JavaScript driver doesn't exist.

**Comment by ttmc** [comment]
The default is for the BigchainDB Server docs to show the "latest" version which is always the same as the most recently-released numbered version (_not_ the `master` branch). 

Power-users, who want to read the docs from the `master` branch can do so: they just go to the version selector in the lower left corner of the docs.

Once we release BigchainDB Server version 1.0.0, the JavaScript driver (and the Ruby driver) will be listed on the default/latest _Drivers & Clients_ page.

I see two options: 

1. Close this issue as a non-issue, or 
2. Always show the `master` branch docs by default (instead of the latest numbered release).

I prefer option 1 because I want the default docs to serve normal users (i.e. users of the latest numbered release), not power-users.

**Comment by TimDaub** [comment]
> Always show the master branch docs by default (instead of the latest numbered release).

Not an option. master can contain breaking changes.

> Close this issue as a non-issue, or

An option I'd consider

**3. Option**

- we release a new patch version of BDB that includes the link to the js driver in the docs

**Comment by TimDaub** [comment]
Fully agreed.

@kremalicious, when I did the drivers page in the docs I actually wanted to aim for something like:

https://docs.mongodb.com/ecosystem/drivers/

In my opinion, our drivers deserve their own page on our website anyways.

Hence, my proposal:

- remove https://docs.bigchaindb.com/projects/server/en/latest/drivers-clients/index.html from docs
- create "Drivers" page under bigchaindb.com
- from docs, link to bigchaindb.com/drivers

**Comment by kremalicious** [comment]
at least Drivers page is in progress here https://trello.com/c/Or2ViAEF/38-get-started-page

Think this shows the bigger problem: our documentation is completely project-based which is not scalable. Drivers & Clients page is one thing, documenting the drivers another thing, where we have already an overlap between python driver and javascript driver.

With our current docs strategy: the Drivers & Clients page should be a somewhat global page, linked to from the start page: https://docs.bigchaindb.com/en/latest/index.html But guess this page is based on current server release version too?

**Comment by ttmc** [comment]
I like the idea of removing the Clients & Drivers page from the BigchainDB Server docs, and moving its contents elsewhere, preferably somewhere that can be updated (in its default view) whenever we like (not just when there's a new version of BigchainDB Server).

I'm not really happy with the word "Clients" any more. For me, a "client" is something like an Android app which uses a driver internally. I'd just call it "Drivers and Tools" where a tool can be anything that falls short of being a full driver, such as a keypair generator.

We could create a patch release to update the links in the BigchainDB "root" docs (/docs/root) and the BigchainDB "server" docs (/docs/server), to point to the URL of the "Drivers and Tools" page.

**Comment by kremalicious** [comment]
For now, we leave the drivers page within the server docs. We are going to have a new Get started page at end of this week, including a section linking to our drivers/tools. But doesn’t hurt having this in both places for now, at least until we figure out a better place for our global docs.

Thanks @ttmc for the "Drivers and Tools" suggestion, less confusing and I'm already using this vocabulary on Get started page so would make sense changing this in the server docs part too?

<img width="904" alt="screen shot 2017-06-26 at 11 19 01" src="https://user-images.githubusercontent.com/90316/27532657-46cca818-5a61-11e7-9c4e-45762e5b55e8.png">
