### ISSUE TITLE
Document undocumented graphite.host config setting?

### ISSUE THREAD

**Issue by ttmc** [bigchaindb/bigchaindb#1537]
I used `bigchaindb -y configure mongodb` to generate a default configuration file (in `~/.bigchaindb`) and when I looked at the generated file, it contained:
```json
    "graphite": {
        "host": "localhost"
    }
```

This setting is not documented in [the BigchainDB Configuration Settings docs page](https://docs.bigchaindb.com/projects/server/en/latest/server-reference/configuration.html). Should it be?

Should that be a configuration setting at all? Can we hard-code the value as `localhost` and leave it up to benchmarkers to edit the BigchainDB Server code if they want to change it to something else? (I'm not sure. I'm just asking.)

I'm assigning this issue to @libscott because I believe he added this setting.

**Comment by r-marques** [comment]
At this point that setting is only used for the benchmarks. It shouldn't be in the config file.

**Comment by libscott** [comment]
Id go with documenting it, since it may well be useful for monitoring production deployments.

**Comment by krish7919** [comment]
@r-marques @libscott To document or not to document?

**Comment by r-marques** [comment]
Let's document it
