### ISSUE TITLE
Tendermint Integration

### ISSUE THREAD

**Issue by jaekwon** [bigchaindb/bigchaindb#154]
Here's an issue to discuss potential integration w/ TMSP.

The purpose of TMSP is to separate the concerns of blockchain BFT network & security from the business logic of the application itself.  [Tendermint Core](http://github.com/tendermint/tendermint) orders the transaction bytes into a blockchain, and speaks to the [TMSP application](http://github.com/tendermint/tmsp).  ([see more](http://tendermint.com/posts/tendermint-socket-protocol/))
### What it provides for BigchainDB:
- Provides [the best BFT solution](https://github.com/tendermint/tendermint/wiki/Byzantine-Consensus-Algorithm).
- Addresses #123, #77, #131, probably #134, and also helps with #127
- Partially solves #126 with the "InitChain" and "EndBlock" TMSP messages.
- Probably some more that aren't on the Roadmap page.

Integration would require creating a TMSP server in Python.  We used to have a Python server but this was before TMSP used Protobuf, so we'll have to re-implement it.

In an example deployment, there would be a network of connected Tendermint Core instances, each running 1-to-1 alongside BigchainDB app instances.  The BigchainDB can expose its own RPC endpoints, can handle state persistence, etc, so integration is straightforward.

**Comment by Xoccam** [comment]
Nice Work :)

**Comment by ttmc** [comment]
Yesterday we had a call with @jaekwon and others to discuss ways that BigchainDB might work with Tendermint. There are a some intriguing options and we'll definitely be exploring this further.

**Comment by ttmc** [comment]
@jaekwon We may use Tendermint or TMSP to provide some functionality (and in fact I have one specific use in mind), but that will get its own issue or set of issues as needed.

**Comment by janhon** [comment]
is there any update on the status of this ?

**Comment by sbellem** [comment]
@janhon well, ..., just in case you still wondered. We're now working on it!

**Comment by ttmc** [comment]
@jaekwon @Xoccam @janhon - BigchainDB 2.0 Alpha was released today and it uses Tendermint for consensus, replication, sync, etc. You can read more about that in my blog post "[BigchainDB 2.0 is Byzantine Fault Tolerant](https://blog.bigchaindb.com/bigchaindb-2-0-is-byzantine-fault-tolerant-5ffdac96bc44)".
