### ISSUE TITLE
HTTP API logger needs to log paths

### ISSUE THREAD

**Issue by TimDaub** [bigchaindb/bigchaindb#1546]
A logging message we currently get from our live deployments is e.g. 

```
[2017-06-15 11:07:08] [ERROR] (bigchaindb.web.views.base) HTTP API error: 400 - Invalid transaction schema: '1' is not of type 'integer' (webapi - pid: 59)
```

As `make_error` in base is returning the 400 error, a user looking at these logs can only speculate on which endpoint this error was throw.

To complete this ticket, include information about the path requested in the logs.

**Comment by ketanbhatt** [comment]
@TimDaub can I take this up?

**Comment by TimDaub** [comment]
@ketanbhatt: Sure, go for it! :)

**Comment by ketanbhatt** [comment]
@TimDaub have submitted a PR. Sorry for the delay, got caught up. Thank you
