### ISSUE TITLE
Version bigchiandb/mongodb container independent of the official mongodb container

### ISSUE THREAD

**Issue by krish7919** [bigchaindb/bigchaindb#1549]
Currently, I have versioned the bigchaindb/mongodb container as per the mongodb version, which is 3.4.4.
This is not a feasible versioning scheme if we are not following the mongodb release cycle.

Today, I had to update the containers after enabling auth. And I had to bump up the version number too.
But I cannot set it to 3.4.5 (as it hasn't been released yet).

In the future, we can look at the bigchaindb/mongodb Dockerfile and find out which version of MongoDB are we running.

Thoughts, @ttmc ?

**Comment by ttmc** [comment]
Maybe we could use an obviously-different versioning scheme for the bigchaindb/mongodb container, e.g. 

bigchaindb/mongodb:67.0
bigchaindb/mongodb:68.0

That way, nobody would think that our version numbers have anything to do with [the version numbers on the official "mongo" container](https://hub.docker.com/r/library/mongo/tags/).

**Comment by krish7919** [comment]
We can use any number we want. I just started with `1.0`, `2.0` was with TLS, and `3.0` will be with TLS+Auth enabled.

**Comment by ttmc** [comment]
:+1:
