### ISSUE TITLE
Events API clients are disconnected after some time the server is inactive

### ISSUE THREAD

**Issue by vrde** [bigchaindb/bigchaindb#1553]
Right now the server implements the ping/pong protocol (`autoping` is set by default to `True`):
> autoping (bool) – Automatically send PONG on PING message from client, and handle PONG responses from client. Note that server does not send PING requests, you need to do this explicitly using ping() method.

So if a client pings, the server pongs :ping_pong:

If we want, we can enable the `heartbeat` feature:
> heartbeat (float) – Send ping message every heartbeat seconds and wait pong response, close connection if pong response is not received.

In this way, the server is *proactive* and pings the client.

See the [aiohttp docs](http://aiohttp.readthedocs.io/en/v2.1.0/web_reference.html#websocketresponse) for more details.

We can do one of the following:
 1) Leave it like this, and add a line to the documentation saying that if a client wants to keep the connection open then it must ping the server (we also need to test this behaviour).
 2) Enable `heartbeat`, so the server takes care of pinging the clients (again, we need to test this as well).

In both cases we need to adapt the `NGINX` timeout.

**Solution 1** is a bit cheaper in terms of resources used by the server, and delegates more to the client (like _hey, if you want to keep the connection please do something_). AFAIK websockets libraries usually implement this feature, so on the client side it should be as easy as setting a flag.

**Solution 2** is simpler for the client.

IMO **solution 1** is safer in case of malicious clients.

**Comment by krish7919** [comment]
We just need to ensure that the NGINX timeout is greater than the timeout the client/server will use for the ping/pong protocol; NGINX will have no reason to timeout as it will always see _some_ activity on the connection.
