### ISSUE TITLE
Returned values of /outputs?safe=true and /outputs?safe=false should be compatible

### ISSUE THREAD

**Issue by TimDaub** [bigchaindb/bigchaindb#1559]
@jmduque made a really good point to me on gitter.

`/outputs` will have [two different return values](https://github.com/bigchaindb/bigchaindb/blob/99499b1f8783719a082813912ac9a0d363ae278f/bdb-ip.md#outputs-return-definition) later, those being:

```
GET /outputs?safe=true

[{
    "transaction_id": "abc",
    "output": 0,
    "asset_id: "e.g. abc - depending on what transaction operation"
}, ...]

GET /outputs?safe=false
[{
    "transaction_id": "abc",
    "output": {
        "amount": 1,
        "condition": {
            "details": {
                "bitmask": 32,
                "public_key": "4K9sWUMFwTgaDGPfdynrbxWqWS6sWmKbZoTjxLtVUibD",
                "signature": null,
                "type": "fulfillment",
                "type_id": 4
            },
            "uri": "cc:4:20:MTmLrdyfhfxPw3WxnaYaQkPmU1GcEzg9mAj_O_Nuv5w:96"
        },
        "public_keys": [
            "4K9sWUMFwTgaDGPfdynrbxWqWS6sWmKbZoTjxLtVUibD"
        ]
    },
    "asset_id": "e.g. abc - depending on what transaction operation",
}]
```

at this point however, these two endpoints are not compatible, as the `output` value is getting replaced from an index to an object. That makes implementation cumbersome.

Instead, why not rename `safe=true`'s `output` value with `output_id` (or anything alike) and in `safe=false` just add `output`. Here is an example:

```
GET /outputs?safe=true

[{
    "tx_id": "abc",
    "output_id": 0,
    "asset_id: "e.g. abc - depending on what transaction operation",
}, ...]

GET /outputs?safe=false
[{
    "tx_id": "abc",
    "output_id": 0, // <======= note how `output_id` is still here
    "output": {
        "amount": 1,
        "condition": {
            "details": {
                "bitmask": 32,
                "public_key": "4K9sWUMFwTgaDGPfdynrbxWqWS6sWmKbZoTjxLtVUibD",
                "signature": null,
                "type": "fulfillment",
                "type_id": 4
            },
            "uri": "cc:4:20:MTmLrdyfhfxPw3WxnaYaQkPmU1GcEzg9mAj_O_Nuv5w:96"
        },
        "public_keys": [
            "4K9sWUMFwTgaDGPfdynrbxWqWS6sWmKbZoTjxLtVUibD"
        ]
    },
    "asset_id": "e.g. abc - depending on what transaction operation",
}]
```

**Note:** Changing this, would probably also mean changing `transaction.fulfills.output` to `transaction.fulfills.output_id`, to stay consistent.

**Comment by ttmc** [comment]
I would call that thing an "output_index" rather than an "output_id".

An "output_id" suggests that it's a unique identifier for that output among all the other outputs in the world (such as a hash or a UUID), but it's not. It's just the index of an output in a list of outputs.

**Comment by TimDaub** [comment]
As always, this tickets requires changes on various components before it can be closed:

A quick task check list:

- [ ] Adjust javascript driver
- [ ] Adjust python driver
- [ ] Adjust CLI
- [ ] Make change in BDB server
- [ ] Add to changelog in
- [ ] Add to upgrade-guide in

**Comment by ttmc** [comment]
@libscott It looks like the "Adjust python driver" step is done, i.e.  https://github.com/bigchaindb/bigchaindb-driver/pull/306/commits/f52fa3869d604842fcb5872c783e5c114398ed3d (That commit is part of a pull request that hasn't been merged yet because it's waiting on BigchainDB Server 1.0.0 to be released.)

Can we get that box checked and close this issue?
