### ISSUE TITLE
Refactor monitoring code

### ISSUE THREAD

**Issue by vrde** [bigchaindb/bigchaindb#156]
I'd like to move the monitoring code from `bigchaindb.core.Bigchain` to the modules `bigchaindb.block` and `bigchaindb.voter`.

Why? For three main reasons:
- to keep the `Bigchain` class cleaner
- the call to `monitor = Monitor()` ([core.py:15](https://github.com/bigchaindb/bigchaindb/blob/develop/bigchaindb/core.py#L15)) might trigger `bigchaindb.config_utils.autoconfigure` **before** other configuration functions
- because `bigchaindb.block` and `bigchaindb.voter` are the places where the computation happens.

Unfortunately #153 partially depends on this issue. I can use a workaround to have #153 merged on `develop` but this issue should be fixed relatively soon.

**Comment by vrde** [comment]
@rhsimplex any thoughts on that?

**Comment by rhsimplex** [comment]
Oh hi just saw this, sorry. Yeah I don't see why not. Do you need anything from me?
