### ISSUE TITLE
Problem with bigchaindb cluster

### ISSUE THREAD

**Issue by chssp02409** [bigchaindb/bigchaindb#1569]
I am trying to connect two bigchaindb nodes as a cluster.I followed doc.. of bigchaindb to set up the connection.  But after the set up while i am trying to do any transaction it is not validating my transactions please help me this.
I am using mongodb as a database.
Thanks in advance.

**Comment by ttmc** [comment]
Hi @chssp02409 

* Which version of BigchainDB Server are you using?
* What operating system are you using?
* Which docs are you following?
* What specific problems are you having? Feel free to share error messages or screenshots.
