### ISSUE TITLE
Remove "output.condition.details.signature" from transaction

### ISSUE THREAD

**Issue by libscott** [bigchaindb/bigchaindb#1583]
Currently our transaction outputs have a `signature` field in the case of an ed25519 condition (see image). This is because it's a fulfillment type that's encoded to get the information neccesary to sign a payload, and the fulfillment may contain a signature.

The proposal is to remove that from the transaction model, since the signature field should never be populated.

@r-marques @diminator @tim @sbellem 

![screenshot from 2017-06-23 11-40-49](https://user-images.githubusercontent.com/125019/27476426-038a2c4c-5809-11e7-86f6-6b8c43adfd27.png)

**Comment by r-marques** [comment]
Instead of using removing the signature can't we just use the condition details instead of the fulfillment details?

**Comment by libscott** [comment]
> Instead of using removing the signature can't we just use the condition details instead of the fulfillment details?

There isn't actually an Ed25519 condition object in the Python driver, that contains the details neccesary to sign, only the fulfillment. Regardless of the implementation though, there's no need for the signature to be in the condition.

**Comment by ttmc** [comment]
I wonder what would happen if someone (who didn't know what they were doing) replaced the `null` value (for an `output.condition.details.signature`) with a valid signature. Would BigchainDB Server complain? Or would it just happily accept the non-null signature, making the output the equivalent of a locked door with a key in the lock?

**Comment by TimDaub** [comment]
As always, this tickets requires changes on various components:

A quick task check list:

- [ ] Adjust javascript driver
- [ ] Adjust python driver
- [ ] Adjust CLI
- [ ] Make change in BDB server #1574
- [ ] Add to changelog in #1561
- [ ] Add to upgrade-guide in #1547
