### ISSUE TITLE
Text search on transactions metadata

### ISSUE THREAD

**Issue by TimDaub** [bigchaindb/bigchaindb#1592]
Similar to the text search provided via `/assets?search=` for assets, we'd like to have the same functionality for a transactions meta data.

Internally for BigchainDB this would mean:

- splitting meta data and transaction apart in the underlying data base
- content linking between the two
- implement an endpoint similar to `/asset?search=` for meta data

This use case was put forth by a high priority customer.

**Comment by r-marques** [comment]
It makes sense and it shouldn't be much work to implement it. Everything is already setup because of the decoupling of the assets.

**Comment by ttmc** [comment]
The problem of not being able to text search metadata was just brought up by a user on Gitter, see:

https://gitter.im/bigchaindb/bigchaindb?at=59721adc614889d475d8a5cf

**Comment by TimDaub** [comment]
@diminator is also interested in this.
