### ISSUE TITLE
[docs] Add a library reference section to documentation

### ISSUE THREAD

**Issue by sbellem** [bigchaindb/bigchaindb#1600]
Currently, the code that has docstrings is partially included in the docs in the Appendices section.

There are a few problems with the current situation:

* It is quite impractical and hard to find.
* Only a partial amount of the code that has docstrings is actually included in the docs.
* Many of the docstrings for the undocumented code are incorrect, but no one knows about it.

**Comment by ttmc** [comment]
@sbellem Is the idea to make a new section a the same level as the Appendices (in the docs hierarchy, and to move all the auto-generated docs based on docstrings to there)?

If so, I think that would help make the Appendices much more manageable.
