### ISSUE TITLE
Remove hardcoded port number from bigchaindb-dep.yaml

### ISSUE THREAD

**Issue by krish7919** [bigchaindb/bigchaindb#1617]
Maybe use `          value: $(MDB_INSTANCE_0_SERVICE_PORT_MDB_PORT)` rather than `          value: "27017"` instead?
And for `          value: "9985"` too

**Comment by ttmc** [comment]
Note: We didn't do this already because it wasn't clear if the environment variable `$(MDB_INSTANCE_0_SERVICE_PORT_MDB_PORT)` is set or has another name, so we deferred figuring that out until later.

**Comment by krish7919** [comment]
Fixed in #1677
