### ISSUE TITLE
WSSERVER_EXTERNAL_HOST setting

### ISSUE THREAD

**Issue by krish7919** [bigchaindb/bigchaindb#1626]
Currently we have this:
```json
{
"api": {
"v1": {
"assets": "/api/v1/assets/",
"docs": "https://docs.bigchaindb.com/projects/server/en/v1.0.0rc1/http-client-server-api.html",
"outputs": "/api/v1/outputs/",
"statuses": "/api/v1/statuses/",
"streams": "ws://0.0.0.0:9985/api/v1/streams/valid_transactions",
"transactions": "/api/v1/transactions/"
}
},
"docs": "https://docs.bigchaindb.com/projects/server/en/v1.0.0rc1/",
"keyring": [],
"public_key": "983tiwtPKXrcWSkDTMiGCNoYAMpSgW5PV2KHqvu12Zsh",
"software": "BigchainDB",
"version": "1.0.0rc1"
}
```

Since we have decided to include a `ws://host:port` section for the `streams` key, we need a way to overwrite the default value of `0.0.0.0` in the configuration.
Thoughts, @TimDaub ?

**Comment by ttmc** [comment]
Today, BigchainDB Server doesn't have enough information to know the hostname of the host serving the WebSocket API. One solution would be to add a new BigchainDB Server configuration setting, as the title of this issue suggests, but it would be informational only (i.e. not actually used internally).

Another solution would be to report something like:

```json
"streams": "ws://<hostname>:9985/api/v1/streams/valid_transactions",
```

with the literal string `<hostname>` and then they can figure out the hostname for themselves.

**Comment by TimDaub** [comment]
I'm confused. I thought this was already in BDB 1.0: https://github.com/bigchaindb/bigchaindb/pull/1538/files#diff-dcbd9f8ec7effff8bc56028986a1d351R24

Using the BDB config file, if you add:

````
{
  "wsserver": {
    "host": "whateveryouwant"
  }
}
````

or an `BIGCHAINDB_WSSERVER_HOST` env var. Did you try that?

**Comment by krish7919** [comment]
@TimDaub The `BIGCHAINDB_WSSERVER_HOST` is the config used to bind to the port; it is not the  config for _displaying_ the `host` to the external clients. The above commit just adds a new `scheme` parameter which is what gets displayed properly.

Reference: https://github.com/bigchaindb/bigchaindb/blob/master/bigchaindb/web/websocket_server.py#L158

**Comment by TimDaub** [comment]
Oh I understand. I flagged this as a bug then.
