### ISSUE TITLE
If the primary node of mongodb replica set is power off, the run_changefeed(conn, table, last_ts) function is hung on

### ISSUE THREAD

**Issue by yihuazhai** [bigchaindb/bigchaindb#1627]
When I power off the primary node of mongodb (not command "reboot" or "shutdown"), the run_changefeed function is hung on the line "record = cursor.next()" because the socket is not set to timeout mode. Default read mode is to read from primary node. If the bug occurs, the remaining nodes can not vote for new blocks because they cannot read from the mongodb by run_changefeed function.

The solution is:
```python
            client = pymongo.MongoClient(self.host,
                                         self.port,
                                         replicaset=self.replicaset,
                                         serverselectiontimeoutms=self.connection_timeout,
                                         ssl=self.ssl,
                                         socketTimeoutMS=20000, #add this
                                         readPreference='nearest') #add this
```
if socketTimeoutMS is set, when the primary node is powered off, after socketTimeoutMS time, the run_changefeed function is going on again.
readPreference is set to improve the performance.

**Comment by libscott** [comment]
Hi @yihuazhai, 

Thanks for this report. I was able to reproduce the issue by running MongoDB inside a Docker container and pausing it. The `cursor.next()` method blocks and does not yield, as you said. With the addition of `socketTimeoutMS`, a timeout is raised and the connection is retried. Upon successful reconnection, the changefeed processes resume.

**Comment by libscott** [comment]
Many thanks @yihuazhai !

**Comment by yihuazhai** [comment]
@libscott 👍
