### ISSUE TITLE
Handling the case of votes pointing to different blocks as the previous block

### ISSUE THREAD

**Issue by ttmc** [bigchaindb/bigchaindb#165]
The following sentence from the whitepaper is bothering me:

> If for some reason, the nodes disagree on the parent of a block, then one node can just mark the block as decided_invalid and copy the transactions to the backlog to try again.

There are some problems with this:

First, We don't actually "mark" blocks as decided_valid or decided_invalid, do we? I thought that was just something that gets determined as needed, at query time. The block model doesn't even have a field for undecided / decided_valid / decided_invalid.

http://bigchaindb.readthedocs.org/en/develop/models.html#the-block-model

Second, even if we do add such a field, if we give any node the power to mark an entire block as decided_invalid, what's to stop a malicious node from abusing that power?

We need a better answer to the question, "What do you do when not all votes point to the same parent block?"

This can happen, for example, if a node does down. When it comes back up, it hasn't seen the bigchain table's changefeed during the time it was down, and there's no reliable way to recover it, including the order of the blocks.

Maybe when a query is made to find out if a block is undecided / decided_invalid / decided_valid , the answer should also depend on whether the pointers to the parent block agree? If they don't all agree, then maybe the block is decided_invalid?

There's a related question: When do the transactions in a decided_invalid block get copied back to the backlog? There's no event to trigger that. It's not like there's a monitor that's checking to see when blocks become decided. Even if there were, who gets the power to do that copying? Is it safe to let one node do that, or is consensus needed?

**Comment by r-marques** [comment]
> What do you do when not all votes point to the same parent block?"

The easiest answer is that this does not happen. We are working under the assumption that rethinkdb guarantees that all nodes see the events on the same order so this should not happen.
There is however the edge case in which a node goes down and loses the pointer to the parent block.
Here there are two solutions:
- Vote invalid (until you receive a new block in the changefeed and re-acquire a pointer to the previous block)
- Follow what the majority decided while the node was down (he can still validate the transactions and use the same parent as the majority)

> We don't actually "mark" blocks as decided_valid or decided_invalid, do we?
We do know the number of votes required for majority. The monitor will be part of the consensus and the monitor once it receives a vote update and sees that the majority as decided the block invalid it can them move the transactions back to the backlog. Which node actually moves the transactions back to the backlog will need to be decided in the consensus protocol (this could probably be done with a pre commit phase in which a majority of the nodes need to decide for the transactions to be sent back to the backlog)

**Comment by ttmc** [comment]
When a node goes down and comes back up, it _can_ validate the transactions in blocks that got created while it was down, but it can't reliably set the `previous_block` field of its votes on those blocks. Maybe it could just put "uncertain" as the value of `previous_block` for those blocks?

**Comment by r-marques** [comment]
The block order is important. You can only correctly validate the transactions in a block if you know the order of the blocks so I don't think that settings previous block as "uncertain" would be a good approach.

**Comment by ttmc** [comment]
I'm going to close this issue and reference it from our (external) faults/issues document (i.e. the one Dimi started on Google Drive).

**Comment by ttmc** [comment]
A node that was down and came back up can vote that a block is invalid, but that says nothing about the id/hash value it gives for the previous_block. `is_block_valid` and `previous_block` are two separate fields.

**Comment by r-marques** [comment]
If the node does not know the previous block it can just set the `previous_block` field to `null`

**Comment by ttmc** [comment]
I'm reopening this issue because we're moving from using that external faults/issues document (on Google Drive) to using GitHub as the place for known faults/issues.

**Comment by ttmc** [comment]
I'll also remark that if a node was down and comes back up, it may not have to vote on a bunch of new blocks that came in while it was gone: those blocks may already have enough votes.

**Comment by ttmc** [comment]
@rhsimplex I will let you decide if this is still open or got resolved by your recent PR.
