### ISSUE TITLE
Possible mongodb query not using secondary index.

### ISSUE THREAD

**Issue by r-marques** [bigchaindb/bigchaindb#1656]
From @ferOnti in gitter https://gitter.im/bigchaindb/bigchaindb?at=595ad1e86ae41d5d33b052db

> Hi, I was stressing the bigchaindb, and after 20k assets, I found this "slow query" in mongodb.log:

```bash
2017-07-03T23:21:26.490+0000 I COMMAND [conn4274] command bigchain.bigchain command: mapReduce { mapreduce: "bigchain", map: "function () {
        this.block.transactions.forEach(function (tx) {
            var key = tx.operation
            var value = 1
            emit(key, value);  
        })
    }", reduce: "function (key, values) {
        //var reduceVal = {count:0, sum: 0}
        var reduceVal = 0
        values.forEach(function(value) {   
            reduceVal +...", query: {}, out: { inline: 1 } } planSummary: COLLSCAN keysExamined:0 docsExamined:3362 numYields:26 reslen:245 locks:{ Global: { acquireCount: { r: 130 } }, Database: { acquireCount: { r: 4, R: 61 } }, Collection: { acquireCount: { r: 4 } } } protocol:op_query 178ms
```
> I think this query is related to get the last transaction

Did this happened only when inserting assets? Or was there some reads also?

From the `planSummary` we can see that this query is doing a collection scan instead of an index scan.

**Comment by r-marques** [comment]
Another occurrence for @ferOnti on gitter https://gitter.im/bigchaindb/bigchaindb?at=59669b4bbf7e6af22cd105da

> hi, I was stressing the server, and I found this slow query in mongo: 

```bash
2017-07-12T21:49:21.599+0000 I COMMAND [conn109] command local.oplog.rs command: find { find: "oplog.rs", filter: { o.id: "35d8494d7b84a0b2d8ace65d50d2ab6120674cf5f3d46b156b3fc02395fdcb1e", op: "i", ns: "bigchain.bigchain" }, sort: { $natural: -1 } } planSummary: COLLSCAN keysExamined:0 docsExamined:508144 cursorExhausted:1 numYields:3976 nreturned:1 reslen:1433 locks:{ Global: { acquireCount: { r: 7954 } }, Database: { acquireCount: { r: 3977 } }, oplog: { acquireCount: { r: 3977 } } } protocol:op_query 1357ms
```

> I sent 5k "create asset" operations, I have a 2-bigchaindb nodes in cluster, but after process the first 2k operations, the mongo's log showed slow queries like this.

**Comment by kansi** [comment]
@r-marques trying to replicate this issue. I tried using [benchmark](https://github.com/bigchaindb/benchmark) library but mongodb logs don't show any of the above listed logs. Could you please suggest how do I go about doing the same?

**Comment by kansi** [comment]
@r-marques @TimDaub  The `oplog` query should not be an issue as the mongodb docs describe it to be of finite size and optimized for sequential reads (the same was suggested by @r-marques). Futhermore, the `mapReduce` query doesn't seem to be there in our codebase although I would love it to be otherwise.

**Comment by ferOnti** [comment]
Hi, you can close this issue, I did some stress testing 5 months ago

The issue with the COLLSCAN in the map reduce is something we can't improve, because as I know, we can't add indexes in the reduce stage, only in the map.

and the oplog query, I don't know if this is happening in last version, because I used a version previous to 1.0

**Comment by kansi** [comment]
@ferOnti  thanks for clearing that up.
@vrde we have a query [here](https://github.com/bigchaindb/bigchaindb/blob/master/bigchaindb/backend/mongodb/query.py#L57) which uses `id`.
