### ISSUE TITLE
BigchainDB python package(1.0.0) does not work out-of-the-box on a fresh Ubuntu installation

### ISSUE THREAD

**Issue by muawiakh** [bigchaindb/bigchaindb#1657]
While following the [quickstart guide](https://docs.bigchaindb.com/projects/server/en/latest/quickstart.html), on a fresh ubuntu 16.04 machine, the BigchainDB(1.0.0) package installation i.e. `sudo pip3 install bigchaindb` does not work out of the box and doesn't install the relevant dependencies. 

My machine had cryptography 1.2.3 but cryptoconditions 0.6.0-dev1 is dependent on cryptography 1.9, instead of downloading and upgrading the package the pip install returns with a package conflict error. Similar case with another module pyasn1, I had an older version of it installed on the fresh Ubuntu and the required version was 0.2.3 for cryptoconditions. Resulting in the same package conflict failure.Error message looks like this:

`    pkg_resources.VersionConflict: (cryptography 1.2.3 (/usr/local/lib/python3.5/dist-packages), Requirement.parse('cryptography~=1.9')) \ 
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-blx46w43/bigchaindb `

**Workaround**
Manually upgrade all the packages that `sudo pip3 install bigchaindb` complains about i.e.

`sudo pip3 install [packageName]==[packageVersion]
OR
sudo pip3 install [packageName] --upgrade`

After upgrading run `sudo pip3 install bigchaindb`

**Issue**
Issue is that "cryptoconditions" is part of setup_requires list of setup.py, and due to some race condition using setup_requires and install_requires together, instead of upgrading the package on the system, it only downloads them to the .eggs directory and errors out after that.

- One solution(tested already) could be to remove cryptoconditions from the setup_requires list in setup.py and after that everything works seamlessly, but if we do this the .eggs directory of bigchaindb repo will not have have the egg file for cryptoconditions. Not sure, if that is needed by someone. Everything else starts working seamlessly. @ttmc or @sbellem can comment.

**Comment by ttmc** [comment]
In `setup.py`, the line:
```python
setup_requires=['pytest-runner', 'cryptoconditions'],
```
never used to have `'cryptoconditions'` in it. That was added between version 0.10.3 and 1.0.0.

The docs about `setup_requires` are at https://setuptools.readthedocs.io/en/latest/setuptools.html 

> setup_requires

> A string or list of strings specifying what other distributions need to be present in order for the setup script to run. setuptools will attempt to obtain these (even going so far as to download them using EasyInstall) before processing the rest of the setup script or commands. This argument is needed if you are using distutils extensions as part of your build process; for example, extensions that process setup() arguments and turn them into EGG-INFO metadata files.

> (Note: projects listed in setup_requires will NOT be automatically installed on the system where the setup script is being run. They are simply downloaded to the ./.eggs directory if they’re not locally available already. If you want them to be installed, as well as being available when the setup script is run, you should add them to install_requires and setup_requires.)

**Comment by muawiakh** [comment]
+1
