### ISSUE TITLE
bigchaindb listens on port 9020 by default, cannot be disabled and port cannot be changed

### ISSUE THREAD

**Issue by skoehler** [bigchaindb/bigchaindb#1660]
As far as I can see from the python source, bigchaindb 1.0.0 always opens a logging server on TCP port 127.0.0.1:9020. It seems like this cannot be disabled and also the port number cannot be changed.

This effectively prohibits me from running multiple bigchaindb instances on the same host (say for the purpose of setting up a development system). I'm aware that I could have multiple docker containers, but I prefer to keep things as simple as possible.

**Comment by r-marques** [comment]
relates to #1625
