### ISSUE TITLE
bigchaindb should not create tables automatically

### ISSUE THREAD

**Issue by skoehler** [bigchaindb/bigchaindb#1661]
Creating the tables automatically is a bad idea. Assume a cluster of rethinkdb servers which do not have the tables yet. Starting bigchaindb simultaneously on two servers may result in the tables being created on 2 rethinkdb nodes. This will eventually lead to conflicts. Rethinkdb then complains loudly about multiple conflicting tables with the same name.

The tables must be created manually on one node of the rethinkdb cluster. All bigchaindb instances must wait until the tables become available.

I would have hoped that there is at least an option to disable automatic table creation.

**Comment by r-marques** [comment]
One way to do it would be not to run `init` with `bigchaindb start`.
This way `bigchaindb init` could be run on one node to setup the database.
If `bigchaindb start` is run without the database being initialized it should just fail instead of attempting to setup the database by running the `init` routine

**Comment by skoehler** [comment]
Currently, bigchaindb start automatically creates the tables, it does not fail. I cannot run bigchaindb init automatically on every node of the cluster, since it would lead to the conflicts I describe. I must manually chose once node of the cluster to initialize the database.

**Comment by krish7919** [comment]
Might be relevant to #1323 and #1375

**Comment by kansi** [comment]
@r-marques @skoehler  We can tackle this issue in two ways:
  - Remove table initializations from `start` command in which case we would need to direct the users to execute `init` before `start`.
  - Create a new command `run` which will allow us to not alter the behaviour of `start` command.

**Comment by r-marques** [comment]
@kansi I agree that `start` should not run `init` by default so we need to change that.
I would propose a third solution which would be to set a flag to the `start` command to force the creation of the tables. Something like
```bash
$ bigchaindb start --init
```

Another thing to keep in mind is that we may need to change the docker files. @sbellem can help with that.
