### ISSUE TITLE
bigchaindb's main process doesn't use signal handlers

### ISSUE THREAD

**Issue by skoehler** [bigchaindb/bigchaindb#1662]
Starting bigchaindb in the terminal and pressing Crtl+C works just fine. All child processes are terminated.

However, starting bigchaindb (e.g. with nohup) and then killing it (either with SIGTERM or SIGINT) will not result in bigchaindb shutting down properly. Only the main process exits. The child processes stay hanging around.

In python, catching KeyboardInterrupt doesn't suffice to respond to signals like SIGINT. Signal handlers must be set to ensure a proper shutdown of bigchaindb.

**Comment by ttmc** [comment]
Related issue:  #1302

**Comment by r-marques** [comment]
Also related to #1397 and #1279

**Comment by sbellem** [comment]
> We should create a project/milestone to bundle all these related issues.

There's already a project: https://github.com/bigchaindb/bigchaindb/projects/7

:smile:

**Comment by ldmberman** [comment]
Addressed in #2395.
