### ISSUE TITLE
Election pipeline fails if a block has an invalid hash

### ISSUE THREAD

**Issue by r-marques** [bigchaindb/bigchaindb#1667]
If a block is written with an invalid hash `Block.from_dict` https://github.com/bigchaindb/bigchaindb/blob/v1.0.1/bigchaindb/pipelines/election.py#L51 will raise an `InvalidHash` exception that is not handled by the election pipeline.

**Comment by vrde** [comment]
We are making architectural changes that will make this issue invalid. Hold tight.
