### ISSUE TITLE
Reevaluate resources and scheduling of pods/services on k8s

### ISSUE THREAD

**Issue by muawiakh** [bigchaindb/bigchaindb#1673]
There is a need to re-evaluate the resources and scheduling for pods/services running on k8s. Recently, we faced an issue where MongoDB pod was crashing because of high memory consumption and turned out the resource limitations for the MongoDB pod were not sufficient and there wasn't any data to backup the resources being used currently.

A fix was made as per the MongoDB deployment guidelines for containers and node resources and that issue might not pop up any time soon, but to avoid a such a scenario with other services in the future, we should reconsider the resource allocation of all the services/pods deployed in the k8s cluster, so that we are able to scale easily, without pods crashing due to resource consumption.

We should also consider the introduction of scheduling constraints to ensure certain pods/services are pinned to specific nodes e.g. MongoDB and other stateful applications.

**Comment by ttmc** [comment]
For more context and discussion, see pull request #1663

**Comment by muawiakh** [comment]
Fixed in the new production setups. We will revisit if we run into any issues.

**Comment by muawiakh** [comment]
Closing issues.
