### ISSUE TITLE
naming convention: util.py or utils.py

### ISSUE THREAD

**Issue by sbellem** [bigchaindb/bigchaindb#168]
Without questioning why there are two util(s) modules, the naming could be consistent, that is, either the plural form is used, or the singular form. 

Or is there a reason for the different approaches?

Currently:

`bigchaindb/util.py`

and

`bigchaindb/db/utils.py`

**Comment by sohkai** [comment]
For posterity: I think we've settled on using `utils.py` throughout. There are still a few leftover instances of `util.py`, and those will be handled.
