### ISSUE TITLE
Add plugin support to tap into the blocks stream

### ISSUE THREAD

**Issue by vrde** [bigchaindb/bigchaindb#1701]
BigchainDB WebSocket Event API emits new valid transactions as soon as a block reached quorum.
While this lightweight approach is suitable for many applications, other use cases require integration with AMPQ services like RabbitMQ (see #1572).

To support those use cases (without bloating the codebase), we can add support to tap into the **blocks** stream using a plugin architecture. In this way custom use cases can easily be implemented with *few lines of code™*.

**Comment by krish7919** [comment]
Can we also use this plugin design to filter out valid block so that not all valid blocks get sent to all subscribers?

**Comment by TimDaub** [comment]
> Are there any plans/designs where we can use this plugin design to filter out valid block so that not all valid blocks get sent to all subscribers?

At this point, no. This ticket is solely to solve the RabbitMQ usecase specified in @1572. We're open to such functionality in the future, but it's currently not a concern.
