### ISSUE TITLE
Use a cloud-agnostic log aggregation and search system

### ISSUE THREAD

**Issue by ttmc** [bigchaindb/bigchaindb#1705]
Currently, our production deployment template uses Microsoft's Operations Management Suite (OMS) to capture all the logs (from a single BigchainDB node), search them, and to send alert emails. See https://docs.bigchaindb.com/projects/server/en/v1.0.1/production-deployment-template/log-analytics.html

We should switch to a system that would work well in any hosting situation. Maybe:

* Fluentd to aggregate logs from all sources and send them on to...
* Elasticsearch for storing and indexing all logs
* Kibana for doing analytics, making reports

**Comment by muawiakh** [comment]
I can definitely take a look into this.

**Comment by ttmc** [comment]
I wouldn't consider it a top priority right now, but we'll need it eventually since not everyone will be running in Azure.

**Comment by krish7919** [comment]
@muawiakh Maybe we can take up the backup/restore and the deployment scripting before this?
We are not moving out of Azure at least till the end of year.

**Comment by muawiakh** [comment]
Sure, I was just saying, I can take it as an action item in the future.

**Comment by ttmc** [comment]
@krish7919 We'll probably be using Azure for quite some time, but our users are a different matter. They may not be able to use Azure.

**Comment by ttmc** [comment]
I'm closing this issue. It's not pressing. We sometimes use OMS and others can use whatever they like. It's not our concern.
