### ISSUE TITLE
Supporting "Single Field" and "Geospatial" indexes

### ISSUE THREAD

**Issue by tomasramanauskas** [bigchaindb/bigchaindb#1710]
Hello,

as I understand at the moment BigchainDB only supports Text indexes.
Text indexes are already supported on assets and soon will be supported for transactions too -
https://github.com/bigchaindb/bigchaindb/issues/1592.

I'd like to propose to add support for other index types too. 
Personally, I'm quite interested in "Geospatial" index support and also "Single Field" indexes.

MongoDB index types:
https://docs.mongodb.com/manual/indexes/#index-types

Bellow are some examples.

**Asset data:**
```
bicycle = {
  "data": {
    "bicycle": {
      "serial_number": "abcd1236",
      "number_of_gears" : 22,
      "manufacturer": {
        "name": "bkfab",
        "location": {
          "type": "Point",
          "coordinates": [
            -73.856077,
            40.848447
          ]
        }
      }
    }
  }
}
```
**Geospatial index:**

```
db.assets.createIndex( { "data.bicycle.manufacturer.location": "2dsphere" } )
```

**Geospatial query:**
```
db.runCommand(
   {
     geoNear: "assets",
     near: { type: "Point", coordinates: [ -73.856077, 40.848447 ] },
     spherical: true,
     query: { },
     minDistance: 0,
     maxDistance: 5000
   }
)
```
**Single Field index:**
```
db.assets.createIndex( { "data.bicycle.number_of_gears" : 1 } )
```
**Single Field index based query:**
```
db.assets.find( { "data.bicycle.number_of_gears": { $gt: 20 } } )
```

**Comment by ttmc** [comment]
We can't add a new index for highly-specialized fields such as  `bicycle.number_of_gears` within assets (nor can we let users do that). What we _might_ do is create some indexes on asset fields that everyone could use, such as `key_a` and `key_b`. The _meanings_ (semantics) of those keys could vary from asset to asset.

**Comment by KrishnaPG** [comment]
Came across this while looking for indexing geospatial (geojson) data. Transactions on geojson / spatial data is valuable for real-estate transactions.

**Comment by ttmc** [comment]
Our current thinking is that a BigchainDB node operator (or their network/consortium) can provide more advanced query functionality, as needed. For details about how they could do that, see https://docs.bigchaindb.com/en/latest/query.html
