### ISSUE TITLE
Move nginx-3scale container to latest released openresty

### ISSUE THREAD

**Issue by muawiakh** [bigchaindb/bigchaindb#1726]
We are using a dns resolver in the `stream` block, which is supported in nginx but not in openresty.
Openresty usually lags behind by 1 version wrt nginx.

Ticket migrated from nginx_3scale repository, required for #1588.

**Comment by ttmc** [comment]
Original issue: https://github.com/bigchaindb/nginx_3scale/issues/3

**Comment by krish7919** [comment]
Just updated container to use openresty v1.11.2.5.
Still waiting for `v1.13`, or rather `v1.14` (Stable).

**Comment by muawiakh** [comment]
Closing this ticket. Fixed already.
