### ISSUE TITLE
Problem while configuring 3 node cluster on Mongodb

### ISSUE THREAD

**Issue by ManujSubhankar** [bigchaindb/bigchaindb#1734]
I have installed Standalone BigchainDB on MongoDB and its working. Now, I am trying to setup a 3 Node BigchainDB Cluster on MongoDB. But getting stuck on connecting the nodes together. 
I have changed the configuration .bigchaindb file adding the public key of the other nodes in the keyring variable  provided. I am running a mongoDB instance in one particular node and trying to connect through all the other bigchainDB instance nodes. The node where mongodb is running, there bigchiandb is starting. But while starting bdchaindb in other 2 hosts, I am getting following error:

> hduser@DMACS-09:~$ bigchaindb start
INFO:bigchaindb.config_utils:Configuration loaded from `/home/hduser/.bigchaindb`
[2017-08-28 15:50:51] [INFO] (bigchaindb.commands.bigchaindb) BigchainDB Version 1.0.1 (MainProcess - pid: 31465)
[2017-08-28 15:50:51] [INFO] (bigchaindb.backend.mongodb.connection) Closing initial connection to MongoDB (MainProcess - pid: 31465)
Traceback (most recent call last):
  File "/usr/local/bin/bigchaindb", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/bigchaindb/commands/bigchaindb.py", line 348, in main
    utils.start(create_parser(), sys.argv[1:], globals())
  File "/usr/local/lib/python3.5/dist-packages/bigchaindb/commands/utils.py", line 204, in start
    return func(args)
  File "/usr/local/lib/python3.5/dist-packages/bigchaindb/commands/utils.py", line 49, in configure
    command(args)
  File "/usr/local/lib/python3.5/dist-packages/bigchaindb/commands/utils.py", line 76, in start_logging
    command(args)
  File "/usr/local/lib/python3.5/dist-packages/bigchaindb/commands/bigchaindb.py", line 199, in run_start
    _run_init()
  File "/usr/local/lib/python3.5/dist-packages/bigchaindb/commands/bigchaindb.py", line 138, in _run_init
    schema.init_database(connection=b.connection)
  File "/usr/local/lib/python3.5/dist-packages/bigchaindb/backend/schema.py", line 99, in init_database
    create_database(connection, dbname)
  File "/usr/lib/python3.5/functools.py", line 743, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "/usr/local/lib/python3.5/dist-packages/bigchaindb/backend/mongodb/schema.py", line 19, in create_database
    if dbname in conn.conn.database_names():
  File "/usr/local/lib/python3.5/dist-packages/pymongo/mongo_client.py", line 1213, in database_names
    ("nameOnly", True)]))["databases"]]
  File "/usr/local/lib/python3.5/dist-packages/pymongo/database.py", line 513, in command
    with client._socket_for_reads(read_preference) as (sock_info, slave_ok):
  File "/usr/lib/python3.5/contextlib.py", line 59, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.5/dist-packages/pymongo/mongo_client.py", line 904, in _socket_for_reads
    with self._get_socket(read_preference) as sock_info:
  File "/usr/lib/python3.5/contextlib.py", line 59, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.5/dist-packages/pymongo/mongo_client.py", line 868, in _get_socket
    server = self._get_topology().select_server(selector)
  File "/usr/local/lib/python3.5/dist-packages/pymongo/topology.py", line 214, in select_server
    address))
  File "/usr/local/lib/python3.5/dist-packages/pymongo/topology.py", line 189, in select_servers
    self._error_message(selector))
pymongo.errors.ServerSelectionTimeoutError: Could not reach any servers in [('localhost', 27017)]. Replica set is configured with internal hostnames or IPs?
^CError in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib/python3.5/multiprocessing/popen_fork.py", line 29, in poll
    pid, sts = os.waitpid(self.pid, flag)

My First Node .bigchaindb config file looks like this. 

> {
    "wsserver": {
        "host": "localhost",
        "port": 9985,
        "scheme": "ws"
    },
    "database": {
        "host": "10.0.3.70",
        "replicaset": "bigchain-rs",
        "certfile": null,
        "ssl": false,
        "max_tries": 3,
        "crlfile": null,
        "keyfile_passphrase": null,
        "password": null,
        "ca_cert": null,
        "name": "bigchain",
        "port": 27017,
        "backend": "mongodb",
        "login": null,
        "connection_timeout": 5000,
        "keyfile": null
    },
    "server": {
        "workers": null,
        "bind": "0.0.0.0:9984",
        "loglevel": "info"
    },
    "backlog_reassign_delay": 120,
    "keypair": {
        "private": "tU7AzCMpYyRAUd8ewrkyf9kXRRr9Q6u8NkQh6yygNnk",
        "public": "CGAQuZs4eNbpHrr9g4QeDKjgXFybkcAYGfxBK3pQdKD7"
    },
    "log": {
        "file": "/home/digen/bigchaindb.log",
        "fmt_logfile": "[%(asctime)s] [%(levelname)s] (%(name)s) %(message)s (%(processName)-10s - pid: %(process)d)",
        "fmt_console": "[%(asctime)s] [%(levelname)s] (%(name)s) %(message)s (%(processName)-10s - pid: %(process)d)",
        "error_file": "/home/digen/bigchaindb-errors.log",
        "datefmt_console": "%Y-%m-%d %H:%M:%S",
        "granular_levels": {},
        "level_console": "info",
        "level_logfile": "info",
        "datefmt_logfile": "%Y-%m-%d %H:%M:%S"
    },
    "graphite": {
        "host": "localhost"
    },
    "keyring": ["5fSV8h3ZBy2bMTd43QSwyD3QhQGfU3iP9uQdzQ8exbks","FgvwKjGwftRzqVJWbXT5Z4pkFe4wqmvswupMEHGoGvtt"]
}

10.0.3.70 is the host where mongo db is running. The other 2 node config file is same except the keyring changes

**Comment by krish7919** [comment]
Hi @ManujSubhankar 

1. BigchainDB connects to MongoDB at `10.x.y.z` as specified in the config file.
2. It connects to MongoDB and then tries to connect to the MongoDB replica set primary, which is `localhost`. And you get the error: `pymongo.errors.ServerSelectionTimeoutError: Could not reach any servers in [('localhost', 27017)]. Replica set is configured with internal hostnames or IPs?`
3. How did you initialize the replica set? Can you paste the full `rs.initiate` command here?

You can also refer to our docs for deployment [here](https://docs.bigchaindb.com/projects/server/en/latest/production-deployment-template/index.html) to get a rough idea of how this might work.

**Comment by ManujSubhankar** [comment]
I initialized the replica set with the following command : 
sudo mongod --replSet=bigchain-rs 
in the terminal

**Comment by ManujSubhankar** [comment]
Thanks @krish7919 
BigchainDB got started after changing the rs.config. But while submitting a transaction its giving some kinda authentication error.
Following is the error : 

> Traceback (most recent call last):
>   File "Asset.py", line 37, in <module>
>     sent_creation_tx = bdb.transactions.send(fulfilled_creation_tx)
>   File "/usr/local/lib/python3.5/dist-packages/bigchaindb_driver/driver.py", line 319, in send
>     method='POST', path=self.path, json=transaction, headers=headers)
>   File "/usr/local/lib/python3.5/dist-packages/bigchaindb_driver/transport.py", line 58, in forward_request
>     headers=headers,
>   File "/usr/local/lib/python3.5/dist-packages/bigchaindb_driver/connection.py", line 57, in request
>     raise exc_cls(response.status_code, text, json)
> bigchaindb_driver.exceptions.TransportError: (407, '<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">\n<HTML><HEAD><META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=iso-8859-1">\n<TITLE>ERROR: Cache Access Denied</TITLE>\n<STYLE type="text/css"></STYLE>\n</HEAD>\n<BODY>\n<H1>ERROR</H1>\n<H2>Cache Access Denied</H2>\n<HR noshade size="1px">\n<P>\nWhile trying to retrieve the URL:\n<A HREF="http://10.0.3.70:9984/api/v1/transactions/">http://10.0.3.70:9984/api/v1/transactions/</A>\n<P>\nThe following error was encountered:\n<UL>\n<LI>\n<STRONG>\nCache Access Denied.\n</STRONG>\n</UL>\n</P>\n\n<P>Sorry, you are not currently allowed to request:\n<PRE>    http://10.0.3.70:9984/api/v1/transactions/</PRE>\nfrom this cache until you have authenticated yourself.\n</P>\n\n<P>\nYou need to use Netscape version 2.0 or greater, or Microsoft Internet\nExplorer 3.0, or an HTTP/1.1 compliant browser for this to work.  Please\ncontact the <A HREF="mailto:root">cache administrator</a> if you have\ndifficulties authenticating yourself or \n<A HREF="http://centos55dot90/cgi-bin/chpasswd.cgi">change</a> your default password.\n</P>\n\n<BR clear="all">\n<HR noshade size="1px">\n<ADDRESS>\nGenerated Tue, 29 Aug 2017 10:25:28 GMT by centos55dot90 (squid/2.6.STABLE21)\n</ADDRESS>\n</BODY></HTML>\n', None)

**Comment by krish7919** [comment]
@ManujSubhankar I do not think this is related to BigchainDB. Are you running the instances behind a firewall or NAT?

**Comment by dominic-healid** [comment]
@ManujSubhankar what changes did you do on rs.config? I'm having similar issue.

**Comment by ttmc** [comment]
This issue was reported using BigchainDB Server version 1.0.1. BigchainDB went through many versions since then, including 1.1, 1.2, and now the 2.x series. Setting up a cluster with the 2.x series is very different than with the 1.x series, because now the inter-node communications is using Tendermint P2P protocols, rather than MongoDB wire protocols. This issue is basically defunct.
