### ISSUE TITLE
Can bigchaindb's cluster be deployed across idc?

### ISSUE THREAD

**Issue by richmonkey** [bigchaindb/bigchaindb#1746]
I think mongodb is't proper across idc in a replica set, 
so bigchaindb cluster need be deployed in a idc?
Am i wrong?

**Comment by krish7919** [comment]
@richmonkey I didn't understand your question. Can you please explain what do you mean? What's an `idc`?

**Comment by richmonkey** [comment]
sorry for my english.
idc is "Internet Data Center".

**Comment by ttmc** [comment]
MongoDB can be deployed spanning many different data centers scattered all over planet Earth.

https://docs.mongodb.com/manual/core/replica-set-architecture-geographically-distributed/
