### ISSUE TITLE
Set up "auto-scaling" so k8s will get a new agent node if one or more crashes

### ISSUE THREAD

**Issue by ttmc** [bigchaindb/bigchaindb#1753]
In our Kubernetes-based production deployment, what if one or more agent/worker nodes (VMs) crashes?

Ideally, new agent nodes will be created right away, somehow. How can this be done? It will depend on where the VMs are (AWS, Azure, etc.) and probably on the tools we're using to manage the k8s cluster (ACS, Tectonic, or whatever).

We probably don't want to have a bunch of extra VMs sitting around, unused, racking up expenses, but that _would_ increase the overall resilience. Right now we only have two agent nodes, and we'd like to reserve one for MongoDB. That seems a bit risque, because it takes time to spin up a new VM. How long? If it's very fast, then maybe that time isn't an issue.

References: 

https://github.com/kubernetes/autoscaler/tree/master/cluster-autoscaler

https://docs.microsoft.com/en-us/azure/container-service/kubernetes/container-service-scale

At the time of writing this issue, with ACS, "... autoscaling of agent nodes in a container service cluster is not supported."

Maybe Tectonic can do it?

**Comment by krish7919** [comment]
Just saw that both Tectonic and k8s on ACS use Azure Availability Sets to solve this problem.
Tectonic reference:
https://coreos.com/tectonic/docs/latest/install/azure/azure-terraform.html#under-the-hood

@ttmc I think we can close this now?

**Comment by ttmc** [comment]
Yes, it seems that the created Azure Availability Sets do resolve this.

https://docs.microsoft.com/en-us/azure/virtual-machines/windows/manage-availability
