### ISSUE TITLE
Problem getting event stream from WebSocket API with a .NET client

### ISSUE THREAD

**Issue by ttmc** [bigchaindb/bigchaindb#1764]
On Twitter, [@SrinivasanSunda](https://twitter.com/SrinivasanSunda) [wrote](https://twitter.com/SrinivasanSunda/status/912961350606848001):

![screenshot from 2017-09-27 11-14-33](https://user-images.githubusercontent.com/1210951/30905441-1a10c356-a375-11e7-9cff-668659a98ba7.png)

He gave more information in [a comment on a blog post](https://medium.com/@SrinivasanSunda/it-looks-the-event-stream-is-not-getting-the-posted-transactions-back-to-the-client-67271547146a) (on Medium):

![screenshot from 2017-09-27 11-18-23](https://user-images.githubusercontent.com/1210951/30905605-9a8a4a98-a375-11e7-95c9-4912e3c24d69.png)

**Comment by azuresrini** [comment]
The client  code is attached.  the connection is successful , but no  transactions received to client.

using System.Linq;
using System.Text;
using System.Threading.Tasks;
using WebSocketSharp;

namespace bigcwsoc
{
    class Program
    {
        static void Main(string[] args)
        {


         using (var ws = new WebSocket("ws://******.westus.cloudapp.azure.com:9985/api/v1/streams/valid_transactions"))
            {
                Console.WriteLine("On Message  Inside I");
                ws.OnMessage += (sender, e) =>
                {
                    Console.WriteLine("On Message  Inside II");
                    Console.WriteLine("Laputa says: " + e.Data);
                };
                  

                ws.Connect();
                ws.Send("BALUS");
                Console.ReadKey(true);
            }



            Console.WriteLine("End");
            Console.ReadLine();

        }
    }
}

**Comment by ttmc** [comment]
I'm not familiar enough with C# to see any obvious issues with that code. One thing I really don't understand is the line that says

```csharp
ws.Send("BALUS");
```

Does that try to send data over the WebSocket connection? The events API isn't meant to be used for two-way communications, at least not today. It's just for getting notified of all recently-validated transactions.

Maybe test the events API using some other tool, such as a command-line WebSocket tool, and if that works then you'll know the issue is with the C# code.

**Comment by azuresrini** [comment]
That  is  just a  standard  code  and  ideally  Send  will be ignored. Will comment  that  also  and  will try. Also  will  try  the  command  line  tool, as you  suggested.

**Comment by azuresrini** [comment]
Hello ttmc,  still  I am  not  seeing a valid transaction  . Here are the steps.

1. Run the WSCAT tool

wscat -c ws://localhost:9985/api/v1/streams/valid_transactions
connected (press CTRL+C to quit)
>

2. Here is the config  Info.
{
  "assets": "/assets/",
  "docs": "https://docs.bigchaindb.com/projects/server/en/v1.0.1/http-client-server-api.html",
  "outputs": "/outputs/",
  "statuses": "/statuses/",
  "streams": "ws://localhost:9985/api/v1/streams/valid_transactions",
  "transactions": "/transactions/"
}

3. Now I create a  transaction  in another  terminal...

4. However  No  Transaction  is  displayed on the WSCAT  window which is listening.

Am I  missing  some thing here.  Here is what  the  Log  shows...

[2017-09-27 14:13:34] [INFO] (aiohttp.access) 127.0.0.1 - - [27/Sep/2017:14:13:34 +0000] "GET /api/v1/streams/valid_transactions HTTP/1.1" 101 0 "-" "-" (ws         - pid: 2618)

**Comment by ttmc** [comment]
Hi @azuresrini, here are some more ideas and questions.

I wonder if a firewall (or network security group) is blocking traffic on port 9985. I see you're using Azure.

Does your BigchainDB node's _HTTP API_ work as expected? For example, what happens when you visit the BigchainDB Root URL in your web browser? (See https://docs.bigchaindb.com/projects/server/en/latest/http-client-server-api.html )

How did you create, sign and send (post) a transaction to your BigchainDB node? Did you use one of the BigchainDB drivers?

What happens if you use the HTTP API to retrieve the transaction that you sent to your BigchainDB node?

You can check your BigchainDB node's config settings using the command-line command:

```bash
bigchaindb show-config
```

before running `bigchaindb start`. If you're still stuck, maybe share those settings here. Remember to obfuscate the sensitive bits.

**Comment by r-marques** [comment]
@azuresrini the only reason I can think of at this point is that the transaction being posted is invalid.

Running version 1.0.1 in localhost this is what I get:

```bash
$ wscat -c ws://localhost:9985/api/v1/streams/valid_transactions
connected (press CTRL+C to quit)
< {"block_id": "912495d01bd3ccbb8946a23e3a5eb08ef2693a68491807b15b67e52d892e02af", "asset_id": "0a792da98fdebef229dca6bd9a4c1ce7523fca9e9e189e66a85922d36032b94b", "transaction_id": "0a792da98fdebef229dca6bd9a4c1ce7523fca9e9e189e66a85922d36032b94b"}
```
when posting this transaction
```bash
$ curl -d '{"inputs": [{"owners_before": ["6r4ENSrHtCUbjJa8nuns9Ge15mojj7o2fJCBDo26GcAV"], "fulfills": null, "fulfillment": "pGSAIFbbjAoZq-UMDFBNxMBgvcwG4CGJgxSwW5gUBO88Q5bagUBSIAGYqIctqAO68CmwsOscpLjKu6S7bPp98EBGOSkWNMX6-BBeG9cJ1Ew8IUjF9hsq1BmIT31HjmDKtSuxF-0P"}], "outputs": [{"public_keys": ["6r4ENSrHtCUbjJa8nuns9Ge15mojj7o2fJCBDo26GcAV"], "condition": {"details": {"type": "ed25519-sha-256", "public_key": "6r4ENSrHtCUbjJa8nuns9Ge15mojj7o2fJCBDo26GcAV"}, "uri": "ni:///sha-256;0B4UFpsSQwmCNF5hR8DrPzQQfjy7C_40XROoS4u0WQE?fpt=ed25519-sha-256&cost=131072"}, "amount": "1"}], "operation": "CREATE", "metadata": null, "asset": {"data": {"msg": "hello"}}, "version": "1.0", "id": "0a792da98fdebef229dca6bd9a4c1ce7523fca9e9e189e66a85922d36032b94b"}' -H "Content-Type: application/json" -X POST http://localhost:9984/api/v1/transactions
```

If you post a valid transaction you should also see something like this on the bigchaindb logs (located by default at `$HOME/bigchaindb.log`)
```bash
[2017-10-02 14:14:21] [INFO] (bigchaindb.pipelines.vote) Voting 'valid' for block 912495d01bd3ccbb8946a23e3a5eb08ef2693a68491807b15b67e52d892e02af (Process-18 - pid: 16817)
```
```

**Comment by azuresrini** [comment]
All,  It  worked  fine  now. Thanks for  all your  support.  .net  client  also  worked  fine.
