### ISSUE TITLE
Discuss user accounts, roles, capabilities, and permissions

### ISSUE THREAD

**Issue by ttmc** [bigchaindb/bigchaindb#177]
The [BigchainDB whitepaper](https://www.bigchaindb.com/whitepaper/) has a section on user accounts, roles, capabilities, and permissions. We need to review that. For example, does it make sense to have a global sysadmin role? That seems like too much power to give one person in a system that's supposed to be decentralized.

RethinkDB now supports basic user accounts ([since version 2.3](https://rethinkdb.com/blog/2.3-release/)). Can we use those? Should we?

I don't think we should tackle this top-down. We need to think through some specific examples, always being mindful that we're trying to create a _decentralized_ system. For example, how _exactly_ does a new node get added to the federation? What are the steps?

Related: PR #167

**Comment by saschad** [comment]
i think that the BigchainDB accounts, roles, capabilities, and permissions should also “get out of the way” of the underlying database. In my case i needed a protection of my RethinkDB and the BigchainDB couldn't connect after i set up a password for the default admin user. Maybe i was a little fast, not looking for other opportunities. 

BigchainDB should use the new features (user account and SSL) to gain secutity on server level and to set up the connection. Protection as described in the whitepaper needs to be handeled by the BigchainDB.

**Comment by ttmc** [comment]
@saschad That's a good point: we could use RethinkDB's new user accounts to help secure _RethinkDB_.

**Comment by ttmc** [comment]
This issue's description touches on things we now consider to be separate issues, e.g. permissions, securing RethinkDB, removing global sysadmin powers, figuring out how to add a new node to a cluster --- all of which have their own open issues now (or at least are in the roadmap). I'm closing this issue.
