### ISSUE TITLE
Use a phrase other than "pluggable consensus" for that feature

### ISSUE THREAD

**Issue by ttmc** [bigchaindb/bigchaindb#1779]
## Background

BigchainDB Server has a nice, albeit somewhat hidden, feature that allows one to change the rules for validating transactions and blocks via a plugin. It used to be documented in the docs, e.g. [in the docs for v0.6.0](https://docs.bigchaindb.com/projects/server/en/v0.6.0/appendices/consensus.html).

## The Problem

The above-described feature was added by an external developer, so we didn't want to be too critical. Unfortunately, they called it "pluggable consensus" and that is a badly misleading name. One can _not_ use it to change the consensus protocol used by BigchainDB Server (e.g. to Raft, Paxos, PBFT, or Uncle Joes' Awesome BFT Protocol). As explained above, one can change the rules to check if a transaction or block is valid.

Other blockchain solutions out there (such as Hyperledger Fabric) _do_ have pluggable consensus. We don't want to confuse people into thinking that BigchainDB Server has the same feature. Moreover, we might want to offer _actual_ pluggable consensus in the future. What would we call _that_?

## Proposal

Use a phrase other than "consensus" to describe this functionality, in the code, the docstrings, and the docs (if any).

How about "pluggable validation"?

The relevant code is the code mentioning the `BaseConsensusRules` class, e.g.

https://github.com/bigchaindb/bigchaindb/blob/master/bigchaindb/consensus.py

**Comment by ttmc** [comment]
I mentioned this issue in today's sprint planning meeting. Some notes:

* Some users are using the "pluggable consensus" feature but a name change would be fairly trivial for them to handle.
* Maybe we should wait a couple weeks, until we have a better picture of roadmap details, before we do this.
* Can we use Python's [deprecation library](https://pypi.python.org/pypi/deprecation) to help us manage the change?

**Comment by sbellem** [comment]
I think we can address this is issue now using a deprecation warning.

That means we support both names (old and new) for the time being until the version by the deprecation warning.

Of relevant interest, in [Blockchain Consensus Protocols in the Wild](https://arxiv.org/abs/1707.01873) by [Christian Cachin](https://arxiv.org/find/cs/1/au:+Cachin_C/0/1/0/all/0/1), [Marko Vukolić](https://arxiv.org/find/cs/1/au:+Vukolic_M/0/1/0/all/0/1):

> ### 3.4  Validation
> In an atomic broadcast protocol resilient to crashes, every message is usually considered to be an acceptable request to the service. For Byzantine consensus, especially in blockchain applications, it makes sense to ask that only “valid” transactions are output by the broadcast protocol. To formalize this, the protocol is parameterized with a deterministic, external predicate `V()`, such that the protocol delivers only messages satisfying `V()`. This notion has been introduced as external validity by Cachin et al. [[19]](http://www.shoup.net/papers/ckps.pdf).
>
> The predicate must be deterministically computable locally by every process. More precisely, `V()` must guarantee that when two correct nodes `p` and `q` in an atomic broadcast protocol have both delivered the same sequence of messages up to some point, then `p` obtains `V(m) = TRUE` for any message `m` if and only if `q` also determines that `V(m) = TRUE`.
>
> This combination of transaction validation and establishing consensus is inherent in permissionless blockchains based on proof-of-work consensus, such as Bitcoin and Ethereum. For permissioned-blockchain protocols, one could in principle also separate this step from consensus and perform the (deterministic) validation of transactions on the ordered “raw” sequence output by atomic broadcast. This could make the protocol susceptible to denial-of-service attacks from clients broadcasting excessively many invalid transactions. Hence most consensus protocols reviewed in this text combine ordering with validation and use a form of external validity based on the current blockchain state.

**Comment by ttmc** [comment]
I looked at the deprecation library more closely and it seems to be for functions and methods only, not classes (such as the `BaseConsensusRules` class). The docs are here:

https://deprecation.readthedocs.io/en/latest/

**Comment by sbellem** [comment]
We can put the warning in the `__init__()`.

It's probably best to look at the docs here: https://docs.python.org/3.6/library/exceptions.html#DeprecationWarning

**Comment by sbellem** [comment]
Since the class relies on static method we'll have to put the warnings in each method, e.g.:

```python
class BaseConsensusRules():

    @staticmethod
    def validate_transaction(bigchain, transaction):
        warnings.warn(
            'Class A is deprecated. Use B instead.', DeprecationWarning, stacklevel=2)
        return transaction.validate(bigchain)
```

**Comment by sbellem** [comment]
Another, perhaps better, approach: https://stackoverflow.com/questions/9008444/how-to-warn-about-class-name-deprecation#9008509

**Comment by ttmc** [comment]
There's also a file that would have to be renamed: `consensus.py`

https://github.com/bigchaindb/bigchaindb/blob/master/bigchaindb/consensus.py
