### ISSUE TITLE
Fix the advertised URL of the WebSocket API on current IPDB Test Network

### ISSUE THREAD

**Issue by ttmc** [bigchaindb/bigchaindb#1783]
When I go to the BigchainDB Root URL of the IPDB Test Network today, at https://test.ipdb.io, I get back:
```json
{
  "api": {
    "v1": {
      "assets": "/api/v1/assets/", 
      "docs": "https://docs.bigchaindb.com/projects/server/en/v1.0.1/http-client-server-api.html", 
      "outputs": "/api/v1/outputs/", 
      "statuses": "/api/v1/statuses/", 
      "streams": "ws://0.0.0.0:9985/api/v1/streams/valid_transactions", 
      "transactions": "/api/v1/transactions/"
    }
  }, 
  "docs": "https://docs.bigchaindb.com/projects/server/en/v1.0.1/", 
  "keyring": [], 
  "public_key": "9CTfU7xezLtjE33CeuKSBZttfQcueuSEzjAhhccrL9my", 
  "software": "BigchainDB", 
  "version": "1.0.1"
}
```

The value for `"streams"` is incorrect. It should be `"wss://test.ipdb.io:443/api/v1/streams/valid_transactions"`

BigchainDB has three configuration settings to control what gets displayed ("advertised") in the `"streams"` value: wsserver.advertised_scheme, wsserver.advertised_host and wsserver.advertised_port

See https://docs.bigchaindb.com/projects/server/en/latest/server-reference/configuration.html#wsserver-advertised-scheme-wsserver-advertised-host-and-wsserver-advertised-port

It seems we need to update the values of those settings on the current IPDB Test Network.

Should we also update the documentation (on our production deployment template) so we remember to set those settings in the future?

**Comment by muawiakh** [comment]
This has already been fixed in the latest codebase. For reference I running on `unfake.io` and I get the following response:
```
{
  "api": {
    "v1": {
      "assets": "/api/v1/assets/", 
      "docs": "https://docs.bigchaindb.com/projects/server/en/v1.1.0/http-client-server-api.html", 
      "outputs": "/api/v1/outputs/", 
      "statuses": "/api/v1/statuses/", 
      "streams": "wss://unfake.io:443/api/v1/streams/valid_transactions", 
      "transactions": "/api/v1/transactions/"
    }
  }, 
  "docs": "https://docs.bigchaindb.com/projects/server/en/v1.1.0/", 
  "keyring": [], 
  "public_key": "EWovQDsR811c9smcfUQygLQAyW2iE2zMdPMUSx1PxVCP", 
  "software": "BigchainDB", 
  "version": "1.1.0"
}
```

**Comment by muawiakh** [comment]
Done.
