### ISSUE TITLE
Running multiple instances of bigchaindb

### ISSUE THREAD

**Issue by domi41** [bigchaindb/bigchaindb#1784]
* BigchainDB version: `1.2.0.dev0`
* Operating System: `Old Kubuntu`
* Deployment Type: `Host` (not Docker)
* BigchainDB driver: `python`

### Description

We tried running **two** instances of bigchaindb, each with its own ports and mongod instance, and the logger complains about its socket already being used.

```
Traceback (most recent call last):
  File "/usr/local/bin/bigchaindb", line 9, in <module>
    load_entry_point('BigchainDB==1.2.0.dev0', 'console_scripts', 'bigchaindb')()
  File "/home/code/fork/bigchaindb/bigchaindb/commands/bigchaindb.py", line 348, in main
    utils.start(create_parser(), sys.argv[1:], globals())
  File "/home/code/fork/bigchaindb/bigchaindb/commands/utils.py", line 204, in start
    return func(args)
  File "/home/code/fork/bigchaindb/bigchaindb/commands/utils.py", line 49, in configure
    command(args)
  File "/home/code/fork/bigchaindb/bigchaindb/commands/utils.py", line 75, in start_logging
    setup_logging(user_log_config=config.get('log'))
  File "/home/code/fork/bigchaindb/bigchaindb/log/setup.py", line 50, in setup_logging
    setup_sub_logger(user_log_config=user_log_config)
  File "/home/code/fork/bigchaindb/bigchaindb/log/setup.py", line 39, in setup_sub_logger
    server = LogRecordSocketServer()
  File "/home/code/fork/bigchaindb/bigchaindb/log/setup.py", line 157, in __init__
    super().__init__((host, port), handler)
  File "/usr/lib/python3.5/socketserver.py", line 440, in __init__
    self.server_bind()
  File "/usr/lib/python3.5/socketserver.py", line 454, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use
```

A way to configure it would be brilliant ! We cannot run Docker.
Looking at the source around `setup_logging(user_log_config=config.get('log'))`, it does not look too complicated to add more options to the config and use them with `LogRecordSocketServer`.
We can probably do it if you agree to the changes.

**Comment by ttmc** [comment]
While it's possible to run a single instance of bigchaindb (and a single instance of MongoDB); it's not possible to run two instances because a MongoDB replica set needs at least three MongoDB instances (and there's a bigchaindb instance associated with each one). Actually, it's more nuanced than that; see issue #1696 

@muawiakh is currently working on some scripts to deploy multiple BigchainDB nodes easily (for testing purposes). That should be available soon.

**Comment by domi41** [comment]
> a MongoDB replica set needs at least three MongoDB instances

Thanks for the tip ! But if we want three bigchaindb instances running on the same box without using Docker, won't we need to make sure they each use a different socket port for logging ?

> @muawiakh is currently working on some scripts to deploy multiple BigchainDB nodes easily (for testing purposes). That should be available soon.

We're kind of doing that too on our end ; TDD is demanding ! :) Can't wait to see what you're coming up with.

**Comment by muawiakh** [comment]
We are currently working on multiple nodes running MongoDB and BigchainDB pair on each node as well as with Dockers. I can try to think about your use case and see if we can come up with something.

**Comment by kansi** [comment]
@domi41 I think this should help you? #1660

**Comment by ttmc** [comment]
As mentioned in other issues, the way that one runs multiple nodes has changed significantly with the BigchainDB 2.x series. These old issues with running multiple nodes of BigchainDB 1.x are defunct.
