### ISSUE TITLE
How to transfer an asset from bob to another person

### ISSUE THREAD

**Issue by raaghavvd** [bigchaindb/bigchaindb#1786]
* BigchainDB version: latest
* Operating System: Mac OSX
* Deployment Type: `[Docker|Host|IPDB|Other]` - Host
 
  
* BigchainDB driver: `[yes|no]` YES
  * If using a driver please specify, driver type `[python|js|java]`
  and version. - Python Driver

### Description
I am unable to figure out how to transfer an asset from bob (As mentioned in the docs) to another person.

Here's the code I've used -> this currently throws an Type Error -> bigchaindb_driver.exceptions.MissingPrivateKeyError: A private key is missing!
in the line - private_keys= bob.private_key,

```python
from bigchaindb_driver import BigchainDB  # This imports the BigchainDB which has been running on the system
from bigchaindb_driver.crypto import generate_keypair #This imports the generate_keypair module which is required for creating private and public kets

bdb_root_url='http://localhost:9984'
bdb=BigchainDB(bdb_root_url) #This denotes the fact that we are not using authentication tokens
alice = generate_keypair()
bob= generate_keypair()
matt = generate_keypair()

                            #Generates public and private key for Alice and Bob
'''
Here the asset being transferred is a bicycle which belongs to Alice
The variable below contains a data property which contains the information about the bicycle
'''

bicycle= {
    'data':{
        'bicycle':{
            'serial_number' : 'XX2334C',
            'manufacturer':'bkfab',
        },

    },
}
metadata={'Country':'France'}  #Any dictionary can be used as Metadata
prepared_creation_tx= bdb.transactions.prepare(operation='CREATE',signers=alice.public_key,asset=bicycle,metadata=metadata) #This creates a digital asset
fulfilled_creation_tx=bdb.transactions.fulfill(prepared_creation_tx,private_keys=alice.private_key) #the transaction gets authenticated using Alice's private key
sent_creation_tx=bdb.transactions.send(fulfilled_creation_tx) #the authorized transaction is now sent over to the BigchainDB
print(sent_creation_tx==fulfilled_creation_tx)
txid= fulfilled_creation_tx['id'] #contains the transaction id
print('transactions id is  ')
print(txid)
'''
The code below keeps checking the transaction until it become valid
As it takes a some time before the transaction is deemed as valid by the BigchainDB Cluster



'''


trials = 0

while trials < 100:
    try:
         if bdb.transactions.status(txid).get('status') == 'valid':
             break
    except bigchaindb_driver.exceptions.NotFoundError:
        trials += 1
print(bdb.transactions.status(txid))



creation_tx= fulfilled_creation_tx #Alice retrieves the transaction
print("Alice retrieves")
print(creation_tx)

'''
Preparing a transaction
To get inforamtion about the id of the asset we are transferrring
'''
asset_id= creation_tx['id']
transfer_asset={
        'id' :asset_id,
}

'''
Transfer transaction
'''
output_index=0
output= creation_tx['outputs'][output_index]
transfer_input={
    'fulfillment': output['condition']['details'],
    'fulfills':{
        'output_index':output_index,
        'transaction_id':creation_tx['id'],
        },
        'owners_before': output['public_keys'],
}

print("public_keys 1")
print(output['public_keys'])
prepared_transfer_tx = bdb.transactions.prepare(
    operation='TRANSFER',
    asset=transfer_asset,
    inputs=transfer_input,
    recipients=bob.public_key,
)
#Fulfillment of transfer
fulfilled_transfer_tx= bdb.transactions.fulfill(
prepared_transfer_tx,
private_keys= alice.private_key,
)
#Send it across the Node
sent_transfer_tx=bdb.transactions.send(fulfilled_transfer_tx)
print(sent_transfer_tx==fulfilled_transfer_tx)
print("Fulfilled transfer looks like")
print(fulfilled_transfer_tx)




print("Is the bob the owner?",sent_transfer_tx['outputs'][0]['public_keys'][0]==bob.public_key)
print("Was Alice the previous owner? ",fulfilled_transfer_tx['inputs'][0]['owners_before'][0]==alice.public_key)


transfer_tx=fulfilled_transfer_tx
asset_id = transfer_tx['asset']['id']
transfer_asset={
        'id' :asset_id,
}
print ("Helllooo")
print (transfer_tx['asset']['id'])



output= creation_tx['outputs'][output_index]
transfer_input={
    'fulfillment': output['condition']['details'],
    'fulfills':{
        'output_index':output_index,
        'transaction_id':transfer_tx['asset']['id'],
        },
        'owners_before': output['public_keys'],
        'owners_after': output['private_keys'],
}

print("public_keys 1")
print(output['public_keys'])
prepared_transfer_tx = bdb.transactions.prepare(
    operation='TRANSFER',
    asset=transfer_asset,
    inputs=transfer_input,
    recipients=matt.public_key,
)
#Fulfillment of transfer
fulfilled_transfer_tx= bdb.transactions.fulfill(
prepared_transfer_tx,
private_keys= bob.private_key,
)
#Send it across the Node
sent_transfer_tx=bdb.transactions.send(fulfilled_transfer_tx)
print(sent_transfer_tx==fulfilled_transfer_tx)
print("Fulfilled transfer looks like")
print(fulfilled_transfer_tx)




print("Is matt the owner?",sent_transfer_tx['outputs'][0]['public_keys'][0]==bob.public_key)
print("Was Alice the previous owner? ",fulfilled_transfer_tx['inputs'][0]['owners_before'][0]==alice.public_key)
print("Was Bob the previous owner? ",fulfilled_transfer_tx['inputs'][0]['owners_before'][1]==alice.public_key)
```

**Comment by raaghavvd** [comment]
[EDIT] new error 

'message': 'Invalid transaction (InvalidSignature): Transaction signature is invalid.', 'status': 400})



from bigchaindb_driver import BigchainDB  # This imports the BigchainDB which has been running on the system
from bigchaindb_driver.crypto import generate_keypair #This imports the generate_keypair module which is required for creating private and public kets
import time

bdb_root_url='http://localhost:9984'
bdb=BigchainDB(bdb_root_url) #This denotes the fact that we are not using authentication tokens
alice = generate_keypair()
bob= generate_keypair()
matt = generate_keypair()

                            #Generates public and private key for Alice and Bob
'''
Here the asset being transferred is a bicycle which belongs to Alice
The variable below contains a data property which contains the information about the bicycle
'''

bicycle= {
    'data':{
        'bicycle':{
            'serial_number' : 'XX2334C',
            'manufacturer':'bkfab',
        },

    },
}
metadata={'Country':'France'}  #Any dictionary can be used as Metadata
prepared_creation_tx= bdb.transactions.prepare(operation='CREATE',signers=alice.public_key,asset=bicycle,metadata=metadata) #This creates a digital asset
fulfilled_creation_tx=bdb.transactions.fulfill(prepared_creation_tx,private_keys=alice.private_key) #the transaction gets authenticated using Alice's private key
sent_creation_tx=bdb.transactions.send(fulfilled_creation_tx) #the authorized transaction is now sent over to the BigchainDB
print(sent_creation_tx==fulfilled_creation_tx)
txid= fulfilled_creation_tx['id'] #contains the transaction id
print('transactions id is  ')
print(txid)
'''
The code below keeps checking the transaction until it become valid
As it takes a some time before the transaction is deemed as valid by the BigchainDB Cluster



'''


trials = 0

while trials < 100:
    try:
         if bdb.transactions.status(txid).get('status') == 'valid':
             break
    except bigchaindb_driver.exceptions.NotFoundError:
        trials += 1
print(bdb.transactions.status(txid))



creation_tx= fulfilled_creation_tx #Alice retrieves the transaction
print("Alice retrieves")
print(creation_tx)

'''
Preparing a transaction
To get inforamtion about the id of the asset we are transferrring
'''
asset_id= creation_tx['id']
transfer_asset={
        'id' :asset_id,
}

'''
Transfer transaction
'''
output_index=0
output= creation_tx['outputs'][output_index]
transfer_input={
    'fulfillment': output['condition']['details'],
    'fulfills':{
        'output_index':output_index,
        'transaction_id':creation_tx['id'],
        },
        'owners_before': output['public_keys'],
}

print("public_keys 1")
print(output['public_keys'])
prepared_transfer_tx = bdb.transactions.prepare(
    operation='TRANSFER',
    asset=transfer_asset,
    inputs=transfer_input,
    recipients=bob.public_key,
)
#Fulfillment of transfer
fulfilled_transfer_tx= bdb.transactions.fulfill(
prepared_transfer_tx,
private_keys= alice.private_key,
)
#Send it across the Node
sent_transfer_tx=bdb.transactions.send(fulfilled_transfer_tx)
print(sent_transfer_tx==fulfilled_transfer_tx)
print("Fulfilled transfer looks like")
print(fulfilled_transfer_tx)




print("Is the bob the owner?",sent_transfer_tx['outputs'][0]['public_keys'][0]==bob.public_key)
print("Was Alice the previous owner? ",fulfilled_transfer_tx['inputs'][0]['owners_before'][0]==alice.public_key)


txid1=fulfilled_transfer_tx['asset']['id']
trials = 0

while trials < 100:
    try:
         if bdb.transactions.status(txid1).get('status') == 'valid':
             break
    except bigchaindb_driver.exceptions.NotFoundError:
        trials += 1
print(bdb.transactions.status(txid))


transfer_tx=fulfilled_transfer_tx
print(transfer_tx)
asset_id = transfer_tx['asset']['id']
print ("Asset Id for BOB")
print(asset_id)

transfer_asset={
        'id' :asset_id,
}
print(transfer_asset)


output= transfer_tx['outputs'][output_index]
transfer_input={
    'fulfillment': output['condition']['details'],
    'fulfills':{
        'output_index':output_index,
        'transaction_id':transfer_tx['asset']['id'],
        },
        'owners_before': output['public_keys'],
}

prepared_transfer_tx = bdb.transactions.prepare(
    operation='TRANSFER',
    asset=transfer_asset,
    inputs=transfer_input,
    recipients=matt.public_key,
)
#Fulfillment of transfer
fulfilled_transfer_tx= bdb.transactions.fulfill(
prepared_transfer_tx,
private_keys= bob.private_key,
)
#Send it across the Node




sent_transfer_tx=bdb.transactions.send(fulfilled_transfer_tx)

print(sent_transfer_tx==fulfilled_transfer_tx)
print("Fulfilled transfer looks like")
print(fulfilled_transfer_tx)




print("Is matt the owner?",sent_transfer_tx['outputs'][0]['public_keys'][0]==bob.public_key)
print("Was Alice the previous owner? ",fulfilled_transfer_tx['inputs'][0]['owners_before'][0]==alice.public_key)
print("Was Bob the previous owner? ",fulfilled_transfer_tx['inputs'][0]['owners_before'][1]==bob.public_key)

**Comment by diminator** [comment]
Hi,

It seems you were trying to transfer the wrong transaction in the second step
Here is a working version of your code - with a bit of cleanup

Notice that now there is a `_again` suffix for the last step

```
from bigchaindb_driver import BigchainDB  # This imports the BigchainDB which has been running on the system
from bigchaindb_driver.crypto import \
    generate_keypair  # This imports the generate_keypair module which is required for creating private and public kets

bdb_root_url = 'http://localhost:9984'
bdb = BigchainDB(bdb_root_url)  # This denotes the fact that we are not using authentication tokens
alice = generate_keypair()
bob = generate_keypair()
matt = generate_keypair()


def poll(transaction_id):
    trials = 0

    while trials < 100:
        try:
            if bdb.transactions.status(transaction_id).get('status') == 'valid':
                break
        except Exception as e:
            trials += 1
    print(bdb.transactions.status(transaction_id))


# Generates public and private key for Alice and Bob
'''
Here the asset being transferred is a bicycle which belongs to Alice
The variable below contains a data property which contains the information about the bicycle
'''

bicycle = {
    'data': {
        'bicycle': {
            'serial_number': 'XX2334C',
            'manufacturer': 'bkfab',
        },

    },
}
metadata = {'Country': 'France'}  # Any dictionary can be used as Metadata
prepared_creation_tx = bdb.transactions.prepare(operation='CREATE', signers=alice.public_key, asset=bicycle,
                                                metadata=metadata)  # This creates a digital asset
fulfilled_creation_tx = bdb.transactions.fulfill(prepared_creation_tx,
                                                 private_keys=alice.private_key)
sent_creation_tx = bdb.transactions.send(
    fulfilled_creation_tx)  # the authorized transaction is now sent over to the BigchainDB
txid = fulfilled_creation_tx['id']  # contains the transaction id
poll(txid)
creation_tx = fulfilled_creation_tx  # Alice retrieves the transaction
print("Alice retrieves", creation_tx)

'''
Preparing a transaction
To get inforamtion about the id of the asset we are transferrring
'''
asset_id = creation_tx['id']
transfer_asset = {
    'id': asset_id,
}

'''
Transfer transaction
'''
output_index = 0
output = creation_tx['outputs'][output_index]
transfer_input = {
    'fulfillment': output['condition']['details'],
    'fulfills': {
        'output_index': output_index,
        'transaction_id': creation_tx['id'],
    },
    'owners_before': output['public_keys'],
}
prepared_transfer_tx = bdb.transactions.prepare(
    operation='TRANSFER',
    asset=transfer_asset,
    inputs=transfer_input,
    recipients=bob.public_key,
)
# Fulfillment of transfer
fulfilled_transfer_tx = bdb.transactions.fulfill(
    prepared_transfer_tx,
    private_keys=alice.private_key,
)
# Send it across the Node
sent_transfer_tx = bdb.transactions.send(fulfilled_transfer_tx)
poll(sent_transfer_tx['id'])
print("Fulfilled transfer looks like", fulfilled_transfer_tx)
print("Is the bob the owner?", sent_transfer_tx['outputs'][0]['public_keys'][0] == bob.public_key)
print("Was Alice the previous owner? ", fulfilled_transfer_tx['inputs'][0]['owners_before'][0] == alice.public_key)
transfer_tx = fulfilled_transfer_tx

'''
Transfer transaction again
'''
asset_id = transfer_tx['asset']['id']
transfer_asset = {
    'id': asset_id,
}
print("Helllooo")
print(transfer_tx['asset']['id'])

output = creation_tx['outputs'][output_index]
transfer_input = {
    'fulfillment': output['condition']['details'],
    'fulfills': {
        'output_index': output_index,
        'transaction_id': transfer_tx['id'],
    },
    'owners_before': [bob.public_key]
}

prepared_transfer_tx_again = bdb.transactions.prepare(
    operation='TRANSFER',
    asset=transfer_asset,
    inputs=transfer_input,
    recipients=matt.public_key,
)
# Fulfillment of transfer
fulfilled_transfer_tx_again = bdb.transactions.fulfill(
    prepared_transfer_tx_again,
    private_keys=bob.private_key,
)
# Send it across the Node
sent_transfer_tx_again = bdb.transactions.send(fulfilled_transfer_tx_again)
poll(sent_transfer_tx_again['id'])
print("Fulfilled transfer looks like")
print(fulfilled_transfer_tx_again)

print("Is Matt the owner?", sent_transfer_tx_again['outputs'][0]['public_keys'][0] == matt.public_key)
print("Was Bob the previous owner? ", fulfilled_transfer_tx_again['inputs'][0]['owners_before'][0] == bob.public_key)
```

**Comment by raaghavvd** [comment]
thanks Diminator, Tim and Troy for helping me out. 
Cheers guys ! :)

**Comment by raaghavvd** [comment]
@diminator can you explain why you suffixed 'again' at the end?
