### ISSUE TITLE
Writing to an already closed websocket connection throws errors and increases endpoint's response time

### ISSUE THREAD

**Issue by TimDaub** [bigchaindb/bigchaindb#1787]
Here is how to reproduce:

1. Run the latest bigchaindb server locally
2. Install and download bigchaindb/benchmarks
3. Run a script that initiates a WS connection with BigchainDB and e.g. counts the messages receives

I've prepared a script already:

```javascript
(function replication() {
    const conns = []
    let messages = 0

    function onOpen() {
        console.log('open')
    }

    function onError(error) {
        if (error.code === 'EAI_AGAIN') {
            console.log('Connection problem with BDB')
        }
    }

    function onClose() {
        //console.log('close')
    }

    function onMessage(data) {
        messages += 1
        console.log(messages)
    }

    const listeners = {
        open: onOpen,
        error: onError,
        close: onClose,
        message: onMessage
    }

    function initSockets() {
        const ws = new WebSocket('ws://localhost:9985/api/v1/streams/valid_transactions')
        Object
            .keys(listeners)
            .forEach(key => ws.addListener(key, listeners[key]))

        conns.push(ws)
    }
    initSockets()
})()
```

4. Send a transaction using the benchmark tool to see if the script works

```
bigchaindb-benchmark -p http://localhost:9984 send -r 1
```

5. If it does. `1` should appear from the console

6. Now increase the number of transactions by several magnitudes such that your script will start to have problems receiving them

```
bigchaindb-benchmark -p http://localhost:9984 send -r 10000000
```

7. Wait for a few thousand messages to be sent, then quickly terminate the script with Ctrl-C

8. BigchainDB should now log this message many times:

```
(asyncio) socket.send() raised exception
```

Likely because the connection bigchaindb just wanted to write a transaction to just got closed by the script.

If you now try to reconnect to BigchainDB, its response time will be extremely high, to the point of connections not getting accepted anymore.

@vrde Happy to fix this myself if you tell me where.

**Comment by vrde** [comment]
I'm able to reproduce the error.

I guess it's related https://github.com/aio-libs/aiohttp/issues/2309. (The previous issue was not acknowledge by the core team: https://github.com/aio-libs/aiohttp/issues/961.).

Seems like the exception is not bubbling up in the stack:
```
[...] [WARNING] (aiohttp.websocket) websocket connection is closing. (ws- pid: 26625)
[...] [WARNING] (asyncio) socket.send() raised exception. (ws         - pid: 26625)
[...] [WARNING] (aiohttp.websocket) websocket connection is closing. (ws- pid: 26625)
[...] [WARNING] (asyncio) socket.send() raised exception. (ws         - pid: 26625)
```

In https://github.com/aio-libs/aiohttp/issues/2283 they have a workaround. I'll try it out.

I think we should take some time to re–implement this websocket feature using a library that is **not** `aiohttp`. The API is convoluted and difficult to understand.

**Comment by kansi** [comment]
@TimDaub @vrde How do we plan to fix this i.e. will the suggested work around suffice or do we re-implement? Incase of latter @vrde do you have any specific libraries in mind?

**Comment by vrde** [comment]
@kansi I've [already started fixing it](https://github.com/bigchaindb/bigchaindb/compare/improve-ws-reliability) (there was also a memory leak).

> How do we plan to fix this i.e. will the suggested work around suffice or do we re-implement?

TBH the work around should suffice for now.
