### ISSUE TITLE
Search API does not work with Regex

### ISSUE THREAD

**Issue by Giehlls** [bigchaindb/bigchaindb#1801]
* BigchainDB version: 1.01
* Operating System: Ubuntu 16.04
* Deployment Type: `Host`
* BigchainDB driver: `[yes]``[python]` [0.4.x]

### Description

The `GET /api/v1/assets?search={text_search}&limit={n_documents}` endpoint (for asset text search) does NOT work for regular expressions.

See in screenshot that searching for ben* will not return to me what I am looking for, in this case 'ben19-24'.

Integrating RegEx into the asset search feature would be very helpful to aggregate similar assets in the many cases where users are not asked to follow strict naming conventions for their assets

### Steps to Reproduce
properly setup a bigchaindb node
query the /assets endpoint using curl or python

### What I Did
![capture](https://user-images.githubusercontent.com/10538113/32075831-f327594a-ba6b-11e7-94a4-794d18b2a89c.JPG)

**Comment by ttmc** [comment]
Our current thinking is that a BigchainDB node operator (or their network/consortium) can provide more advanced query functionality, as needed. For details about how they could do that, see https://docs.bigchaindb.com/en/latest/query.html
