### ISSUE TITLE
getstarted does not work for newer browser version

### ISSUE THREAD

**Issue by shahbazn** [bigchaindb/bigchaindb#1815]
* BigchainDB version: v1.1
* Operating System: Ubuntu
* Deployment Type: `IPDB`
  * network type: `test`
  * URL:` https://www.bigchaindb.com/getstarted/`
* BigchainDB driver: `no`

### Description

Getting started page does not work for Chrome browser versions >61.x latest browser versions does not set `http_referer` to `bigchaindb.com` as is expected by the backend server and as a result nginx refuses the request.

### Steps to Reproduce
update to a chrome version > 61.x and try `https://www.bigchaindb.com/getstarted/`

**Comment by muawiakh** [comment]
As discussed with @jernejpregelj , we can try moving the `OPTIONS` request before we check for the `PROXY_EXPECTED_REFERER/ORIGIN_HEADER` i.e. change

```
      # check if the request originated from the required web page
      # use referer header.
      if ($http_referer !~ "PROXY_EXPECTED_REFERER_HEADER" ) {
        return 403 'Unknown referer';
      }

      # check if the request has the expected origin header
      if ($http_origin !~ "PROXY_EXPECTED_ORIGIN_HEADER" ) {
        return 403 'Unknown origin';
      }

      if ($request_method = 'OPTIONS') {
        add_header 'Access-Control-Allow-Origin' '*';
        add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
        add_header 'Access-Control-Allow-Headers' 'DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Content-Range,Range,app_key,app_id';
        add_header 'Access-Control-Max-Age' 43200;
        add_header 'Content-Type' 'text/plain charset=UTF-8';
        add_header 'Content-Length' 0;
        return 204;
      }
```

To something like this:
```
      if ($request_method = 'OPTIONS') {
        add_header 'Access-Control-Allow-Origin' '*';
        add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
        add_header 'Access-Control-Allow-Headers' 'DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Content-Range,Range,app_key,app_id';
        add_header 'Access-Control-Max-Age' 43200;
        add_header 'Content-Type' 'text/plain charset=UTF-8';
        add_header 'Content-Length' 0;
        return 204;
      }

      # check if the request originated from the required web page
      # use referer header.
      if ($http_referer !~ "PROXY_EXPECTED_REFERER_HEADER" ) {
        return 403 'Unknown referer';
      }

      # check if the request has the expected origin header
      if ($http_origin !~ "PROXY_EXPECTED_ORIGIN_HEADER" ) {
        return 403 'Unknown origin';
      }
```

**Comment by shahbazn** [comment]
@jernejpregelj @muawiakh  I think the best solution would be to set the `Referrer-Policy` on the client side to `origin-when-cross-origin`. Since that the only change is see form current workflow that the browser now just expect the client application to configure a referrer policy from one of the options available [here](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Referrer-Policy#Examples) instead of just adding the referrer by default

**Comment by muawiakh** [comment]
So, will you be taking care of it? Or reassign to @kremalicious ?

**Comment by shahbazn** [comment]
@muawiakh reassigning

**Comment by shahbazn** [comment]
@kremalicious since you were away when we created this let me know if you need to discuss it offline

**Comment by jernejpregelj** [comment]
@shahbazn @muawiakh Referrer-Policy cannot be set in all browsers for CORS preflight (OPTIONS) request. I think the best way is to check origin instead of referrer header or move referrer check after options.
