### ISSUE TITLE
Get an error TypeError: port should be int or None, got <class 'str'>

### ISSUE THREAD

**Issue by yrozhkov** [bigchaindb/bigchaindb#1817]
* BigchainDB version: BigchainDB Version 1.1.0
* Operating System: Linux
* Deployment Type: `[Docker|Host|IPDB|Other]` Docker
  * If you are using IPDB, please specify your network type `[test, prod]`
  and the `bdb_url(BigchainDB URL)` you are using.
  * For every other type of deployment, please specify the documentation/instructions
  you are following.
* BigchainDB driver: `[yes|no]` yes
  * If using a driver please specify, driver type `[python|js|java]` java
  and version.

### Description

I see  following error in log Get an error TypeError: port should be int or None, got <class 'str'>

### Steps to Reproduce
On bigchaindb startup

### What I Did

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback/error message here.
```

**Comment by kansi** [comment]
@yrozhkov Could you share you `.bigchaindb` config file?

**Comment by yrozhkov** [comment]
I run it using env variables with default .bigchaindb config file

 BIGCHAINDB_DATABASE_HOST: xxxx
        BIGCHAINDB_DATABASE_CONNECTION_TIMEOUT: 25000
        BIGCHAINDB_DATABASE_MAX_TRIES: 20
        BIGCHAINDB_DATABASE_NAME: bigchain
        #BIGCHAINDB_DATABASE_PORT: 28015
        #BIGCHAINDB_DATABASE_BACKEND: rethinkdb
        BIGCHAINDB_DATABASE_REPLICASET: bigchain-rs
        BIGCHAINDB_DATABASE_PORT: 27017
        BIGCHAINDB_DATABASE_BACKEND: mongodb

        BIGCHAINDB_SERVER_BIND: 0.0.0.0:9984
        BIGCHAINDB_SERVER_LOGLEVEL: debug
        BIGCHAINDB_SERVER_WORKERS: 5

        BIGCHAINDB_WSSERVER_SCHEME: ws
        BIGCHAINDB_WSSERVER_HOST: 0.0.0.0
        BIGCHAINDB_WSSERVER_PORT: 9985

       

        BIGCHAINDB_BACKLOG_REASSIGN_DELAY: 120

        BIGCHAINDB_GRAPHITE_HOST: localhost

**Comment by kansi** [comment]
@yrozhkov based on the error you described previously I think the value of port was specified as a string rather than integer i.e. `"9985"` or `"27017"` instead of `9985` or `27017`

**Comment by yrozhkov** [comment]
as you see there is no quotes around ports that is why I find this message confusing
