### ISSUE TITLE
[CRITICAL] (gunicorn.error) WORKER TIMEOUT (pid:927) (webapi     - pid: 184)

### ISSUE THREAD

**Issue by yrozhkov** [bigchaindb/bigchaindb#1818]
* BigchainDB version: BigchainDB Version 1.1.0
* Operating System: Linux
* Deployment Type: `[Docker|Host|IPDB|Other]` Docker
  * If you are using IPDB, please specify your network type `[test, prod]`
  and the `bdb_url(BigchainDB URL)` you are using.
  * For every other type of deployment, please specify the documentation/instructions
  you are following.
* BigchainDB driver: `[yes|no]` yes
  * If using a driver please specify, driver type `[python|js|java]` java
  and version.

### Description

I am sending transactions to bigchaindb after some time sending fails and in bigchaindb log I see 

```text
November 7th 2017, 16:22:10.587 | [2017-11-07 21:22:10] [INFO] (gunicorn.error) Booting worker with pid: 957 (webapi     - pid: 957)
-- | --

  | November 7th 2017, 16:22:10.578 | [2017-11-07 21:22:10] [INFO] (gunicorn.error) Worker exiting (pid: 952) (webapi     - pid: 952)

  | November 7th 2017, 16:22:10.577 | [2017-11-07 21:22:10] [CRITICAL] (gunicorn.error) WORKER TIMEOUT (pid:952) (webapi     - pid: 184)
```
 

### Steps to Reproduce
Send 1000 transactions using java client

**Comment by ttmc** [comment]
@yrozhkov Were you using MongoDB or RethinkDB?

**Comment by yrozhkov** [comment]
MongoDB

**Comment by yrozhkov** [comment]
I tried rethinkdb have the same issue with mongo I am able to send ~30 transactions a second and with rethink ~4 transactions with rethink I see it starts failing later on

**Comment by yrozhkov** [comment]
I think the problem with Java driver

**Comment by ttmc** [comment]
This is an old issue involving an version of BigchainDB that we don't support any more (v1.1.0), so I'm closing this issue.
