### ISSUE TITLE
Update configuration settings for BigchainDB 2.0.0

### ISSUE THREAD

**Issue by sbellem** [bigchaindb/bigchaindb#1826]

**Comment by ttmc** [comment]
I believe this issue is about updating the BigchainDB configuration settings for the first release of BigchainDB that integrates Tendermint. If so, I think that will be done by @shahbazn and @vrde

**Comment by ttmc** [comment]
One thing that needs to be done for sure is to add two new configuration settings to BigchainDB Server:

- `tendermint.host` i.e. `BIGCHAINDB_TENDERMINT_HOST`
- `tendermint.port` i.e. `BIGCHAINDB_TENDERMINT_PORT`

I talked to @muawiakh about that yesterday and he said he'll do that.

**Comment by ttmc** [comment]
It seems we can remove the `backlog_reassign_delay` setting.

**Comment by ttmc** [comment]
@shahbazn suggested I close this issue and create a set of smaller issues. I will do that now.

**Comment by ttmc** [comment]
New issues created:

- Issue #2254 
- Issue #2255
