### ISSUE TITLE
Revisit HTTP API for tendermint integration

### ISSUE THREAD

**Issue by sbellem** [bigchaindb/bigchaindb#1828]
- [x] Identify tendermint endpoints and their purpose
- [x] Bind bigchaindb endpoints to tendermint ones, when relevant.

**Comment by kansi** [comment]
Usefull links:
- [List of tendermint endpoints](http://tendermint.readthedocs.io/en/master/specification/rpc.html#endpoints) 
- [Events API](https://docs.bigchaindb.com/projects/server/en/latest/events/websocket-event-stream-api.html) could be built using `/subscribe?event=` endpoint from tendermint.
- [Get block](https://docs.bigchaindb.com/projects/server/en/latest/http-client-server-api.html#get--api-v1-blocks-block_id) could be suplimented via `/block?height=_`

**Comment by kansi** [comment]
#### [Transaction status](https://docs.bigchaindb.com/projects/server/en/latest/http-client-server-api.html#get--api-v1-statuses?transaction_id=transaction_id)
According to comments [here](https://github.com/tendermint/tendermint/blob/master/rpc/core/tx.go#L11) it seems we cannot figure out if a transaction is `undecided` or `invalid`. This would imply that inorder to keep track of the transaction status i.e. `undecided`, `valid`, `invalid` we would need to maintain the state it BigchainDB?

**Comment by vrde** [comment]
@kansi great work here! :nail_care:

Ignore for now the last two endpoints `blocks` and `votes`. The implementation depends on how far we are with #1845. All other endpoints depend on the `transactions` and `assets` collection, so you should be able to integrate them """easily""".

**Comment by ttmc** [comment]
Some questions about the `votes` endpoint:

- It seems Tendermint has no "votes." It has "pre-votes", "pre-commits" and "commits"? Is that right?
- Are those things available via some Tendermint API?
- Would any end-users care about those things (e.g. auditors) enough to _want_ endpoints to get them?

**Comment by ttmc** [comment]
@sbellem and @kansi I think this issue can be closed because issues #2036 and #2037 should take care off all remaining things-to-do.
