### ISSUE TITLE
Send the hash to tendermint

### ISSUE THREAD

**Issue by sbellem** [bigchaindb/bigchaindb#1829]
_description will be added soon_

**Comment by kansi** [comment]
@sbellem  @vrde The tendermint docs [here](https://tendermint.readthedocs.io/en/master/app-development.html#commit) describe that the `commit` should return a byte array which would be included in the header of the next block. So, I guess we could send the [merkle root](https://github.com/Tierion/pymerkletools) of the transactions included in the previous block?

**Comment by vrde** [comment]
Sounds good to me. Should we also add in the `hash` the merkle root of the previous block?

**Comment by kansi** [comment]
@vrde yes, I think that is good idea. Do we store the hash of the previous block ourselves or query it from tendermint?

**Comment by vrde** [comment]
I guess we should add a new collection to store this information. We will need to store something like:
```
{
    "height": "<int>",
    "app_hash": "<string>"
}
```

This information should be exposed by the [`info`](https://github.com/davebryson/py-abci/blob/master/abci/application.py#L39) method.
