### ISSUE TITLE
Implement what is needed to support dynamic federation changes

### ISSUE THREAD

**Issue by sbellem** [bigchaindb/bigchaindb#1832]
_description will be added soon_

**Comment by ttmc** [comment]
@kansi wrote a spec for a way to change the number of validators in a federation (consortium cluster) at run time; see [BEP-3](https://github.com/bigchaindb/BEPs/tree/master/3). It was implemented and was first available in [BigchainDB 2.0 Alpha](https://github.com/bigchaindb/bigchaindb/releases/tag/v2.0.0a1).

Other run-time changes to federation parameters can be spec'd out in future BEPs.
