### ISSUE TITLE
dev env: use docker-compose to run bdb/tm integration

### ISSUE THREAD

**Issue by sbellem** [bigchaindb/bigchaindb#1844]
- [x] provide docker-compose file for single node
- [x] provide docker-compose file for a 4 node cluster
- [x] document single node and multi node usages, for dev environments
- [x] use "custom" dockerfile for tendermint instead of dockerhub one

**Comment by muawiakh** [comment]
All tasks done. I assume. Please re-open if needed. Closing for now.
