### ISSUE TITLE
Single entry point script to deploy single node bdb+tendermint+mongo dev setup

### ISSUE THREAD

**Issue by shahbazn** [bigchaindb/bigchaindb#1850]
Wrapper script to bootstrap/clean up dev environment on ubuntu to start a BDB server + tendermint + mongoDB + levelDB

**Comment by ttmc** [comment]
We now have several ways to deploy a whole BigchainDB node (e.g. `make start` and `stack.sh`). We might add more, but I think we can close this issue and open a new, more specific issue if we decide we want to implement another way.
