### ISSUE TITLE
Managing the "current keyring" in the federation

### ISSUE THREAD

**Issue by ttmc** [bigchaindb/bigchaindb#187]
I wrote a command-line command `bigchaindb add-to-keyring KEY` to add another node's public key (`KEY`) to the node's keyring. (I was working on resolving issue #179.) Then I realized that there are problems with the current keyring model...

**What is the keyring?**

For a given node, the keyring a list of the public keys of all the other nodes in the federation. It determines who is in the federation (and not). Every node has its own keyring. It's one of the node's configuration settings.

The keyring is used in two situations:
1. When a node assigns a transaction to another node, it randomly picks one from its keyring.
2. When a node creates a new block, it includes a list of all nodes which can vote on that block. That list is its keyring.

**The problems**

Each node has its own keyring. Those keyrings might not agree (i.e. no consensus on the list of current federation members). The nodes should all get the current list of federation nodes from the same standard source that they can all agree upon.

Secondly, we may want to know more than the public keys of the current federation nodes. We may want additional information about them, such as the associated organization name.

**Proposal**

Store all **proposed lists of federation nodes** in JSON documents in a new `fednodes` table in the RethinkDB database. (Not all will be accepted, but they'll all be kept, hence the word "proposed.")

Data model for a proposed list of federation nodes ("prop_list"?)

```javascript
{
    "id": "<hash of the serialized proposal>",
    "proposal": {
        "prop_num": // <an integer>,
        "previous_id": "<id of previous proposed list>",
        "timestamp": "<proposal-creation timestamp>",
        "creator_pubkey": "<public key of node that created this proposal>",
        "nodes": [
            {"node_owner": "Organization Name 253",
             "public_key": "29tgo20IIUG857..."},
            {"node_owner": "Orgname A23",
             "public_key": "HUi93isohFFI56..."}
        ],
    },
    "signature": "<signature of the proposal>",
    "votes": // <a list of signed votes, something like what blocks have>
}
```

As with blocks, a proposed list can be `undecided`, `decided_valid`, or `decided_invalid`. It depends on the votes that the proposed list has gotten so far. (It can be determined by querying.) The rules are the same as for blocks?

The first proposed list (i.e. the genesis list) is always `decided_valid`.

The "current list of federation nodes" is the latest `decided_valid` list. (This can be determined by querying. `prop_num` is there to make this query a bit easier: you can start by looking at the proposed list with `prop_num` == "number of documents in `fednodes`" and then follow the links backwards until you get to a `decided_valid` proposed list.)

Any federation node can submit a new proposed list (which may have more nodes, fewer nodes, or changed organization names). It signs the proposed list, appends its vote, and writes the proposed list to the `fednodes` table.

All nodes in the "current list of federation nodes" can vote on the new proposed list? What if a node is being ejected against its will? Maybe departing nodes' votes don't count: they're not taken into consideration when determining if a quorum has been reached.

A node can vote to accept or reject a proposed list, and must sign their vote.

**TODO:**

Discuss this proposal in the comments below, and once we agree on how to proceed, create some new GitHub issue(s) listing what to do.

**Comment by r-marques** [comment]
I like the open ended todo list 
- [ ] etc.

**Comment by ttmc** [comment]
I modified the original description to add the signature of the creator node to the data structure of a proposed list. Now it's even more like the block model. It doesn't include the list of nodes required to vote on the proposal, because that can be determined from other available information.

I should add that I didn't include a timestamp in the model because in distributed systems, timestamps generally don't mean that much (unless you go to a lot of trouble like what Google Spanner does), yet the unfamiliar user might think (wrongly) that a timestamp is more meaningful than it is.

Should we include a timestamp anyway?

**Comment by diminator** [comment]
> As with blocks, a proposed list can be undecided, decided_valid, or decided_invalid. It depends on the votes that the proposed list has gotten so far. (It can be determined by querying.) The rules are the same as for blocks?

having a voted version makes sense.

How does a federation node casts a vote? manually/automatically?

**Comment by ttmc** [comment]
Maybe the default would be that the owner/controller (person) running each node must manually cast the vote.

First, they would have to be notified of the requirement to vote (how? Email? Slack? SMS? OS-level notifications? PagerDuty integration?).

Then they'd be asked to cast their vote. How would they do that? A command-line voting command? `bigchaindb vote-on-proposals`? It would then explain the next outstanding proposal in detail, ask for their vote, and confirm their choice. (There may be several proposals for them to vote on.)

The node owner might create tools or scripts to automatically vote sometimes. There could be a command to make that easier, e.g. `bigchaindb proposal-vote 245 yes`

**Comment by ttmc** [comment]
I decided to add a timestamp to node list proposals after all, to be consistent with the rest of BigchainDB. We can revisit _all_ timestamps together at the same time; see issue #132

**Comment by ttmc** [comment]
Re: https://github.com/bigchaindb/bigchaindb/issues/187#issuecomment-211393944

I removed the open-ended checklist because GitHub was interpreting it literally, showing that "0 out of 3" items were done, complete with a progress bar.

**Comment by ttmc** [comment]
Just a note: There may be some overlap in functionality between the process for voting on blocks and the process for voting on federation-list proposals. There are differences; as mentioned above, we probably want the default voting on proposals to be somewhat manual.

**Comment by ttmc** [comment]
Today I mentioned that I was wondering when we should do this (i.e. move the public key lists out of the BigchainDB configuration files [one per node] and into a RethinkDB database table).

I guess it should wait until after the code has been refactored into server, drivers/python, and shared python code.

**Comment by ttmc** [comment]
I am closing this issue. To understand why, see the last comment on issue https://github.com/bigchaindb/bigchaindb/issues/436#issuecomment-251392149

**Comment by trentmc** [comment]
> To understand why, see the last comment on issue #436 (comment)

It's no longer the last comment on #436. The relevant quote in the relevant comment, by @ttmc, is:

> Today we had a meeting to discuss this and we concluded that the existing system (where the keyring is read from the configuration settings at launch and is then stored in memory) is probably good enough
