### ISSUE TITLE
TX metadata size

### ISSUE THREAD

**Issue by ivooz** [bigchaindb/bigchaindb#1879]
* BigchainDB version: bigchaindb 1.1.0
* Operating System: Ubuntu 16.04 LTS
* Deployment Type: Host
  * For every other type of deployment, please specify the documentation/instructions
  you are following.

```
docker run -p 27017:27017 mongo:3.4 mongod --replSet=bigchain-rs

bigchaindb -y configure mongodb

bigchaindb start
```

* BigchainDB driver: yes, js

### Description

Describe what you were trying to get done.
I'm tryin to create a TRANSFER tx, which a metadata field of size 5.15 KB.

### Steps to Reproduce

Create an asset, the transfer it to some public key with the aformentioned metadata size.

### What I Did

```
/** @dev Updates the state (metadata) of an asset by creating a transfer function
 *
 * @params txSigned - The unspent signed transaction that the state will be updated from
 * @params metadata - This will be used to store the user information, this can be used to store changing data
 * @params keypair - The public and private key of the owner of the asset
 */
exports.updateAssetState = async function updateAssetState(txSigned, metadata, keypair) {
    var condition = bigchain.Transaction.makeEd25519Condition(keypair.publicKey)
    var outputs = [bigchain.Transaction.makeOutput(condition)]

    var txTransferAsset = bigchain.Transaction.makeTransferTransaction(
        txSigned,
        metadata,
        outputs,
        0 // reference to outputs[0] of the txSigned
    );

    // Needs to be signed by the User for it to be valid
    var txTransferAssetSigned = bigchain.Transaction.signTransaction(txTransferAsset, keypair.privateKey);

    const conn = new bigchain.Connection(settings.BIGCHAIN_CONNECTION_STRING);

    conn.postTransaction(txTransferAssetSigned);

    return txTransferAssetSigned.id;
};
```

There is no error, the asset simply never updates, returns the old metadata from the ISSUE transaction.

NOTE: this works for smaller metadata sizes, fails for bigger i.e. metadata has nested array of objects: after adding one more small object in subarray it fails.

NOTE2: restarting bigchain solves the issue!

**Comment by manolodewiner** [comment]
This was happening using an old version of BigchainDB. I guess we can close this issue @kansi
