### ISSUE TITLE
Metadata endpoint does not appear in the api/v1/ for BigchainDB 1.3

### ISSUE THREAD

**Issue by manolodewiner** [bigchaindb/bigchaindb#1888]
Metadata search has been implemented and is working properly in the 1.3 version, but when connecting to the API, it does not show the metadata endpoint. I think it would be useful.
![screenshot from 2017-11-22 14-01-27](https://user-images.githubusercontent.com/11859909/33130907-25e751a8-cf95-11e7-8d80-2a3091859ca0.png)

**Comment by kansi** [comment]
Sure, will be fixed asap.

**Comment by muawiakh** [comment]
@kansi, @manolodewiner showed this to me, I have a fix for it. If you don't already have a PR, I can push it. It is just a one liner.

**Comment by kansi** [comment]
@muawiakh sure, but there is another change that needs to be added before we can merge the PR i.e. update the metadata documentation to refect the list of allowed languages for the `language` key.

**Comment by muawiakh** [comment]
Can you give me a link for that, if possible? So I can mention in the PR?

**Comment by kansi** [comment]
[here](https://docs.bigchaindb.com/projects/server/en/v1.3.0/data-models/transaction-model.html) is the link. You can just copy and paste the language from "The Asset Model" page
