### ISSUE TITLE
Skip/abort voting on a block if/when it is already decided

### ISSUE THREAD

**Issue by ttmc** [bigchaindb/bigchaindb#190]
I discussed this with @r-marques on April 18 and figured I should make an issue for it so we don't forget it.

If a block already has a quorum of votes (either in favor or against), then there's no point for any other nodes to vote on it: their vote won't change the outcome. Similarly, a node can abort voting on / validating a block if it notices the block has become decided.

(Right now, every node votes on every block, and therefore must validate every transaction. See `bigchaindb/core.py`)

One nice bonus is that if a node crashes for a while, then when it comes back, it can catch up to all the other blocks quicker, because it won't have to vote on a bunch of blocks that it didn't vote on yet: those blocks will have been decided already.

Note: the meaning of "quorum" might vary from one consensus plugin to another. Some might define "quorum" as 50% of nodes + 1, others might say 2/3 of nodes + 1, and others might require unanimous agreement.

**Comment by rhsimplex** [comment]
I think we should close this issue without fixing. We may have to monitor Byzantine behavior by how other nodes vote.  This also helps the node verify itself.  What happens if one slow node never votes?

**Comment by ttmc** [comment]
This isn't about detecting Byzantine behavior; it's about avoiding unnecessary validations to reduce CPU and RAM usage (and their associated costs).

There are some other issues about detecting Byzantine behavior.

Your question about slow nodes is a good one. My gut response is that all nodes in a federation should be voting at roughly the same speed, but it's possible that there might be some relatively distant nodes (e.g. in Australia); those ones might seem slow to the others. Ideally, we want each node to have roughly the same number of votes per second. Maybe "fast" nodes could introduce small delays in their voting to come closer to the system-wide average voting rate?

**Comment by rhsimplex** [comment]
> Maybe "fast" nodes could introduce small delays in their voting to come closer to the system-wide average voting rate?

This could be an attack vector.  I worry about increasing complexity here.  And this absolutely could hide Byzantine behavior: n/2+1 nodes take over and vote together without validating.  The remaining nodes not only get these Byzantine results, they never even know somethings wrong because they never cast votes themselves.

Of course if n/2+1 collude take over, the federation is compromised in a theoretical sense, but if the other nodes never vote, they'll never even know.

**Comment by ttmc** [comment]
Ah, I see, good point! In summary, all nodes should vote on all assigned blocks (i.e. all blocks where they are in the voting list).

There's still the question of what to do if a node goes down for a long time, so that when it comes back up, it has a huge backlog of voting to do. If we require it to vote on all those old blocks, it may never catch up and contribute to actual decision-making. I suppose the returning node could deploy more validators to be able to do validation faster, so that it can catch up. If we go with that strategy, then we'll have to add the necessary code. We're not in a position to do that today, because today we have no hooks to change the number of validators (i.e. automatically, based on need).

There was another idea mentioned above: the idea that the size of a "quorum" might vary between federations (e.g. 50% + 1, 2/3 + 1, unanimous, etc.). I'll put that in its own issue, because it's a separate idea.

**Comment by ttmc** [comment]
It seems we've agreed that the original proposal (in the title), i.e. "Skip/abort voting on a block if/when it is already decided" is not the right idea: every node should vote on every block. In other words, we've decided to not implement the original proposal. I will mark this issue as `wontfix` and close it.

However, if every node must vote on every block, how do we ensure they can all keep up? I'll create a new issue for that.
