### ISSUE TITLE
update docs following #1899

### ISSUE THREAD

**Issue by sbellem** [bigchaindb/bigchaindb#1912]
see #1899 for details

**Comment by ttmc** [comment]
@sbellem PR #1899 is merged now. What docs did you have in mind to update? Maybe the IPDB Transaction Spec? Any others?

**Comment by sbellem** [comment]
Not sure, will double check soon.

**Comment by ttmc** [comment]
[The IPDB Transaction Spec, Version 2.0](https://github.com/ipdb/ipdb-tx-spec/tree/master/v2.0), documents how to construct a transaction of version 2.0, including "fulfill first, then hash." I also wrote about that change, and why it was made, in [a blog post](https://blog.bigchaindb.com/three-transaction-model-changes-in-the-next-release-dadbac50094a). Therefore, I'm closing this issue.
