### ISSUE TITLE
Transactions from an invalid block should be put back into the backlog

### ISSUE THREAD

**Issue by r-marques** [bigchaindb/bigchaindb#193]
When a block is marked invalid the transactions in the block need to be re-assigned and put back into the backlog.

The difficult part is to decide which node should do it. A simple solution would be to have a changefeed listening to updates on the `bigchain` table (the only updates permitted should be appending new votes) and everytime a new vote comes in we check if a majority decision was reached. If so and if the decision is invalid put the transactions back into the `backlog`. Since the primary key in the `backlog` table is the `id` of the transaction even if several nodes try to do this at the same time there will be no duplicated transactions in the `backlog`.

**Comment by rhsimplex** [comment]
Ok, trying to get some understanding here.  It seems the functions involved from `core.py` is `write_vote`.
`write_vote` occasionally looks up a block by primary key, and appends a new `vote` to the `votes` field at that record.

So the changefeed will look something like 

```python
feed = r.table('bigchain').filter(r.row['votes']).changes().run(self.conn)
```
Which I suppose will go somewhere in `processes.py` (somewhere in the `map_bigchain` function)?  When a majority invalid vote happens (btw, how does bigchain know what a majority is...from the number of keys?) then all transactions are put back into `q_new_transactions` or inserted directly? I think inserted directly.  The question is where does the function which does that go...in `block.py`?

Do the votes currently trigger anything at all? It looks like the votes get written but are never used again, correct?

Finally, should an invalidated block be deleted once all of its transactions are liquidated?

**Comment by r-marques** [comment]
> So the changefeed will look something like 
```python
feed = r.table('bigchain').filter(r.row['votes']).changes().run(self.conn)
```
Which I suppose will go somewhere in `processes.py` (somewhere in the `map_bigchain` function)?  

We can use the already existing changefeed `r.table('bigchain').changes().run(b.conn)` and just act on updates assuming that the only updates in bigchain table will be new votes.
You can put the `new_val` in a queue and then create a process that will read from the queue, check if the block was decided invalid and if so write the transactions back to the backlog using `write_transactions` in every transaction in the block.
