### ISSUE TITLE
broken links in docs

### ISSUE THREAD

**Issue by codegeschrei** [bigchaindb/bigchaindb#1934]
* BigchainDB version: latest
* Operating System: /
* Deployment Type: /
* BigchainDB driver: no
 
### Description

https://docs.bigchaindb.com/projects/server/en/latest/data-models/block-model.html
On this page, there are three links to IPDB readthedocs and none of them works
same goes for this page:
https://docs.bigchaindb.com/projects/server/en/latest/data-models/vote-model.html

### Steps to Reproduce
None

### What I Did
None

**Comment by ttmc** [comment]
Good catch: those links point to URLs like https://the-ipdb-protocol.readthedocs.io/en/latest/crypto-hashes.html but they were changed to https://the-ipdb-transaction-spec.readthedocs.io/en/latest/common-operations/crypto-hashes.html 

I will fix this.
