### ISSUE TITLE
Prevent updates on the backlog table

### ISSUE THREAD

**Issue by r-marques** [bigchaindb/bigchaindb#194]
There should be no updates on the `backlog` table.
We need to create a changefeed to listen to updates in the `backlog` and if an update occurs revert the change. The tricky part is that several nodes will try to do this a the same and the revert will trigger a new update in itself.

**Comment by rhsimplex** [comment]
Same problem as #195, I don't think it's merely tricky but actually impossible in the current setup.

**Comment by rhsimplex** [comment]
Also this is incompatible with #198 since transactions will need to be updated periodically with new assignees and fresh timestamps.

**Comment by ttmc** [comment]
@rhsimplex Can you say a bit about why you think this issue can be closed? Is it because maliciously updated transactions can only become invalid, and therefore will get handled anyhow?

**Comment by rhsimplex** [comment]
Sorry.  #198 requires updates to backlog. And since Byzantine operations will be stopped by some other preventative measure in the future, these handle delete/update to [table] don't really make a whole lot of sense anymore.  In fact, with #544 we actually have removed the existing functionality.
