### ISSUE TITLE
Incentivize writing good asynchronous code

### ISSUE THREAD

**Issue by vrde** [bigchaindb/bigchaindb#1956]
Python 3.6 introduces the new keywords `async` and `await`, that can be combined with `def`, `for`, `with` (and more?).

We are [adding more code](https://github.com/bigchaindb/bigchaindb/pull/1928) that requires asynchronous primitives.

Python 3.5 supports asynchronous-function definitions and asynchronous-function calls by using `@asyncio.coroutine` and `yield from`. AFAIK there is no way to decorate or wrap `with` and `for`, and this disincentivize writing good asynchronous code.

My proposal is to drop support for Python 3.5.

**Comment by sbellem** [comment]
> My proposal is to drop support for Python 3.5.

Great!

**Comment by vrde** [comment]
> Is this for the Tendermint integration only?

The `tendermint` branch will be merged in `master` at one point.

**Comment by sbellem** [comment]
> New in version 3.6: SHA3 (Keccak) and SHAKE constructors sha3_224(), sha3_256(), sha3_384(), sha3_512(), shake_128(), shake_256().

-- https://docs.python.org/3.6/library/hashlib.html#hash-algorithms

**Comment by sbellem** [comment]
> Python 3.6 introduces the new keywords async and await, that can be combined with def, for, with (and more?).

This should be available in Python 3.5 as per [PEP 492](https://www.python.org/dev/peps/pep-0492/).
