### ISSUE TITLE
Handle deletes on the backlog table

### ISSUE THREAD

**Issue by r-marques** [bigchaindb/bigchaindb#196]
We need to create a changefeed that listens to deletes in the `backlog` table. Deletes in the `backlog` should only be allowed if the transactions were included in a block in the `bigchain` table.

The voter code right now deletes the transactions as it processes them which means that there will a some time gap between the time a transaction is deleted and the time the block makes it to the `bigchain`. I can think of two solutions for this:

1. When a transaction is deleted cache it and check the `bigchain` table for the transaction after a timeout period (e.g. 30 seconds). If after the timeout period the transaction is not in the `bigchain` re-insert the transaction in the backlog.
2. The node creating the block first waits for the block to be written to the `bigchain` and them deletes the transactions from the `backlog`.

The second solution seems more robust since it does not rely on a timeout period but it requires changes to the voter process

**Comment by rhsimplex** [comment]
How does the second solution stop unauthorized deletes?

**Comment by rhsimplex** [comment]
Related to #568 and #198, closing to consolidate discussion (see #568)
