### ISSUE TITLE
Consolidate dockerization

### ISSUE THREAD

**Issue by shahbazn** [bigchaindb/bigchaindb#1960]
- Depricate old Dockerfiles and docker-compose files and replace with new ones with tendermint
- Update Quickstart docs to use docker compose workflow #1895 
- Remove Dockerfiles un-relevant to this repo e.g. compose/bigchaindb-server
- Repo restructure and remove un-necessary docker/docker-compose files/folder

**Comment by ttmc** [comment]
@shahbazn I already updated the Quickstart page in pull request #1952 . It's very different from before; mostly just pointing elsewhere.

**Comment by shahbazn** [comment]
@ttmc So I suppose this can now go to contributing.md?

**Comment by ttmc** [comment]
@shahbazn Yes, once pull request #1952 gets merged, the Quickstart page will point readers to contributing.md and the instructions about how to use Docker Compose can be in that file.

**Comment by shahbazn** [comment]
Closing this issue will be tracked as a separate effort cc @muawiakh @sbellem
