### ISSUE TITLE
Update README.md with commands to run BigchainDB with Vagrant

### ISSUE THREAD

**Issue by vrde** [bigchaindb/bigchaindb#1974]
* BigchainDB version: BigchainDB + Tendermint
* Operating System: Ubuntu
* Deployment Type: `Vagrant`

### Description
Update `README.md` with commands to run BigchainDB with Vagrant.

```sh
$ vagrant plugin install vagrant-cachier
$ vagrant plugin install vagrant-vbguest
# Set git branch to use (only available for tendermint branch for now)
$ export GIT_BRANCH=tendermint
# Download the script
$ curl -fOL https://raw.githubusercontent.com/bigchaindb/bigchaindb/${GIT_BRANCH}/pkg/scripts/install_stack.sh
# Run the script
$ bash install_stack.sh
```

**Comment by ttmc** [comment]
Or maybe just point from `README.md` to the Vagrant page in the docs, i.e. https://docs.bigchaindb.com/projects/server/en/latest/appendices/run-with-vagrant.html

**Comment by ttmc** [comment]
I think I want to close this issue. `README.md` should be minimal and instructions about using Vagrant should go elsewhere, probably in a special page in the new "Contributing to BigchainDB" docs, created in pull request #2119 

@vrde 
@shahbazn 

Can we close it? Please?
