### ISSUE TITLE
Use config file for mongo

### ISSUE THREAD

**Issue by sbellem** [bigchaindb/bigchaindb#1975]
Instead of passing a bunch of cmd line params.

see https://docs.mongodb.com/manual/reference/configuration-options/

**Comment by ttmc** [comment]
AFAIK, the standard way of starting MongoDB for BigchainDB today doesn't involve passing any command line parameters. In fact, if people follow the BigchainDB [Simple Deployment Template](http://docs.bigchaindb.com/projects/server/en/master/simple-deployment-template/index.html), then they don't have to do _anything_ to start MongoDB: the very act of installing it using `sudo apt install mongodb` also starts MongoDB running in the background as a service. That even installs a startup script, so MongoDB will be restarted if the machine is rebooted.
