### ISSUE TITLE
Handle stale transactions on the `backlog` table

### ISSUE THREAD

**Issue by r-marques** [bigchaindb/bigchaindb#198]
We need to handle the case in which a transactions in the `backlog` is assigned to nodeA and nodeA becomes unavailable (network connection, the node went down, couldn't handle the awesomeness of BigchainDB and caught on fire)

The solution would be a process that would check the backlog periodically for stale transactions and reassign them.

**Comment by ttmc** [comment]
For reference, this is the routine `reassignOldTransactions()` in **Listing 3** in the [whitepaper](https://www.bigchaindb.com/whitepaper/bigchaindb-whitepaper.pdf) (around page 23, although the page number may change as we edit the whitepaper).
