### ISSUE TITLE
Dynamically adding new validators

### ISSUE THREAD

**Issue by kansi** [bigchaindb/bigchaindb#1989]
### Description
The current approach to adding new nodes to the network requires the whole network to update their respective validator config and reboot the network. This approach works when developing and testing but is not feasible for production. It is crucial that new nodes could be added or removed while the existing nodes are running.

Tendermint allows the application to update the validator's set by allowing to send [validator diff](https://tendermint.readthedocs.io/en/master/app-development.html#endblock) during `end_block` response. 

### How this works
Validators in Tendermint propose and vote on blocks. A block is validated by a set of validators which is stored as `ValidatorsHash` in the header of the block. In case a new validator joins the network there are two possible scenarios i.e. the validator is known by `>2/3` of the network or the validator is not known by `>2/3` of the network. In the latter case i.e. when majority of the network doesn't know the validator any block which includes this new validator in its `ValidatorsHash` won't be able to get majority votes on that block. Hence the new validator cannot participate in the network untill a majority of the nodes acknowledge the new validator.

### Approach 1
Expose `end_block` directly to the client app using BDB via a web hook. The client would return a list of validators to add/remove.

#### Downside
Possible peformance hit since the web hook would be called every time during `end_block`.

### Approach 2
When using the BFT version (i.e. BDB w/ Tendermint or TBDB) it is reasonable to expect a permissioned network. This means that the network should be made aware of any new joining nodes using off-chain[1] methods i.e. each node might have their own logic of allowing new nodes in the network. 

The list of validators is maintained as an asset in the database. To add a new validator it has to secure `>2/3` of voting power (using off-chain methods). Once that is achieved any existing node can submit a transaction which includes the `pub_key` and `power` of the new node. Each node in the network validates[2] this transaction and adds the node by returning the [validator diff list](https://github.com/davebryson/py-abci/blob/master/abci/types_pb2.py#L1464) in `end_block` response.

#### Technicals
- When the network is booted `init_chain` is called with current list of validators. This should be used to initialize the validators list in BDB (maybe in form of an asset).  
- When a new node has secured a majority voting power it can ask any existing node to trigger a transaction which adds its public key to list of known validator nodes.
- New APIs need to be exposed:
  - `POST /api/v1/node` : add a new node
  - `PUT /api/v1/node` : update an existing node.
  - `DELETE /api/v1/node` : delete a existing node from the network.
- The client could expose a webhook which would be called by the BDB server to validate the above discussed transaction.

#### Downside
Complex !

### Related Issues
Either of the approaches suggested above will have to implement a web hook system so that the client app using bigchaindb could be delegated the task of the verifying if the new validator is in fact valid. A general implementation of web hooks system would facilitate resolving #1868

### Appendix
**[1]** It is also possible to use on chain methods and the client app can implement mechaincs such as buying token to achieve validator status.

**[2]** The validaton should be delegated to the client app. If the client doesn't implement a validation logic then the transaciton is assumed to be invalid.

**Comment by ttmc** [comment]
> Expose `end_block` directly to the client using a web hook.

I get confused by the word "client" when Tendermint is involved. Could you clarify who is sending what messages to whom in Approach 1?

**Comment by kansi** [comment]
Oh, by client I ment the client app which is using BigchainDB.

**Comment by ttmc** [comment]
Doesn't Tendermint Core see itself as a client of BigchainDB?

**Comment by kansi** [comment]
Yeah, its a little confusing. Tendermint and BigchainDB are both client for one another depending on the scenario. BigchainDB as client posts a txn to Tendermint which then as client uses the ABCI server run inside BigchainDB to validate, concent and deliver the txn back to BigchainDB.

**Comment by ttmc** [comment]
There was some thinking about the process to dynamically add/remove nodes in some old, now-closed issues. It might be worthwhile reading the comments in those issues, even if some of the ideas are no longer relevant. In particular, see issue #187

**Comment by kansi** [comment]
@ttmc I think _Approach 2_ (kind of) solves the probelm described in #187 and the peers don't have to manually vote i.e. I expect the peer application running on top of bigchaindb to have some kind of local db that tracks known validators. Then whenever a txn to update the validators set is sent in the network bigchaindb would execute a web hook of the application (the one using bigchaindb) which would validate the txn by checking its local db for the list of valid nodes.

**Comment by ttmc** [comment]
I think it's important that there be some kind of permanent record of the validator list, so that future auditors can know who was able to verify what transactions when.

**Comment by kansi** [comment]
I think Approach 2 will achieve that by making validator set as an asset in the bigchaindb itself. I haven't fully worked out the details but the idea is make use of bigchaindb itself to track the validators

**Comment by muawiakh** [comment]
Also, adding or removing validators can be a function of stake. Since some discussions about a version(product) of BigchainDB which is tokenized/incentivized. We might not need an off-chain consensus for that scenario, if someone wants to join the network. With the current implementation, I think the approaches @kansi mentioned can be looked into. Thoughts?

**Comment by ttmc** [comment]
We've implemented "upsert-validator elections" and all that remains to do is update some documentation; _that_ is covered by issue #2372, so this issue can be closed.
