### ISSUE TITLE
Missing Endpoints in Info Views

### ISSUE THREAD

**Issue by stylesuxx** [bigchaindb/bigchaindb#1999]
* BigchainDB version: 1.3.0
* Operating System: Debian Sid
* Deployment Type: Host

### Description
When inspecting the API Info screen http://127.0.0.1:9984/ and http://127.0.0.1:9984/api/v1/ I would expect the following endpoints to be listed too:
* /metadata/ (I have seen there is a PR for this)
* /blocks/
* /votes/

### Steps to Reproduce
* Mint installation of BigchainDB via pip
* Open API root URL in browser

**Comment by ttmc** [comment]
- /metadata/ was added to the response
- /votes/ was removed from the HTTP API completely
- /blocks/ wasn't added to the response yet, so I created a newer issue to remind us to do that: #2544
 
Therefore I'm going to close this issue.
