### ISSUE TITLE
Write transactions on block commit

### ISSUE THREAD

**Issue by kansi** [bigchaindb/bigchaindb#2009]
### Description
The transactions in a block are delivered by Tendermint using `deliver_tx` and in the current implementation they are [stored when they are received](https://github.com/bigchaindb/bigchaindb/blob/tendermint/bigchaindb/tendermint/core.py#L88). In case there is any crash during `deliver_tx`, [`end_block`](https://github.com/bigchaindb/bigchaindb/blob/tendermint/bigchaindb/tendermint/core.py#L92) or [`commit`](https://github.com/bigchaindb/bigchaindb/blob/tendermint/bigchaindb/tendermint/core.py#L110) the database will be left in an inconsistent state i.e. Tendermint will try to replay the transaction which will only result in failure as some transactions may already be present in the database.

### Approach
A possible approach to resolve this would be to write transactions during [`commit`](https://github.com/bigchaindb/bigchaindb/blob/tendermint/bigchaindb/tendermint/core.py#L110).

/cc @vrde @sbellem

**Comment by vrde** [comment]
Yes, this can be a problem. The current implementation is a simple solution to the problem of finding double spends in set of transactions in the current round: by immediately writing the transaction `tx₀` to the database, the transaction at `tx₁` will be checked against the previous state **plus** `tx₀`.

If you want to make a patch to solve this problem you need to check if a transaction is a double spent against two sets:
- the UTXO; and
- all the previous transactions in the current round.

During `commit` you can also use `db.collection.bulkWrite()`, so you need less round trip.

**Comment by sbellem** [comment]
From [tendermint's docs](http://tendermint.readthedocs.io/en/master/app-development.html#commit):

> It is expected that the app will persist state to disk on Commit.

**Comment by sbellem** [comment]
Seems to be some kind of two-phase commit.

* First phase: some kind of UTXO cache is updated for each `deliver_tx` call.
* Second phase: the UTXO cache is persisted to a persistent storage.

**Comment by kansi** [comment]
Fixed #2017
