### ISSUE TITLE
Create Status endpoint to get information about if a node is running, BigchainDB version, etc

### ISSUE THREAD

**Issue by manolodewiner** [bigchaindb/bigchaindb#2014]
Status endpoint providing information about a BigchainDB node.
We have a project where this endpoint is needed.

For example in IOTA blockchain there is the `getNodeInfo` with the following response example:
```
[
{
"appName": "IRI Testnet",
"appVersion": "1.4.1.6",
"jreAvailableProcessors": 2,
"jreFreeMemory": 2102394880,
"jreVersion": "1.8.0_91",
"jreMaxMemory": 4294967296,
"jreTotalMemory": 2147483648,
"latestMilestone": "ASDERPTHKBERTYITVOLHKWNGSTXESQZRRNAZNJRAXIGWMIWFWWGPYDEYG9STXGQOIUXWINZSKRGX9999",
"latestMilestoneIndex": 243001,
"latestSolidSubtangleMilestone": "ASDERPTHKBERTYITVOLHKWNGSTXESQZRRNAZNJRAXIGWMIWFWWGPYDEYG9STXGQOIUXWINZSKRGX9999",
"latestSolidSubtangleMilestoneIndex": 243001,
"neighbors": 0,
"packetsQueueSize": 0,
"time": 1515745784516,
"tips": 0,
"transactionsToRequest": 0,
"duration": 1
}
]
```

**Comment by ttmc** [comment]
The HTTP API has the so-called "BigchainDB Root URL" endpoint. It's documented at https://docs.bigchaindb.com/projects/server/en/latest/http-client-server-api.html#bigchaindb-root-url

An example is `https://example.com:9984` (with no /api/v1 or whatever on the end, because it's not about the API, it's about the server). An example response is:

```http
HTTP/1.1 200 OK
Content-Type: application/json

{
  "api": {
    "v1": {
      "assets": "/api/v1/assets/",
      "docs": "https://docs.bigchaindb.com/projects/server/en/v1.3.0/http-client-server-api.html",
      "outputs": "/api/v1/outputs/",
      "statuses": "/api/v1/statuses/",
      "streams": "ws://localhost:9985/api/v1/streams/valid_transactions",
      "transactions": "/api/v1/transactions/"
    }
  },
  "docs": "https://docs.bigchaindb.com/projects/server/en/v1.3.0/",
  "keyring": [
    "6qHyZew94NMmUTYyHnkZsB8cxJYuRNEiEpXHe1ih9QX3",
    "AdDuyrTyjrDt935YnFu4VBCVDhHtY2Y6rcy7x2TFeiRi"
  ],
  "public_key": "NC8c8rYcAhyKVpx1PCV65CBmyq4YUbLysy3Rqrg8L8mz",
  "software": "BigchainDB",
  "version": "1.3.0"
}
```

Maybe we could add _more_ information to the response at that endpoint?

**Comment by manolodewiner** [comment]
Yes that will be a good option I guess.
What about if I want to query for a specific node?
If you are running a cluster, which `public_key` is in the response when accessing `https://example.com:9984`? 
Can you obtain somehow the status for any other node in the cluster?

**Comment by ttmc** [comment]
Every node in the cluster will have its own public IP address, at the very least, e.g. 11.22.33.44, so you'll be able to send a GET request to 11.22.33.44:9984 for example to get the information about that specific node. A domain or subdomain might map to just one IP address, or it might map to several of them. (For example, a four-node cluster might have four DNS A Records mapping one domain (e.g. example.com) to four different IP addresses.

**Comment by manolodewiner** [comment]
I think we can close this issue. In our infrastructure each node will have a public IP address, so accessing the 9984 will be enough to check if that node is running.
