### ISSUE TITLE
Travis CI failing: Expired CRL

### ISSUE THREAD

**Issue by muawiakh** [bigchaindb/bigchaindb#2015]
* BigchainDB version: master

### Description
Travis CI is currently failing because CRL is expired for the mongodb + ssl tests. 

### Steps to Reproduce
Make a PR on bigchaindb/bigchaindb master branch, all builds failing on 30Jan2018.

https://travis-ci.org/bigchaisudndb/bigchaindb/builds/335209805?utm_source=github_status&utm_medium=notification

https://travis-ci.org/bigchaindb/bigchaindb/builds/335209819?utm_source=github_status&utm_medium=notification

**Comment by muawiakh** [comment]
@sbellem any update on this? I can take care of it, if needed.

**Comment by sbellem** [comment]
Will take care of it in the next hours.
