### ISSUE TITLE
Replace MongoDB oplog tailing with Change Streams?

### ISSUE THREAD

**Issue by rlondner** [bigchaindb/bigchaindb#2016]
Are there any plans to support MongoDB 3.6 Change Streams instead of tailing the oplog as is the case [here](https://github.com/bigchaindb/bigchaindb/blob/0.9/bigchaindb/backend/mongodb/changefeed.py)?

This is now the recommended method to achieve real-time notifications.

**Comment by ttmc** [comment]
BigchainDB 2.0 works very differently from earlier versions, and one of the consequences is that BigchainDB doesn't need to follow changes in MongoDB any more. To understand why, see my blog post https://blog.bigchaindb.com/bigchaindb-2-0-is-byzantine-fault-tolerant-5ffdac96bc44
