### ISSUE TITLE
404 - HTTP Error: Requested page not reachable

### ISSUE THREAD

**Issue by DalderupMaurice** [bigchaindb/bigchaindb#2022]
* BigchainDB version: 1.1.0 -> 1.1.3 (Tried both)
* Operating System: Mac OSX
* Deployment Type: `Local Docker & test.bigchaindb.com`
  * network type `test`
  * `bdbUri = 'http://0.0.0.0:9984/api/v1/' || 'https://test.bigchaindb.com/api/v1/transactions';`
  * Code based off these: https://docs.bigchaindb.com/projects/js-driver/en/latest/index.html && https://github.com/bigchaindb/bigchaindb-react-redux-boilerplate/blob/master/src/bdb.js
* BigchainDB driver: `yes`
  * driver type `js@3.2.0`

### Description

``
{ message: 'HTTP Error: Requested page not reachable',
  status: '400 BAD REQUEST',
  requestURI: 'http://0.0.0.0:9984/api/v1/transactions' }
``

### Steps to Reproduce

Happens at random when trying to CREATE and/or TRANSFER a transaction

### What I Did

I call the following functions in order, which triggers a 404 at random times (really inconsistent)

```javascript
export function postAsset(preparedAsset, connection, returnFullAsset) {
  // Post transaction to BC
  return new Promise((resolve, reject) => {
    connection.postTransaction(preparedAsset)
    // Fetch Tx
      .then(() => connection.pollStatusAndFetchTransaction(preparedAsset.id))
      .then(tx => {
        returnFullAsset ? resolve(tx) : resolve(tx.id);
      })
      .catch(err => {
        reject(err)
      });
  });
}



export const transferAsset = (txId, keypairTo, metaData, keypairFrom, connection) => {
  return new Promise((resolve, reject) => {
    connection.getTransaction(txId)
      .then(tx => {
        const txTransfer = driver.Transaction.makeTransferTransaction(
          [{tx, output_index: 0}],
          [
            driver.Transaction.makeOutput(
              driver.Transaction.makeEd25519Condition(keypairTo.publicKey)
            )
          ],
          metaData
        );

        const txTransferSigned = Transaction.signTransaction(txTransfer, keypairFrom.privateKey);
        // send it off to BigchainDB
        return connection.postTransaction(txTransferSigned)
          .then(() => {
            connection.pollStatusAndFetchTransaction(txTransferSigned.id);
          })
          .then(() => resolve(txTransferSigned))
          .catch(err => reject(err));
      })
      .catch(err => reject(err));
  });
};
```

**Comment by manolodewiner** [comment]
Could you please have a look at the logs? 
Do you get `HTTP API error: 400 - POST:/api/v1/transactions - Invalid transaction (TransactionNotInValidBlock): input xxxxxxxxxxx does not exist in a valid block `.
If yes, that means that the `create` transaction was not include it in a block yet, so you can not spend it. You will have to wait until that happens

**Comment by manolodewiner** [comment]
Please use async/await functions to avoid those kind of problems:
https://github.com/bigchaindb/project-jannowitz/blob/code-examples/js-examples/create_transfer.js
