### ISSUE TITLE
Invalid transaction (InvalidHash) isn't equal to the hash of its body, i.e. it's not valid

### ISSUE THREAD

**Issue by moskalyk** [bigchaindb/bigchaindb#2026]
* BigchainDB version: 1.4.0.dev
* Operating System: MacOS Sierra
* Deployment Type: `Docker`
  * If you are using IPDB, please specify your network type `test`
  and the `bdb_url(BigchainDB URL)` you are using.
  * For every other type of deployment, please specify the documentation/instructions
  you are following.
* BigchainDB driver: `yes`
  * If using a driver please specify, driver type `python`
  and version.

### Description
I was attempting to send a transaction to the database, however I keep reciving this error.

### Steps to Reproduce
Was Following the exact same code: https://docs.bigchaindb.com/projects/py-driver/en/latest/usage.html

### What I Did

```

fulfilled_creation_tx = bdb.transactions.fulfill(prepared_creation_tx, private_keys=alice.private_key)
sent_creation_tx = bdb.transactions.send(fulfilled_creation_tx)

[ERROR] (bigchaindb.web.views.base) HTTP API error: 400 - POST:/api/v1/transactions/ - Invalid transaction (InvalidHash): The transaction's id '03092f963ef6c65038405e53f6d660a5b7362961f617f7c227d5c8a9961d34e5' isn't equal to the hash of its body, i.e. it's not valid. (webapi     - pid: 46)
```

**Comment by codegeschrei** [comment]
Hey @moskalyk 
Can you please give me your python driver version?

**Comment by moskalyk** [comment]
@codegeschrei from my requirements.txt 
```
BigchainDB==1.0.1
bigchaindb-driver==0.4.1
```

**Comment by Baisang** [comment]
ran into and fixed this issue by pinning the docker image bigchaindb version to 1.0.1, matching the one in `requirements.txt`

**Comment by codegeschrei** [comment]
I'm going to close this for now. 
@moskalyk if you have any further questions feel free to reopen this issue, open a new issue or join our Gitter channel :)

**Comment by moskalyk** [comment]
Thanks for the help @codegeschrei and @Baisang . For the time being I had moved on from using bigchaindb for the project I was working on, but will be looking to revisit in the future. Thanks for all the work, the project is exciting!

**Comment by codegeschrei** [comment]
Cool, we look forward to see you again!
