### ISSUE TITLE
Restricted-Access Private Network without Using 3scale

### ISSUE THREAD

**Issue by ttmc** [bigchaindb/bigchaindb#2035]
### Problem

The current production deployment template uses 3scale to ensure that POST requests to the network (from anyone) only get through if they come from a client with an account (app_id and app_key).

A private network wants to launch so that _all_ HTTP requests (POST and GET) sent to the nodes in the network get be dropped unless they come from a small set of known (and unchanging) clients/sources. They don't need 3scale. They will want a modified version of the production deployment template.

### Potential Solution

- Generate a special HTTP header and share it with all the known clients/sources.
- Have a single NGINX in each node which checks for that HTTP header value. If it's present, let the request pass through to the network. (HTTP headers are encrypted if HTTPS is used.)

Are there other simpler or better options?

**Comment by shahbazn** [comment]
> Generate a special HTTP header and share it with all the known clients/sources.
This can work and this actually how 3scale hosted solution works by sharing a secrete among server/client and verifying that secrete on each request.
