### ISSUE TITLE
Add a command line argument to print the version with `bigchaindb` cli

### ISSUE THREAD

**Issue by r-marques** [bigchaindb/bigchaindb#204]
Add a command line argument to print the version

```bash
$ bigchaindb --version
bigchaindb 0.1.5
$ bigchaindb -v
bigchaindb 0.1.5
```
Maybe this issue is a good place to resolve #70

**Comment by diminator** [comment]
v0.2.1?

**Comment by ttmc** [comment]
I wonder if this would be a good time to resolve Issue #70 as well (i.e. have one place/method of setting the current version number).
