### ISSUE TITLE
Problem: some ports are not exposed/published by docker-compose

### ISSUE THREAD

**Issue by sbellem** [bigchaindb/bigchaindb#2041]
### Problem
When troubleshooting it may be useful to ping or query a container from the host machine. In order to do so, ports need to be exposed, so that they can be mapped to some arbitrary port on the host.

### Solution
Expose the ports, using the `ports` field so that the ports are published on the host.

### Documentation
https://docs.docker.com/compose/compose-file/#ports

**Comment by shahbazn** [comment]
While we are exposing more port it might be a good idea to change the port format "CONTAINER:HOST" at-least for the bdb service since its more convenient to just go with 9984 port on the host.
Ref: https://docs.docker.com/compose/compose-file/#ports
>Either specify both ports (HOST:CONTAINER), or just the container port (an ephemeral host port is chosen).

**Comment by sbellem** [comment]
For development purposes ephemeral ports are desirable because one may need to spin up multiple containers for the same service (build/image), and if ports are mapped on the host then there will be conflicts, such as:

```bash
Error response from daemon: driver failed programming external connectivity on endpoint bigchaindb_bdb_run_2 (9d6ae2fe02cfabf8d87d0e7207ebc3eae0b771c68dd99aba015e34ac926dcd87): Bind for 0.0.0.0:9984 failed: port is already allocated
```
