### ISSUE TITLE
Exit gracefully if rethinkdb is not running

### ISSUE THREAD

**Issue by r-marques** [bigchaindb/bigchaindb#205]
When using bigchaindb and trying to perform some database operations, if rethinkdb is not running bigchaindb will exit some stack trace and the exceptions thrown by the rethinkdb python driver.

We should check if rethinkdb is running running bigchaindb commands and if not exit if a message saying that rethinkdb is not running.

**Comment by vrde** [comment]
BigchainDB 2.0 doesn't support RethinkDB out of the box.
