### ISSUE TITLE
HTTP API docs built locally from tendermint branch differ from those built by ReadTheDocs from tendermint branch

### ISSUE THREAD

**Issue by ttmc** [bigchaindb/bigchaindb#2072]
If I checkout the `tendermint` branch locally and build the server docs, i.e.

```bash
$ git checkout tendermint
$ git pull
$ cd docs/server
$ make clean
$ make html
```

and I compare the locally-generated HTTP API docs to the same HTTP API docs generated by ReadTheDocs (from the `tendermint` branch), they differ.

Specifically, the example HTTP requests and responses differ throughout the page. It's as if the examples generated by ReadTheDocs were generated using BigchainDB v1.3.0, rather than the latest code in the `tendermint` branch.

Here's a specific example: the very first example, namely the HTTP response from the BigchainDB Root URL. Locally, I get:

```http
HTTP/1.1 200 OK
Content-Type: application/json

{
  "api": {
    "v1": {
      "assets": "/api/v1/assets/",
      "docs": "https://docs.bigchaindb.com/projects/server/en/v1.4.0.dev/http-client-server-api.html",
      "metadata": "/api/v1/metadata/",
      "outputs": "/api/v1/outputs/",
      "streams": "ws://localhost:9985/api/v1/streams/valid_transactions",
      "transactions": "/api/v1/transactions/"
    }
  },
  "docs": "https://docs.bigchaindb.com/projects/server/en/v1.4.0.dev/",
  "keyring": [
    "6qHyZew94NMmUTYyHnkZsB8cxJYuRNEiEpXHe1ih9QX3",
    "AdDuyrTyjrDt935YnFu4VBCVDhHtY2Y6rcy7x2TFeiRi"
  ],
  "public_key": "NC8c8rYcAhyKVpx1PCV65CBmyq4YUbLysy3Rqrg8L8mz",
  "software": "BigchainDB",
  "version": "1.4.0.dev"
}
```

but if I go to the same page which ReadTheDocs generated from the `tenermint` branch, i.e. at https://docs.bigchaindb.com/projects/server/en/tendermint/http-client-server-api.html 
I see this:

```http
HTTP/1.1 200 OK
Content-Type: application/json

{
  "api": {
    "v1": {
      "assets": "/api/v1/assets/",
      "docs": "https://docs.bigchaindb.com/projects/server/en/v1.3.0/http-client-server-api.html",
      "outputs": "/api/v1/outputs/",
      "statuses": "/api/v1/statuses/",
      "streams": "ws://localhost:9985/api/v1/streams/valid_transactions",
      "transactions": "/api/v1/transactions/"
    }
  },
  "docs": "https://docs.bigchaindb.com/projects/server/en/v1.3.0/",
  "keyring": [
    "6qHyZew94NMmUTYyHnkZsB8cxJYuRNEiEpXHe1ih9QX3",
    "AdDuyrTyjrDt935YnFu4VBCVDhHtY2Y6rcy7x2TFeiRi"
  ],
  "public_key": "NC8c8rYcAhyKVpx1PCV65CBmyq4YUbLysy3Rqrg8L8mz",
  "software": "BigchainDB",
  "version": "1.3.0"
}
```

Note how the `"version"` is `"1.3.0"`, `"statuses"` is still there, and `"metadata"` is absent: just like the response when using BigchianDB version 1.3.0!

The example HTTP requests and responses are all generated by the helper script in `docs/server/generate_http_server_api_documentation.py` It creates a client using:

```python
client = server.create_app().test_client()
```

where `server` comes from the import at the top, i.e.

```python
from bigchaindb.web import server
```

I think that's where the problem is, but I'm not familiar enough with what's going on with the "old code" versus the code in the new `tendermint/` directory.

Maybe it can't find `bigchaindb.web` locally, so it uses the `bigchaindb` package from PyPI, which is currently version 1.3.0.

**Comment by kansi** [comment]
@ttmc there is a `docs/server/requirements.txt` which contains the following
```
...
sphinxcontrib-httpdomain>=1.5.0
pyyaml>=3.12
bigchaindb
```
Maybe this is the reason its installing older version of bigchaindb?

**Comment by ttmc** [comment]
Aha! Yes, that `bigchaindb` should probably be `-e ../../` to be clear that we want it to install the _local_ bigchaindb, not the one in PyPI. I'll create a pull request to make this change.

**Comment by kansi** [comment]
@ttmc Maybe that is not required as we are now using [`.readthedocs.yml`](https://github.com/bigchaindb/bigchaindb/blob/tendermint/.readthedocs.yml#L6) and it uses [`pip_install: true`](https://docs.readthedocs.io/en/latest/yaml-config.html#python-pip-install)
