### ISSUE TITLE
Make container ports static for k8s deployment templates

### ISSUE THREAD

**Issue by shahbazn** [bigchaindb/bigchaindb#2077]
* BigchainDB version: `tendermint`
* Deployment Type: `k8s`
* BigchainDB driver: `no`

### Description
Currently we manually configure ports in deployment and service files for k8s deployment e.g [here](https://github.com/bigchaindb/bigchaindb/blob/d5f45d4094a3e3671cf55722b9632d083ffccf56/k8s/bigchaindb/bigchaindb-dep.yaml#L123). Instead these ports should be constant since these are always the same for each deployment

**Comment by ttmc** [comment]
@shahbazn I guess this issue can be closed? (GitHub only auto-closes issues if the pull request gets merged into the `master` branch [i.e. this repository's default branch]).
