### ISSUE TITLE
stale.py Node(stm.check_transactions) is crushing

### ISSUE THREAD

**Issue by yrozhkov** [bigchaindb/bigchaindb#2085]
* BigchainDB version: 1.3
* Operating System: linux Mesos
* Deployment Type: Docker
* BigchainDB driver: yes
* If using a driver please specify, driver type java 0.1
.
I am sending around  100 transactions  per second to bigchaindb server running inside docker
After several minutes I see 2 [bigchaindb] defunct processes
and transactions are not leaving backlog

There is no error messages

**Comment by yrozhkov** [comment]
After further debugging I see that Node which has check_transactions is crushing.

**Comment by codegeschrei** [comment]
hey @yrozhkov 
we have new versions of the driver and server, can you use the news ones and try again?
The server is ```v2.0.0a1``` and the js-driver is ```v4.0.0```

**Comment by ttmc** [comment]
This issue arose with BigchainDB version 1.3. The latest version, BigchainDB 2.0.0x, works [very differently](https://blog.bigchaindb.com/bigchaindb-2-0-is-byzantine-fault-tolerant-5ffdac96bc44). For example, BigchainDB no longer maintains a backlog of transactions. (Something similar is maintained by Tendermint, but that's not our concern.) Version 1.3 wasn't an LTS release so we're not supporting it. I'm closing this issue.
