### ISSUE TITLE
Migrate cli for Tendermint

### ISSUE THREAD

**Issue by muawiakh** [bigchaindb/bigchaindb#2087]
With Tendermint integration some of the cli sub-commands have been rendered obsolete. It would be only appropriate to remove those sub-commands.

- [x] Submit a proposal on how this problem will be handled.
- [x] Implement the accepted proposal.(Core changes)
- [x] Update the documentation.

**Comment by muawiakh** [comment]
`Submit a proposal on how this problem will be handled.` is taken care of by #1976

**Comment by ttmc** [comment]
@muawiakh - Can this issue be closed? - "Migrate cli for Tendermint" -  #2087

**Comment by muawiakh** [comment]
Yes.
