### ISSUE TITLE
Problem: bigchaindb can not run successfully

### ISSUE THREAD

**Issue by beyondgcy** [bigchaindb/bigchaindb#2110]
* BigchainDB version: bigchaindb 1.0.1
* Operating System: ubuntu 16.04 
* Deployment Type: Host
* BigchainDB driver: yes 
                     python diver-0.4.1

### Description

I installed bigchaindb server yesterday and ran it very well.
But today i can't run it.

### Steps to Reproduce
The first terminal printscreen:
![2018-03-01 21-49-15](https://user-images.githubusercontent.com/34889975/36847995-e7c4d98c-1d9a-11e8-9125-0291c2ad8ca6.png)
![2018-03-01 21-49-42](https://user-images.githubusercontent.com/34889975/36848009-efc35848-1d9a-11e8-948e-a9ca828bf159.png)
![2018-03-01 21-50-24](https://user-images.githubusercontent.com/34889975/36848015-f3dda2f8-1d9a-11e8-918a-2fbcb03b8b82.png)
![2018-03-01 21-50-28](https://user-images.githubusercontent.com/34889975/36848019-f720ca08-1d9a-11e8-8fe8-6e75c8a9df0e.png)
The second:
![2018-03-01 21-51-35](https://user-images.githubusercontent.com/34889975/36848030-0027a86a-1d9b-11e8-9755-427dfc0d8041.png)

The errors log:
[bigchaindb-errors.log](https://github.com/bigchaindb/bigchaindb/files/1771385/bigchaindb-errors.log)

### What I Did
I did it as follows:
1,  $ sudo mkdir -p /data/db
2,  $ sudo chmod -R 700 /data/db
3,  $ sudo mongod --replSet=bigchain-rs
4,  open a new terminal 
5,  $ bigchaindb -y configure mongodb
6,  $ bigchaindb start

**Comment by manolodewiner** [comment]
Hi @beyondgcy , which version are you using? Please make sure to use the latest version (1.3) of BigchainDB. Can you just try again removing every data and configuration with:

```
Remove all of the config files for all of the nodes

# sudo rm -rf /data/db

# sudo rm -f /data/configdb
```

**Comment by beyondgcy** [comment]
thank you very much!@manolodewiner
It worked when i upgrade to version1.3
