### ISSUE TITLE
Validating the same transaction twice?

### ISSUE THREAD

**Issue by judenaveenraj** [bigchaindb/bigchaindb#2124]
In the process of trying to minimise the time taken to send a transaction to bigchaindb, I came across the fact that each transaction is validated twice.
1. Once when the transaction is sent via POST /transactions.
2. Once when the block.py pipeline processes the transaction in the block.

In (1) the transaction is validated before writing it to the backlog.
In (2) the transaction is validated and deleted from the block in case it is invalid.

So do we really have to validate it at both times? Can we avoid (1) and only have (2)? It would greatly increase write throughput to the backlog.

Pardon me if I'm wrong about this. This is my first time venturing into bigchaindb.

**Comment by ttmc** [comment]
It all changes in the next release, coming out this month. That code currently lives in the `tendermint` branch but should become the `master` branch code soon.

Every node must check every transaction, but only once. If some nodes are down, it's okay, so long as we can get a 2/3 vote, things can progress.
