### ISSUE TITLE
Python ORM for BigchainDB/RethinkDB

### ISSUE THREAD

**Issue by diminator** [bigchaindb/bigchaindb#214]
# Python ORM

Relates to #98 
## Motivation

End-users and devs that use BigchainDB want to have the look-and-feel of a queryable database.
Since RethinkDB is a document store, there are no schema's nor schema enforcement rules.

There are many [third-party ORM implementations for RethinkDB](https://rethinkdb.com/docs/frameworks-and-libraries/). In contrast with the Javascript/Node ORMs, the Python ORMs are typically unmaintained or incomplete.

Thankfully, RethinkDB provides ReQL to facilitate this process.

BigchainDB provides a chain of transactions, which can be regarded as subsequent updates on an object/asset. However, many times people are just interested in the current state of the objects (~UTXO database) and want to query the asset properties as given by the payload .
### Generic ORM requirements

The [Django Models](https://docs.djangoproject.com/ja/1.9/topics/db/) provide a good basis for what's needed in a python ORM:
- Define models with schemas
- Support CRUD operations on models
- Models have field primitives that may have constraints
- Relationships between models: 
  - Table Joins
  - x-to-x relationships
  - foreignkeys
  - ...
- Extensive queryability: 
  - filters
  - selectors
  - distincts
  - exclusions
  - ...
- Schema migrations
- Signals: pre and post operations
- Data aggregation
- Object managers and serialization
### BigchainDB-specific requirements
- Schema template for BigchainDB transactions:
  - Conditions/Fulfillments: provided by BigchainDB ORM framework
  - Payload: defined by user
- Chained assets:
  - Extract provenance chain/history
  - Get UTXO
  - Merge history updates
## Possible Implementation(s)

WIP
## Difficulties

WIP
## Resources
- [remodel](https://github.com/linkyndy/remodel)
- [thinky](https://github.com/neumino/thinky)

**Comment by r-marques** [comment]
Replace `CRUD` with `CRU`

The proposal seems good. We need to agree on a minimum set of features to implement and then build from there. Looking at use cases would be a good place to start.

**Comment by r-marques** [comment]
another reference would be [sqlalchemy](http://www.sqlalchemy.org/)

**Comment by ttmc** [comment]
Once we have a more stable client-server protocol, we can think about tools and libraries to make it easier for developers to write client-side applications. An "ORM" is one option, but there are others.

BigchainDB's current client-server protocol is akin to that of ElasticSearch or CouchDB, i.e. HTTP with JSON in the message body. (It's _not_ like ReQL wire protocol or Postgres wire protocol.) What sorts of libraries and tools exist to make it easier to build applications that talk to ElasticSearch or CouchDB? Can we make something similar for BigchainDB?

@sbellem mentioned **Elasticsearch DSL**:  https://github.com/elastic/elasticsearch-dsl-py

**Comment by sbellem** [comment]
Has there been some thoughts around BigchainDB having its own query language, e.g.: **chainQL**?  The query language would allow one to easily, and efficiently query BigchainDB for transactions, blocks, and votes, etc.

**Comment by ttmc** [comment]
I don't think we discussed a whole new query language, but see issue #287

**Comment by sbellem** [comment]
Ah ok thanks!

**Comment by TimDaub** [comment]
In #820 I outlined how an ORM could be implemented.

**Comment by trentmc** [comment]
Maybe helpful: ming.

"Ming is an Object Document Mapper (like an ORM but for Document based databases), for MongoDB. Ming extends pymongo providing declarative models, schema validation, schema evolution, more."
http://ming.readthedocs.io/en/latest/

**Comment by TimDaub** [comment]
Closing as we now have: https://github.com/bigchaindb/js-driver-orm

**Comment by JonathanCalderon** [comment]
Is there a ORM for python? Because I'm trying to do an append to an asset in python and I don't find any documentation. I know that an append is just a transfer to the same owner, however I do not find how one can update parts of the asset in the process.

**Comment by ttmc** [comment]
@JonathanCalderon There is no ORM for Python. A TRANSFER transaction has a `"metadata"` section which can be an arbitrary JSON string; you can put the updates to the asset in there.
