### ISSUE TITLE
'Too many request' error posting and fetching data from test network

### ISSUE THREAD

**Issue by manolodewiner** [bigchaindb/bigchaindb#2143]
* BigchainDB version: 1.3
* Operating System: Ubuntu
* Deployment Type: `test network`
  * If you are using IPDB, please specify your network type `test`
* BigchainDB driver: `JS Driver`

### Steps to Reproduce
Trying to post several records to the test network, the JS driver calls the `pollStatusAndFetchTransaction` and then I get the following error:

```
{ message: 'HTTP Error: Requested page not reachable',
  status: '429 Too Many Requests',
  requestURI: 'https://test.bigchaindb.com/api/v1/statuses?transaction_id=788e6bb8ebd32345696953aa12a24a8ea815fb674074870e52570936d080499d' }
```

**Comment by ttmc** [comment]
I think this issue was just NGINX doing what it was told to do, but we didn't all know about that. I asked around and it seems we can close it, so that's what I will do.
