### ISSUE TITLE
Remove "invalid_reason" from the vote model?

### ISSUE THREAD

**Issue by ttmc** [bigchaindb/bigchaindb#217]
The `vote` model (documented at http://bigchaindb.readthedocs.org/en/master/models.html#the-vote-model ) for the vote-on-a-block includes an "invalid_reason":

``` javascript
"invalid_reason": "<None|DOUBLE_SPEND|TRANSACTIONS_HASH_MISMATCH|NODES_PUBKEYS_MISMATCH",
```

but a block may contain several invalid transactions, each one invalid for a different reason, therefore it doesn't make sense to give only one reason for voting that a block is invalid.

A node stops looking at the transactions in a block once it encounters the first invalid transaction, so it doesn't even know if there are other invalid transactions in the block, or why they are invalid.

Alternatives to removing "invalid_reason":
- rename it "first_invalid_reason"
- replace it with "first_invalid_transaction_id" (but don't store the reason; anyone else can check the transaction to figure out the reason)

I prefer the latter option: replacing "invalid_reason" with "first_invalid_transaction".

**Comment by r-marques** [comment]
I also like the option of of `first_invalid_transaction`.
Another solution would be to just removed that field for now since we are not using it.

**Comment by diminator** [comment]
or one could provide a `set` or `dict` of reasons is there are multiple?

could be:
```
"invalid_reason": {
    "DOUBLE_SPEND": <count>/[<txid>], 
    "TRANSACTIONS_HASH_MISMATCH": <count>/[<txid>],
    ...
}
```

**Comment by r-marques** [comment]
Right now the transaction validation raises an exception at the first invalid condition so we don't have multiple reasons (this also increases performance). I guess that the txid would be enough for other nodes to just run he validator and find out what was wrong with the transaction.

**Comment by r-marques** [comment]
Since @libscott has been working on simplifying the models and adding schema validation now would be a good time to just remove it.
We can re-add it later if we have a use for it

**Comment by ttmc** [comment]
BigchainDB 2.0 works differently from BigchainDB 1.3 and earlier.

Invalid blocks are no longer a thing in BigchainDB 2.0. There is no need for a reason to be given for a block being invalid, since there is no block being invalid.

**Comment by isaacwalkercox** [comment]
> or one could provide a `set` or `dict` of reasons is there are multiple?
> 
> could be:
> 
> ```
> "invalid_reason": {
>     "DOUBLE_SPEND": <count>/[<txid>], 
>     "TRANSACTIONS_HASH_MISMATCH": <count>/[<txid>],
>     ...
> }
> ```

I realy like this option but if you are going to do that why not make it clearer with a tx id/reason keypair instead:
"invalid_reasons": [{ "TXID": "<TXID>", "reason": "<MISMATCH_HASH,DOUBLESPEND ETC.>"}]
