### ISSUE TITLE
400 BAD REQUEST when Post Transaction

### ISSUE THREAD

**Issue by DragonZelda** [bigchaindb/bigchaindb#2186]
I am using bigchaindb test server to do tutorial.
But when I try to create a Divisible Assets I am facing issue.
I am using the NodeJS javascript drive to run the function.

First I generate a user with 
PublicKey: "cQ4LrENQYB3EeEc2svUyvvKN6sqydnxs6U58NFhL8J6"
PrivateKey: "AmTJQBivKDAhZRnbYUZkkj4KDWH7cdN1pvpyUQe7sXgp"

So first I try to generate the tx with the following javascript:

>            
       const txCT = driver.Transaction.makeCreateTransaction({
            token: TokenName.toString(),
            number_tokens: TokenNumber
            },
            {
                description: MetaDataMessage,
                datetime: new Date().toString()
            },
            [driver.Transaction.makeOutput(driver.Transaction
                .makeEd25519Condition(TokenCreatorPublicKey), TokenNumber.toString())],
            TokenCreatorPublicKey
        );

Then I get the following output:

>            
       {
             "id":null,
             "operation":"CREATE",
             "outputs":[
                          {"condition":
                                       {"details":
                                                    {"type":"ed25519-sha-256",
                                                    "public_key":"cQ4LrENQYB3EeEc2svUyvvKN6sqydnxs6U58NFhL8J6"},
                                                    "uri":"ni:///sha-256;R4ZnldRlBSHEEZPwM_szE9i8vte0O6S_NaXYHxXIP1o?fpt=ed25519-sha-256&cost=131072"},
                          "amount":"1000000000",
                          "public_keys":["cQ4LrENQYB3EeEc2svUyvvKN6sqydnxs6U58NFhL8J6"]
                          }],
             "inputs":
                          [{"fulfillment":null,
                          "fulfills":null,
                          "owners_before":["cQ4LrENQYB3EeEc2svUyvvKN6sqydnxs6U58NFhL8J6"]}],
             "metadata":{"description":"Version 6",
                                       "datetime":"Mon Apr 09 2018 11:39:27 GMT+0800 (Malay Peninsula Standard Time)"},
             "asset":{
                          "data":{"token":"Testing TT (Tutorial Tokens)",
                          "number_tokens":1000000000}},
             "version":"2.0"}

Then I post the transaction to the server:

> 
            const txSignedCT = driver.Transaction
                        .signTransaction(txCT, TokenCreatorPrivateKey);

But I get the following response:
{ message: 'HTTP Error: Requested page not reachable',
  status: '400 BAD REQUEST',
  requestURI: 'https://test.bigchaindb.com/api/v1/transactions' }

It is same with other post transaction if it involve Divisible Asset like Transfer Token or Combination.
It all stuck at this part. I am not sure it is my code problem or the server issue.
But I check my code it is totally follow the tutorial format.

**Comment by ttmc** [comment]
@DragonZelda The BigchainDB Testnet is currently running BigchainDB Server version 1.3.0, which only accepts transactions with `"version":"1.0"`. It seems you posted a version 2.0 transaction, which is what BigchainDB 2.0+ accepts.

We plan to upgrade the BigchainDB Testnet run BigchainDB Server 2.0.0 Alpha later today (around 12:00 CEST, Berlin time on 9 April 2018). Maybe just wait until we've done the upgrade and try again? Another option would be to get an older version of the driver that works with BigchainDB Server 1.3.0.

**Comment by DragonZelda** [comment]
I have updated the latest npm bigchaindb-driver.
I suppose the test server has been fully upgraded.
But after I try, the result become the following:

{ message: 'HTTP Error: Requested page not reachable',
  status: '502 Bad Gateway',
  requestURI: 'https://test.bigchaindb.com/api/v1/transactions' }

It still stuck at the post transaction signature part.
Any advice? Thank you very much.

**Comment by ttmc** [comment]
The BigchainDB Testnet was upgraded to run BigchainDB 2.0.0 Alpha on Monday, but we've been having intermittent issues with it, and sometimes the response to a proper HTTP request can be 502 Bad Gateway. We're working on resolving those issues.

**Comment by DragonZelda** [comment]
I created a Token (Asset ID: 90722b1691e81335168711c91d4298666656f4d1889680dcb71a1c3266ecbc86).

I create a user for assign.
PublicKey: AwLZ8dGPDGZZgpRKE6Z2pesoC296gKiz4RcsMkumJhZv
PrivateKey: BzcoJ1ECJPY76sy4a8jYSaAHCQKuSe6PgSe2yK5qvD53

Then I assign to this user 10000 tokens.
After that I assign to a same user 10000 tokens again.
Because this user has 2 transactions, so I combine this 2 transactions to the same user and it become 1 transaction which has 20000 tokens. (Transaction ID: 81a891cb4b87e84ae0d866194db33a088a335bfa8f700fa9d088efa7c969194e).

Then I try to assign this combine transaction to another user.

Another user info:
PublicKey: 8sYhk6rmpPU3KdP3fj3PoEFTm7K9CFAd3sjToRifZFgA
PrivateKey: FiaRNKGY7Fxg4h1a84iYAoFZA6yfNZPAiScWBd66Sc9d

I generate the signedTransferAssign as below:

> {"id":"54f590cb8b8c2c4d03a66fe67fa968c940f4d2e30854a6fd26254a6c9c55a189","operation":"TRANSFER","outputs":[{"condition":{"details":{"type":"ed25519-sha-256","public_key":"AwLZ8dGPDGZZgpRKE6Z2pesoC296gKiz4RcsMkumJhZv"},"uri":"ni:///sha-256;qmCQ1g-eO3G1rLPBGk2xdIiyhST8Xi18yD4uz4gxOaA?fpt=ed25519-sha-256&cost=131072"},"amount":"0","public_keys":["AwLZ8dGPDGZZgpRKE6Z2pesoC296gKiz4RcsMkumJhZv"]},{"condition":{"details":{"type":"ed25519-sha-256","public_key":"8sYhk6rmpPU3KdP3fj3PoEFTm7K9CFAd3sjToRifZFgA"},"uri":"ni:///sha-256;sX0mgOhSe3FE8A7u718ZXWZ3trvnRf08K9_B357ASZo?fpt=ed25519-sha-256&cost=131072"},"amount":"20000","public_keys":["8sYhk6rmpPU3KdP3fj3PoEFTm7K9CFAd3sjToRifZFgA"]}],"inputs":[{"fulfillment":"pGSAIJOkp-IxX821AXGF40-HOqnfF0c40hUCrFoRp0Nf-Du9gUAUfMAZ-YeuQAGTkAor1CjpxnkIzI12i8nhRy-nzs6a6KNCqGV6A-FUiQ_tNuzmVIos7OiRZdcA-0IwiPRQtIkN","fulfills":{"output_index":0,"transaction_id":"81a891cb4b87e84ae0d866194db33a088a335bfa8f700fa9d088efa7c969194e"},"owners_before":["AwLZ8dGPDGZZgpRKE6Z2pesoC296gKiz4RcsMkumJhZv"]}],"metadata":{"transfer_to":"ender","tokens_assign":"20000","tokens_left":"0"},"asset":{"id":"90722b1691e81335168711c91d4298666656f4d1889680dcb71a1c3266ecbc86"},"version":"2.0"}

and use function conn.postTransactionCommit(signedTransferAssign) but the server response:

{ message: 'HTTP Error: Requested page not reachable',
  status: '400 BAD REQUEST',
  requestURI: 'https://test.bigchaindb.com/api/v1/transactions?mode=commit' }

**Comment by muawiakh** [comment]
Maybe, I am missing something, so starting with a basic @Eurythmax @DragonZelda are you guys using `app_id` and `app_key` in the headers?

**Comment by DragonZelda** [comment]
Yes. The following is the code in NodeJS:

var http = require('http');
var url = require('url');

const driver = require('bigchaindb-driver');
const conn = new driver.Connection('https://test.bigchaindb.com/api/v1/', { 
    app_id: '2f2d99a5',
    app_key: 'b5e4420818e3d71fd135640e98e1c7e0'
});

**Comment by muawiakh** [comment]
Can you send over the snippet that you are using? Or the steps to reproduce? I think @jernejpregelj and @manolodewiner might also have some thoughts. Since, they maintain the `js-driver` as well.

**Comment by jernejpregelj** [comment]
@DragonZelda I run your code with including "AssignToken" and it went trough without a problem. Please try to repeat the process and let me know if you still have a problem.

**Comment by DragonZelda** [comment]
@jernejpregelj I repeat the process and yes it still has the same issue. Please note that the error will appear after first time transfer. 

For example UserA create the token, then assign the token to UserB, no problem at this step. 

But if UserB assign the token he received to UserA or other user like UserC, then error 400 will appear:

{ message: 'HTTP Error: Requested page not reachable',
  status: '400 BAD REQUEST',
  requestURI: 'https://test.bigchaindb.com:443/api/v1/transactions?mode=commit' }
