### ISSUE TITLE
Cannot follow the tutorial ; raise exc_cls(response.status_code, text, json) bigchaindb_driver.exceptions.BadRequest

### ISSUE THREAD

**Issue by spider-hand** [bigchaindb/bigchaindb#2187]
I'm new to BigchainDB and I just followed the python driver tutorial on the documentation and when I followed Divisible Assets part, https://docs.bigchaindb.com/projects/py-driver/en/latest/usage.html, this error occured. This error occured when I did `sent_transfer_tx = bdb.transactions.send(fulfilled_transfer_tx)`.
The error message is like this

```
File "test.py", line 223, in <module>
    sent_transfer_tx = bdb.transactions.send(fulfilled_transfer_tx)
  File "/usr/local/lib/python3.5/dist-packages/bigchaindb_driver/driver.py", line 319, in send
    method='POST', path=self.path, json=transaction, headers=headers)
  File "/usr/local/lib/python3.5/dist-packages/bigchaindb_driver/transport.py", line 58, in forward_request
    headers=headers,
  File "/usr/local/lib/python3.5/dist-packages/bigchaindb_driver/connection.py", line 57, in request
    raise exc_cls(response.status_code, text, json)
bigchaindb_driver.exceptions.BadRequest: (400, '{\n  "message": "Invalid transaction (TransactionNotInValidBlock): input `f5ad3daa0dc3a530d63d7e2b4439807f359191315456edb3f5793d8e1df74327` does not exist in a valid block", \n  "status": 400\n}\n', {'message': 'Invalid transaction (TransactionNotInValidBlock): input `f5ad3daa0dc3a530d63d7e2b4439807f359191315456edb3f5793d8e1df74327` does not exist in a valid block', 'status': 400})
```
My codes should be just the same as the tutorial's but I will show the `fullfilled_token` dictionary just in case.

```
{'outputs': [{'amount': '2', 'public_keys': ['38SkeQUWFVPHStHZSuJ77NgBNfVVuMCqWjwcECUEgJcm'], 'condition': {'details': {'type': 'ed25519-sha-256', 'public_key': '38SkeQUWFVPHStHZSuJ77NgBNfVVuMCqWjwcECUEgJcm'}, 'uri': 'ni:///sha-256;K-jMivpYM_1B01UFSAW61wibuoKoRO-zbg-iqPlK27Q?fpt=ed25519-sha-256&cost=131072'}}, {'amount': '8', 'public_keys': ['HewA718FH7nV634EYJEXL3cpsBbeh5Szc39AzqQz8HaE'], 'condition': {'details': {'type': 'ed25519-sha-256', 'public_key': 'HewA718FH7nV634EYJEXL3cpsBbeh5Szc39AzqQz8HaE'}, 'uri': 'ni:///sha-256;9j7aDEIg5v6uPJ7wVcYacD6sbMy1AXItSjyq6vze-sE?fpt=ed25519-sha-256&cost=131072'}}], 'inputs': [{'fulfills': {'transaction_id': '2ce0c6711b1398f70ea1ee47bcbbfe00cfda1cea9ef97b08cfbea2450ba6dfcc', 'output_index': 0}, 'owners_before': ['HewA718FH7nV634EYJEXL3cpsBbeh5Szc39AzqQz8HaE'], 'fulfillment': 'pGSAIPdyt1psnXVTgpYDXwRjVm7oJ4ch3_HJQHSkNVklnZZPgUDPPfIgrG9Bdw36ejpDmEJw9OY7HTxCIVkouHSx3hScXcKQZkRmCFOUBBQZn_oc6OpPngwnfdRIN7o1QyDOBuYK'}], 'metadata': None, 'version': '1.0', 'id': '5aa90ef9c1bbb7f5694fa121a8709f7029b8f29c7d794ecf7cf2dc5cf7dde143', 'asset': {'id': '2ce0c6711b1398f70ea1ee47bcbbfe00cfda1cea9ef97b08cfbea2450ba6dfcc'}, 'operation': 'TRANSFER'}
```

How can I fix this error?
Sorry if I'm making a dumb mistake.

**Comment by codegeschrei** [comment]
Hey @spider-hand 
Can you tell me which versions you are using for BigchainDB and the driver?

**Comment by spider-hand** [comment]
Hi, bigchaindb-driver-0.4.1 and BigchainDB-1.3.0 and I upgraded them to the latest version.  (BigchainDB-2.0.0a1 and bigchaindb-driver-0.5.0a1)
But now I cannot even start bigchaindb.  When I do `bigchaindb start`, 

```
[2018-04-09 11:23:19] [INFO] (bigchaindb.commands.bigchaindb) Starting BigchainDB main process. (MainProcess - pid: 806)
Traceback (most recent call last):
  File "/usr/local/bin/bigchaindb", line 11, in <module>
    load_entry_point('BigchainDB==2.0.0a1', 'console_scripts', 'bigchaindb')()
  File "/usr/local/lib/python3.5/dist-packages/bigchaindb/commands/bigchaindb.py", line 245, in main
    utils.start(create_parser(), sys.argv[1:], globals())
  File "/usr/local/lib/python3.5/dist-packages/bigchaindb/commands/utils.py", line 160, in start
    return func(args)
  File "/usr/local/lib/python3.5/dist-packages/bigchaindb/commands/utils.py", line 45, in configure
    command(args)
  File "/usr/local/lib/python3.5/dist-packages/bigchaindb/commands/utils.py", line 72, in start_logging
    command(args)
  File "/usr/local/lib/python3.5/dist-packages/bigchaindb/commands/bigchaindb.py", line 181, in run_start
    from bigchaindb.tendermint.commands import start
  File "/usr/local/lib/python3.5/dist-packages/bigchaindb/tendermint/__init__.py", line 6, in <module>
    from bigchaindb.tendermint.lib import BigchainDB  # noqa
  File "/usr/local/lib/python3.5/dist-packages/bigchaindb/tendermint/lib.py", line 165
    f'''{utxo['transaction_id']}{utxo['output_index']}'''.encode()
                                                        ^
SyntaxError: invalid syntax
```
this error occured.

**Comment by codegeschrei** [comment]
I guess it is because you're using python 3.5
So you could either use python 3.6 instead or use the latest BigchainDB Server (master)

**Comment by spider-hand** [comment]
Thanks a lot. It works.

**Comment by codegeschrei** [comment]
Glad I could help :)

**Comment by spider-hand** [comment]
Actually the same error is still happening...
I meant I could start bigchaindb in python3.6 and I thought it works. Sorry.

```Traceback (most recent call last):
  File "test.py", line 223, in <module>
    sent_transfer_tx = bdb.transactions.send(fulfilled_transfer_tx)
  File "/usr/local/lib/python3.6/dist-packages/bigchaindb_driver/driver.py", line 319, in send
    method='POST', path=self.path, json=transaction, headers=headers)
  File "/usr/local/lib/python3.6/dist-packages/bigchaindb_driver/transport.py", line 58, in forward_request
    headers=headers,
  File "/usr/local/lib/python3.6/dist-packages/bigchaindb_driver/connection.py", line 57, in request
    raise exc_cls(response.status_code, text, json)
bigchaindb_driver.exceptions.BadRequest: (400, '{\n  "message": "Invalid transaction (TransactionNotInValidBlock): input `c9a8aaac19abc808e5e147dbdd6bd8148b39b31cb3058e231740c43da26eb797` does not exist in a valid block", \n  "status": 400\n}\n', {'message': 'Invalid transaction (TransactionNotInValidBlock): input `c9a8aaac19abc808e5e147dbdd6bd8148b39b31cb3058e231740c43da26eb797` does not exist in a valid block', 'status': 400})
```
I'm sure I upgraded to the latest.

**Comment by codegeschrei** [comment]
Are you using docker or did you start BigchainDB locally? 
I'm trying to reproduce your error

**Comment by spider-hand** [comment]
I'm using BigchainDB which is connected to MondoDB locally.

I was checking if there's a typo, difference between the tutorial and my codes but I'm sure they are just the same.

**Comment by codegeschrei** [comment]
Ok, since you didn't mention tendermint, I assume you didn't start it.
Can you check the documentation and see if you missed a step?
[Notes on Running a Local Dev Node as Processes](https://docs.bigchaindb.com/projects/contributing/en/latest/dev-setup-coding-and-contribution-process/run-node-as-processes.html#notes-on-running-a-local-dev-node-as-processes)
if you want to use docker instead:
[Notes on Running a Local Dev Node with Docker Compose](https://docs.bigchaindb.com/projects/contributing/en/latest/dev-setup-coding-and-contribution-process/run-node-with-docker-compose.html#notes-on-running-a-local-dev-node-with-docker-compose)

**Comment by spider-hand** [comment]
Actually yes, I didn't follow this step... I will follow the instruction. 
My way is just setting up mongodb and bigchaindb, bigchain_driver like  `sudo mongod --replSet=bigchain-rs`,  `bigchaindb start`, and run the program.
I will report after doing this step.

**Comment by spider-hand** [comment]
Actually I want you to try to reproduce my error just in case if you can because to do the way you suggested, the requirements are much more complicated than I do. 

Also I found another weird thing. When I used the older version of BigchainDB and driver, Querying assets part did work completely. But now when I set limit to parameter, it does query nothing.

 As I said, my way is just build mongoDB like `sudo mongod --replSet=bigchain-rs` and start bigchaindb `bigchaindb start` on other console, and run the program on the third console.
I want you to check if the same result comes out.

**Comment by spider-hand** [comment]
I will try your way as well but it takes time because I have trouble setting up Docker both on Ubuntu (Windows subsystem).

**Comment by codegeschrei** [comment]
I'm sorry but the new versions need Tendermint, there is no way to get it working with just BDB and mongoDB. Additional to that, when switching from older versions to the newer version there were some major changes which you can read about here: 
[Some HTTP API Changes in the Next Release](https://blog.bigchaindb.com/some-http-api-changes-in-the-next-release-49612a537b0c)
[Three Transaction Model Changes in the Next Release](https://blog.bigchaindb.com/three-transaction-model-changes-in-the-next-release-dadbac50094a)

**Comment by spider-hand** [comment]
okay no worries,  I will figure it out anyway. I will report after doing it. Thanks a lot.
