### ISSUE TITLE
bigchaindb configure: error: argument backend: invalid choice: 'mongodb'

### ISSUE THREAD

**Issue by ekanath25** [bigchaindb/bigchaindb#2189]
I have tried to install BigchainDB in windows10 using docker  getting the error like **"bigchaindb configure: error: argument backend: invalid choice: 'mongodb' (choose from 'localmongodb')"**
![docker error](https://user-images.githubusercontent.com/20681626/38506788-7756e534-3c38-11e8-8490-9909fe292c04.PNG)

**Comment by codegeschrei** [comment]
Hey @ekanath25 can you run the same command and use `localmongodb` instead of `mongodb`?

**Comment by ekanath25** [comment]
Thank you @codegeschrei . It worked
