### ISSUE TITLE
'utxos' collection created and updated but currently unused

### ISSUE THREAD

**Issue by ttmc** [bigchaindb/bigchaindb#2191]
The code in the current `master` branch creates and updates the 'utxos' collection, but we don't currently use that collection or its contents, so it and the code to maintain it could be removed for now.

**Comment by kansi** [comment]
@ttmc I was mistaken about the "updates" part. The collections are created but [never updated ](https://github.com/bigchaindb/bigchaindb/blob/master/bigchaindb/tendermint/lib.py#L90)

**Comment by ttmc** [comment]
If we're not spending any computing power on updates of the `utxos` collection, then I suppose there's no harm in having that collection sitting around doing nothing for now.

@kansi - You can close this issue if we're not spending any computing resources on updating the UTXO set or on the other way of computing the app hash.

**Comment by kansi** [comment]
Closing because compute power is not spent on UTXO
