### ISSUE TITLE
Problem: The BigchainDB Root URL is returning some wrong values

### ISSUE THREAD

**Issue by ttmc** [bigchaindb/bigchaindb#2192]
Today, with BigchainDB 2.0 Alpha, when one sends an HTTP request to the BigchainDB Root URL, such as https://test.bigchaindb.com/ they get back a response like:
```json
{
   "api": {
      "v1": {
         "assets": "/api/v1/assets/",
         "docs": "https://docs.bigchaindb.com/projects/server/en/v2.0.0a1/http-client-server-api.html",
         "metadata": "/api/v1/metadata/",
         "outputs": "/api/v1/outputs/",
         "streams": "wss://test.bigchaindb.com:443/api/v1/streams/valid_transactions",
         "transactions": "/api/v1/transactions/",
         "validators": "/api/v1/validators"
      }
   },
   "docs": "https://docs.bigchaindb.com/projects/server/en/v2.0.0a1/",
   "keyring": [],
   "public_key": null,
   "software": "BigchainDB",
   "version": "2.0.0a1"
}
```

The problem is that "keyring" and "public_key" used to be the BigchainDB node's keyring and public key, but BigchainDB doesn't have an associated keyring or public key any more --- the equivalents are all maintained by Tendermint now.

**Solution Idea 1** - Remove the "keyring" and "public_key" from the HTTP response.

**Solution Idea 2** - Change "keyring" to "tendermint_validators" and return the same list as the `GET /api/v1/validators` endpoint. Change the "public_key" to return the "tendermint_public_key".

**Comment by vrde** [comment]
> Solution Idea 2 - Change "keyring" to "tendermint_validators" and return the same list as the GET /api/v1/validators endpoint. Change the "public_key" to return the "tendermint_public_key".

I like this :dancer:

**Comment by ttmc** [comment]
@muawiakh If we go with *Solution 2*, then we would no longer need a special micro-service to get the Tendermint public key of a node. We could just send a GET request to the BigchainDB Root URL and look at the value of "tendermint_public_key".

**Comment by ttmc** [comment]
As noted above, we implemented Solution Idea 1, so this issue can be closed. We can always add more stuff to the response in the future, but a new issue can be created for that, if we decide it's important enough.
