### ISSUE TITLE
Bigchaindb installation Error using Vagrant in windows10 

### ISSUE THREAD

**Issue by ekanath25** [bigchaindb/bigchaindb#2214]
I am getting the error **"Message: Errno::ENOENT: No such file or directory @ rb_sysopen - configuration/hosts/all"** while installing bigchaindb using vagrant  

![vagrant error](https://user-images.githubusercontent.com/20681626/38821229-9697ae4e-41bd-11e8-9162-67140559be4e.PNG)

Please help

Thanks in advance

**Comment by ttmc** [comment]
We don't support installing BigchainDB using Vagrant on Windows 10.
