### ISSUE TITLE
bigchaindb_1   | standard_init_linux.go:190: exec user process caused "no such file or directory"

### ISSUE THREAD

**Issue by ekanath25** [bigchaindb/bigchaindb#2215]
I was trying to start bigchaindb and this error has occured when I did 
`docker-compose up bigchaindb`

```
$ docker-compose up bigchaindb
Starting bigchaindb_tendermint_1 ...
Starting bigchaindb_mongodb_1 ...
Starting bigchaindb_tendermint_1
Starting bigchaindb_tendermint_1 ... done
Starting bigchaindb_bigchaindb_1 ...
Starting bigchaindb_bigchaindb_1 ... done
Attaching to bigchaindb_bigchaindb_1
bigchaindb_1   | standard_init_linux.go:190: exec user process caused "no such file or directory"
bigchaindb_bigchaindb_1 exited with code 1
```

I am using Docker Toolbox windows
How to fix this Error?

**Comment by ttmc** [comment]
> I am using Docker Toolbox windows

Maybe try a more standard way of running BigchainDB Server, such as on an Linux machine or virtual machine. We don't test on windows.

**Comment by danacr** [comment]
I just did a clone of the latest git. Everything works fine in windows with docker-compose up bigchaindb, just make sure to share the right directories with docker on windows.

**Comment by CodeScriptum** [comment]
I've had the same issue on windows. it's related to line-ending auto conversion.
deleting the cloned repo and cloning again with  `core.autocrlf` set to `input` solved it.

`git clone https://github.com/bigchaindb/bigchaindb.git --config core.autocrlf=input`

**Comment by ttmc** [comment]
Thanks @danacr and @CodeScriptum!

@danacr Our `Makefile` also uses (or used to use) `docker-compose up bigchaindb` but that was causing problems. It seems the problems can be resolved by using:

```text
docker-compose up --no-deps mongodb tendermint bigchaindb
```

instead. For more background, see pull request #2341.

As for this issue, I think the above comments (by others) resolve it. Therefore I am closing this issue.

**Comment by ttmc** [comment]
@Gxz-NGU Thanks for the tip!
