### ISSUE TITLE
API Endpoint not accessible

### ISSUE THREAD

**Issue by dominic-healid** [bigchaindb/bigchaindb#2218]
I am able to setup and bigchaindb, rethinkdb in vagrant Ubuntu, however I can't access the API endpoint.

Please see attached screenshot.
![screen shot 2018-04-17 at 6 44 08 pm](https://user-images.githubusercontent.com/32921921/38865208-bcc4ea84-426f-11e8-979a-6591b938eec9.png)

**Comment by muawiakh** [comment]
Which version of BigchainDB are you using? Support for RethinkDB is removed from BigchainDB 2.0.0.

**Comment by dominic-healid** [comment]
I see, but I have 1.3.0 installed.

**Comment by dominic-healid** [comment]
@muawiakh, if I install BigchainDB using Docker and if I only have trial access on Docker EE and when the trial expired, should we still able to use BigchainDB?

**Comment by ttmc** [comment]
@dominic-healid You should run BigchainDB with MongoDB. It works with MongoDB Community Edition, which is free and open source.

**Comment by dominic-healid** [comment]
@ttmc Thank you, will try that.

**Comment by dominic-healid** [comment]
@ttmc I tried using MongoDB 3.4 and I still have BigchainDB 1.3.0 but still I can't access the API Endpoint.

Please see attached screenshot and let me know if you have any thoughts about why it is still not working.

Ubuntu trusty
MongoDB 3.4
BigchainDB 1.3.0

P.s How do I upgrade to 2.0 using pip3?
![screen shot 2018-04-19 at 4 44 02 pm](https://user-images.githubusercontent.com/32921921/38981354-c710c836-43f1-11e8-9055-bf6b75347ff1.png)
![screen shot 2018-04-19 at 4 44 44 pm](https://user-images.githubusercontent.com/32921921/38981356-c794d2de-43f1-11e8-8b3a-ea72942560f2.png)

**Comment by ttmc** [comment]
You can upgrade BigchainDB Server to the latest release (2.0.0a2) using:

`pip3 install --upgrade bigchaindb`

You might have to put `sudo` in front of that, depending on your situation.

**Comment by dominic-healid** [comment]
I have tried that but it only says the BighcainDB and other dependencies are already updated. 

Any thoughts?

![screen shot 2018-04-21 at 4 45 38 pm](https://user-images.githubusercontent.com/32921921/39082301-979f4f6c-4583-11e8-92e4-bd6718e0e79c.png)

**Comment by ttmc** [comment]
Oh, I guess PyPI sees that the latest version of BigchainDB (2.0 Alpha) is alpha, so it considers 1.3.0 to be the latest stable version and will only upgrade to that. You can force pip3 to install a specific version, using for example:

`sudo pip3 install bigchaindb==2.0.0a2`

See also https://pypi.org/project/BigchainDB/2.0.0a2/

**Comment by dominic-healid** [comment]
I see. I will try that later and will let you know, but isn't also because of the ubuntu version that I'm using on vagrant, right now I have Ubuntu trusty 14.04? Should I also try 16.04?

**Comment by ttmc** [comment]
Ubuntu 14.04 should be fine.

**Comment by dominic-healid** [comment]
@ttmc I followed your step but I was still having the same issues but I was able to resolved by removing some commands on the config.sh (vagrant) and followed what's indicated on this http://bigchaindb-server.readthedocs.io/en/v0.4.2/servers/installing-server.html

Updating to MongoDB 3.4 and to BigchainDB 2.0.0a2 went fine however I'm getting another issue. You may have another thoughts on this issue?

![screen shot 2018-04-23 at 12 05 54 pm](https://user-images.githubusercontent.com/32921921/39106581-312e0ce2-46ef-11e8-8b37-f22c582beaac.png)
