### ISSUE TITLE
Problem: bigchaindb and tendermint are not packaged as a single service unit

### ISSUE THREAD

**Issue by shahbazn** [bigchaindb/bigchaindb#2238]
bigchaindb version: `v2.0.0a2`
tendermint version: `0.12`
setup: `4 node network with docker-compose`

# Description
Tendermint polls to bigchaindb pyabci interface only on startup. So if at any point bigchaindb service crashes and restarts tendermint never tries to re-establish connection with bigchaindb, and bigchaindb in absence of a connection request form tendermint crashes again.

This tight coupling between tendermint and bigchaindb services requires them to be packaged together as a single unit to improve the crash recovery mechanism. 

# Solution
 - package tendermint binary as part of bigchaindb python package. This binary will be installed as part of bigchaindb package. (This needs to be scoped yet)
 - Add supervisord configs for spawning bigchaindb and tendermint services together and restart both in the expected order if one crashes. Supervisord will allow similar behavior across platforms and can be packaged with un-privileged docker containers as compared to other process managers like systemd which are distribution specific and can only work with privileged containers.

**Comment by muawiakh** [comment]
Related to #2232

**Comment by ttmc** [comment]
Resolving this issue was (or is) being blocked by some issues that prevented a clean shutdown of BigchainDB (i.e. _all_ BigchainDB processes).

One of those issues was resolved by pull request #2304 

I think there may still be other issues.

**Comment by ttmc** [comment]
See https://github.com/bigchaindb/bigchaindb/projects/7

**Comment by ttmc** [comment]
@shahbazn Will supervisord also start BigchainDB+Tendermint when the machine is restarted?
