### ISSUE TITLE
just question 

### ISSUE THREAD

**Issue by msalek** [bigchaindb/bigchaindb#2247]
Hello
I am new to the community, I have a small question
i have installed bigchaindb 2.0.0.dev and i have 2 node launch, i can send and store data usign python bigchaindb driver or js driver. all work very well

node1: http://192.168.2.187:9984/
node2: http://192.168.2.188:9984/

my question :
I try to create a cluster without succee, I crossed pubkey in keyring.
how to do that correctly?
I have to use the ip address?

thank you

**Comment by danacr** [comment]
this is not a 2.0 issue, the poster is referring to 1.3 and the solution is to implement the mongodb replicaset
