### ISSUE TITLE
BDB on Virtual machine becomes unresponsive and starts paging continuously to disk

### ISSUE THREAD

**Issue by agwego** [bigchaindb/bigchaindb#2272]
Hardware  AMD Athlon(tm) II X4 640 Processor, 16 GB RAM
Running Fedora release 17 (Beefy Miracle)
Virtual machine (VBOX 5.1) running Ubuntu 16.04.3 LTS with 3 GB RAM, vm resides on a 10k velociraptor
Bigchaindb: alpha-3

I started the bigchaindb instance, left it idle for several hours and then it began trying to grind my harddisk into dust, the VM instance became unresponsive, eventually I was able to shut it down but it took almost 20 minutes of constant disk access. No messages in the  bigchain log. Lots of messages in the syslog mostly relating to docker. Mostly meaningless. 

Update: added syslog

[syslog.1.txt](https://github.com/bigchaindb/bigchaindb/files/1985137/syslog.1.txt)

**Comment by vrde** [comment]
@muawiakh did we ever experienced this in our test network?

@agwego can you share some of the messages in the syslog? Even if it's docker related, it can help us understanding the problem better, thanks.

**Comment by shahbazn** [comment]
@agwego thanks for filling the issue I looked at the logged and could not find anything specific to bdb service. Seems like an issue with an older release of docker where containerd after restart fails to establish connection with docker-engine. I was not able to reproduce the problem with `Docker Version 18.03.1-ce-mac65 (24312)`. Can you please update the docker engine to latest release and check if the problem persists?

**Comment by agwego** [comment]
This appears to be a docker issue, having switched to the head, the issue seems to have gone away, but after shutting down Bigchain, docker went on it's merry way trying to destroy my disk.

**Comment by kansi** [comment]
@agwego You don't need docker to run BigchainDB. We use docker-compose to ease the setup but if you don't like that then you may find [this](https://gist.github.com/kansi/d6e059076e79f19663a2b5aeac74c8c0) interesting.

**Comment by shahbazn** [comment]
Issue seemed to be docker related.
