### ISSUE TITLE
Block validation does not check for the signature in the block

### ISSUE THREAD

**Issue by r-marques** [bigchaindb/bigchaindb#229]
Currently `validate_block` does not check if the signature in the block is correct. This would allow a malicious node that gains access to the cluster to create valid blocks without a valid private key.

relates to #228

**Comment by ttmc** [comment]
In addition to checking that that signature is valid, the public key of the block-creator node must be checked to ensure that it's a known public key (i.e. part of the federation list of public keys).

Is a similar check done for transactions, ensuring that they were created by nodes with known public keys?

**Comment by r-marques** [comment]
Yes for `CREATE` transactions we check if the transaction was created by a federation node.
https://github.com/bigchaindb/bigchaindb/blob/master/bigchaindb/consensus.py#L124

```python
if transaction['transaction']['current_owner'] not in (bigchain.federation_nodes + [bigchain.me]):
                raise exceptions.OperationError( 'Only federation nodes can use the operation `CREATE`')
```
