### ISSUE TITLE
Handle and test installation on various OSes+distros

### ISSUE THREAD

**Issue by ttmc** [bigchaindb/bigchaindb#23]
The BigchainDB installation requirements will differ slightly from OS to OS, especially the list of OS-level dependencies and how to install them. The setup.py file can take care of the Python dependencies, but not the OS-level dependencies.

How shall we handle OS-specific installation differences? Maybe write a Python script that checks the OS+distro and then installs the appropriate dependencies? Maybe create a Conda installer? Docker? Saltstack?

Would it make sense to test installation on various OS+distro combinations with Travis CI?

* [x] Make list of OSes + versions we want to support now
* [ ] Write an installer (or installers) to install BigchainDB, and all OS-level dependencies, on each of those OSes + versions
* [ ] Add installation tests in Travis CI

**Comment by andreasATascribe** [comment]
List of OSes to support now:
- [X] Ubuntu/Debian
- [ ] Centos/Fedora/RHEL
- [ ] ArchLinux

List of OSes to support later:
- [ ] Alpine Linux
- [ ] Raspian
- [ ] BSD
- [ ] Windows

**Comment by SohKai** [comment]
And OSX, please :innocent:?

**Comment by r-marques** [comment]
Just for reference here are the os level dependencies tested on Fedora 23

`libffi-devel gcc-c++ redhat-rpm-config python3-devel openssl-devel`

**Comment by ttmc** [comment]
For now, we've decided to focus on supporting Linux, with Ubuntu 14.04 as the primary distro & version.

For other OSes, we have [some support for running with Docker](https://bigchaindb.readthedocs.org/en/develop/installing-server.html#run-bigchaindb-with-docker).
