### ISSUE TITLE
API example response's customer keys are not 32 bytes

### ISSUE THREAD

**Issue by jonathanong** [bigchaindb/bigchaindb#230]
i think i'm tripping... i'm trying to build this request body in node.js: http://docs.bigchaindb.apiary.io/#reference/0/transactions-collection/push-a-new-transaction

i used https://github.com/cryptocoinjs/bs58 and got:

```js
const bs58 = require('bs58')
const key = bs58.decode(body.transaction.current_owner)
console.log(key.length) // 33
console.log(new Buffer(key).toString('hex')) // 03fce0773b9fba633dd7b08e1828b91036efe197a16334f49f0ac65efe3591f8eb'
```

i've also tried https://www.npmjs.com/package/base-58, reaching the same result.

is there a specific base-58 algorithm we should be using?

**Comment by diminator** [comment]
Hi Jonathan,

that's weird indeed.

can you maybe provide:
- the version of bigchaindb you are running
- the raw transaction

thanks

**Comment by r-marques** [comment]
Hi @jonathanong 

We recently changed the signature algorithm and forgot to update the documentation on apiary. We were using  `ecdsa` and we are now using `ed25519`

With `ecdsa` the key as an extra byte in the beginning stating how the key was compressed.

A valid `ed25519` public key would be `76wcv6iHcX5bYVyAxJYDbQXXexaRPMH1M6B6yHBp8ey1`. Can you try with this key?

**Comment by jonathanong** [comment]
@diminator didn't even reach that point! i was just trying to replicate the request body

@r-marques ah ok. thanks. let me try that

**Comment by r-marques** [comment]
#232 

Closing this since the questions seemed to have been answered.
