### ISSUE TITLE
Problem: Unsure if default POST /transactions mode should be 'async' or 'commit'

### ISSUE THREAD

**Issue by ttmc** [bigchaindb/bigchaindb#2307]
In BigchainDB 1.3 and before, the `POST /transactions` endpoint (to post a new transaction to a BigchainDB node), didn't have any query parameters.

As of BigchainDB 2.0, there are three possible query parameters: `/transactions?mode=async`, `/transactions?mode=sync` and `/transactions?mode=commit`.

Currently, if _no_ query parameter is included in the HTTP request, then mode is _assumed_ to be `async`, i.e. the _de facto_ default in the HTTP API is `async`.

The original reasoning for that was that `mode=async` means the same as having no query parameter always meant, i.e. you get back a `202 ACCEPTED` response if the initial node thought the transaction was valid, even if the transaction subsequently got lost or rejected by the network.

However, in the Python driver, the default mode is currently assumed to be `commit`. The reasoning there is that the user doesn't have to think too much. If they get back a 200-level response, then they can rest assured that their transaction got accepted and committed into a block. And if it was invalid or rejected, they find out why. In other words, `commit` is more user-friendly.

What _should_ the default mode be, `async` or `commit`?

**Comment by gautamdhameja** [comment]
I would agree with @codegeschrei that the default mode should be `commit` as the developers who are getting started with the code examples and implementation should be able to see the transaction response in real time.

**Comment by ldmberman** [comment]
The `async` mode allows for more scalable applications and is a better default unless we are focusing on the experience of just trying the system out, what seems to be the case.

Also, changing the default mode is a backwards-incompatible API change, how do we approach this?

**Comment by ttmc** [comment]
Maybe it's _okay_ if the default mode on the HTTP API is `async` (to stay backwards-compatible), and the default mode in the drivers is `commit`? The inconsistency might lead to confusion. 

An alternative would be for drivers to _require_ the mode parameter to be set explicitly when posting a new transaction (i.e. have no default value). Driver users would be forced to think about the mode. We could recommend that they use `commit`.

**Comment by vrde** [comment]
>An alternative would be for drivers to require the mode parameter to be set explicitly when posting a new transaction (i.e. have no default value). Driver users would be forced to think about the mode. We could recommend that they use commit.

I agree with @ttmc, the idea is to deprecate the current one `POST /transactions?mode=...` and have two (three?) different API endpoints:
- `POST /commit/transaction`
- `POST /async/transaction`
- `POST /sync/transaction`

This change is reflected by both Python and JavaScript drivers by adding the methods `commit_transaction`, `async_transaction`, and `sync_transaction`. By removing the default, we force the developer to make a conscious choice when coding. In the tutorials and examples we can use `commit_transaction` always.

**Comment by ttmc** [comment]
That's not _exactly_ what I had in mind, but it would work. The Tendermint endpoints are named:

```text
/broadcast_tx_async
/broadcast_tx_sync
/broadcast_tx_commit
```
We always spell out "transaction" or "transactions" (by convention) so maybe we could have:

```text
POST /transaction_async
POST /transaction_sync
POST /transaction_commit
```
with no `/` because that has a different purpose in RESTful endpoint names (e.g. `POST /groups/45/members/7`).

**Comment by ttmc** [comment]
I don't think it's a good idea to be changing fundamental APIs (like how to post a transaction to a BigchainDB network) at this point, that is, just before releasing BigchainDB 2.0.0 Beta. It would break a lot of code and documentation. Here's what I had in mind in my first comment above:

First, don't change the BigchainDB Server HTTP API at all. The default mode would be async, which is what it has always been, since before mode was a thing you could choose.

Second, change the drivers, but only slightly. Keep the same method name for posting a transaction, but make the mode argument required, with no default value. For example, with the Python driver:

```python
sent_creation_tx = bdb.transactions.send(fulfilled_creation_tx)
```

would become

```python
sent_creation_tx = bdb.transactions.send(fulfilled_creation_tx, 'commit')
```
The second argument in that method (`send`) is already the mode, but it has a default value of `mode='commit'`. I'm just saying that we should give it no default value, so an exception would be raised if someone tried to call that method without explicitly specifying the mode. We can recommend that people use 'commit'.

**Comment by ttmc** [comment]
@manolodewiner That's a nice solution, i.e. three functions, with `postTransaction()` doing what it always did, i.e. mode=async, so as not to change the meaning of existing code. I'm not sure we need to have one function with a mode parameter. Maybe it's okay if the Python and JavaScript drivers have different functions.

**Comment by codegeschrei** [comment]
I like @manolodewiner's solution but I'd still go with a required parameter for the python driver instead. 
The changes to the code are minimal and it's still the same behaviour to what we have now. Some people might use it already so they can still use it the same way. I already have an idea for the documentation to not overwhelm new users who just want to know about the basics.
Maybe we can agree on a solution for the python driver soon and I can change everything accordingly.

**Comment by ttmc** [comment]
@codegeschrei @manolodewiner I think we could:

- leave the three-function solution as-is in the JavaScript driver (i.e. where the default is async, as it has always been)
- change the Python driver to have a required third parameter (mode) with no default. This will break existing code, so we should raise a helpful exception that tells them what to do to fix it; at that point we can recommend that they set the mode to 'commit'.

**Comment by manolodewiner** [comment]
Looks good for me, and I hope that for the users of the drivers as well :)

**Comment by ttmc** [comment]
> If the parameter is like an enumerated type (i.e. it can be only async, sync, or commit), then it makes sense to have three different functions/methods, as it is in the JavaScript driver.

I'm not familiar with that coding guideline. It would imply that if there are exactly 20 possible values, then there should be 20 different functions/methods, which seems wrong.

**Comment by ttmc** [comment]
I discussed this with @codegeschrei and @manolodewiner this morning and here is what we decided to do:

For both drivers (Python and JavaScript), have four methods, with the one that doesn't specify the mode doing the same as the one that uses "commit" (because "commit" it a better user experience).

For the JavaScript driver:
```js
postTransaction()
postTransactionAsync()   // new method
postTransactionSync()
postTransactionCommit()
```

For the Python driver:
```python
send(fulfilled_creation_tx) # with no optional mode=something parameter, always does commit
send_async(fulfilled_creation_tx)   # new method
send_sync(fulfilled_creation_tx)   # new method
send_commit(fulfilled_creation_tx)    # new method
```

**Comment by vrde** [comment]
@ttmc sounds good to me. For the Python driver, we can also add a [`warning`](https://docs.python.org/3/library/warnings.html) to deprecate `send`.

**Comment by vrde** [comment]
The deprecation note for Python can be something like: ``The method `.send` will be deprecated soon, use `send_commit`, `send_sync`, or `send_async` instead <https://link-to-the-docs>``.

**Comment by ttmc** [comment]
All that remains is to update the JS Driver and an issue has been created to do that: https://github.com/bigchaindb/js-bigchaindb-driver/issues/191

The purpose of _this_ issue was to serve as a forum for discussion. Since that discussion seems to be done, I will close this issue now.
