### ISSUE TITLE
Error in Documentation and Documentation unclear

### ISSUE THREAD

**Issue by NomanMaqsood** [bigchaindb/bigchaindb#2308]
I choosed bigchaindb for one of my project, first of all I would like to highlight the mistake in one of your shared [tutorial](https://www.bigchaindb.com/developers/guide/tutorial-piece-of-art/). The JSON is not correct, please correct it. 
I have two concerns and I request you to please address it with example. 

- There is no example of how to define models for javascript orm, please address how to make model
- In your guide section, no example of how to query records from database, one record or multiple.

Please address my concerns. Thank you 

Regards:
Noman Maqsood

**Comment by manolodewiner** [comment]
Hi @NomanMaqsood  thank you for chosen us. I am going add the comma as you are right, the JSON is not correct. We are going to modify it as soon as possible.
Appreciate your effort for working with us and communicating us errors. 
Please check https://docs.bigchaindb.com/projects/js-driver/en/latest/usage.html#querying-for-assets
Also if you want to query MongoDB directly, this repo was working for me in the past. Might be helpful for you https://github.com/manolodewiner/query-mongodb-bigchaindb

**Comment by NomanMaqsood** [comment]
Yes I noticed the same error.


Regards:
Noman Maqsood
Software Engineer
SkypeId: nomanmaqsood91



________________________________

**Comment by NomanMaqsood** [comment]
@manolodewiner @ttmc can anyone of please answer the first part of my questions i.e

1. There is no example of how to define models for javascript orm, please address how to make model

In documentation url of some site has given which not accessible, can you please guide here ?

**Comment by kremalicious** [comment]
Question number 1 would be better asked in the respective project https://github.com/bigchaindb/js-driver-orm since that's where this documentation you're asking about should be.

The json error in the tutorial has been addressed in https://github.com/bigchaindb/site/pull/243

Question number 2: that would be a completely new tutorial I guess

**Comment by manolodewiner** [comment]
The JSON error has been resolved.
This is not an issue related with this repo.
