### ISSUE TITLE
tutorial problem on readthedocs

### ISSUE THREAD

**Issue by jvsteiner** [bigchaindb/bigchaindb#231]
going through the tutorial here: http://bigchaindb.readthedocs.io/en/master/python-server-api-examples.html, i found i needed to manually create and add blocks in order to insert the actual transactions:

```
y=b.create_block([tx_signed])
b.write_block(y)
```
where b is the `Bigchain` object in the tutorial.

**Comment by r-marques** [comment]
Did you do these steps
```bash
$ bigchaindb configure
$ bigchaindb init
$ bigchaindb start
```

If `bigchaindb start` process is running it should pick up the transactions and create the blocks after using `b.write_transaction(..)`

**Comment by jvsteiner** [comment]
I did, (and have wiped down the db, re-initialized, and started from scratch to be sure) but no joy.  the only thing I notice is, at `bigchaindb start` I see the following:

```
Process validate_transactions:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/multiprocessing/process.py", line 254, in _bootstrap
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/jamie/Code/bigchain/venv/lib/python3.5/site-packages/bigchaindb/block.py", line 60, in validate_transactions
    self.q_tx_to_validate.qsize(),
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/multiprocessing/queues.py", line 117, in qsize
    return self._maxsize - self._sem._semlock._get_value()
NotImplementedError
```
in the shell output before gunicorn starts.  Also, I am running this on OSX with a native installation of everything (RethinkDB 2.3.1 installed to OSX not VM/Docker, etc).  Python v3.5.1

**Comment by r-marques** [comment]
Yes its a known problem. We are currently only focusing on supporting linux. For other systems we have a docker deployment http://bigchaindb.readthedocs.io/en/latest/installing-server.html#run-bigchaindb-with-docker

**Comment by jvsteiner** [comment]
Understood - it's worth pointing out that docker is quite a bit less convenient for developing against the server api, which is my main interest.

**Comment by r-marques** [comment]
@jvsteiner I understand. Although with the new docker setup you can access the running in a docker container from the host
