### ISSUE TITLE
Update or replace apiary documentation

### ISSUE THREAD

**Issue by r-marques** [bigchaindb/bigchaindb#232]
relates to #230 

The apiary documentation is out of date. The keys used in the examples are keys generate by the old `ecdsa` signing algorithm instead of `ed25519`.

The apiary documentation is a bit useless because the api endpoints do not call any running server. We should decide if we want to keep using apiary or move the api documentation to readthedocs

**Comment by vrde** [comment]
We can keep the documentation for the API endpoints in our `docs` folder, IMO apiary is cumbersome to maintain.

I found this [httpdomain](http://pythonhosted.org/sphinxcontrib-httpdomain/) extension to Sphinx to describe RESTful HTTP APIs, should we try it? /cc @ttmc, @sbellem

**Comment by Latrasis** [comment]
The docs at https://bigchaindb.readthedocs.io/en/latest/http-client-server-api.html are recursive still point to apiary which point back.

**Comment by r-marques** [comment]
This shouldn't take long. We should do this sooner rater then later

**Comment by ttmc** [comment]
My feeling is that if someone wants to prototype BigchainDB-based apps today, then they should use the Python server API (not the HTTP API, which is way too rudimentary). Based on how the [BigchainDB Examples](https://github.com/bigchaindb/bigchaindb-examples) (app demos) have been going, it seems we will be switching to a websocket-based API anyhow.

I could update the [HTTP API documentation page on ReadTheDocs](https://bigchaindb.readthedocs.io/en/latest/drivers-clients/http-client-server-api.html) to say this. It already does, sort of, but it could be more clear.

**Comment by r-marques** [comment]
Not sure about the websocket-based API part. Anyhow its still something that needs to be implemented at the API level. Using the python server api like the examples are doing right now is bad practice and should not be encouraged, we just have no other way of doing it right now.

What we need is to keep working on the api so that it can provide the same features as the python server api.

**Comment by ttmc** [comment]
I will remove the page of documentation about the client-server HTTP API for now (including its link to Apiary). We can put it back later.

**Comment by sohkai** [comment]
Closing after #434. For now all API documentation will be on readthedocs.
