### ISSUE TITLE
Add more documentation about the command `bigchaindb load`

### ISSUE THREAD

**Issue by ttmc** [bigchaindb/bigchaindb#234]
The documentation about the `bigchaindb load` command should be fleshed out to explain the `-c` and `-m` options. The source for that documentation is in `bigchaindb/docs/source/bigchaindb-cli.md`

**Comment by ttmc** [comment]
While doing this, the `--help` documentation for `bigchaindb load` could be revised as well. Right now, if you do `bigchaindb --help`, part of the response is:
```text
Commands:
  {configure,show-config,export-my-pubkey,init,drop,start,load}
    configure           Prepare the config file and create the node keypair
    ...
    load                Write transactions to the backlog
```

but these days, `bigchaindb load` pushes "create" transactions to the HTTP API endpoint (i.e. not directly to the backlog table).

**Comment by TimDaub** [comment]
Closing this ticket, as `bigchaindb load` was removed in: https://github.com/bigchaindb/bigchaindb/pull/1273
