### ISSUE TITLE
Gitter chat room displayed on BigchainDB website

### ISSUE THREAD

**Issue by Bilel2038** [bigchaindb/bigchaindb#2343]
Hi, could we please add Gitter chat room buttons on [BigchainDB's landing](https://www.bigchaindb.com/) and [services pages](https://www.bigchaindb.com/services/)?

Buttons that say "Open chat" or "Ask us your questions now!"  next to the "Get Started" and "Get in touch" buttons that would display the thread directly on BDB's website so it's easier for visitors to see it and avoids technical questions to be submitted to the contact form as it is frequently done. 

Thank you!

**Comment by ttmc** [comment]
The BigchainDB landing page already has a link to the Gitter chat room, just click on "Chat":

![screenshot from 2018-06-11 13-05-40](https://user-images.githubusercontent.com/1210951/41228302-346ed350-6d78-11e8-8316-fd12405966ec.png)

**Comment by Bilel2038** [comment]
Yes, that's a link to the channel. What I meant is a platform (a plug-in) integrated on the website that is more visible. A [previous version of Ethereum's website](https://web.archive.org/web/20180531101700/https://ethereum.org/) has it (the Open chat button on bottom right).

**Comment by ttmc** [comment]
We had one of those "chat now, on page" things in the old ascribe.io website and web app. It was powered by Intercom. We got rid of it.

**Comment by ttmc** [comment]
I'm going to close this issue here. If you still want this, please create a new issue in the https://github.com/bigchaindb/site repo and reference this issue ( https://github.com/bigchaindb/bigchaindb/issues/2343 ).
