### ISSUE TITLE
python setup.py install fail.

### ISSUE THREAD

**Issue by nexusz99** [bigchaindb/bigchaindb#236]
I tried to install bigchaindb from source and i got an error like this.

Environment : OS X (10.11.04), python 3.5

`error: Setup script exited with error in BigchainDB setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers`

Fortunately, 'pip3 install bigchaindb' works good.

**Comment by nexusz99** [comment]
PR #237 can solve this error

**Comment by vrde** [comment]
Hi @nexusz99, unfortunately some Python distributions come with a very old version of `setuptools`.

Can you try to run:
```
$ pip install --upgrade setuptools
```
and tell me if it resolves the problem? It should install `setuptools-20.10.1`.

Related to #237, the `~` is to pin a [compatible release](https://www.python.org/dev/peps/pep-0440/#compatible-release) of gunicorn.

**Comment by nexusz99** [comment]
My pip environment was " pip (1.5.6) setuptools (3.6)". 

And after run "pip install --upgrade setuptools", the problem solved!!

Thanks a lot. It was my fault. 

Thanks.

**Comment by nexusz99** [comment]
How about check the version of setuptools before install?

**Comment by vrde** [comment]
> How about check the version of setuptools before install?

That's an interesting idea, will think about it and update this issue soon.

**Comment by ttmc** [comment]
Resolved by PR #276 and PR #279
