### ISSUE TITLE
Invalid transaction (DuplicateTransaction)

### ISSUE THREAD

**Issue by charlespetchsy** [bigchaindb/bigchaindb#2367]
### Bug Report

- What computer are you on (hardware)?
VMWare Fusion 10.1.2
- What operating system are you using, including version. e.g. Ubuntu 14.04? Fedora 23?
Ubuntu 16.04 LTS (Linux ubuntu 4.13.0-45-generic)
- What version of BigchainDB software were you using? Is that the latest version?
`v2.0.0b1` with the js driver `v4.0.2`

Hello,

I am running a local instance of BigchainDB using `make start`. The version of bigchaindb used is cloned from the repository without any modifications.

I am experiencing an issue where I lose the ability to post the same transaction to the chain. The first transaction was successful, but when I try to post the same transaction again it produces the following error:

```
{ message: 'HTTP Error: Requested page not reachable',
  status: '400 BAD REQUEST',
  requestURI: 'http://127.0.0.1:9984/api/v1/transactions?mode=commit' }
```
The same error persists even without the commit mode.
When creating a new asset record, there should be no conflict since a new asset id / transaction id is created each time a new asset record is created.

The error log produced by bigchaindb:
```
[2018-06-28 21:25:29] [ERROR] (bigchaindb.web.views.base) HTTP API error: 400 - POST:/api/v1/transactions - Invalid transaction (DuplicateTransaction): transaction `274afa8b1c7fd906b1d0dd661945d1766c5def489bf9b1a73babaf98e813c6d3` already exists (webapi     - pid: 32)
```
I have attached the js script (createAsset.js) that replicates this problem. All it does is creates an asset to the chain with a `.json` file as its input and creates a record of the transaction as an `.output` file.

Usage: `$ node createAsset.js data.json`
```
const BigchainDB = require('bigchaindb-driver');
const bip39 = require('bip39');
const fs = require('fs');

const jsonFile = require('./' + process.argv[2]);
const inputarg = process.argv[2];

const conn = new BigchainDB.Connection(jsonFile.api_path, {
    app_id: '',
    app_key: ''
})

// Generate a new key pair for this asset
const keypair = new BigchainDB.Ed25519Keypair(bip39.mnemonicToSeed('cclDecrypt').slice(0, 32));
// The keypair is retrieved from the input file
//createSimpleAsset(keypair, jsonFile.asset, jsonFile.metadata)
createSimpleAsset(jsonFile.keypair, jsonFile.asset, jsonFile.metadata)

async function createSimpleAsset(keypair, asset, metadata){

    const txSimpleAsset = BigchainDB.Transaction.makeCreateTransaction(
        asset,
        metadata,
        // counterparty is the owner
        [BigchainDB.Transaction.makeOutput(
            BigchainDB.Transaction.makeEd25519Condition(keypair.publicKey))],
          keypair.publicKey
    )
    // Sign the transaction with private keys
    const txSigned = BigchainDB.Transaction.signTransaction(txSimpleAsset, keypair.privateKey)

    return conn.postTransactionCommit(txSigned)
        .then(res => {
            fs.writeFile(inputarg.substring(0,inputarg.length-5)+'.output', 
            JSON.stringify(txSigned, null, 2), 
            function (err) {
                if (err) throw err
                console.log('Saved asset id to file');
            })
            console.log('Created simple asset', txSigned.id, 'accepted')
            return res
        })
}
```

The contents of the `data.json` file:
```
{
  "keypair": {
    "publicKey" : "vc2dTwXcucGZmBN6sYNwZ1uEDcGFmLKBZ1w3Hpk5UAT",
    "privateKey" : "C3SXPM68TT7Le5DwrUgc2XqEaoi29twDqZsyMAVgfjJG"},
  "assetId": "9b6f223de6dd3cebb8b9f42e1b8c34e213c68febdfb21a5941bdfb1604b891c5",
  "asset": {"entity":"COUNTERPARTY","type":"CA2"},
  "metadata":{
    "lei":null,
    "cpPublicKey":"vc2dTwXcucGZmBN6sYNwZ1uEDcGFmLKBZ1w3Hpk5UAT",
    "entity":"COUNTERPARTY",
    "bic":null,
    "cpLegalName":"CP INDUSTRIES",
    "createDate":"2018-02-06T11:30:53.422Z",
    "cpShortName":"CP",
    "group_Ids":
    ["",
      ""
      ],
    "parentCpId":null,
    "cpLogo":null,
    "appendDate":null,
    "createUserID":"SYSTEM",
    "type":"BRK",
    "appendUserID":null,
    "notificationProfiles_brk":
    [{
      "ccEmailAddress":["cc@email.com"],
      "rejectEmailAddress":["rejects@email.com"],
      "fromEmailAddress":"cc@email.com",
      "documentType":"C",
      "assetClass":"ALL"
    },
      {
        "ccEmailAddress":["cc@email.com"],
        "rejectEmailAddress":["rejects@email.com"],
        "FromEmailAddress":"cc@email.com",
        "DocumentType":"S",
        "assetClass":"ALL"
      }
    ]},
  "metadataSearch": "",
  "assetSearch":"",
  "api_path":"http://127.0.0.1:9984/api/v1/"
}
```

**Comment by codegeschrei** [comment]
Hey @charlespetchsy 
I'm not quite sure I understand what happened.
You tried to post the exact same transaction twice and you got an error?
And you tried to post a different transaction and you got an error?

**Comment by aadps** [comment]
I can reproduce the issue. The bigchaindb would give following error message in the log.

```
POST:/api/v1/transactions - Invalid transaction (DuplicateTransaction): transaction `878067604dd4a1beeda8086dd759d6ddd5a5a306a5a4e723ed91
ad46ca2522d8` already exists
```

It seems that the txid is generated by the driver as a hash of signed transaction. So exact same transactions would yield an exact same id.

Bigchaindb 1.3.0 would not produce this error for it used [a different method](https://github.com/bigchaindb/bigchaindb/blob/af996650c3369e18a97a83949636fff18d714397/bigchaindb/common/transaction.py) to detect duplicate block.

```
        # Check that the block contains no duplicated transactions
        txids = [tx.id for tx in self.transactions]
        if len(txids) != len(set(txids)):
            raise DuplicateTransaction('Block has duplicate transaction')
```

Whereas in 2.0.0, it does compare the actual id value.

```
        if self.operation == Transaction.CREATE:
            duplicates = any(txn for txn in current_transactions if txn.id == self.id)
            if bigchain.get_transaction(self.to_dict()['id']) or duplicates:
                raise DuplicateTransaction('transaction `{}` already exists'
                                           .format(self.id))
```

**Comment by codegeschrei** [comment]
Thanks for your clarification.
Posting a transaction twice was never possible. With BigchainDB 1.3.0 it seemed like it was possible. When posting the duplicate transaction it was taken but later on rejected when it was supposed to go into a block, because it is a duplicate. The user was not informed about this situation. Now we let the user know immediately and thus a duplicate transaction can not be posted any more.

**Comment by KevinBaylor** [comment]
Hi, guys! I'm using bigchaindb 2.0.0b9 and python driver to post a new transaction. Yet still this problem happens. Can you tell me how wrong with that? Thanks.
