### ISSUE TITLE
Bigchain DB nodes in a 4 node cluster unable to replicate the data

### ISSUE THREAD

**Issue by CosmicCoder96** [bigchaindb/bigchaindb#2393]
I have set up a cluster of 4 nodes.
The operating system on each of those is **Ubuntu 16.04** 
The bigchaindb version is : **2.0.0b3**
Tendermint version: **0.22.3**

The nodes were set up as per instructions in 
https://docs.bigchaindb.com/projects/server/en/latest/simple-network-setup.html

The ports mentioned in the above link are open on each of those machines.

### Current Behavior
- I make a simple hello world create transaction on a particular node (say node 1).
- Transaction is completed and a transaction ID is returned.
- I query node 1 (using http api or directly accessing database)
- I am able to find the transaction
- I query the other nodes' (node2, node3, node4) HTTP API or their database, I am unable to find the transaction.

### Expected Behavior
- The transaction data should be replicated among the nodes of the cluster.

### What I want
Some help in debugging. I expect bigchaindb should raise a warning or an error, when replication fails in a cluster. It might even be raising it, but I am not sure what is the right place to look for. (There were no errors on output of the `bigchaindb start` output.)

### What I have tried so far
- Tested ping for nodes - they were able to ping each other
- Unblocked the required ports and double checked them

output of ` sudo lsof -i -P -n `
![image](https://user-images.githubusercontent.com/17252805/42906321-22325952-8adb-11e8-818d-98f9002feef9.png)

**Comment by kansi** [comment]
@CosmicCoder96 It seems to me that something from the above description is missing i.e. what you are trying to imply here is that only 1 node commits the transaction in a 4 node network. This is not possbile as a transaction is considered commited if at least 3 nodes commit the transaction. I would suggest making sure that all the nodes are infact connected and are part of the same blockchain.

**Comment by CosmicCoder96** [comment]
@kansi how can I check that - presently when I say it's a 4 node network, it's based on the following:
- They share the same **genesis.JSON**
- In **config.toml** - all 4 nodes are listed as `persistant peers`

**Comment by ttmc** [comment]
@vrde wrote some tips to help you get diagnostics on your Tendermint network, at https://github.com/vrde/notes/tree/master/tendermint 

Note that port 46657 has changed to port 26657 in the latest release. (This change was made by Tendermint.)

**Comment by CosmicCoder96** [comment]
@ttmc Thanks for sharing this, this has certainly given me the information I was looking for.
This is the output
```json
{
  "jsonrpc": "2.0",
  "id": "",
  "result": {
    "listening": true,
    "listeners": [
      "Listener(@212.189.207.119:26656)"
    ],
    "n_peers": "0",
    "peers": []
  }
}
```
Which justifies the current behaviour. So essentially the connection has failed.
This is my `genesis.json`:
```json
{
  "genesis_time": "2018-07-18T15:48:46.24269529Z",
  "chain_id": "test-chain-cl61op",
  "consensus_params": {
    "block_size_params": {
      "max_bytes": "22020096",
      "max_txs": "10000",
      "max_gas": "-1"
    },
    "tx_size_params": {
      "max_bytes": "10240",
      "max_gas": "-1"
    },
    "block_gossip_params": {
      "block_part_size_bytes": "65536"
    },
    "evidence_params": {
      "max_age": "100000"
    }
  },
  "validators": [
    {
      "pub_key": {
        "type": "tendermint/PubKeyEd25519",
        "value": "ntjRee68kn5ijvCMd01LyNm2dMuhpKaLieeaydLg3ns="
      },
      "power": "10",
      "name": "Coordinator"
    },
    {
      "pub_key": {
        "type": "tendermint/PubKeyEd25519",
        "value": "2cU5ZnA3bo6Rm01XRqyQxqIddc4GQAMwEbRQ38+lDGI="
      },
      "power": "10",
      "name": "Member 2"
    },
    {
      "pub_key": {
        "type": "tendermint/PubKeyEd25519",
        "value": "v3CI6fpQ59tNnmZ4VkFWZPs4sFKnl6L7mnGjZCxr97Y="
      },
      "power": "10",
      "name": "Member 3"
    },
    {
      "pub_key": {
        "type": "tendermint/PubKeyEd25519",
        "value": "90cslPYMfdWD640GSuIafCQVQOi7wBgzF6PMqBwYHWM="
      },
      "power": "10",
      "name": "Member 4"
    }
  ],
  "app_hash": ""
}
```
What could be the possible next steps for debugging, thank you.

**Comment by CosmicCoder96** [comment]
@ttmc @kansi 
Thanks for all your help, I have managed to fix the issue by doing:
`tendermint unsafe_reset_all`
and 
`tendermint unsafe_reset_priv_validator`

Maybe this can be pointed out in the bdb documentation as well 😅apparently if the nodes have ever been run before independently, after changing the genesis file, they need to be reset using the above commands.

**Comment by ttmc** [comment]
Where are you running your nodes? If they're running in a cloud like AWS or Azure, you need to make sure that the "security group" (firewall) on each VM allows incoming TCP traffic on ports 22, 9984, 9985 and 26656. The last one (26656) is for Tendermint inter-node communications and is the most critical for allowing the nodes to talk to each other.

Please also run some Linux commands, such as `sudo netstat -plnt`, to check what's listening on various ports, and share the results here.

**Comment by CosmicCoder96** [comment]
@ttmc as I said, using those Tendermint commands has fixed the issue. And the transactions are replicating. So it was not a networking issue.

**Comment by ttmc** [comment]
@CosmicCoder96 I'm glad you got it working!

P.S. The current master branch of the Tendemint docs gives these instructions to reset Tendermint:

> To reset a blockchain, stop the node, remove the ~/.tendermint/data directory and run
>
> `tendermint unsafe_reset_priv_validator`

From https://tendermint.readthedocs.io/projects/tools/en/master/using-tendermint.html#reset

I will update our docs accordingly.

**Comment by BarathKumarDharani** [comment]
Hi Everyone ,
Could you please clarify me on the following scenario
I have 4 nodes in bigchain db network, and i have some assets (belongs to one of node ). i edited the asset details in db accidentally
now i am not able to transfer asset since it is expected behavior . but i want to transfer the assets with old details . how to make my db sync with all nodes. is there anyway to do that .
please share the documents for the same if any .

**Comment by thangasblockchain** [comment]
we have been trying to set up a bigchaindb cluster in two instances. but it is not getting replicated in other instance.
Is there any protocol to define the cluster setup of BigchainDB (regarding number of nodes and tendermint)
