### ISSUE TITLE
Bigchaindb cluster

### ISSUE THREAD

**Issue by riyazlafir** [bigchaindb/bigchaindb#2396]
Hi,
I'm trying to create Bigchaindb cluster Node with two Bigchaindb instances. Individually two nodes are works fine but when I try to cluster both are not communicate/connect each other.

I have followed the steps mentioned in here,
https://docs.bigchaindb.com/projects/server/en/v1.3.0/production-nodes/setup-run-node.html

My first machine details;

- The machine runs in Linux AWS EC2 instance.
- Bigchaindb version 1.3
-  .bigchain  config file 
`{
    "graphite": {
        "host": "172.31.6.11"
    },
    "keypair": {
        "private": "<privatekey>",
        "public": "D2HQBDr6ss48ZmZawDbhuispBngZPyqqwqYcLUpNYYrM"
    },
    "server": {
        "workers": null,
        "loglevel": "info",
        "bind": "0.0.0.0:9983"
    },
    "log": {
        "datefmt_logfile": "%Y-%m-%d %H:%M:%S",
        "file": "/home/ubuntu/bigchaindb.log",
        "level_console": "info",
        "level_logfile": "info",
        "datefmt_console": "%Y-%m-%d %H:%M:%S",
        "error_file": "/home/ubuntu/bigchaindb-errors.log",
        "granular_levels": {},
        "fmt_logfile": "[%(asctime)s] [%(levelname)s] (%(name)s) %(message)s (%(processName)-10s - pid: %(process)d)",
        "port": 9020,
        "fmt_console": "[%(asctime)s] [%(levelname)s] (%(name)s) %(message)s (%(processName)-10s - pid: %(process)d)"
    },
   "wsserver": {
        "scheme": "ws",
        "advertised_scheme": "ws",
        "advertised_port": 9985,
        "host": "172.31.6.11",
        "advertised_host": "localhost",
        "port": 9985
    },
    "backlog_reassign_delay": 120,
    "database": {
        "login": null,
        "certfile": null,
        "keyfile_passphrase": null,
        "backend": "mongodb",
        "password": null,
        "host": "172.31.6.11",
        "ssl": false,
        "max_tries": 3,
        "name": "bigchain",
        "ca_cert": null,
        "keyfile": null,
        "replicaset": "bigchain-rs",
        "crlfile": null,
        "port": 27017,
        "connection_timeout": 5000
    },
    "keyring": ["CZ1T7hppQWuLTqg5dsPdZXWx9RVzfB4ffFtusADRMWFS"]
}`

Second machine details;

- The machine runs in Linux AWS EC2 instance.
- Bigchaindb version 1.3
-  .bigchain  config file 
`
{
    "graphite": {
        "host": "172.31.8.222"
    },
    "keypair": {
        "private": "<private key>",
        "public": "CZ1T7hppQWuLTqg5dsPdZXWx9RVzfB4ffFtusADRMWFS"
    },
    "server": {
        "workers": null,
        "loglevel": "info",
        "bind": "0.0.0.0:9984"
    },
    "log": {
        "datefmt_logfile": "%Y-%m-%d %H:%M:%S",
        "file": "/home/ubuntu/bigchaindb.log",
        "level_console": "info",
        "level_logfile": "info",
        "datefmt_console": "%Y-%m-%d %H:%M:%S",
        "error_file": "/home/ubuntu/bigchaindb-errors.log",
        "granular_levels": {},
        "fmt_logfile": "[%(asctime)s] [%(levelname)s] (%(name)s) %(message)s (%(processName)-10s - pid: %(process)d)",
        "port": 9020,
        "fmt_console": "[%(asctime)s] [%(levelname)s] (%(name)s) %(message)s (%(processName)-10s - pid: %(process)d)"
    },
    "wsserver": {
        "scheme": "ws",
        "advertised_scheme": "ws",
        "advertised_port": 9985,
        "host": "localhost",
        "advertised_host": "172.31.8.222",
        "port": 9985
    },
    "backlog_reassign_delay": 120,
    "database": {
        "login": null,
        "certfile": null,
        "keyfile_passphrase": null,
        "backend": "mongodb",
        "password": null,
        "host": "172.31.8.222",
        "ssl": false,
        "max_tries": 3,
        "name": "bigchain",
        "ca_cert": null,
        "keyfile": null,
        "replicaset": "bigchain-rs",
        "crlfile": null,
        "port": 27017,
        "connection_timeout": 5000
    },
    "keyring": ["D2HQBDr6ss48ZmZawDbhuispBngZPyqqwqYcLUpNYYrM"]
}}`

I need to know what is the problem in my scripts? and do I need to do any other configuration steps to create cluster node ?

Thanks,
Riyaz.

**Comment by ttmc** [comment]
1. Please don't use BigchainDB 1.3. It worked very differently from the 2.x series and isn't being supported any more (or at least not by the BigchainDB team).
2. A BigchainDB cluster must have at least four nodes.

See the instructions at http://docs.bigchaindb.com/projects/server/en/latest/simple-network-setup.html

**Comment by riyazlafir** [comment]
Hi @ttmc,
Thanks for the reply. What is the process of version upgrading?

**Comment by muawiakh** [comment]
v2.0 is not backwards compatible with v1.3, hence there is no upgrade path. We have made a lot of breaking changes with v2.0. You can read more about it [here](https://blog.bigchaindb.com/bigchaindb-2-0-is-byzantine-fault-tolerant-5ffdac96bc44).

**Comment by thangasblockchain** [comment]
@ttmc hi I have been using bigchaindb 2.0.0 is it mandatory that I should have at least 4 nodes to complete the cluster set up ?

**Comment by ttmc** [comment]
@thangasblockchain Yes a BigchainDB cluster must have at least four nodes. Also, please note that I'm no longer working on BigchainDB and I don't provide support for it.
