### ISSUE TITLE
Skip invalid blocks upon transaction reads

### ISSUE THREAD

**Issue by diminator** [bigchaindb/bigchaindb#241]
`get_transaction` and maybe others do not skip the invalid blocks, yielding an exception in the case of DoubleSpents:

```
Transaction ids should be unique. There is a problem with the chain
```

**Comment by r-marques** [comment]
![ufdv1tg](https://cloud.githubusercontent.com/assets/1793187/14988831/e39ee6fc-1155-11e6-9552-f1e98a0ee951.gif)
