### ISSUE TITLE
Bigchaindb network validator

### ISSUE THREAD

**Issue by riyazlafir** [bigchaindb/bigchaindb#2418]
Hi,

I have created my own Bigchaindb network with four nodes and followed the steps mentioned in here (https://docs.bigchaindb.com/projects/server/en/latest/simple-network-setup.html) for configuration steps. But out of this four nodes, only two nodes identify as validators.

Configuration (all 4 machines): 
Bigchaindb version : 2.0.0b3
Tendermint version : 0.22.3-2aa2b63c
OS : Ubuntu 16.4
python : 3.6
mongodb : v3.4.1

when I try this endpoint in my browser: http://<host_ip>:9984/api/v1/validators

Success 2 nodes gives 
`[{"pub_key": {"type": "tendermint/PubKeyEd25519", "value": "9KyVM6ZwvQQDyq9ZRA4C1D8sw+f/h8gJL7J8YQvkvMU="}, "voting_power": "10"}, {"pub_key": {"type": "tendermint/PubKeyEd25519", "value": "ttuQEkezd9bX0RCXfxK0NzUrVXXl14AwE+pJlDZCbkc="}, "voting_power": "10"}]`

but failure 2 nodes gives the following error : 
`{"message": "Internal Server Error"}`

And in my server side, I'm getting following error message : 

`[2018-07-30 02:04:13] [ERROR] (flask.app) Exception on /api/v1/validators [GET] (bigchaindb_webapi - pid: 2188)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.6/dist-packages/flask_restful/__init__.py", line 480, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/flask_restful/__init__.py", line 595, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/bigchaindb/web/views/validators.py", line 16, in get
    validators = bigchain.get_validators()
  File "/usr/local/lib/python3.6/dist-packages/bigchaindb/tendermint/lib.py", line 467, in get_validators
    validators = resp.json()['result']['validators']
KeyError: 'result'`

I need to know how to fix this error? 
Please let me know any further details require.

Thanks.

**Comment by ttmc** [comment]
Is Tendermint running in the two nodes that give the error message? To check, you could ssh into the node and do `ps -aux | grep tendermint`

Note: The docs you used are for Ubuntu 18.04. There might be slight differences when using Ubuntu 16.04.

**Comment by riyazlafir** [comment]
when I execute  `ps -aux | grep tendermint`  . returns following outputs in the all 4 nodes,

ubuntu    2877  0.0  4.4 462452 45288 pts/0    Sl+  07:18   0:00 bigchaindb_ws_to_tendermint
root      2886  0.0  0.3  55740  3976 pts/1    S+   07:18   0:00 sudo tendermint node
root      2887  2.6  3.8  66448 38848 pts/1    Sl+  07:18   0:00 tendermint node
ubuntu    2903  0.0  0.1  12944  1084 pts/2    S+   07:18   0:00 grep --color=auto tendermint

**Comment by ttmc** [comment]
It's very strange that `http://<host_ip>:9984/api/v1/validators` works for two of your notes (two `host_ip` values) but not for two other nodes. It's almost as if the failing nodes were set up differently somehow. Did you try nuking the bad nodes and setting up fresh new ones in their place?

I wonder why you're seeing both `tendermint node` _and_ `sudo tendermint node`, with different process ids. You don't need to use `sudo` to run Tendermint, or at least you shouldn't.

**Comment by kansi** [comment]
@riyazlafir  @ttmc is right, I would also like to know why are there two tendermint instances on the same vm?

Also, could you please share the output of `curl localhost:26657/validators` from all nodes?
If you cannot get the output of the above command then most likely Tendermint hasn't been started properly.

**Comment by riyazlafir** [comment]
When I run `curl localhost:26657/validators`.It returns 

working two nodes : 
`{
  "jsonrpc": "2.0",
  "id": "",
  "result": {
    "block_height": "193",
    "validators": [
      {
        "address": "104B8F4B19DD50718639D89BFA34A31549F47B92",
        "pub_key": {
          "type": "tendermint/PubKeyEd25519",
          "value": "9KyVM6ZwvQQDyq9ZRA4C1D8sw+f/h8gJL7J8YQvkvMU="
        },
        "voting_power": "10",
        "accum": "-10"
      },
      {
        "address": "E9FE23AFDB9DF7E982B300E0BCEED26EEA099CA4",
        "pub_key": {
          "type": "tendermint/PubKeyEd25519",
          "value": "ttuQEkezd9bX0RCXfxK0NzUrVXXl14AwE+pJlDZCbkc="
        },
        "voting_power": "10",
        "accum": "10"
      }
    ]
  }
}`

and error two nodes gives,
`{
  "jsonrpc": "2.0",
  "id": "",
  "error": {
    "code": -32603,
    "message": "Internal error",
    "data": "Could not find validator set for height #0"
  }
}`

I can run all 4 nodes only with tendermint node with sudo.
without sudo getting following error
```
ubuntu@ip:~$ tendermint node
open /home/ubuntu/.tendermint/config/priv_validator.json: permission denied
```

**Comment by ldmberman** [comment]
@riyazlafir there are only 2 validators in your `/validators` output. Did you specify 4 validators in all of the 4 `genesis.json` files? See [here](https://docs.bigchaindb.com/projects/server/en/latest/simple-network-setup.html#coordinator-initialize-the-network).

**Comment by riyazlafir** [comment]
yes I have used the same genesis.json file for all 4 nodes
this is the my genesis.json
`{
  "genesis_time": "2018-07-24T00:38:16.190478116Z",
  "chain_id": "test-chain-wERhSn",
  "consensus_params": {
    "block_size_params": {
      "max_bytes": "22020096",
      "max_txs": "10000",
      "max_gas": "-1"
    },
    "tx_size_params": {
      "max_bytes": "10240",
      "max_gas": "-1"
    },
    "block_gossip_params": {
      "block_part_size_bytes": "65536"
    },
    "evidence_params": {
      "max_age": "100000"
    }
  },
  "validators": [
    {
      "pub_key": {
        "type": "tendermint/PubKeyEd25519",
        "value": "9KyVM6ZwvQQDyq9ZRA4C1D8sw+f/h8gJL7J8YQvkvMU="
      },
      "power": "10",
      "name": "firstMachine"
    },
	{
      "pub_key": {
        "type": "tendermint/PubKeyEd25519",
        "value": "QrUAX1Wnb46PNOWRthcPSiy4YdE4Sx2YqhSwFLso4WU="
      },
      "power": "10",
      "name": "ThirdMachine"
    },
   {
      "pub_key": {
        "type": "tendermint/PubKeyEd25519",
        "value": "ttuQEkezd9bX0RCXfxK0NzUrVXXl14AwE+pJlDZCbkc="
      },
      "power": "10",
      "name": "secondMachine"
    },
	
	 {
      "pub_key": {
        "type": "tendermint/PubKeyEd25519",
        "value": "d+RtWf6X6oyP/GeLLAGY0SET0eC0V1TLyO/B541CVlk="
      },
      "power": "10",
      "name": "FourthMachine"
    }
  ],
  "app_hash": ""
}
`

**Comment by ldmberman** [comment]
Did you try to run a smaller set of the same validators previously? Just in case, you can not increase an existing network by updating `genesis.json` - if you want to include an existing node into a new network, you need to reset the data by `tendermint unsafe_reset_all`.

**Comment by ldmberman** [comment]
Ok, all good on that front then.

Could you, please, post the BigchainDB logs of the failing nodes?

**Comment by riyazlafir** [comment]
[bigchaindb-errors.log](https://github.com/bigchaindb/bigchaindb/files/2240763/bigchaindb-errors.log)

**Comment by ldmberman** [comment]
@riyazlafir in this file I see some of the error logs you reported in the other [issue](https://github.com/bigchaindb/bigchaindb/issues/2400), the one about the missing index. Did you also run 4 nodes when you reproduced that issue? Or did you re-use that node for the new setup?

In any case, since you had to do `bigchaindb drop` on this machine, you also need to execute `tendermint unsafe_reset_all` to clean up the corresponding Tendermint data. It is not very convenient that you have to run 2 commands now - improving this is on our radars.

Also, according to the RPC response, the two working nodes have committed 193 blocks as a 2-node cluster somehow. Did you create the 4-node `genesis.json` before or after running them?

So, in order to get a running 4-node cluster, on each of the 4 machines do:

1. Stop BigchainDB and Tendermint.
2. Execute `bigchaindb -y drop` and `tendermint unsafe_reset_all`.

Hope this helps.

**Comment by riyazlafir** [comment]
@ldmberman   Great it works fine. 👍  
Thanks. I need to if I need to another node in future, do I need to reset tendermint node and drop the db ? If yes will I lose my existing data?

**Comment by ldmberman** [comment]
@riyazlafir awesome!

We are currently working on the process of adding new validators to the network. We expect to finish the work within the next 2-3 weeks. It is one of the essential parts of the upcoming stable release.

Until then, the only way to add new nodes is to build a new cluster from scratch.

Yes, you lose the existing data when you do `bigchaindb drop` and `tendermint unsafe_reset_all`.

**Comment by riyazlafir** [comment]
@ldmberman great .

Thanks for the support.

**Comment by rupam150** [comment]
hi @riyazlafir @ldmberman @ttmc  i tried to host the netwrok in aws i created one instance and created api image of other three ( they have different pub and priv key though ) but when i tried to open http;//hostname:26657/api/v1/validators
i got only one validator in return , what coulld be the reason , also i have configured the genesis and config.toml as mentioned in the document , please helpstuck from a month ....

**Comment by ttmc** [comment]
I have no idea. I haven't been involved with this project since 2019.
