### ISSUE TITLE
[installation error]     build/temp.linux-x86_64-3.6/_openssl.c:22:24: fatal error: pyconfig.h: No such file or directory

### ISSUE THREAD

**Issue by xiaoxi99cs** [bigchaindb/bigchaindb#2431]
Hi guys, 

I install bigchaindb following this doc: https://docs.bigchaindb.com/projects/server/en/latest/simple-network-setup.html

**Environment** : I am using AWS
Ubuntu Server 16.04 LTS (HVM), SSD Volume Type - ami-5e8bb23b
Ubuntu Server 16.04 LTS (HVM),EBS General Purpose (SSD) Volume Type. Support available from Canonical (http://www.ubuntu.com/cloud/services).

> ubuntu@ip-172-31-34-26:~$  pip3 -V
> pip 18.0 from /home/ubuntu/.local/lib/python3.6/site-packages/pip (python 3.6)
> ubuntu@ip-172-31-34-26:~$ python3 -V
> Python 3.6.5

I run the following commands: 

sudo apt update
sudo apt full-upgrade
sudo apt install -y python3-pip libssl-dev
**I got error when run this command:**  sudo pip3 install bigchaindb==2.0.0b5

==============The following is the error: =====================
    build/temp.linux-x86_64-3.6/_openssl.c:22:24: fatal error: pyconfig.h: No such file or directory
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    
    ----------------------------------------
  Rolling back uninstall of cryptography
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-qngv1kx7/cryptography/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-lt9e91tg/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-qngv1kx7/cryptography/

Any suggestions?

**Comment by xiaoxi99cs** [comment]
Firstly, downgrade pip since pip10+  no longer uninstalls distutils packages.   

`sudo -H pip3 install pip==8.1.1`

And then uninstall PyYAML 
`sudo python3 -m pip uninstall PyYAML`

**Comment by ttmc** [comment]
@xiaoxi99cs I think the reason you ran into issues with the necessary apt packages is that the docs page in question is for *Ubuntu 18.04* (not 16.04).

As for PyYAML, wow, that's annoying. Here's a question & answer on StackOverflow with more details:

https://stackoverflow.com/questions/49911550/how-to-upgrade-disutils-package-pyyaml

Also, two days ago, @drcrook1 opened an issue about this very problem in the PyYAML repo:

https://github.com/yaml/pyyaml/issues/210

**Comment by xiaoxi99cs** [comment]
Got it. thank u . @ttmc btw, when I install bigchaindb, do I need to use virtualenv? I guess not necessary.

**Comment by ttmc** [comment]
@xiaoxi99cs You don't need to use virtualenv when installing bigchaindb. It's handy if you want to create a Python environment where you have total control over the Python version, the pip version, and all the installed packages (i.e. inside the virtualenv).
