### ISSUE TITLE
MIMO `sign_transaction` with threshold conditions can yield cryptoconditions.KeyError

### ISSUE THREAD

**Issue by diminator** [bigchaindb/bigchaindb#244]
When providing an array of inputs to a `create_transaction`, that contains multisigs of different signature,
an KeyError is thrown upon `sign_transaction` by the cryptoconditions library on line

```
ThresholdSha256Fulfillment.calculate_smallest_valid_fulfillment_set(self.threshold, subfulfillments)['set']
```
in `cryptoconditions.types.threshold_sha256.py` due to returned `{'size': inf}` when `self.threshold > len(subfulfillments)`

This should be checked/catched in `sign_transaction`

**Comment by r-marques** [comment]
@diminator is this still valid?

**Comment by diminator** [comment]
addressed by [issue 6 in cryptoconditions](https://github.com/bigchaindb/cryptoconditions/issues/6)
