### ISSUE TITLE
Is any feature will available like AND ,OR operators in future ?

### ISSUE THREAD

**Issue by riyazlafir** [bigchaindb/bigchaindb#2462]
Hi,
Currently, in Bigchaindb for searching purpose, we have mainly two methods such as search assets and search metadata. These two options will return all the data related to a search string.

Ex:  http://<host>/api/v1/assets?search=101001

Is there are any option will be available like this,

nosql : db.inventory.find( { status: "A", qty: 30  } )
sql : SELECT * FROM inventory WHERE status = "A" AND qty = 30

Bigchaindb: http://<host>/api/v1/assets?status=101001&qty=30

Thanks.

**Comment by ttmc** [comment]
You can already do that now: just connect directly to the MongoDB instance in one of the nodes and send it  any query that MongoDB can handle. For more details, see https://docs.bigchaindb.com/en/latest/query.html

Note: The BichainDB Testnet doesn't currently give external users direct access to MongoDB.
