### ISSUE TITLE
Open source reusable React components for building front-ends on top of BigchainDB

### ISSUE THREAD

**Issue by SohKai** [bigchaindb/bigchaindb#247]
Abstract
-----------

Release a set of high quality front-end components to help us and others build apps, hopefully on top of BigchainDB.

Motivation
--------------

As we internally build more apps (and example apps), a set of quality, self-contained front-end components helps us move quicker with less bugs. Open sourcing this component library will allow other developers to benefit from our work and help them build their apps. We're opinionated and like using React for our front-ends, so we recommend it to our friends too.

The goal is not to replace existing front-end component libraries like [React-Bootstrap](https://react-bootstrap.github.io/), [Material-UI](http://www.material-ui.com/), [React-Toolbox](http://react-toolbox.com/), or etc, but to provide additional, more involved, components that live on top of the basic UI components that these other libraries provide; for example, an uploader.

We've been secretly building this out as ascribe/react-components, but now it's moving to BigchainDB.

Goals
--------

* Create a `bigchaindb/react-components` repo that will house current and future components
* Existing apps and demos should have their reusable components generalized and put into `react-components`

Tasks
--------

**Friday, May 6th:**
* [x] Upgrade dependencies to allow React 15 as a peer dependency
* [x] Create tiny boilerplate for initializing JS apps with Babel, Webpack, and React built in
* [ ] Create JS utils library for non-React utilities
* [ ] Overhaul ESLint configuration (also to help with BigchainDB's JS api)

**Friday, May 13th:**
* [ ] Resolve outstanding pull-requests in ascribe/react-components
* [ ] Implement theming, probably using [react-css-themr](https://github.com/javivelasco/react-css-themr)
* [ ] Use components in ascribe/onion
* [ ] Use components in bigchaindb/bigchaindb-examples
* [ ] Finish documentation of components
* [ ] Add unit tests for the easy stuff (ie. not uploader)
* [ ] Move ascribe/react-components to bigchaindb/react-components
* [ ] Publish to npm

**Comment by wrigley** [comment]
@SohKai 

I copied this to https://github.com/bigchaindb/org/issues/14 so I'm closing this issue here.
