### ISSUE TITLE
sign_transaction fails with "TypeError: string indices must be integers"

### ISSUE THREAD

**Issue by bitcartel** [bigchaindb/bigchaindb#248]
`	tx_transfer_signed = b.sign_transaction(tx_transfer, testuser1_priv)
`
Results in an error:
```
  File "/usr/local/lib/python3.4/dist-packages/BigchainDB-0.3.0-py3.4.egg/bigchaindb/util.py", line 489, in get_fulfillment_message
    previous_tx = b.get_transaction(fulfillment['input']['txid'])
TypeError: string indices must be integers
```

Where tx_transfer is:

```
tx_transfer = {
  "id": "c42c55f59ef14840e71dc1df6d93c1a71f78761228164c02200baaf9c52fcfbc",
  "transaction": {
    "conditions": [
      {
        "cid": 0,
        "condition": {
          "details": {
            "bitmask": 32,
            "public_key": "J5c2aiAFQfGMJ2bjhYjncpzM9SbSRk5vYosmuSYYB3hH",
            "signature": null,
            "type": "fulfillment",
            "type_id": 4
          },
          "uri": "cc:4:20:_cSbP2BD6MOB26LBVgUGYHqYfrYi3U_tRQ5DtnRaGog:96"
        },
        "new_owners": [
          "J5c2aiAFQfGMJ2bjhYjncpzM9SbSRk5vYosmuSYYB3hH"
        ]
      }
    ],
    "data": null,
    "fulfillments": [
      {
        "current_owners": [
          "C5T2mqSmZbZA76mFgVYuXeKAY8NCG1dbkHk353pigfm9"
        ],
        "fid": 0,
        "fulfillment": null,
        "input": "ff68f58a7a5dc0cf1be82bac7458380e2404330ff823e0861c4325ea27a5038d"
      }
    ],
    "operation": "TRANSFER",
    "timestamp": "1462428844.375934"
  },
  "version": 1
}
```

**Comment by diminator** [comment]
Hi @bitcartel 

a few questions:

- `tx_transfer = {} {...`: I am assuming the first curly braces are a typo?
- How did you create the transaction?

```
"fulfillments": [
      {...
        "input": "ff68f58a7a5dc0cf1be82bac7458380e2404330ff823e0861c4325ea27a5038d"
      }
    ],
``` 

In the current version `0.3.0` , we support multiple inputs and outputs. Hence the input to a transaction should be of the form

```
"input": {
    "txid": "ff68f58a7a5dc0cf1be82bac7458380e2404330ff823e0861c4325ea27a5038d",
    "cid": <some integer, in this case 0>
}
```

For more info, see https://bigchaindb.readthedocs.io/en/latest/python-server-api-examples.html#transfer-the-digital-asset

**Comment by bitcartel** [comment]
Oops, typo.  {} fixed now.

Using 0.3.0, commit 2b34c939b20de6cb3c545b89e6b93c428297f03d

Transaction created like this, based on API docs:

```
	b = bigchaindb.Bigchain()
	testuser1_priv, testuser1_pub = bigchaindb.crypto.generate_key_pair()
	digital_asset_payload = {'msg': 'Hello BigchainDB!'}
	tx = b.create_transaction(b.me, testuser1_pub, None, 'CREATE', payload=digital_asset_payload)
	tx_signed = b.sign_transaction(tx, b.me_private)
	b.write_transaction(tx_signed)
	# wait for asset in loop (sleep, poll)
	tx_retrieved = b.get_transaction(tx_signed['id'])

	testuser2_priv, testuser2_pub = bigchaindb.crypto.generate_key_pair()
	tx_transfer = b.create_transaction(testuser1_pub, testuser2_pub, tx_retrieved['id'], 'TRANSFER')
	tx_transfer_signed = b.sign_transaction(tx_transfer, testuser1_priv)
```

**Comment by r-marques** [comment]
@bitcartel like @diminator mentioned since version 0.3.0 an input also needs to specify the `condition id` (since we added support for multiple inputs and outputs).

In your previous code you should replace `tx_retrieved = b.get_transaction(tx_signed['id'])` with
```python
# Retrieve the transaction with condition id
tx_retrieved_id = b.get_owned_ids(testuser1_pub).pop()
```

More details here http://bigchaindb.readthedocs.io/en/latest/python-server-api-examples.html#transfer-the-digital-asset

**Comment by bitcartel** [comment]
Thanks. Might be worth removing older docs like 0.2 and just keeping 'latest' and the most recent point release.

**Comment by bitcartel** [comment]
Also, after creating a tx or transfer and then writing it to bigchaindb, I enter into a loop where I sleep and poll to retrieve the tx.  It takes around 5 seconds each time to retrieve a tx.  It's the same if I create and write multiple tx to bigchaindb, and try to retrieve them all.  Is bigchaindb polling rethinkdb every 5 seconds?  Is that why tx are not retrieved quicker than this?  Is this configurable?

**Comment by r-marques** [comment]
> If user1 has received many transactions, are the spendable outputs returned by get_owned_ids() unsorted or in some order e.g. timestamp, most recent tx is at end of list?

The outputs are not ordered.

> Also, after creating a tx or transfer and then writing it to bigchaindb, I enter into a loop where I sleep and poll to retrieve the tx. It takes around 5 seconds each time to retrieve a tx. It's the same if I create and write multiple tx to bigchaindb, and try to retrieve them all. Is bigchaindb polling rethinkdb every 5 seconds? Is that why tx are not retrieved quicker than this? Is this configurable?

The 5 seconds is an hardcoded timeout in the block creation method. What we do is try to bundle up to 1000 transactions per block for performance reasons, so when a node is creating a block and if has fewer then 1000 transactions it waits up to 5 seconds for new incoming transactions. That is the reason for the wait. We do this to avoid creating a lot of small blocks if the transactions are coming in at a slow pace. We will be looking at ways to optimize this timeout (or possibly remove it).

**Comment by r-marques** [comment]
relates to #427

Closing this since all questions seemed to have been answered
