### ISSUE TITLE
Database setup untested

### ISSUE THREAD

**Issue by rhsimplex** [bigchaindb/bigchaindb#249]
The code for setting up RethinkDB appears to live in `bigchaindb\db\utils.py`, but is not tested directly.  Instead, the code is (mostly) copy pasted into `tests\db\conftest.py`.  The function in `utils.py` should be imported into `conftest.py`.

The current setup is error prone because it must be maintained in two places, for instance the code in `conftest.py` doesn't set up an index on `transaction_id`, while `utils.py` does.

**Comment by sohkai** [comment]
@r-marques I believe we can close this now, after everything we've been doing with testing the schema?
