### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by dolphinsd** [bigchaindb/bigchaindb#2497]
Hitting testnet with this transaction causes internal server error.

```json
{
  "asset": {
    "data": {
      "city": "San Diego",
      "temperature": "74",
      "datetime": "2018-08-30T13:20:01.2177734-07:00"
    }
  },
  "id": "a1bfc2d08819f7d9acc764379fe40f73b3c1b55fa723b5f986b54e3c54e5f59b",
  "inputs": [
    {
      "fulfillment": "pGSAINdamAGCsQq31Uv-08lkBzoO4XLz2qYjJa8CGmj3B1EagUDlVkMAw2CscpCG4syAboKKh",
      "fulfills": null,
      "owners_before": [
        "1CQ2iq1dCX66yE1oSn1ksVpRbj7ezPjPJ6BcwEMCJYo"
      ]
    }
  ],
  "metadata": {
    "metadata": [
      {
        "Key": "what",
        "Value": "My first transaction"
      }
    ]
  },
  "operation": "CREATE",
  "outputs": [
    {
      "amount": "1",
      "condition": {
        "details": {
          "public_key": "1CQ2iq1dCX66yE1oSn1ksVpRbj7ezPjPJ6BcwEMCJYo",
          "type": "ed25519-sha-256"
        },
        "uri": "ni:///sha-256;MAAAACgAAACAAAAAIAAAAAAM4v7QDNWRVUssyo7jvw5NoPLDDxt8QykUkO2d82Ww?fpt=ed25519-sha-256&cost=131072"
      },
      "public_keys": [
        "1CQ2iq1dCX66yE1oSn1ksVpRbj7ezPjPJ6BcwEMCJYo"
      ]
    }
  ],
  "version": "2.0"
}
```

**Comment by ttmc** [comment]
"Internal Server Error" isn't a very informative error message, I know. It doesn't help me much more than it helps you. We want to make the error messages more informative, but there are a few other things that are currently higher-priority for our team.

Meanwhile, I wonder what happens if you try building the exact same transaction with one of the other drivers. Is the final hash (id) the same? If so, then it's not a problem with your C# driver and we need to investigate more deeply.

**Comment by ttmc** [comment]
Actually, there's one more thing that might go wrong with a new driver: the HTTP POST request might have problems. Maybe it's not including all the necessary HTTP request headers? Does your POST request include the `Content-Type: application/json` header? Maybe it's not encoding the HTTP request body properly?

**Comment by ttmc** [comment]
@dolphinsd Are you still having this issue now that your C# driver is working?

**Comment by ttmc** [comment]
@dolphinsd We haven't heard back from you and so we're going to close this issue. If it's still an issue, then feel free to re-open it or, if that's not possible, then just open a new issue.
