### ISSUE TITLE
get_tx_by_payload_hash

### ISSUE THREAD

**Issue by rhsimplex** [bigchaindb/bigchaindb#250]
The core function `get_tx_by_payload_hash` has no unit tests.  I can write some of course, but it might be faster if the author of the function could (looking at you, @wrigley).

**Comment by r-marques** [comment]
I can create some tests, although this functionality will change when we add better support for digital assets

**Comment by rhsimplex** [comment]
Thanks, it would be helpful for #192

**Comment by r-marques** [comment]
resolved in #411
