### ISSUE TITLE
Problem: Events API returns all txs recorded by Tendermint in blocks, including invalid ones

### ISSUE THREAD

**Issue by ttmc** [bigchaindb/bigchaindb#2506]
We recently realized that if BigchainDB's response to DeliverTx tells Tendermint that a transaction is invalid, Tendermint still records that transaction in its block. (BigchainDB _doesn't_ record invalid transactions in MongoDB.) That's not a bug on Tendermint's part: invalid transactions are needed as proof of Byzantine behavior, so Byzantine nodes can be punished later on. There's a good discussion of this and related ideas in the Tendermint issue https://github.com/tendermint/tendermint/issues/2175 .

## The Problem

Currently, the Events API reports the latest block of transactions _according to Tendermint_, so there might be invalid transactions in that block.

## A Solution Idea

MongoDB now has something like RethinkDB's "changefeeds" called "[Change Streams](https://docs.mongodb.com/manual/changeStreams/)." They were new as of MongoDB 3.6. See "[An Introduction to Change Streams](https://www.mongodb.com/blog/post/an-introduction-to-change-streams)" in the MongoDB Blog. BigchainDB could get a feed of all the latest valid transactions by subscribing to a change stream on [the transactions collection](https://bigchaindb.readthedocs.io/en/latest/query.html#example-documents-from-transactions) in MongoDB.

BigchainDB could return the same info as what the Events API currently returns.

Question: [The docs](http://docs.bigchaindb.com/projects/server/en/master/events/websocket-event-stream-api.html#id3) say that what gets returned is something like:

```js
{
    "transaction_id": "<sha3-256 hash>",
    "asset_id": "<sha3-256 hash>",
    "block_id": "<int>"
}
```
Is that right? If so, shouldn't it be giving the "block_height" rather than the "block_id"?

**Comment by vrde** [comment]
@ttmc thanks for the write up.

> Is that right? If so, shouldn't it be giving the "block_height" rather than the "block_id"?

We use `block_id` because it was in the original event stream specification, anyway it is filled with the `block_height` of the block:

https://github.com/bigchaindb/bigchaindb/blob/8e55b11da2bec4b576e85bd9ee56c30b04812c28/bigchaindb/event_stream.py#L49-L52

**Comment by ttmc** [comment]
The [HTTP API uses "block_height" as a query parameter](http://docs.bigchaindb.com/projects/server/en/master/http-client-server-api.html#get--api-v1-blocks-block_height) and [the `blocks` collection records the block height inside the value of the "height" key](https://docs.bigchaindb.com/en/latest/query.html#example-document-from-blocks). I think it would be more consistent to call it the block height everywhere.
