### ISSUE TITLE
Problem: Server docs failing to build on ReadTheDocs

### ISSUE THREAD

**Issue by ttmc** [bigchaindb/bigchaindb#2511]
1. In the bigchaindb/cryptoconditions repo, pull request https://github.com/bigchaindb/cryptoconditions/pull/114 upgraded PyNaCl from `PyNaCl~=1.1.0` to `PyNaCl~=1.2.1` in setup.py
1. We did a new release of the `cryptoconditions` package, version 0.7.3, including that change and that change only. The previous version was 0.7.2.
1. In this repo (bigchaindb/bigchaindb), in setup.py, `cryptoconditions~=0.7.2` so it automatically upgraded to 0.7.3 on its own
1. Builds of the `master` branch of the server docs started failing. For example, see https://readthedocs.org/projects/bigchaindb-server/builds/7732907/ . The error seems to be caused by the change in PyNaCl, e.g. "AttributeError: cffi library '_sodium' has no function, constant or global variable named 'crypto_box_seedbytes'" 

Strangely, the server docs build fine in our Travis CI tests, and locally on my machine.

**Comment by kansi** [comment]
Let's try the temporary solutions for the moment?
