### ISSUE TITLE
RethinkDB woes

### ISSUE THREAD

**Issue by thelinuxlich** [bigchaindb/bigchaindb#2523]
Hello, I'm kind of a Product Owner for RethinkDB(we are ressurrecting it!) and I knew about BigchainDB back in 2016, I read a very good article by you battletesting a big RethinkDB cluster to check if it would fit the workload of a blockchain.
And I totally understand you decided to migrate to MongoDB as the primary option, we are in a 2-year hiatus. but I'd like to know, besides the problem of the startup closing and the project stagnating, if you found any performance/usability/networking issues worth mentioning so we can take a look into it for the 2.5 roadmap, since the 2.4 release is nearly finished.

**Comment by ttmc** [comment]
Hi @thelinuxlich - thanks for asking. I'm glad to hear that RethinkDB isn't completely defunct. Generally speaking, we were quite happy with it.

Most of the people in our company (BigchainDB) who worked directly with RethinkDB are now gone. Such is the nature of tech, I suppose.

One thing I remember is that the changefeed was ephemeral, so if a node crashes and comes back up, it will just miss the changefeed events that came in while it was down. MongoDB does that differently: you can tail the MongoDB oplog, which is a "capped collection" and can be queried backwards in time. It's capped in that they only record a certain number of ops, and the older ones get discarded. MongoDB 3.6+ also has "change streams" but I haven't looked into those yet.
