### ISSUE TITLE
Problem: BigchainDB init process is breakable

### ISSUE THREAD

**Issue by shahbazn** [bigchaindb/bigchaindb#2534]
Steps to reproduce the issue:

1) start bigchaindb node
2) login to mongo shell and run the following commands to drop a collection:
```
use bigchain
db.asset.drop()
```
3) Restart BigchainDB

At this point while restarting BigchainDB does not check if all the expected collections are already created or not and appears to restart correctly.

Expected Behaviour should be that on re-start system should notify the user that node is in bad state

**Comment by ldmberman** [comment]
It is not generally possible to tell if an existing collection was removed or a new collection was created after a software update.

Moreover, we can not possibly detect the inconsistency after an arbitrary database change. Users are not supposed to update data themselves.

**Comment by shahbazn** [comment]
Arbitrary database changes for sure should not be validated on bigchaindb but in a recent event for some reason when user tried to init bigchaindb it failed after the stage when it had created the database but only two of the collections. When the user restarted bigchaindb and it seemed to have started correctly because it only checked if the database exists and moved on without creating collections.

**Comment by ldmberman** [comment]
@shahbazn note the update I made [here](https://github.com/bigchaindb/bigchaindb/pull/2520). Every collection that is not yet created is gonna be created upon `bigchaindb init` or `bigchaindb start`.

**Comment by shahbazn** [comment]
okay I will close the issue when the PR gets merged

**Comment by ldmberman** [comment]
@shahbazn #2520 fixes the collection initialisation so that if you interrupt the initialisation process, it will anyway be completed after the next attempt.

I was confused by the `asset.drop` example a little bit. BigchainDB might create some database artifacts very soon after the startup so dropping collections is not a good idea anyway.

**Comment by shahbazn** [comment]
#2520 is merged now so closing this issue
