### ISSUE TITLE
Error while setting up BigchainDB network

### ISSUE THREAD

**Issue by AbhishaB** [bigchaindb/bigchaindb#2574]
Hello,

I am trying to setup a single node BigchainDB network on Ubuntu 16.04 by following the instructions in http://docs.bigchaindb.com/projects/server/en/latest/simple-deployment-template/network-setup.html . Since these instructions are for Ubuntu 18.04 I have tried to modify where required. I installed Python3.6 using the below commands

```sudo add-apt-repository ppa:deadsnakes/ppa```
```sudo apt-get update```
```sudo apt-get install python3.6```

Python3.6 was installed successfully 

![image](https://user-images.githubusercontent.com/36175238/46160051-ce0d8e80-c24f-11e8-85c0-b62f61985d28.png)

After this I installed pip3 using the below commands

```sudo apt-get update```
```sudo apt-get -y install python3-pip```

pip3 installed successfully
![image](https://user-images.githubusercontent.com/36175238/46160305-55f39880-c250-11e8-99d3-25ba41d91ec6.png)

Now when I try to install the latest version of BigchainDB I am getting the below error.

![image](https://user-images.githubusercontent.com/36175238/46160594-21cca780-c251-11e8-8652-734a1b81d823.png)

Please could someone give some pointers on how to fix this error.

**Comment by ttmc** [comment]
I think you're going to have to change the default version of Python used by your system. One way to do that is to use virtualenv to create a virtualenv where the default Python is Python 3.6, and then to work inside that virtualenv.

```bash
virtualenv -p /usr/bin/python3.6 bdbenv
. bdbenv/bin/activate
```

Once you're inside that virtualenv, "pip" will already be a Python 3 version of pip, so you don't have to type "pip3"; you can just use "pip" to install Python packages.

Also, you will have to install one other OS-level dependency:

```bash
sudo apt install -y libssl-dev
```

**Comment by AbhishaB** [comment]
Hi,

Thank you for the instruction to change the version of python in my system. After changing the version to 3.6 I was able to resolve the error I was previously getting. Now when I run the command 

```sudo pip3 install bigchaindb==2.0.0b7```

I am running into the below errors.

![image](https://user-images.githubusercontent.com/36175238/46298689-af6c0800-c56d-11e8-877e-07567d49eb07.png)

![image](https://user-images.githubusercontent.com/36175238/46298732-cdd20380-c56d-11e8-9df1-46ad7a06cd23.png)

![image](https://user-images.githubusercontent.com/36175238/46298769-e4785a80-c56d-11e8-95d1-54eba0333689.png)

As can be seen in the screenshots, it is failing with a lot of "no such file or directory" error. Am I missing some files that I need to download before installing BigchainDB?

Thanks!

**Comment by ttmc** [comment]
The error with `python_requires` occurs if you use an old version of `pip` (or `pip3`) or `setuptools`. You need at least version 24.2.0 of `setuptools` and at least version 9.0.0 of `pip` (or `pip3`). Source: https://packaging.python.org/guides/distributing-packages-using-setuptools/#python-requires

If you don't know how to upgrade `pip` or `setuptools`, then Google it.

You will also get recent versions of `pip` and `setuptools` inside an active virtualenv. It seems you created a virtuaenv named `bdbenv` and you got it activated, but then you tried to install BigchainDB Server using:

`sudo -H pip install bigchaindb==2.0.0a4`

When you are in a virtualenv, you should not put "sudo -H" in front. Just use `pip install blahblahblah`. Also, you should try installing the latest version of BigchainDB Server, which (as I write this) is 2.0.0b7 (not 2.0.0a4).
