### ISSUE TITLE
bigchaindb message "internal server error" 500 on ubuntu dekstop virtual machine

### ISSUE THREAD

**Issue by massodasuki** [bigchaindb/bigchaindb#2584]
Hello BighchainDB team .

I am using virtual machine installed with Ubuntu Dekstop 18.01
I try to use 'python bigchaindb-driver' but the server gives "internal server error" after run the python program. Then I tried install pip_abci but nothing happen. 

![bigchaindb internal server error](https://user-images.githubusercontent.com/17770615/47144746-c004d800-d2fa-11e8-8ffd-0fd8cac366ae.JPG)

**Comment by ttmc** [comment]
The URL should be
```text
http://localhost:9984/api/v1/transactions/
```
not
```text
http://localhost:9984//api/v1/transactions/
```
(with two slashes after the 9984)

**Comment by massodasuki** [comment]
Ok sir..
.
I just delete the slash '/'
.
The same error occur. 
.
![bigchaindb internal server error2](https://user-images.githubusercontent.com/17770615/47145393-3ce48180-d2fc-11e8-9f1f-9a0030fb64ee.JPG)
.

**Comment by massodasuki** [comment]
I am sorry.
I did not install "monit" yet.
after installed the monit the error did not occurs. 

- sudo apt install monit
- bigchaindb-monit-config
- monit -d 1

![monit](https://user-images.githubusercontent.com/17770615/47145930-85506f00-d2fd-11e8-9884-1e8e57a39677.JPG)

my silly mistake .. tq for your respon sir .

**Comment by massodasuki** [comment]
I will close the issues .. i am sorry and tqvm @ttmc because talk to inspire me  .. :+1:
