### ISSUE TITLE
ERROR! 'mode' is not a valid attribute for a Task 

### ISSUE THREAD

**Issue by jdiegosierra** [bigchaindb/bigchaindb#2586]
#2577 
When I run stack.sh I got this error. Is not the first time I run this script but now it doesn't work.
```
diego@Diego:~/Proyectos/testchain$ bash ./stack.sh
Capturing output to logs/install-20181019-203244.log
Installation started at 2018-10-19 20:32:44
Using bigchaindb repo: 'bigchaindb/bigchaindb'
Using bigchaindb branch 'master'
Clonar en «bigchaindb»...
######################################################################### 100,0%
Configuring Dockers locally!
Operation Sytem: ubuntu
Version: 16.04
Dependencies already installed:[ ansible ]
ERROR! 'mode' is not a valid attribute for a Task

The error appears to have been in '/home/diego/Proyectos/testchain/bigchaindb/pkg/configuration/roles/py36/tasks/debian.yml': line 18, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:


- name: Creating files for python 3.6 installation
  ^ here

This error can be suppressed as a warning using the "invalid_task_attribute_failed" configuration
Finished stacking!
```

**Comment by ttmc** [comment]
Hi @jdiegosierra --- I'm afraid we don't have anyone maintaining that script (`stack.sh`) any more, so unless you figure out how to fix it, or someone else fixes it, I'm afraid it won't get fixed. If you do fix it, please feel free to submit a pull request.

**Comment by lana-shanghai** [comment]
@jdiegosierra 
The current best installation options are:

- a docker-all-in-one solution (installs Mongo, Tendermint, python, BigchainDB)
- an ansible script that runs nodes either on one machine, or several, and connects them into a network
- the manual step-by-step installation

All are available in the "Installation" section of the re-organized documentation http://docs.bigchaindb.com/en/latest/installation/index.html
The "Drivers" section describes the connectors used to send transactions to BigchainDB.
