### ISSUE TITLE
[proposal] I want to contribute by translating document

### ISSUE THREAD

**Issue by gamjapark** [bigchaindb/bigchaindb#2588]
[proposal] I want to contribute by translating document

Hello @ttmc ?

I want to translate docuemt of this repository to korean.

Can I translate your docs then PR?

I will refer 'https://docs.bigchaindb.com/projects/contributing/en/latest/ways-to-contribute/write-docs.html'.

**Comment by ttmc** [comment]
@gamjapark Yes, that would be okay with me. Please not that you'll have to agree to our CLA before we'll be able to merge any PR from you. See [BEP-16](https://github.com/bigchaindb/BEPs/tree/master/16) to understand what that means.

**Comment by gamjapark** [comment]
Thanks to your response, I confirmed the site and agreed to CLI. Thank you:)

**Comment by gamjapark** [comment]
BEGIN BLOCK

This is to confirm that I agreed to and accepted the BigchainDB Individual Contributor Agreement at https://www.bigchaindb.com/cla/ and to represent and warrant that I have authority to do so.

F6PqLRQiB0kqEudXdbbOZipLM2e6ZaRvTkiKCkpg3mOu8gQVZLIFl9Ufxy5EH83

END BLOCK

**Comment by ttmc** [comment]
Thanks @gamjapark --- Now when you make a pull request, we won't have to go through the CLA process.
