### ISSUE TITLE
Which latest version of BigchainDB and Bigchaindb-driver is compatible?

### ISSUE THREAD

**Issue by saikumar-neelam** [bigchaindb/bigchaindb#2589]
### Incompatible versions of cryptoconditions and python-rapid-json

Hi,
currently i installed BigchainDB 2.0.0b7 version on my centos7.4.
when i am installing bigchaindb-driver 0.6.1. it throws me warning about cryptoconditions and python-rapid-json versions are incompatible for BigchainDB server.
please help me about which two versions of BigchainDB server and bigchaindb-driver are compatible.

Thanks in Advance,
Regards
SAI KUMAR

**Comment by ttmc** [comment]
It seems you're running both BigchainDB Server and the BigchainDB Python driver on the same machine using the same Python environment (set of installed Python packages). That won't work. You should install and run each one in its own Python virtualenv (or VM, or Docker container, or I think you get the idea).
