### ISSUE TITLE
Tendermint is not initialising with MONIT...

### ISSUE THREAD

**Issue by saikumar-neelam** [bigchaindb/bigchaindb#2590]
### tendermint is not working
Hi,
I am using bigchaindb2.0.0b7 version and tendermint 0.22.8-40d6dc2e on my centos7.4
i have followed the same steps that are described in the bigchaindb server deployment documentation.
The link i followed is [http://docs.bigchaindb.com/projects/server/en/latest/simple-deployment-template/network-setup.html]
now i was unable to connect to the server using bigchaindb-driver and i have noticed the fault in tendermint when i run the command 
### monit status

The output of the above command is posted below.
![image](https://user-images.githubusercontent.com/44022482/47549756-a0813700-d91a-11e8-8c41-fbdcec30e350.png)

I also resetted the previous blockchain history by 
### tendermint unsafe_reset_all 
But there is no result. 
I also removed the .tendermint/ directory and tried again. But the issue couldn't be resolved.
please help to resolve this issue.

Thanks in Advance
Regards,
Sai Kumar

**Comment by ttmc** [comment]
I think the problem might be CentOS. Maybe try using Ubuntu 18.04 (e.g. on a VM in AWS or Azure) and if you can't get _that_ to work, then something is really wrong.

Also, there are slightly-newer "Simple Deployment Template" docs in the `master` branch, see:

http://docs.bigchaindb.com/projects/server/en/master/simple-deployment-template/index.html

**Comment by saikumar-neelam** [comment]
@ttmc 
Thanks for the reply,
If there is master branch then why those many versions are released.
Is BigchainDB supports only on ubuntu.
we have already installed on centos7.x systems. sometime it is working fine.But after sometime it is not working.
Please help me with a document so that i can work with them.

Thanks in Advance
Regards,
Sai Kumar

**Comment by ttmc** [comment]
I'm sorry but we do not support CentOS.

**Comment by saikumar-neelam** [comment]
@ttmc 
Thanks for the help. Now we are moving the setup to ubuntu 18.04 version

**Comment by virginialicerio** [comment]
Hi, i have the same problem. Trying to build 4 nodes network and in monit summary shows that Tendermint Process does noot exist. I´m using Ubuntu18.04.
Please, help me with this issue.

Thanks.
Virgínia

![image](https://user-images.githubusercontent.com/45876140/50043563-8a137400-005d-11e9-9ea7-01336f01f233.png)

**Comment by saikumar-neelam** [comment]
@virginialicerio 
Hi,  Check the peers and seeds that you had added to the config.toml and re run the script again. we had cleared the previous history and initialised tendermint from the beginning. 
Also check the tendermint.err.logs, It may help you
