### ISSUE TITLE
Is it possible to connect different nodes consisting different tendermint versions in a cluster?

### ISSUE THREAD

**Issue by saikumar-neelam** [bigchaindb/bigchaindb#2591]
### Persistent peers or seeds between different nodes with different tendermint versions
Hi,
I have installed tendermint on 7 different systems but with different versions. Is it possible to connect all.

Thanks in Advance,
Regards,
Sai Kumar

**Comment by ttmc** [comment]
Even if it's possible, it's probably not a good idea. In any case, that's a question about Tendermint, not about BigchainDB.
