### ISSUE TITLE
Connection refused Error

### ISSUE THREAD

**Issue by saikumar-neelam** [bigchaindb/bigchaindb#2593]
Hi,
I have tried connecting four of my local systems for bigchaindb. when i am using benchmarking tool for load test. it throws me an error as shown below.
I have used a command to run is:
bigchaindb-benchmark\
    --csv results/master-32proc-1000000sync.csv\
    --processes=32\
    --peer http://10.40.20.150:9984\
    --peer http://10.40.20.33:9984\
    --peer http://10.40.20.44:9984\
    --peer http://10.40.20.57:9984\
    send -r1000000 --mode=sync

I have followed the steps mentioned clearly from https://github.com/bigchaindb/BEPs/tree/master/23

![image](https://user-images.githubusercontent.com/44022482/47909319-8f559e80-deb5-11e8-99fc-f43b0d31a0ca.png)
please help to resolve this issue.
Thanks in Advance
Regards,
Sai Kumar N

**Comment by ttmc** [comment]
I don't know if this is what's wrong, or the only thing that's wrong, but since your nodes are using private IP addresses (`10.x.y.z`), see the tips on the page:

http://docs.bigchaindb.com/projects/server/en/latest/simple-deployment-template/troubleshooting.html

**Comment by saikumar-neelam** [comment]
@ttmc 
This was not tendermint issue. Tendermint is working fine.
bigchaindb-benchmark  throws an error

Regards,
Sai Kumar N

**Comment by Mrsulian** [comment]
Hello, have you solved it? I have the same problem.

**Comment by Mrsulian** [comment]
Hi, have you solved it? I meet the same problem.

@saikumar-neelam @ttmc
