### ISSUE TITLE
Error while setting up BigchainDB network 

### ISSUE THREAD

**Issue by trinayanbhatt** [bigchaindb/bigchaindb#2619]
After following all the steps for setting up the bigchaindb network when I try to install BigchainDB on my server using this command:

`sudo pip3 install bigchaindb`

I got following errors and the installation gets stopped without completion

![screenshot from 2019-01-09 14-28-10](https://user-images.githubusercontent.com/25535404/50889590-5b9b7580-141e-11e9-8bd0-227d8c309afc.png)

![screenshot from 2019-01-09 14-28-04](https://user-images.githubusercontent.com/25535404/50889602-635b1a00-141e-11e9-9f34-90c7b2fedeb9.png)

![screenshot from 2019-01-09 14-28-00](https://user-images.githubusercontent.com/25535404/50889610-6950fb00-141e-11e9-9b79-4e3ab033e9e4.png)

Can anyone please help as I have to setup BigchainDB network as soon as possible?

**Comment by ttmc** [comment]
You need to install some operating-system-level dependencies first, e.g. using
```text
sudo apt install -y python3-pip libssl-dev
```

For full instructions, see the Simple Deployment Template at http://docs.bigchaindb.com/projects/server/en/latest/simple-deployment-template/index.html

**Comment by trinayanbhatt** [comment]
I was following this documentation only and already installed the above mentioned dependencies but this still gives me this error.

**Comment by ttmc** [comment]
Are you using Ubuntu 18.04 or Ubuntu Server 18.04?
