### ISSUE TITLE
Unable to connect a node to an existing BigchainDB node

### ISSUE THREAD

**Issue by manolodewiner** [bigchaindb/bigchaindb#2622]
## Description
- BigchainDB version: 2.0.0-beta9
- Tendermint version: 0.22.8
- MongoDB version: 3.6.3
- OS: Ubuntu 18.04.1 LTS bionic

Unable to join a node to a BigchainDB network of one node. I get the following error when trying to connect the second node to the first one after adding the second validator with the [bigchaindb election CLI](http://docs.bigchaindb.com/projects/server/en/latest/server-reference/bigchaindb-cli.html#bigchaindb-election)
`Invalid commit -- wrong set size: 2 vs 1`
Looking at the [tendermint code ](https://github.com/tendermint/tendermint/blob/master/types/validator_set.go#L332) it seems that there are two validators but just one precommit.

## Steps to reproduce

- Run a single BigchainDB node
- `tendermint init` to create a second tendermint for the second node
- Via the  [bigchaindb election CLI](http://docs.bigchaindb.com/projects/server/en/latest/server-reference/bigchaindb-cli.html#bigchaindb-election) add the second validator to the first node.
- Once added by checking http://localhost:9984/api/v1/validators on the first node, run the second BigchainDB node (using the same genesis.json)

I also check the http://localhost:26657/dump_consensus_state tendermint endpoint in both nodes and I can see the two validators in both nodes with their respective voting power.
The first node has a voting power of 10, while the second has a voting power of 1.

**Comment by ttmc** [comment]
This is an unusual case, adding one node to a "network" that only has one node. Typically, you'd want the initial network (genesis file) to have at least four nodes, so it can tolerate one faulty node. In general, if you want the network to tolerate k faulty nodes, it must have 3k+1 nodes.

**Comment by manolodewiner** [comment]
Yes @ttmc you are right. I have tried with 4 nodes and it worked. I've just realised the problem was that I was adding the second validator in the `genesis` file of the second tendermint config, but the genesis files should be exactly the same.

**Comment by fr4nc1stein** [comment]
I would like to ask, since i followed the http://docs.bigchaindb.com/projects/server/en/latest/simple-deployment-template/network-setup.html

is the IP of COORDINATOR will be including in persistent_peers?
