### ISSUE TITLE
Ambiguity in the volume mounted to mongoDB docker

### ISSUE THREAD

**Issue by manjush08** [bigchaindb/bigchaindb#2633]
https://github.com/bigchaindb/bigchaindb/blob/7781f5aae8fd6a578175370d4f2775c3bfe2e9ce/pkg/configuration/roles/mongodb/defaults/main.yml#L26

# Description

MongoDB's default database storage path is `/data/db`. In the code referenced, why are we mounting the host's `/data/db` to the containers' `/data/db/main` path.

## Problem
* This keeps on increasing the Mongodb containers' size with increasing number of transactions.
* Also, the data gets lost when we purge the container.

**Comment by manjush08** [comment]
@ttmc Could you look at this issue?

**Comment by muawiakh** [comment]
I assume just changing the path to `/data/db` would work as well. Have to tried changing it?

**Comment by manjush08** [comment]
@muawiakh Yes it works, I was just curious why they did that.
