### ISSUE TITLE
How to run BigchainDB local in 4-node

### ISSUE THREAD

**Issue by huynhminhtufu** [bigchaindb/bigchaindb#2646]
I did those steps to have a BigchainDB **1 node** on local:

```
git clone https://github.com/bigchaindb/bigchaindb.git
cd bigchaindb
make run
```

But how to start a **4-node** BigchainDB, not mentioned in README.md

**Comment by ttmc** [comment]
One option is to follow the "[Simple Deployment Template](http://docs.bigchaindb.com/projects/server/en/latest/simple-deployment-template/index.html)" in the docs.
