### ISSUE TITLE
Unable to install bigchaindb server on ubuntu 18.04 LTS ?

### ISSUE THREAD

**Issue by drj1990** [bigchaindb/bigchaindb#2649]
# Do you want to:

- make a bug report? Then read below about what should go in a bug report.
Yes
- make a feature request or proposal? Then read [the page about how to make a feature request or proposal](https://docs.bigchaindb.com/projects/contributing/en/latest/ways-can-contribute/make-a-feature-request-or-proposal.html).
- ask a question about BigchainDB? Then [go to Gitter](https://gitter.im/bigchaindb/bigchaindb) (our chat room) and ask it there.
- share your neat idea or realization? Then [go to Gitter](https://gitter.im/bigchaindb/bigchaindb) (our chat room) and share it there.

# What Should Go in a Bug Report

- What computer are you on (hardware)?
```
2 CPU 
8 GB RAM
 Google Cloud VM

```
- What operating system are you using, including version. e.g. Ubuntu 14.04? Fedora 23?
```
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.2 LTS
Release:	18.04
Codename:	bionic
```

- What version of BigchainDB software were you using? Is that the latest version?
**Unable to install BigchainDB**
- What, exactly, did you do to get to the point where you got stuck? Describe all the steps so we can get there too. Show screenshots or copy-and-paste text to GitHub.

**Step 1.sudo apt update
Step 2.sudo apt full-upgrade
Step 3.sudo apt install -y python3-pip libssl-dev**

- Show what actually happened.
```
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    
    ----------------------------------------
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-87jm9mry/gevent/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-gmdh5zyy-record/
```

- Say what you tried to do to resolve the problem.
Tried to install 
`sudo apt install python3.6-dev
`
- Provide details to convince us that it matters to you. Is it for a school project, a job, a contract with a deadline, a child who needs it for Christmas?
**a contract with deadline**

We will do our best but please understand that we don't have time to help everyone, especially people who don't care to help us help them. "It doesn't work." is not going to get any reaction from us. We need _details_.

Tip: Use Github code block formatting to make code render pretty in GitHub. To do that, put three backticks followed by a string to set the type of code (e.g. `Python`), then the code, and then end with three backticks. There's more information about [inserting code blocks](https://help.github.com/articles/creating-and-highlighting-code-blocks/) in the GitHub help pages.

**Comment by ttmc** [comment]
Try updating pip to the latest version, i.e.

`sudo pip3 install -U pip`

To understand why that might help, see the comments on pull request https://github.com/bigchaindb/bigchaindb/pull/2645

This is all in the `master` branch of the docs, but there has been no new release since that update, so it's not in the `latest` (i.e. the default) docs. See:

http://docs.bigchaindb.com/projects/server/en/master/simple-deployment-template/set-up-node-software.html#install-bigchaindb-server

**Comment by drj1990** [comment]
> Try updating pip to the latest version, i.e.
> 
> `sudo pip3 install -U pip`
> 
> To understand why that might help, see the comments on pull request #2645
> 
> This is all in the `master` branch of the docs, but there has been no new release since that update, so it's not in the `latest` (i.e. the default) docs. See:
> 
> http://docs.bigchaindb.com/projects/server/en/master/simple-deployment-template/set-up-node-software.html#install-bigchaindb-server

This solution worked for me.
