### ISSUE TITLE
How to get bigchain node unique ID?

### ISSUE THREAD

**Issue by huynhminhtufu** [bigchaindb/bigchaindb#2651]
I run 4 BigchainDB nodes, is there **any unique ID that will be responded from BigchainDB Node HTTP API** (like CPU id or container id)?

I see that when open `http://localhost:9984`, it always return the same information for nodes:

```
{
api: {
v1: {
assets: "/api/v1/assets/",
blocks: "/api/v1/blocks/",
docs: "https://docs.bigchaindb.com/projects/server/en/v2.0.0b9/http-client-server-api.html",
metadata: "/api/v1/metadata/",
outputs: "/api/v1/outputs/",
streams: "ws://0.0.0.0:9985/api/v1/streams/valid_transactions",
transactions: "/api/v1/transactions/",
validators: "/api/v1/validators"
}
},
docs: "https://docs.bigchaindb.com/projects/server/en/v2.0.0b9/",
software: "BigchainDB",
version: "2.0.0b9"
}
```

**Comment by ttmc** [comment]
If you run the four nodes on four _different_ servers (or virtual machines, or equivalent), and each of those has its own public IP address, then that's their "unique id" (as you call it). `localhost` is just the "id" of the node from the point of view of some user who is on the same node (e.g. via ssh).
