### ISSUE TITLE
Should I request directly to BigchainDB's Mongo to do queries?

### ISSUE THREAD

**Issue by huynhminhtufu** [bigchaindb/bigchaindb#2653]
I see that BigchainDB doesn't have any **exposed API to get all assets** (which is in blocks), and if I directly do a query to a node's MongoDB, it's possible. So should I do that, or my idea is wrong in mind? 😢 

And what will happen if **I do some changes directly on a node's MongoDB**, will it be recovered by other nodes (auto - synchronous) or just become an invalid node (no more a validator)?

**Comment by huynhminhtufu** [comment]
In addition, how can I get all assets keeping by a certain owner (by public key)? Thank you.

**Comment by lana-shanghai** [comment]
> I see that BigchainDB doesn't have any **exposed API to get all assets** (which is in blocks), and if I directly do a query to a node's MongoDB, it's possible. So should I do that, or my idea is wrong in mind? 😢
> 
> And what will happen if **I do some changes directly on a node's MongoDB**, will it be recovered by other nodes (auto - synchronous) or just become an invalid node (no more a validator)?

Hi - if you run `mongo` in the terminal, you will see the mongo shell. There, run `show dbs` - it will show bigchain as one of the dbs. Run `use bigchaindb` .`Show collections` to see tables, e.g. blocks, assets, transactions. Command `db.assets.find()` to see all of your assets.

**Comment by lana-shanghai** [comment]
> I see that BigchainDB doesn't have any **exposed API to get all assets** (which is in blocks), and if I directly do a query to a node's MongoDB, it's possible. So should I do that, or my idea is wrong in mind? 😢
> 
> And what will happen if **I do some changes directly on a node's MongoDB**, will it be recovered by other nodes (auto - synchronous) or just become an invalid node (no more a validator)?

If you edit mongo data directly, bigchaindb will override the correct data, so if you insert a fake transaction, it will be deleted.
