### ISSUE TITLE
Can not install bigchaindb - tendermint

### ISSUE THREAD

**Issue by paulcristiann** [bigchaindb/bigchaindb#2664]
After command: sudo pip3 install bigchaindb==2.0.0b9
Output is: 
Traceback (most recent call last):
  File "/usr/local/bin/bigchaindb", line 6, in <module>
    from bigchaindb.commands.bigchaindb import main
  File "/usr/local/lib/python3.6/dist-packages/bigchaindb/__init__.py", line 12, in <module>
    from bigchaindb.core import App  # noqa
  File "/usr/local/lib/python3.6/dist-packages/bigchaindb/core.py", line 11, in <module>
    from abci.application import BaseApplication
  File "/usr/local/lib/python3.6/dist-packages/abci/__init__.py", line 2, in <module>
    from .server import ABCIServer
  File "/usr/local/lib/python3.6/dist-packages/abci/server.py", line 21, in <module>
    from .types_pb2 import Request
  File "/usr/local/lib/python3.6/dist-packages/abci/types_pb2.py", line 17, in <module>
    from github.com.tendermint.tendermint.crypto.merkle import merkle_pb2 as github_dot_com_dot_tendermint_dot_tendermint_dot_crypto_dot_merkle_dot_merkle__pb2
ModuleNotFoundError: No module named 'github.com.tendermint.tendermint'

Ubuntu version is: 18.04 LTS

**Comment by eckelj** [comment]
Hi, I've had the same issue with 2.0.0b9 lately. It seems like the tendermint based crpyot communication defined by protobuf cannot be resolved. Try to run pip install tm-abci to resovle the import. 

At the same time, I can recommend to update to bigchaindb==2.0.0 this works out of the box without any issues.

**Comment by jrb0043** [comment]
@eckelj I tried installing the version 2.0.0 with the command: 
sudo pip3 install bigchaindb==2.0.0
but it returns a version error.

**Comment by eckelj** [comment]
@jrb0043 just have a look at https://pypi.org/project/BigchainDB/#history
I use pip 19.2.3 with python 3.6 and are able to resolve the following 
with pip 
Collecting bigchaindb==
  ERROR: Could not find a version that satisfies the requirement bigchaindb== (from versions: 0.0.0.dev1, 0.1.0, 0.1.1, 0.1.2, 0.1.3, 0.1.4, 0.1.5, 0.2.0, 0.3.0, 0.4.0, 0.4.1, 0.4.2, 0.5.0, 0.5.1, 0.6.0, 0.7.0, 0.8.0, 0.8.1, 0.8.2, 0.9.0, 0.9.1, 0.9.2, 0.9.3, 0.9.4, 0.9.5, 0.10.0, 0.10.1, 0.10.2, 0.10.3, 1.0.0rc1, 1.0.0, 1.0.1, 1.1.0, 1.2.0.dev0, 1.2.0, 1.3.0, 2.0.0a1, 2.0.0a2, 2.0.0a3, 2.0.0a4, 2.0.0a5, 2.0.0a6, 2.0.0b1, 2.0.0b2, 2.0.0b3, 2.0.0b4, 2.0.0b5, 2.0.0b6, 2.0.0b7, 2.0.0b8, 2.0.0b9, 2.0.0)
ERROR: No matching distribution found for bigchaindb==

you can clearly see that 2.0.0 is available via pip and on pypi. Please verify your pip and python versions. Having everything we might be able to help you.

**Comment by jrb0043** [comment]
#pip -V
pip 19.2.3 from /usr/local/lib/python3.5/dist-packages/pip (python 3.5)

I tried upgrading the python version using:
# sudo apt-get install python3.6
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package python3.6
E: Couldn't find any package by glob 'python3.6'
E: Couldn't find any package by regex 'python3.6'

Any idea?

**Comment by eckelj** [comment]
which OS and version do you use?

**Comment by jrb0043** [comment]
> which OS and version do you use?

I was trying to install it on my Orange pi with ubuntu 16, just saw that in ubuntu 18 the pip returns all the versions... I guess i cant install it on my pi?

**Comment by davie-lab** [comment]
Well pip is quirky. It might has something to do with its cache.
I i know there is no official way to clear it. You could:
- try to install with --no-cache-dir option
- upgrade pip with pip3 install -U pip3
- or remove ~/.cache/pip/ content

Installing python3.6 on ubuntu 16.04 is doable, you have several options:
- use ppa (deadsnakes is the popular one it has arm builds too)
- compile python from source (it might take a while on pi)
- use platform-agnostic package manager (guix/nix/snap)

**Comment by lana-shanghai** [comment]
@paulcristiann @jrb0043 
The current best installation options are: 
- a docker-all-in-one solution (installs Mongo, Tendermint, python, BigchainDB)
- an ansible script that runs nodes either on one machine, or several, and connects them into a network
- the manual step-by-step installation
All are available in the "Installation" section of the re-organized documentation http://docs.bigchaindb.com/en/latest/installation/index.html 
The "Drivers" section describes the connectors used to send transactions to BigchainDB.

**Comment by paulcristiann** [comment]
Thank you, I will try these options.
