### ISSUE TITLE
Not able to run the Bigchaindb server

### ISSUE THREAD

**Issue by kalyanipullela** [bigchaindb/bigchaindb#2665]
Hello,

While I am trying to install BigchainDb and run the command **make run**, I am getting the following error:

![error](https://user-images.githubusercontent.com/38915385/66032913-e760af00-e523-11e9-8881-128963b27306.png)

I have checked with docker ps -a and the container is getting exited.
The bigchainDB is working in one system and not running in another system.
Can anyone help with this?

Thanks in Advance

**Comment by davie-lab** [comment]
Hi kalyanipullela!
Could you specify which release did you use? This issue is probably already addressed in recent release v2.0.0.

You could just pull recent changes, ensure that your working tree is clean and try again.
Let me know how it worked out for you.

**Comment by kalyanipullela** [comment]
> Hi kalyanipullela!
> Could you specify which release did you use? This issue is probably already addressed in recent release v2.0.0.
> 
> You could just pull recent changes, ensure that your working tree is clean and try again.
> Let me know how it worked out for you.

Hey davie-lab
The latest version of bigchaindb is now working fine
Thank you
