### ISSUE TITLE
Installation on ARM device

### ISSUE THREAD

**Issue by jrb0043** [bigchaindb/bigchaindb#2668]
Hi, Im trying to install bigchainDB on a Raspberry PI 3 Model B+ for a IoT project and I'm getting a lot of errors.

The first one says theres a fatal error ffi.h: No such file or directory.

My guesses are either its not ready for an ARM device or my ubuntu version is running on a x64 version and the installer is trying to install a 32bit i386 version, therefore it doesnt have the dependencies...

Any guide or any suggestion?
Thanks in advance.

**Comment by davie-lab** [comment]
I should be possible. But it will require more effort.

To install BigchainDB you need following components:
  - Mongodb
  - Tendermint (does not have a deb package, you'll need to comile it yourself)
  - Python3.6 (install from official repos or using ppa or build from source)
  - BigchainDB (installed with pip)

Do you have libffi-dev package installed? it might be a cause of ffi.h error.
What are you referring to by "installer"?
It would be more helpful if you could provide with more detailed specification of your setup and steps taken.

**Comment by jrb0043** [comment]
@davie-lab installing libffi-dev package helped a lot but I ended up with this error on the raspy:
https://ibb.co/gzYHLGV

**Comment by jrb0043** [comment]
Fixed using this:

sudo -H pip3 install --ignore-installed PyYAML

node working on raspberry pi 3 b+

**Comment by jrb0043** [comment]
Tendermint: cannot execute binary file: Exec format error

I will let you know if I'm success compiling it.

**Comment by davie-lab** [comment]
> Fixed using this:
> 
> sudo -H pip3 install --ignore-installed PyYAML

It probably has happened because you have installed PyYaml running setup.py by hand in the past. This is roughly analogous to running `make install` and not using system package manager. And now pip doesn't know how to uninstall it because it was not installed with pip in first place.

Well i'm guessing. But it's a good idea not to use distutils or pip on system level site-packages.

**Comment by davie-lab** [comment]
> Tendermint: cannot execute binary file: Exec format error
> 
> I will let you know if I'm success compiling it.

Where did you get the binary? It looks like you pulled binary for wrong target (arm/amd 32/64bit).

**Comment by jrb0043** [comment]
yeah i did pull the amd version, now i tried with 0.32.6 arm but theres a proble, when I use tendermint node it tells me that version its still not supported only 0.31.5. I though the last version would work, I will delete it and use the 31.5.

**Comment by davie-lab** [comment]
That is true. This info is present in [docs](http://docs.bigchaindb.com/projects/server/en/latest/simple-deployment-template/set-up-node-software.html#install-tendermint):
It should work with 0.31.5.

**Comment by jrb0043** [comment]
![image](https://user-images.githubusercontent.com/23051779/66878353-b79cb700-efb9-11e9-8330-6fd556c2db4e.png)

I got this error :/

**Comment by jrb0043** [comment]
I got this error @davie-lab:
![image](https://user-images.githubusercontent.com/23051779/66898269-2c431600-eff9-11e9-9233-01d6cb0adb12.png)

**Comment by jrb0043** [comment]
just deleted config and data from .tendermint, the node its working :)

**Comment by davie-lab** [comment]
Great! That was quite a challenge.
Did you try to `curl` 9984 port?
Have you tried making transaction?

**Comment by jrb0043** [comment]
I used the javascript driver with my service web and commited a block. Then the block propagated to all the nodes including the Raspberry pi.
