### ISSUE TITLE
Unable to connect to mongodb using bigchaindb/bigchaindb:all-in-one image

### ISSUE THREAD

**Issue by JulyElektra** [bigchaindb/bigchaindb#2673]
**Describe the bug**
After running bigchaindb/bigchaindb:all-in-one image using instruction on page https://docs.bigchaindb.com/projects/server/en/latest/appendices/all-in-one-bigchaindb.html I'm unable to connect to mongodb instance despite the port 27017 being forwarded.

**To Reproduce**
Try to connect to localhost:27017 from any mongo client. It will display timeout error.

**Expected behavior**
Successfully connects to mongodb.

**Logs or terminal output**
Mongo connection times out

**Desktop (please complete the following information):**
bigchaindb/bigchaindb:all-in-one image

**Comment by NaveenReddy198** [comment]
hii @JulyElektra can u share me how u fixed this problem.
