### ISSUE TITLE
Is the project still alive?

### ISSUE THREAD

**Issue by blaluc** [bigchaindb/bigchaindb#2680]
Hello,
I'm trying to evaluate BigchainDB but I soon realized that there are some blocking bugs still in open status. E.g.
https://github.com/bigchaindb/js-bigchaindb-driver/issues/268

It's a very blocking issue since, without fixing it, even the "Getting Started" example does not work.

Before investigating further, I would ask you if the project is still mainteined or not.

Many thanks in advance.

**Comment by davie-lab** [comment]
Hi @blaluc! The project has been inactive for a while. It is in the process of transitioning to IPDB. There is lot to be done but we are not too far from pulling it off. Thanks for mentioning the issue. I haven't paid enough attention to js libs. I'll address this issue soon. Stay tuned we have big plans for 2020

**Comment by ivanminutillo** [comment]
Hi!
i'm in the same situation of @blaluc, is it published somewhere the roadmap? 
can we consider stable the bigchaindb 2.0.0 release?
thanks :)

**Comment by zzappie** [comment]
Hi @ivanminutillo!
Bigchaindb 2.0.0 is frozen stable ;)
I am currently involved in an effort of simplification and unification of bigchaindb deployments. We are planing to implement integrations testsuite. And finally we'll through issues log that has been hanging for a looong time. I cant say for sure at the moment but my feeling is that 2.0.x will be supported long term and and than 3.0 will introduce some breaking changes and new features. We suffer from lack of involvement in in the project. So any help is welcome!

Announcements and bug fixes ahead!

**Comment by lana-shanghai** [comment]
> Hello,
> I'm trying to evaluate BigchainDB but I soon realized that there are some blocking bugs still in open status. E.g.
> [bigchaindb/js-bigchaindb-driver#268](https://github.com/bigchaindb/js-bigchaindb-driver/issues/268)
> 
> It's a very blocking issue since, without fixing it, even the "Getting Started" example does not work.
> 
> Before investigating further, I would ask you if the project is still mainteined or not.
> 
> Many thanks in advance.

Hi blaluc - is the issue still occurring when you run the code, as of today?

**Comment by lana-shanghai** [comment]
> Hi!
> i'm in the same situation of @blaluc, is it published somewhere the roadmap?
> can we consider stable the bigchaindb 2.0.0 release?
> thanks :)

The latest version of the js driver has the updates and works as expected. Closing the current issue.
