### ISSUE TITLE
ARG and v${TM_VERSION} is incorrect 

### ISSUE THREAD

**Issue by raisullip** [bigchaindb/bigchaindb#2691]
how can this work ?

https://github.com/bigchaindb/bigchaindb/blob/186cd874443e957fd23ebba20e72373baf63614d/Dockerfile-all-in-one#L4

https://github.com/bigchaindb/bigchaindb/blob/master/Dockerfile-all-in-one#L24
`/v${TM_VERSION}/`

**Comment by zzappie** [comment]
Thanks for the notice @raisullip!
