### ISSUE TITLE
AttributeError: module 'bigchaindb' has no attribute 'config_utils'

### ISSUE THREAD

**Issue by asimonov** [bigchaindb/bigchaindb#27]
i see the following error trying to run bigchaindb example:

Python 3.5.1 (v3.5.1:37a07cee5969, Dec  5 2015, 21:12:44) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> 
>>> from bigchaindb import Bigchain
>>> b = Bigchain()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/bigchaindb/core.py", line 47, in __init__
    bigchaindb.config_utils.autoconfigure()
AttributeError: module 'bigchaindb' has no attribute 'config_utils'
>>> b
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'b' is not defined

i am on mac os.

**Comment by vrde** [comment]
Hi @asimonov, thanks for your bug report, we just fixed the issue.

We uploaded `v0.1.1`, can you try to upgrade your package and test again? If you are using `pip`, then you can run `pip install --upgrade bigchaindb`.
