### ISSUE TITLE
asyncio.coroutine has been deprecated and will be removed in Python 3.10

### ISSUE THREAD

**Issue by tirkarthi** [bigchaindb/bigchaindb#2703]
**Describe the bug**
asyncio.coroutine has been deprecated and will be removed in Python 3.10. Using `async def` is recommended. Upstream issue : https://bugs.python.org/issue36921

**To Reproduce**

```
tests/web/test_websocket_server.py
55:@asyncio.coroutine
113:@asyncio.coroutine
138:@asyncio.coroutine

bigchaindb/web/websocket_server.py
99:    @asyncio.coroutine
121:@asyncio.coroutine
```

**Expected behavior**

Use `async def` syntax

**Desktop (please complete the following information):**
 - Distribution: [e.g. Ubuntu 18.04]
 - Bigchaindb version: master branch
 - Tendermint version:
 - Mongodb version:
- Python full version: 3.8

**Comment by zzappie** [comment]
Thanks for reporting @tirkarthi!
Fixed in #2710
