### ISSUE TITLE
upgrading from 2.0.0 to 2.2.0

### ISSUE THREAD

**Issue by dolphinsd** [bigchaindb/bigchaindb#2711]
Is there any documentation on how to perform upgrade. For example from version 2.0.0 and 2.2.0?

Thank you.

**Comment by dolphinsd** [comment]
shutting down instance and running sudo pip3 install bigchaindb==2.2.1 does the trick

**Comment by zzappie** [comment]
Hello!  Yes it will work for minor version changes but you need to check whether your current tendermint version is supported with new bigchaindb version or otherwise you'll probably need to do chain migration
