### ISSUE TITLE
Tendermint fails to create node,  due to connection refused from ABCIServer

### ISSUE THREAD

**Issue by javaandra** [bigchaindb/bigchaindb#2719]
Hi ! 

I have set up a BigchainDB node manually on a Ubuntu 20.04.1 LTS virtual machine. The BigchainDB version installed is 2.2.2 ( latest version) and the installed tendermint version is 0.31.5-d2eab536. For the installation I have followed the steps in [Simple Deployment Template](http://docs.bigchaindb.com/projects/server/en/latest/simple-deployment-template/deploy-a-machine.html).
I haven't added any peers or validators in Tendermint config.toml and genesesis.json yet, to ease the troubleshooting. 
MongoDb and Nginx are running.
These are the first entries in the bigchain confirguation file $HOME/.bigchaindb:
 ```
"server": {
        "bind": "127.0.0.1:9984",
        "loglevel": "info",
        "workers": null
    },
    "wsserver": {
        "scheme": "ws",
        "host": "0.0.0.0",
        "port": 9985,
        "advertised_scheme": "wss",
        "advertised_host": "10.5.6.72",
        "advertised_port": 443
    },
    "tendermint": {
        "host": "127.0.0.1",
        "port": 26657,
        "version": "v0.31.5"
    },
```
When I start the Bigchaindb and Tedermint services and monitor them with `monit -d 1`,  monit status all look OK. In bigchaindb.log the last message (after all the database initializations) is:
`"[INFO] (abci.app) ABCIServer started on port: 26658".`
There are no errors in **bigchaindb-errors.log**.
In **tendermint.err.log** the following error messages show up:
```
ERROR: Failed to create node: Error during handshake: Error calling Info: read tcp 127.0.0.1:48902->127.0.0.1:26658: read: connection reset by peer
ERROR: Failed to create node: Error during handshake: Error calling Info: read tcp 127.0.0.1:48922->127.0.0.1:26658: read: connection reset by peer
ERROR: Failed to create node: Error during handshake: Error calling Info: read tcp 127.0.0.1:48942->127.0.0.1:26658: read: connection reset by peer
```
In **tendermint.out.log** the folllowing messages are avaiable:
```
E[2021-01-07|17:50:27.049] abci.socketClient failed to connect to tcp://127.0.0.1:26658.  Retrying... module=abci-client connection=query err="dial tcp 127.0.0.1:26658: connect: connection refused"
E[2021-01-07|17:50:30.232] Stopping abci.socketClient for error: EOF    module=abci-client connection=consensus
E[2021-01-07|17:50:30.232] Stopping abci.socketClient for error: read tcp 127.0.0.1:49022->127.0.0.1:26658: read: connection reset by peer module=abci-client connection=query
```

Monit will try restaring the services every n seconds depending on the argument in monit -d n, which leads to an increase of memory, if running over night for example, as some  bigchaindb processess are not killed.
`netstat -tunlp ` is showing at first that the main bigchaindb process is listening on 0.0.0.0:26658, but short after the process disappears. 

At this point I am stuck and don't know how to troubleshoot. Any hint is highly appreciated.

Regards,
Andra

**Comment by javaandra** [comment]
I managed to fix the problem by doing the following steps:
-  Investigated the source of a warning in the bigchaindb.log, which admittedly I have first ignored:

`<frozen importlib._bootstrap>:219: RuntimeWarning: greenlet.greenlet size changed, may indicate binary incompatibility. Expected 144 from C header, got 152 from PyObject`

-  Upgraded gevent with the command:  `$ pip install --upgrade gevent`
-  Started bigchaindb in the background, manually (not using monit -d 1): `$ bigchaindb start & disown`
-  Started tendermint  in the background with output to the logfiles with `$ monit start tendermint`

After this, the connection between Tendermint and Bigchaindb was established and no more errors were written to tendermint.err.log.

**Comment by rupam150** [comment]
Hi @javaandra  i have created 4 node setup using bigchaindb and out of them 2 of them are running well and showing all the set of 4 validator , but of the rest two when i tried to start it always show TENDERMINT INITIALIZING in monit summary 
I checked the tendermint out log of the not working nodes and it shows something like this 
![tendermint out log of peer 4](https://user-images.githubusercontent.com/76766096/111303709-d570be80-867a-11eb-9b79-6f0c5ffc6140.PNG)


And the rest which i think are working shows 

![tendermint output log of peer 1](https://user-images.githubusercontent.com/76766096/111303787-f20cf680-867a-11eb-9c7b-751b1d62db3a.PNG)

Any kind of help from your side will be highly aprreciated .
Thank you in advance

**Comment by javaandra** [comment]
Hi @rupam150 , 

it might seem trivial, but my first questions would be:
- did you make sure to replace the `gensis.json` ( with the 4 validators) in all 4 Tendermint nodes? 
- did you modify the persistent_peer configuration in config.toml of each Tendermint node, so that it referrs the other 3 peers? ( avoid copy paste errors)
In worst case, if you have no valuable data to lose, you can try the command: tendermint unsafe_reset_all.

Regards,
Andra

**Comment by rupam150** [comment]
Hi @javaandra  , i have replicated the steps given in simple deployment template of Bigchaindb Doc and here is my genesis.json (which i copied in every node of the network ) 
{
  "genesis_time": "2021-03-11T06:12:00.851676087Z",
  "chain_id": "test-chain-ULmGQu",
  "consensus_params": {
    "block": {
      "max_bytes": "22020096",
      "max_gas": "-1",
      "time_iota_ms": "1000"
    },
    "evidence": {
      "max_age": "100000"
    },
    "validator": {
      "pub_key_types": [
        "ed25519"
      ]
    }
  },
  "validators": [
    {
      "address": "0C9D9FB3107DCE8714131556B4DA07F2B00EF833",
      "pub_key": {
        "type": "tendermint/PubKeyEd25519",
        "value": "8uXIALV9Q+gg6zJt/IDgxBt8Hp/ajNZNyoCHVX46uKo="
      },
      "power": "10",
      "name": "Node_1"
    },
    {
      "address": "6E0476AAA6B2B0017F8128D5BF1F6458668366FB",
      "pub_key": {
        "type": "tendermint/PubKeyEd25519",
        "value": "SvJNIzuuWoJNokWzfcRR8nBM3WMP3OhSsFGZAlzeE0M="
      },
      "power": "10",
      "name": "Node_2"
    },
    {
      "address": "30F0193A802D6176A1E676399CF32A55D934646F",
      "pub_key": {
        "type": "tendermint/PubKeyEd25519",
        "value": "yZHktDxNKVrzM7GPgSLzcGdnj72KDnGRkOsheMBViQw="
      },
      "power": "10",
      "name": "Node_3"
    },
    {
      "address": "5C3CE187297EF14CB9D7849A5BB81A6DCF803F8B",
      "pub_key": {
        "type": "tendermint/PubKeyEd25519",
        "value": "NNEr+P/WB6TfSag79KKDu3s+jtZiRiC3bLd2RbUh9S8="
      },
      "power": "10",
      "name": "Node_4"
    }
  ],
  "app_hash": ""
}


And for config.toml , here is the snap of my config.toml persistent peers ---

![config toml](https://user-images.githubusercontent.com/76766096/111422204-4c0dca80-8714-11eb-873f-b2b96b880607.PNG)

Morever i have also run tendermint unsafe_reset _all on the not working nodes but still it's the same .
