### ISSUE TITLE
Allow environment variables to specify location of config

### ISSUE THREAD

**Issue by SohKai** [bigchaindb/bigchaindb#272]
It'd be nice to also let users use an environment variable to specify their configuration locations (for `bigchaindb configure`, `bigchaindb init`, `bigchaindb start`, and any others?) so that they don't need to keep specifying it in every command. Especially useful when using docker.

**Comment by ttmc** [comment]
When determining the value of a configuration setting, this is what BigchainDB does:

1. Is it set in a local configuration file (`~/.bigchaindb` by default, but you can specify a different one using the `-c` command line option)? If yes, use that value.
2. Otherwise is it set by an environment variable? If yes, use that value.
3. Otherwise use the default value from `bigchaindb.__init__`

This is documented in the docs: http://bigchaindb.readthedocs.io/en/latest/configuration.html#order-of-precedence-in-determining-configuration-values

**Comment by SohKai** [comment]
@sbellem and I also discussed some potential enhancements to the initial start up sequence for `bigchaindb`:
* Could we ship a default configuration?
* Could we combine the `configure` and `init` commands or, with the above, skip one?
* The configuration file should be pretty formatted to be easily human readable and editable

Not a priority at all, but maybe it'd be nice to review this flow in the future?

**Comment by ttmc** [comment]
* The default configuration is in `bigchaindb.__init__`: https://github.com/bigchaindb/bigchaindb/blob/master/bigchaindb/__init__.py
* The `configure` command is for writing a new local config file. The `init` command is for initializing the RethinkDB database (e.g. create the database, create the two tables, define some indexes, create the genesis block).
* The configuration file is JSON, so you can use a JSON pretty printer to view it if you like.

**Comment by SohKai** [comment]
> The default configuration is in bigchaindb.__init__

If I plan to just use the default settings all the time, do I need to run the `configure` step at all?

> The configuration file is JSON, so you can use a JSON pretty printer to view it if you like.

I'm of the opinion we should pretty print this JSON ourselves rather than force users to do that.

**Comment by r-marques** [comment]
@SohKai `bigchaindb show-config` already does a pretty print of the json

**Comment by SohKai** [comment]
@r-marques But man, why can't I just run `cat` on this config and read it or modify it by hand, like any other json config? Does `bigchaindb show-config` merge the config with the defaults?

**Comment by r-marques** [comment]
`bigchaindb show-config` shows the `~/.bigchaindb` by default if it exists or the default config if the file does not exist.

I understand now. You want us to write the config to file indentend.

**Comment by r-marques** [comment]
bigchaindb already allows us to specify the location of the configuration file using the `BIGCHAINDB_CONFIG_PATH` env.

I will update the documentation to reflect this, create another issue to save the json indented in the file and close this.

Sounds good @SohKai?

**Comment by SohKai** [comment]
👍. You can assign the JSON pretty print issue to me.
