### ISSUE TITLE
Error in docker-compose how to resolve?

### ISSUE THREAD

**Issue by THEBESTSZ** [bigchaindb/bigchaindb#2733]
in "docker-compose up -d" this error occurs: 

`ERROR: for tendermint  Cannot start service tendermint: OCI runtime create failed: invalid mount {Destination:[ Type:bind Source:/var/lib/docker/volumes/dc480f76c79cb178eef04ab77ae262b1961d03ab5e4217f264063f5b47fcd563/_data Options:[rbind]}: mount destination [ not absolute: unknown
ERROR: Encountered errors while bringing up the project.`

How to solve, does anyone know?

**Comment by Basketballforce** [comment]
Did you ever figure out what went wrong? I am running into a similar issue :(

**Comment by Basketballforce** [comment]
Updating docker fixed my issues!

Also remember on windows you need to clone bigchain with unix line endings or you may get a "exec user process caused. No file or directory"

Add ```--config core.autocrlf=input``` to your git clone command to preserve/use unix line endings
