### ISSUE TITLE
I cannot install bigchaindb..

### ISSUE THREAD

**Issue by jindragon** [bigchaindb/bigchaindb#274]
I installed many times with these commands.
-----------------------------------------------------------------------------------------------------------
source /etc/lsb-release && echo "deb http://download.rethinkdb.com/apt $DISTRIB_CODENAME main" | sudo tee /etc/apt/sources.list.d/rethinkdb.list

wget -qO- https://download.rethinkdb.com/apt/pubkey.gpg | sudo apt-key add -

sudo apt-get update

sudo apt-get install rethinkdb

sudo apt-get update

sudo apt-get install g++ python3-dev

sudo apt-get install python3-setuptools

sudo easy_install3 pip

sudo pip install bigchaindb

sudo pip install --upgrade bigchaindb
-------------------------------------------------------------------------------------------------------
But recently, I tried to install and there was an error message.
![image](https://cloud.githubusercontent.com/assets/16792324/15203138/b783aad4-183b-11e6-9626-8431b607e41e.png)

So i tried with
pip install bigchaindb==0.1.5
but also failed.

![image](https://cloud.githubusercontent.com/assets/16792324/15203166/f3e4733c-183b-11e6-9ccf-707ad09fd877.png)

How can I fix it?

**Comment by r-marques** [comment]
BigchainDB v0.1.5 required libffi-dev so you would need to also do `apt-get install libffi-dev` before installing bigchaindb.

For the latest version it seems to be because the setuptools installed from the repos is a really old version. Can you try doing `pip install --upgrade pip wheel setuptools` before installing bigchaindb.

We updated the docs in this pull request #276

**Comment by vrde** [comment]
@jindragon before updating `setuptools`, can you please run this in a terminal:
```bash
 $ python3 -c 'import setuptools; print(setuptools.__version__)'
```

**Comment by vrde** [comment]
@jindragon would be amazing if you can try #279 before upgrading `setuptools`. The pull request checks if the version of `setuptools` you are using supports the `~` operator, and throws a human-friendly error if not.

**Comment by jindragon** [comment]
I didn't installed setuptools..
But I installed BigchainDB successfully.
I will install setuptools, latest version.

**Comment by vrde** [comment]
hey @jindragon, after applying @r-marques suggestions, are you able to install BigchainDB?

**Comment by jindragon** [comment]
Yes! Thanks very much!
