### ISSUE TITLE
Transaction schema validation

### ISSUE THREAD

**Issue by diminator** [bigchaindb/bigchaindb#275]
When an transaction is send to bigchaindb that doesnt follow the schema, TypeErrors will occur.

A first step of the validation should be checking the schema.

e.g https://pypi.python.org/pypi/voluptuous

We should consider:
- [ ] missing fields
- [ ] surplus fields
- [ ] value types
- [ ] value content

**Comment by vrde** [comment]
Would be cool to use [JSON Schema](http://json-schema.org/) to define the schema of the transaction. In this way we have a language independent schema we can reuse also on different drivers, without re-implementing the validation every time. Adding a JSON schema would also improve the documentation.

I know @TimDaub knows more about [JSON LD](http://json-ld.org/) but it should not fit this use case (any thoughts?).

After defining the schema, I can use [jsonschema](https://pypi.python.org/pypi/jsonschema) to do the actual validation.

**Comment by libscott** [comment]
Superseded by https://github.com/bigchaindb/bigchaindb/pull/798
