### ISSUE TITLE
Use .gitattributes to shrink the archive file produced by git archive

### ISSUE THREAD

**Issue by ttmc** [bigchaindb/bigchaindb#277]
The AWS deployment scripts can send a local Git branch (of BigchainDB) to all remote servers. They do that by using the `git archive` command to archive the specified branch into a tar file. The `git archive` command ignores the files in `.gitignore` but there are many other files that don't need to be sent to the remote servers, e.g. all the documentation.

A `.gitattributes` file can be used to specify additonal files and directories to exclude when producing an archive. Some help:

* https://feeding.cloud.geek.nz/posts/excluding-files-from-git-archive/
* http://stackoverflow.com/questions/21832151/git-archive-export-ignore-ignoring-directories
* https://git-scm.com/docs/gitattributes

**Comment by sbellem** [comment]
:+1:
