### ISSUE TITLE
Support snapshots / archival backup

### ISSUE THREAD

**Issue by trentmc** [bigchaindb/bigchaindb#283]
# Abstract
Modern database management systems (DBMSs) include a means to periodically back up ("snapshot") the actual data state as well as the log (which can be replayed to recover the state). This typically goes to magnetic drives or other offline storage. Leverage the tech & infrastructure of other DBMSs to support snapshots / archival.

Also to consider: increase the replication factor of the tables. Replicas are like "live backups" (of a shard).

# Motivation
If primary and all replicas of a shard are deleted, then data is lost. There's a similar problem with _changes_ to all nodes associated with a shard.

Backups help with security, and feelings of security. Will probably help to solve some of #284. Customers ask about it.

# Challenges
If there is no currently-available and _scalable_ RethinkDB backup option, then developing one might be challenging.

# Tasks

* [x] Document existing backup options offered by RethinkDB and third parties: PR #406 (Troy)
* [x] If necessary, design, develop and document additional backup options

**Comment by ttmc** [comment]
I just finished writing the documentation about existing backup options and I think those options are probably good enough for now. I'm going to close this issue. If we hear from users that they want more backup functionality, then we can open a new issue.
