### ISSUE TITLE
Gallery & documentation for performance vs. different configurations

### ISSUE THREAD

**Issue by trentmc** [bigchaindb/bigchaindb#285]
# Abstract

Benchmark performance for local deployment, cheap cloud deployment, full-on expensive cloud deployment.  Create a gallery (like matplotlib gallery) of results, make that gallery accessible from github and also at bigchaindb.com.
# Motivation

Make it easy for people deploying BDB to have a good understanding of performance, so that we set expectations accordingly.
# Goals

WIP
- foo goal 1
- foo goal 2
# Challenges

Foo
- foo challenge 1?
- foo challenge 2?
# Architecture

foo
## Examples

foo
# Tasks

**Friday, foo date 1:**
- [ ] foo task 1
- [ ] foo task 2

**Friday, foo date 2:**
- [ ] foo task 3
- [ ] foo task 4

**Comment by ttmc** [comment]
We will probably be doing something like this, but there are already other similar issues, so I'm closing this one.
