### ISSUE TITLE
Enable queries from clients. Requires indexes for speed. Includes data schema

### ISSUE THREAD

**Issue by trentmc** [bigchaindb/bigchaindb#287]
# Abstract

Make it possible to do easy ReQL style queries on BDB data payloads. Reconcile querying on data payloads and querying more broadly as well. Part of the solution will include a data schema.
# Motivation

Querying is a big potential benefit of BDB. Right now, we don't make it easy for our users to do complex queries, despite that it's pretty low hanging fruit given the power of ReQL querying. Let's expose that!
# Goals

WIP
- foo goal 1
- foo goal 2
# Challenges

WIP
- foo challenge 1?
- foo challenge 2?
# Architecture

WIP
## Examples

WIP
# Tasks

**Friday, foo date 1:**
- [ ] foo task 1
- [ ] foo task 2

**Friday, foo date 2:**
- [ ] foo task 3
- [ ] foo task 4

**Comment by sbellem** [comment]
Comment initially posted on #214: 

BigchainDB could have its own query language, e.g.: **chainQL**? The query language would allow one to easily, and efficiently query BigchainDB for transactions, blocks, and votes, etc.

**Comment by trentmc** [comment]
Closing this. New roadmap will capture this and create an issue as needed.
