### ISSUE TITLE
ascribe.io uses IPDB; include IPDB live net

### ISSUE THREAD

**Issue by trentmc** [bigchaindb/bigchaindb#288]
# Abstract
Issue #310 was the prototype; this ticket takes it to production. This includes the need for an IPDB live net (vs. just test net).

# Motivation
WIP

# Goals
WIP
* foo goal 1
* foo goal 2

# Challenges
WIP
- foo challenge 1?
- foo challenge 2?

# Architecture
WIP

## Examples
WIP

# Tasks

**Friday, foo date 1:**
* [ ] foo task 1
* [ ] foo task 2

**Friday, foo date 2:**
* [ ] foo task 3
* [ ] foo task 4

**Comment by wrigley** [comment]
Copied to https://github.com/bigchaindb/org/issues/6 so closing this issue here.
