### ISSUE TITLE
DACS DB searchable from WOTN and in IPDB

### ISSUE THREAD

**Issue by trentmc** [bigchaindb/bigchaindb#289]
# Abstract
If I go to whereonthe.net, and I search for an image that is in the DACS DB, then the results page should include a card that has metadata {title, artist, year, ascribe ID}, link to DACS, and link to ascribe.

# Motivation
For creators: a new means to get proper attribution, and license their work. For web surfers: a means to see who has rights to an image. For us: high value prop for DACS because of attribution & licensing.

# Goals
- Upload DACS data to IPDB (& media files to S3?)
- Build cards in WOTN to support use case

# Challenges
WIP
- foo challenge 1?
- foo challenge 2?

# Architecture
WIP

## Examples
WIP

# Tasks
WIP

**Friday, foo date 1:**
* [ ] foo task 1
* [ ] foo task 2

**Friday, foo date 2:**
* [ ] foo task 3
* [ ] foo task 4

**Comment by wrigley** [comment]
Copied to https://github.com/bigchaindb/org/issues/13 so closing this issue here.
