### ISSUE TITLE
Open-source ascribe.io front & back end

### ISSUE THREAD

**Issue by trentmc** [bigchaindb/bigchaindb#290]
(WIP)

# Abstract
Open source the ascribe webapp.

# Motivation
We have no desire to keep it closed. By open-sourcing it, we make it easy for others to create their own custom frontends and backends, by changing whatever they like, without dependence on us.

# Goals
* Open-source frontend
* Open-source backend 

# Challenges
WIP
- Make sure we don't expose private keys (should be straighforward)
- How to handle when our backend currently spends bitcoin, and uses other 3rd party web services that cost $ ? (should be straighforward)

# Architecture
foo

## Examples
foo

# Tasks

**Friday, foo date 1:**
* [ ] foo task 1
* [ ] foo task 2

**Friday, foo date 2:**
* [ ] foo task 3
* [ ] foo task 4

**Comment by wrigley** [comment]
Copied to https://github.com/bigchaindb/org/issues/12 so closing this issue here.
