### ISSUE TITLE
3rd party security audit, and fixes

### ISSUE THREAD

**Issue by trentmc** [bigchaindb/bigchaindb#292]
# Abstract

Contract external security auditors for theory & code. Work with them in finding flaws, and resolving flaws. Document the findings.
# Motivation

We can't think of all attack vectors on our own. This will help.
# Goals
- foo goal 1
- foo goal 2
# Challenges

Foo
- foo challenge 1?
- foo challenge 2?
# Architecture

foo
## Examples

foo
# Tasks

**Friday, foo date 1:**
- [ ] foo task 1
- [ ] foo task 2

**Friday, foo date 2:**
- [ ] foo task 3
- [ ] foo task 4

**Comment by janhon** [comment]
The approach for this is typically to split it up OSI-layers, and analyse the risk on each of the layers, the 7-OSI layers are: 1. Application/2.Presentation/3.session/4.transport/5.network/6.data link/7.physical.  In the case of bigchainDB you add a layer in between physical and data layer, you could call this concensus layer. If you structure all work on this your analysis and defence should not take ages.

**Comment by ttmc** [comment]
Thanks for the tips @janhon

**Comment by janhon** [comment]
This link has a paper of the SANS-institute:
https://www.giac.org/paper/gsec/3908/layered-security-model-osi-information-security/106272
If each of the vulnerabilities are described for each of the layers, in the case of a communication from client application towards server application I think we have a good start. In an auditor comes by he can only confirm with penetration tests on each of the layers. Like that you can manage to break the big elephant into smaller pieces.
