### ISSUE TITLE
In Azure Marketplace

### ISSUE THREAD

**Issue by trentmc** [bigchaindb/bigchaindb#294]
[Azure Marketplace](https://azure.microsoft.com/en-us/marketplace/):

"Your online store for thousands of certified, open source, and community software applications, developer services, and data—pre-configured for Microsoft Azure. Download, deploy, and get more done."

**Comment by sohkai** [comment]
@ttmc Maybe we can either close this, or repurpose it to a narrower scope (i.e. only Azure for now)?

**Comment by ttmc** [comment]
@sohkai Good idea! In fact, issue #173 already covers the AWS Marketplace, so this one can be changed to be Azure only. I'll do that.

**Comment by ttmc** [comment]
Looking at this issue now, it still seems too vague and broad. We _do_ intend to make some things available on the Azure Marketplace, but I think we'll make some specific issues for those as needed (probably some time in Q1 2017). I'm closing this issue.
