### ISSUE TITLE
Updatable assets

### ISSUE THREAD

**Issue by trentmc** [bigchaindb/bigchaindb#297]
# Abstract

Schema versioning / database migration. Data versioning that is git-like. Draw on IPFS & IPLD as much as possible.
# Motivation

Database migration. Provenance of creation. More.
# Goals
- foo goal 1
- foo goal 2
# Challenges

Foo
- foo challenge 1?
- foo challenge 2?
# Architecture

foo
## Examples

foo
# Tasks

**Friday, foo date 1:**
- [ ] foo task 1
- [ ] foo task 2

**Friday, foo date 2:**
- [ ] foo task 3
- [ ] foo task 4

**Comment by sohkai** [comment]
In lieu of https://github.com/bigchaindb/bigchaindb/issues/125, this project is more or less about the updatability of assets.

**Comment by trentmc** [comment]
Closing this. New roadmap will capture this and create an issue as needed.
