### ISSUE TITLE
Better Eth integration

### ISSUE THREAD

**Issue by trentmc** [bigchaindb/bigchaindb#298]
# Abstract
Better integrate into Ethereum smart contracts infrastructure. We have several options (see Trent's slides).

# Motivation
Many people want decentralized processing.

# Goals
WIP
* foo goal 1
* foo goal 2

# Challenges
- We need to define the goal more clearly, otherwise we could spin our wheels. Customer driven ideally
- Ethereum can't directly call external REST APIs, because that would kill its deterministic nature.

# Architecture
WIP

## Examples
WIP

# Tasks

**Friday, foo date 1:**
* [ ] foo task 1
* [ ] foo task 2

**Friday, foo date 2:**
* [ ] foo task 3
* [ ] foo task 4

**Comment by r-marques** [comment]
This should either be better defined or closed.

We have been working to integrate the interledger protocol stack into bigchaindb to allow for inter-ledger transfers. We have a working example of a transfer of a digital asset between two bigchaindb ledgers (two non-currency ledgers) and we are currently working on an example for transfers between a currency ledger and a bigchaindb ledger.

To we know of anyone from the ethereum side or knowledgeable about ethereum and possibly interledger to help us spec how use cases for this?

I can send an email to the interledger mailing list to see if anyone is interested.

This seems like a good idea for an hackaton with bigchaindb and ethereum devs

**Comment by ttmc** [comment]
Maybe BigchainDB could be used to implement Raiden nodes? See http://raiden.network/
