### ISSUE TITLE
IPDB live net usable by vetted third parties

### ISSUE THREAD

**Issue by trentmc** [bigchaindb/bigchaindb#300]
# Abstract
IPDB live net usable by vetted third parties

# Motivation
foo

# Goals
* foo goal 1
* foo goal 2

# Challenges
Foo
- foo challenge 1?
- foo challenge 2?

# Architecture
foo

## Examples
foo

# Tasks

**Friday, foo date 1:**
* [ ] foo task 1
* [ ] foo task 2

**Friday, foo date 2:**
* [ ] foo task 3
* [ ] foo task 4

**Comment by wrigley** [comment]
Copied to https://github.com/bigchaindb/org/issues/4 so closing this issue here.
