### ISSUE TITLE
Support CC FR Project; including CC licenses & IPFS in ascribe.io app

### ISSUE THREAD

**Issue by trentmc** [bigchaindb/bigchaindb#303]
# Abstract
The CC FR Project has specific needs for extending cc.ascribe.io. The main ones are: 
-rights statements (beyond the current support for CC licenses), just as project europeana uses. As developed by Paul Keller / Kennisland
-as an option instead of AWS S3 buckets, the possibility to use IPFS to store media. Note that it still needs *some* physical storage medium. One option is to have an IPFS node running on each IPDB node. Another option is to keep using S3 buckets, but have IPFS based disintermediation. 

# Motivation
This is good for the cultural commons, and good driver for supporting rights statements and IPFS.

# Goals
* foo goal 1
* foo goal 2

# Challenges
Foo
- foo challenge 1?
- foo challenge 2?

# Architecture
foo

## Examples
foo

# Tasks

**Friday, foo date 1:**
* [ ] foo task 1
* [ ] foo task 2

**Friday, foo date 2:**
* [ ] foo task 3
* [ ] foo task 4

**Comment by wrigley** [comment]
Copied to https://github.com/bigchaindb/org/issues/11 so closing this issue here.
