### ISSUE TITLE
API on WOTN for others to add new DB corpora

### ISSUE THREAD

**Issue by trentmc** [bigchaindb/bigchaindb#304]
# Abstract
This generalizes on the learnings of #289: make the DACS DB searchable from WOTN and in IPDB to make adding corpora accessible to anyone, and easy for us with new corpora.

# Motivation
Reduces the barrier to entry to populate IPDB with other cultural commons content.

# Goals
* foo goal 1
* foo goal 2

# Challenges
Foo
- foo challenge 1?
- foo challenge 2?

# Architecture
foo

## Examples
foo

# Tasks

**Friday, foo date 1:**
* [ ] foo task 1
* [ ] foo task 2

**Friday, foo date 2:**
* [ ] foo task 3
* [ ] foo task 4

**Comment by wrigley** [comment]
Copied to https://github.com/bigchaindb/org/issues/10 so closing this issue here.
