### ISSUE TITLE
Add {Euro, DPLA, Met} corpora such that searchable in WOTN and in IPDB

### ISSUE THREAD

**Issue by trentmc** [bigchaindb/bigchaindb#305]
# Abstract
Like #289 but repeat for other key corpora. Take advantage of new infrastructure since then, namely #304 (API to add corpora). For sure include: Project Europeana, DPLA, and The Met. Potentially also British Library, Flickr, Wikimedia commons, and other CC licensed content too. 

# Motivation
This helps to expose the value proposition of ascribe, WOTN, and IPDB to major works in the cultural commons.

# Goals
* foo goal 1
* foo goal 2

# Challenges
Foo
- foo challenge 1?
- foo challenge 2?

# Architecture
foo

## Examples
foo

# Tasks

**Friday, foo date 1:**
* [ ] foo task 1
* [ ] foo task 2

**Friday, foo date 2:**
* [ ] foo task 3
* [ ] foo task 4

**Comment by wrigley** [comment]
Copied to https://github.com/bigchaindb/org/issues/9 so closing this issue here.
