### ISSUE TITLE
Prototype: ascribe.io uses IPDB; include IPDB test net for ascribe.io

### ISSUE THREAD

**Issue by trentmc** [bigchaindb/bigchaindb#310]
# Abstract
This is a prototype to: Connect all the dots between ascribe.io webapp and IPDB, such that IPDB replaces the hashes in Bitcoin, and metadata stored in SQL too (but not the user & app maintenance data in SQL). Maintain owner = private key property of Bitcoin. 

IPDB should be running a test net that isn't just local. It only needs to be good enough to trust ascribe.io, it doesn't need to worry about vetted third parties or arbitrary 3rd parties. That's for later tickets.

Follow-up tickets include: production ascribe-IPDB (#288), then opening up IPDB test & live nets to 3rd parties.

If there are >1 possible architectures, take the time to explore them, at least at a high level.

# Motivation
Bitcoin doesn't scale.

# Goals
WIP
* foo goal 1
* foo goal 2

# Challenges
WIP
- foo challenge 1?
- foo challenge 2?

# Architecture
WIP

## Examples
WIP

# Tasks
WIP

**Friday, foo date 1:**
* [ ] foo task 1
* [ ] foo task 2

**Friday, foo date 2:**
* [ ] foo task 3
* [ ] foo task 4

**Comment by wrigley** [comment]
Copied to https://github.com/bigchaindb/org/issues/1 so closing this issue here.
