### ISSUE TITLE
Transactions can be orphaned

### ISSUE THREAD

**Issue by rhsimplex** [bigchaindb/bigchaindb#323]
Just to note a very obtuse edge case in #193.  Due to the change, any block voted invalid (by quorum) immediately has all its transactions put back in the backlog by every federation member.  This redundancy is good but has one pitfall -- if EVERY SINGLE node goes down while liquidating the block, leftover transactions will be orphaned upon restart.  

The block is never revisited unless a new vote is cast, which may never happen again.  Thus any transactions that didn't make it back in before the federation crashed will not make it back to the backlog.

**Comment by r-marques** [comment]
We need to assume that at any given time a majority of the nodes will be working correctly. If this is not true then we have no way to ensure consistency or prevent data loss. I think we should close this issue. @rhsimplex ?

**Comment by rhsimplex** [comment]
This would be solved by #568
