### ISSUE TITLE
All backend implementations of get_transactions_by_asset_id() should ignore invalid blocks

### ISSUE THREAD

**Issue by ttmc** [bigchaindb/bigchaindb#332]
This was one of the subissues inside issue #192 . PR #324 resolved most of that issue, except for this, which we may or may not do. I just created this issue so we won't forget about it.

See issue #192 and PR #324 for more explanation and discussion.

**Comment by r-marques** [comment]
#411 implemented the functionality to get a transaction by the payload uuid and tests. We need to add the missing logic to only return transactions in valid blocks.

**Comment by ttmc** [comment]
It seems this issue is still open. If you look at the code implementing the RethinkDB version of `get_transactions_by_asset_id()`, it still doesn't ignore invalid blocks, as far as I can tell. See:

https://github.com/bigchaindb/bigchaindb/blob/master/bigchaindb/db/backends/rethinkdb.py

I'm going to rename this issue so nobody thinks it's out-of-date because of the old terminology in the title.
