### ISSUE TITLE
Denial-of-service attack from clients: mitigations & defenses

### ISSUE THREAD

**Issue by ttmc** [bigchaindb/bigchaindb#335]
Clients could (in theory) send transactions to the BigchainDB API servers so fast that those servers become overloaded and appear unavailable to regular users: a denial-of-service (DoS) attack.

Investigate and implement some mitigation & defense strategies (within reason).

A good place to get an overview is the [_Denial-of-service attack_ article on Wikipedia](https://en.wikipedia.org/wiki/Denial-of-service_attack).

**Comment by r-marques** [comment]
Since the only point of contact for clients will be the HTTP API this should be implemented at that level.
This is a common case for API rate limiting

**Comment by r-marques** [comment]
@ttmc @krish7919 didn't we solve this already with nginx?

**Comment by ttmc** [comment]
I agree that rate limiting should should be done by something like nginx, before the traffic ever gets to BigchainDB. That is, it's outside the scope of BigchainDB Server.

@krish7919 do you agree? Can we close this issue?

**Comment by krish7919** [comment]
@r-marques We can close this as it is handled by nginx currently.
The current rate limits are hardcoded though and we can optimize it over time.
