### ISSUE TITLE
Handle case of faulty node dropping just-received transactions

### ISSUE THREAD

**Issue by ttmc** [bigchaindb/bigchaindb#336]
When a transaction first arrives at a node, that node might just drop the transaction, doing nothing with it. (In particular, the transaction wouldn't get written to the backlog table.)

That might happen because the server crashed after receiving the transaction (e.g. because of a thunderstorm) or because the server is compromised. A compromised server might even lie and send a response to the client saying that everything is going great.

A similar problem is if the initial node (or assigned node) says that a valid transaction is invalid, deletes it, and informs the client that it's invalid.

Implement some way(s) to mitigate this problem.

Ideas:
- A client could send the transaction to one node, wait a while, and if it hasn't been told that the transaction is invalid, it could query for the transaction: if the transaction is "lost" then the client could re-send the transaction, but to a different node.
- A client could just send the transaction to multiple nodes from the start (e.g. using multicast). Surely one will stick...
- Push more feedback to clients on the status of their transactions; with more information, they can better reason about what they should do.
- Modify the "GET tx_id" query to respond with a variety of possible "current state" messages, enabling the client to better-determine the current state of their transaction.

A client should probably send a query to multiple nodes, just in case some are faulty. (This is a common assumption in the fault tolerance literature.)

**Comment by libscott** [comment]
Since we are currently not aiming to provide this as a guarantee, it starts to look like a client concern (clients need to be prepared to talk to several nodes and retry if their (valid) transactions are not validated). Can we therefore close this issue?

**Comment by ttmc** [comment]
We should document that we don't guarantee that transactions will get processed. (There are many reasons they might not get processed, including getting lost in transit.)

**Comment by ttmc** [comment]
My comment from February 15, 2017 still holds true for BigchainDB 2.0.

I think @libscott had the right idea. It's a client concern. We should have closed this issue a long time ago, but we didn't. I'm rectifying that now. I'm closing it.
