### ISSUE TITLE
Handle the case of a faulty node saying that an invalid tx is valid?

### ISSUE THREAD

**Issue by ttmc** [bigchaindb/bigchaindb#338]
I'm not sure this is really an issue, but I'm including it here in case someone disagrees with me.

It seems to me that if there is a faulty node (or several), and it's falsely saying that an invalid transaction is valid, then we still have nothing to worry about because once the transaction gets into a block, a majority of the nodes will deem it invalid.

(We _assume_ that a majority of nodes are not faulty. That's not a limitation of BigchainDB: it's something that all similar systems must assume—there's no way to achieve consensus if more than a majority of the nodes are faulty.)

**Comment by r-marques** [comment]
I don't think this is an issue. Assuming that the majority of nodes is not faulty the block would be voted invalid and this is already implemented.

relates to #354

**Comment by ttmc** [comment]
Yeah, this is just one example of Byzantine behavior to report as per issue #354 (which was created after this issue). I'll close this issue as suggested.
