### ISSUE TITLE
Transaction malleability of transactions containing no signatures

### ISSUE THREAD

**Issue by ttmc** [bigchaindb/bigchaindb#339]
Some transactions might not contain any signatures and that makes them malleable.

For example, if a TRANSFER transaction only has to fulfill hashlock or timelock conditions (or some combination of them), then it doesn't have to contain any signatures.

That means that the receiving node could change some things in the transaction, recompute the transaction id/hash, and it would still be a valid transaction. The receiving node would then write the modified transaction to the backlog.

It's not clear if this problem is specific to TRANSFER transactions, as the question of who should/must sign CREATE transactions is still undecided. For example, see issue #347

**Comment by r-marques** [comment]
On solution would be include the transaction data in the hash.

`hashlock = h(fulfillment_message | pre-image)`

**Comment by ttmc** [comment]
Another solution idea:

Make it so that every transaction submitted by a client must be signed by that client. (A client can use a different private/signing key every time if they want.) They'd have to include the public/verifying key in the transaction body (e.g. in transaction.transaction.submitter_pubkey). Their signature could go outside the transaction body, e.g. in transaction.submitter_signature.

And of course, add a new step to transaction validation: check the new submitter_signature.

Notes:
- Transaction is no longer malleable, because any change to the transaction body will make the submitter_signature invalid.
- Bad-client can't submit a valid transaction on behalf of some other public key because they don't have the corresponding private/signing key
- The other signatures in the transaction (if there are any) do just one job: they fulfill conditions.
- The submitter_pubkey can be different from the other public keys associated with the transaction.

I'm not sure of the implications for CREATE transactions because as mentioned in the first comment on this  issue, 

> the question of who should/must sign CREATE transactions is still undecided. For example, see issue #347

**Comment by ttmc** [comment]
Over in the comments on issue #327, @r-marques wrote his thoughts on this issue:

> Honestly I don't think [this issue] #339 is an issue.
> Cryptoconditions is a flexible spec that allow us to program cryptographic conditions (for good or bad) that dictates how a transaction is verified. If a user decides that a condition does not need a signature then they should be aware that it may lead to transaction malleability. The most that we could do is enforce the use of signatures in conjunction with hashlocks, although I don't think we should restrict how users decide to use crypto conditions.

**Comment by ttmc** [comment]
In response to @r-marques comment:

Okay, but:

* This issue is not an issue with hashlock conditions alone. It's a problem with any conditions which don't include signatures. There may be many kinds of those in the future.
* We should have lots of documentation explaining the pitfalls of conditions involving no signature conditions.
* Our tooling for building conditions should throw up warnings about the dangers of using hashlocks alone, i.e. provide warnings at the time of potential error.
* Maybe nodes could enforce a requirement that every transfer transaction contain at least one signature, somewhere

**Comment by r-marques** [comment]
I am closing this for now.
There is a new issue #1230 related to BigchainDB 1.0 correctness guarantees that covers this.
Also at this point we do not support hashlocks so this problem does not exist.
