### ISSUE TITLE
Move "version" inside transaction body and include it in what gets hashed

### ISSUE THREAD

**Issue by ttmc** [bigchaindb/bigchaindb#341]
Right now, the "version" (version number of the transaction model) of a transaction lives outside of the "transaction" in the [transaction data model](http://bigchaindb.readthedocs.io/en/latest/models.html#the-transaction-model).

Also, when computing the id/hash of a transaction, the "version" isn't included in what gets hashed.

Proposal: move "version" inside the "transaction" body and include it in what gets hashed (when computing the transaction id/hash).

Fulfillment signatures already include the "version" (in what gets signed), so this would make signature-calculation more consistent with hash-calculation (in transactions).

**Comment by eladve** [comment]
@ttmc Note that this feature might have implications on backwards compatibility.

**Comment by ttmc** [comment]
Resolved by pull request #518
