### ISSUE TITLE
Compromised node ruining blocks by including 1+ invalid tx in blocks it builds

### ISSUE THREAD

**Issue by ttmc** [bigchaindb/bigchaindb#346]
If a federation node includes just one invalid transaction in a block (on purpose), the whole block becomes invalid, yet the block will still get written to the bigchain table and voted on (validated by a quorum of federation nodes), tying up resources with no useful outcome.

It's a weak, partial, internal denial-of-service attack. The valid transactions in the invalid block will get copied back to the backlog for inclusion in a new block, so they should be okay, just delayed.

**Solution Ideas**

* Randomly assign transactions to nodes for inclusion in a block, both initially and when copying them back to the backlog from an invalid block. I believe we already do this. Please verify.
* Have a watchdog process checking blocks in the bigchain table to see if invalid blocks tend to come from certain nodes. Investigate federation nodes which seem to be making more invalid blocks than normal.
* Have a watchdog process investigating all invalid transactions to look for patterns.
* Other ideas?

**The Case of the Unlucky Valid Transaction**

It might happen that an unlucky valid transaction gets included in a sequence of invalid blocks. Maybe we could check valid transactions at block-building time to see how many invalid blocks they've been in before, and if it's greater than three (say), we could just put the unlucky transaction in its own block to ensure that it gets into a valid block ASAP.

**Comment by r-marques** [comment]
> Randomly assign transactions to nodes for inclusion in a block, both initially and when copying them back to the backlog from an invalid block. I believe we already do this. Please verify.

This is the current behavior. The other solutions I think should be moved to #354

**Comment by ttmc** [comment]
Okay I will close this issue, move the two watchdog ideas to issue #354, and create a new issue for "The Case of the Unlucky Valid Transaction"
