### ISSUE TITLE
Rename current_owners and new_owners field in the transaction

### ISSUE THREAD

**Issue by diminator** [bigchaindb/bigchaindb#348]
A transaction now contains `current_owners` in the condition field and `new_owners` in the fulfillment field. 

However, this is ambiguous when reasoning about `bigchaindb.get_owned_ids()`:
- The resulting transactions include these where one has been included in the condition, hence the `new_owners` field
- There might be co-ownership

Solution: rename the `current_owners` and `new_owners` field into `source` and `destination`

**Comment by ttmc** [comment]
I'm not sure `source` and `destination` are an improvement. They obscure the fact that they are lists, and that they are lists of owners (i.e. public keys of owners).

The purpose of a transaction is, in part, to change the owners of one or more assets. Each asset has a fulfillment-condition pair, with the "owners just before this transaction happened" listed in the fulfillment, and the "owners just after this transaction happened" listed in the condition.

It would be nice if we could just call the two lists `owners_just_before_this_transaction_happened` and `owners_just_after_this_transaction_happened` but those names are clearly too long.

How about `owners_before` and `owners_after` (where "this transaction" is implicit)?

Those names aren't very different from what we have now (`current_owners` and `new_owners`). The problem with the current names is that you have to take a very particular point of view to reason about them properly (namely the view of the world _before_ the transaction happened), and that's not obvious... especially for someone trying to understand the transaction in the future.
