### ISSUE TITLE
Make timeout condition and escrow more robust

### ISSUE THREAD

**Issue by diminator** [bigchaindb/bigchaindb#349]
It is unclear which times are used when creating a timeout condition (also used by escrow):
- The `expire_time` is set by the client
- The `expire_time` is validated by the node upon `bigchaindb.write_transaction()`
- Validation of the history should be consistent and eliminate the notion of the current time

Proposals:
- [ ] when the client needs to set the expiry time: 
  - have a way for a client to know what's the time on the servers, using median times of the servers. Or..
  - Use relative times, based on the voting times in the block. Or...?
- [ ] Once written and accepted to bigchaindb eliminate the notion of variable time:
  - prune out the time by replacing the time-based switch by a hard-wired connection, or...
  - use the block voting times

**Comment by libscott** [comment]
I think we can close this since we don't support escrow or timeouts right now? @diminator @ttmc @r-marques

**Comment by ttmc** [comment]
I think there's some vestigial support for some of that functionality. @TimDaub knows more.

In any case, do we plan to fully-and-properly support timeouts again eventually (including proper documentation)? I think we do. I know it's something some specific customers want.

**Comment by diminator** [comment]
There are many reasons (ILP, customers, escrow, hold, ...) to keep this in the timeline

But first things first:
- update CC to new RFC
- shim CC vs BDB-CC
- update timelocks

**Comment by ttmc** [comment]
Issue #726 (Add full support for timeout) may be related.

**Comment by ttmc** [comment]
@nileshtrivedi shared an interesting idea on Gitter:

@ttmc wrote: 

> @nileshtrivedi We might add support for timelocks in the future. As you mentioned, it's problematic because transactions should always be publicly verifiable.

@nileshtrivedi wrote:

> @ttmc How about making it depend on the hash of a specific future block on BTC or ETH blockchains? Those are public and not known in advance. To spend this output, one would have to not just sign the transaction with a private key but also provide this hash - which ensures that certain amount of time has passed.
It's a workable solution for the short term, but not Internet-scale that will continue to work reliably even after decades. Also, to validate this transaction, we'd have to connect to Bitcoin/ETH networks which would make it VERY slow. Still, a possible approach.

Source:  https://gitter.im/bigchaindb/bigchaindb?at=59dbb442bbbf9f1a383e310c

**Comment by ttmc** [comment]
A nice collection of ideas about how to do timeouts / timelocks: https://www.gwern.net/Self-decrypting-files

**Comment by ttmc** [comment]
I'm going to remove the "BUG" label because we currently don't support timeout conditions or escrow, so there's no "bug" in them. People looking at the list of issues with the "BUG" label should be getting current bugs, not past bugs or potential future bugs.
