### ISSUE TITLE
Fault: Atomicity of multiple updates/deletes is not guaranteed

### ISSUE THREAD

**Issue by ttmc** [bigchaindb/bigchaindb#352]
(From the original "BigchainDB attack vectors" document.)

From C.M.: 

Fault: Atomicity of multiple updates/deletes is not guaranteed, hence MIMO (multiple input - multiple output) transactions are possibly not consistent or UTXO table might not be.

Possible solutions (also from C.M.):
- switch to DB backend that guarantees atomicity
- avoid dependency on atomicity by design (SISO, no complex UTXO table)

**Comment by libscott** [comment]
Since we don't have a UTXO table, can be closed?

**Comment by ttmc** [comment]
Ignoring the fact that there's no UTXO table, maybe the comments raise some real concerns?

**Comment by libscott** [comment]
Suppose there's no harm in keeping it open, food for thought :smile:
