### ISSUE TITLE
Restart of the server required after changing the config file ?

### ISSUE THREAD

**Issue by gekko68** [bigchaindb/bigchaindb#357]
Hi,
after changing the config file .i.e adding the Keyring for all my attached nodes do I have to restart the server and if yes - how do I need this as I only found an option to "Start" the server but not how to "Stop or Restart" 
Best, Michael

**Comment by r-marques** [comment]
Hi @gekko68 

Yes you need to re-start the server in order to read the new configuration. At this point there is no clean way to stop the server. We are currently refactoring the multiprocessing code which should solve this.

**Comment by ttmc** [comment]
Closing since this issue is covered under issue #662
