### ISSUE TITLE
Digital asset definition & creation

### ISSUE THREAD

**Issue by ttmc** [bigchaindb/bigchaindb#391]
# Outline

__assumption__: In a real world application, users care about the assets, not so much about the underlying transactions.

Assets can be viewed as permissioned documents, and the ownership of the document is orchestrated by the underlying asset transactions. Hence the creation of the asset coincides with asset issuing, and permissioning of the asset with asset transfer. This way, the document is referred to as the payload of the `CREATE` action and the ownership changes/permissioning to the `TRANSFER` actions. Similarly one could define an update as being a `TRANSFER` with a specific diff for the document. The final state would then be the squash of all diffs together with the initial payload.

Creation of assets should be limited when:
- the ledger allows minting
- one can only mint coins to himself, not other public keys
- the minting should be requested and signed off by the federation nodes

@r-marques and @diminator could you write a few lines to outline this project's goals etc.? (This is not just for us but for people following what we're doing and planning to do.)

**Comment by r-marques** [comment]
The contents have this issue are already being addressed by other issues
