### ISSUE TITLE
Proposal to change bigchaindb configuration system

### ISSUE THREAD

**Issue by r-marques** [bigchaindb/bigchaindb#394]
##### Change the order of precedence of the configuration system:

The current order of precedence is:
1. default config
2. env config
3. file config

Proposed precedence order:
1. default config
2. file config
3. env config (mostly for overriding settings at runtime)

It would be helpful to change just a few settings at runtime (e.g. run several bigchaindb instances that share the same settings except for the db name and api port). Right now the easier way to do it would be to create a config file for each instance.

##### Add a method to programmatically update the configuration.

When calling bigchaindb programmatically it may be useful to change some of the configuration. Some settings can be passed to `Bigchain.__init__()` but not all the configuration can be changed this way (e.g. statds or api settings)

`config_utils` provides `set_config` that takes the default config and updtes the keys passed. It would be helpful to have a method `update_config` to take the current configuration and update some keys.

__TODO__:
- [x] change config precedence
- [x] implement update config method
- [x] update the docs
- [x] update / write tests

**Comment by ttmc** [comment]
The relevant docs to update will be:

* http://bigchaindb.readthedocs.io/en/latest/nodes/configuration.html#order-of-precedence-in-determining-configuration-values
* The docstring for `class Bigchain` in `/bigchaindb/core.py`

**Comment by SohKai** [comment]
+1. We had discussed some other configuration upgrades in #272, might be worth thinking about some the items there if they'll simply things with the examples (#272 was also created from experiences with the examples).
