### ISSUE TITLE
Bugs when Bigchain().write_transaction(tx_signed) is called twice or more, for the same 'tx_signed' 

### ISSUE THREAD

**Issue by guozhongxin** [bigchaindb/bigchaindb#400]
when Bigchain().write_transaction(tx_signed) is called twice or more, for the same 'tx_signed', it seams  to cause the double spent.

**Comment by r-marques** [comment]
Can you put here the votes that are produced. Votes are outputted by `bigchaindb start`

**Comment by guozhongxin** [comment]
```
from bigchaindb import Bigchain
from bigchaindb import crypto
b = Bigchain()
testuser1_priv, testuser1_pub = crypto.generate_key_pair()

digital_asset_payload = {'msg': 'test***'}
tx = b.create_transaction(b.me, testuser1_pub, None, 'CREATE', payload=digital_asset_payload)
tx_signed = b.sign_transaction(tx, b.me_private)
b.write_transaction(tx_signed)
b.write_transaction(tx_signed)
b.write_transaction(tx_signed)
...
```
The votes:

> 
> INFO:bigchaindb.voter:new_block arrived to voter
> INFO:bigchaindb.voter:updating block cefa5b490c8bf3ba0dd4a278b54d7a0fe435b87520460e3e951f91af847cc6e5 with number 41 and with vote {'signature': '2ezDPvdXqgCgExyvJLo44nXDFgzjcgNtFVEJpZ8dDdme3CZteMWsQWVakR6j2xxN4cgmh4eKkw4yJMVmpwpuiTdo', 'node_pubkey': 'DNh9fJwqfh8rMgxi2uZ8znCra1xhEYczFfcp6HKii4zu', 'vote': {'is_block_valid': True, 'invalid_reason': None, 'timestamp': '1466665201.353322', 'voting_for_block': 'cefa5b490c8bf3ba0dd4a278b54d7a0fe435b87520460e3e951f91af847cc6e5', 'previous_block': '11f9433ddf4b9c60c65e4ce808e1ba1c3268fc29c6e4e25d0e06dda6c93b3435'}}
> INFO:bigchaindb.voter:new_block arrived to voter
> INFO:bigchaindb.voter:updating block 48085808d94115075314e4ef1731680b44b0ef2a70d20d318fb661d14f40483d with number 42 and with vote {'signature': '566bhQnXPMSdFZJQBAxQW5wrE85f1pPi4VYYzZMrmDPyCM2CkMhqeYsKUfRVJ2QdFxzbxgFVe4FLVmGaDKb3ESjV', 'node_pubkey': 'DNh9fJwqfh8rMgxi2uZ8znCra1xhEYczFfcp6HKii4zu', 'vote': {'is_block_valid': True, 'invalid_reason': None, 'timestamp': '1466665760.747011', 'voting_for_block': '48085808d94115075314e4ef1731680b44b0ef2a70d20d318fb661d14f40483d', 'previous_block': 'cefa5b490c8bf3ba0dd4a278b54d7a0fe435b87520460e3e951f91af847cc6e5'}}
> INFO:bigchaindb.voter:new_block arrived to voter
> INFO:bigchaindb.voter:updating block 1d0faa22302af968cc5d70e58fbdbda9ab08f79ecd0611abee5c5b6234e46e59 with number 43 and with vote {'signature': '3JYkqu3XPsdq2WFEqKGAT9JgUZjE1afsweKYspFv9vyUNps1Bup6yNWpPamkLmvRm6Lz1XsH5Ufcr6yKhd8PQGjE', 'node_pubkey': 'DNh9fJwqfh8rMgxi2uZ8znCra1xhEYczFfcp6HKii4zu', 'vote': {'is_block_valid': True, 'invalid_reason': None, 'timestamp': '1466665900.297192', 'voting_for_block': '1d0faa22302af968cc5d70e58fbdbda9ab08f79ecd0611abee5c5b6234e46e59', 'previous_block': '48085808d94115075314e4ef1731680b44b0ef2a70d20d318fb661d14f40483d'}}
> INFO:bigchaindb.voter:new_block arrived to voter
> INFO:bigchaindb.voter:updating block 8081e90455265282d7a0a04c3000185d48e034ba60a40c9373f1d12a349c1963 with number 44 and with vote {'signature': 'AbrWFcC3vfAMHk7oh1U7vSwUDi59azPaAsW3YNJjq1Sn1p1hyeiHWgpoYrZPyhbUx98mEenTvZekF7GmruSxD7L', 'node_pubkey': 'DNh9fJwqfh8rMgxi2uZ8znCra1xhEYczFfcp6HKii4zu', 'vote': {'is_block_valid': True, 'invalid_reason': None, 'timestamp': '1466666375.640100', 'voting_for_block': '8081e90455265282d7a0a04c3000185d48e034ba60a40c9373f1d12a349c1963', 'previous_block': '1d0faa22302af968cc5d70e58fbdbda9ab08f79ecd0611abee5c5b6234e46e59'}}
> INFO:bigchaindb.voter:new_block arrived to voter
> INFO:bigchaindb.voter:updating block a984ed3198703c4fd537643cdcb44c27507c3d3a8a493a99ca36eb4f542b12eb with number 45 and with vote {'signature': '4kWLjfUsvy5kAhhTymBx8cexKknTSFEW9742p2KconpWqMXx5TvDgKTYj9vHpa6cLvSd3XbADWtoxqtYxLn7QgFB', 'node_pubkey': 'DNh9fJwqfh8rMgxi2uZ8znCra1xhEYczFfcp6HKii4zu', 'vote': {'is_block_valid': True, 'invalid_reason': None, 'timestamp': '1466666381.087502', 'voting_for_block': 'a984ed3198703c4fd537643cdcb44c27507c3d3a8a493a99ca36eb4f542b12eb', 'previous_block': '8081e90455265282d7a0a04c3000185d48e034ba60a40c9373f1d12a349c1963'}}
> INFO:bigchaindb.voter:new_block arrived to voter
> INFO:bigchaindb.voter:updating block 2eab5ebeb2e7528e7858428e5dd9d25e5edaba80407371caf0adbe72042b8903 with number 46 and with vote {'signature': '2nyjTZyWY5QDgkzE6Gp1c2TZ5xiVsFTEveFXK3qXfPPh2exMaNnenZiRD12APs1maAYsF4Bmdbnvete3gELodG8s', 'node_pubkey': 'DNh9fJwqfh8rMgxi2uZ8znCra1xhEYczFfcp6HKii4zu', 'vote': {'is_block_valid': True, 'invalid_reason': None, 'timestamp': '1466666395.634089', 'voting_for_block': '2eab5ebeb2e7528e7858428e5dd9d25e5edaba80407371caf0adbe72042b8903', 'previous_block': 'a984ed3198703c4fd537643cdcb44c27507c3d3a8a493a99ca36eb4f542b12eb'}}
> INFO:bigchaindb.voter:new_block arrived to voter
> INFO:bigchaindb.voter:updating block a64321480f837a23079a0162df51d37da95689d245eb889db48b8e79cd7cd2dc with number 47 and with vote {'signature': '39rBnbcgaG4vfHmjLniNUrLmbofubYmA9XDzSpvfb1y56zNBSziSd7Z9uaGSx4HrQN5f9sjstN5H6KntUjGxcWxp', 'node_pubkey': 'DNh9fJwqfh8rMgxi2uZ8znCra1xhEYczFfcp6HKii4zu', 'vote': {'is_block_valid': True, 'invalid_reason': None, 'timestamp': '1466666514.264808', 'voting_for_block': 'a64321480f837a23079a0162df51d37da95689d245eb889db48b8e79cd7cd2dc', 'previous_block': '2eab5ebeb2e7528e7858428e5dd9d25e5edaba80407371caf0adbe72042b8903'}}
>

When I check b.get_owned_ids(testuser1_pub):

> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/usr/local/lib/python3.4/dist-packages/bigchaindb/core.py", line 313, in get_owned_ids
>     validity = self.get_blocks_status_containing_tx(tx['id'])
>   File "/usr/local/lib/python3.4/dist-packages/bigchaindb/core.py", line 219, in get_blocks_status_containing_tx
>     .format(tx=txid, block_ids=block_ids))
> Exception: Transaction 183985d94805c44acd88339556c23b9a246d61388779bedb951bc8d5fdb08cd3 is present in multiple valid blocks: ['a64321480f837a23079a0162df51d37da95689d245eb889db48b8e79cd7cd2dc', '8081e90455265282d7a0a04c3000185d48e034ba60a40c9373f1d12a349c1963', 'a984ed3198703c4fd537643cdcb44c27507c3d3a8a493a99ca36eb4f542b12eb', '2eab5ebeb2e7528e7858428e5dd9d25e5edaba80407371caf0adbe72042b8903']

**Comment by r-marques** [comment]
Thanks for reporting this. We will take a look and fix this.

**Comment by TimDaub** [comment]
https://github.com/bigchaindb/bigchaindb/issues/592

These two tickets are basically the same.

**Comment by MitchK** [comment]
I have a similar issue after playing a bit.

```
...
tx = b.create_transaction(b.me, testuser1_pub, None, 'CREATE', payload=digital_asset_payload)
tx_signed = b.sign_transaction(tx, b.me_private)

b.write_transaction(tx_signed)
b.write_transaction(tx_signed)

b.get_transaction(tx_signed['id'])
```

Output: 
```
Exception: Transaction f4597e5a1c9d1aa791b6bceddc689e277a891fada7823dd0ff127ec33a56248d is present in multiple valid blocks: ['079d640e22110edbd5a099f72ded02a7162cca1731fdc6b473f89865645cc9b1', 'e10a874a6b38cd17c5557462217551f999c524ae41a7ccfa2d269b37a5df8b97']
```

I assume I am now in a block tie, correct?
```
                        Genesis block 
                         ^                 ^
Block #  e10...                   Block # 079....
Containing                        Containing
trans # f45...                     trans # f45...
```

How to resolve it?

**Comment by rhsimplex** [comment]
Hey @MitchK, I'm looking into this bug.  Will get back to you shortly.

**Comment by MitchK** [comment]
:+1:

**Comment by rhsimplex** [comment]
You can also drop it through the command line interface, i.e. `bigchaindb drop`

https://bigchaindb.readthedocs.io/en/latest/server-reference/bigchaindb-cli.html

**Comment by rhsimplex** [comment]
Hey @MitchK,

We've merged #359 and #609, which seems to solve the problem.  I believe there are still ways to insert duplicate create tx, but this should solve it for the majority of cases.

Let me know if this fixes things for you.

**Comment by TimDaub** [comment]
Any updates @rhsimplex?

**Comment by sohkai** [comment]
Closing this for now. We can either reopen this issue or create a new one if new double spend bugs are found.
