### ISSUE TITLE
Failed when I test with "The Python Driver API by Example"

### ISSUE THREAD

**Issue by guozhongxin** [bigchaindb/bigchaindb#401]
I meet errors when I follow the guide of "The Python Driver API by Example" http://bigchaindb.readthedocs.io/en/latest/drivers-clients/python-driver-api-examples.html.

> \>>> from bigchaindb.client import temp_client
> \>>> c1 = temp_client()
> \>>> tx = c1.create({'value':'233333', 'msg':'test client'})
> \>>> tx
> {'transaction': {'conditions': [{'new_owners': ['Ghve9ecC9gekwWh7LHMdrTDthVcD5LUiA3uLHcsHcRdG'], 'cid': 0, 'condition': {'uri': 'cc:4:20:6VswEYH3o-jW8AkaY_-SiCEibRQGDkFdeGF9ZzvdPw8:96', 'details': {'type': 'fulfillment', 'signature': None, 'type_id': 4, 'bitmask': 32, 'public_key': 'Ghve9ecC9gekwWh7LHMdrTDthVcD5LUiA3uLHcsHcRdG'}}}], 'operation': 'CREATE', 'fulfillments': [{'fid': 0, 'input': None, 'current_owners': ['DNh9fJwqfh8rMgxi2uZ8znCra1xhEYczFfcp6HKii4zu'], 'fulfillment': 'cf:4:t9rWS08U6nMrazXOwBhZvPUGmB4HU59_rQYBM4Z370Lne68F5Ph2TE_ZFQy_bVHVpMum52JJWe3OQ8EAGd1i4eUtF6J_5_2XSs5UFbIYTWOC1n1Hg6bmRC3LnhmcM7cM'}], 'timestamp': '1466667154.303503', 'data': {'hash': '28e538ae3672b171a33286901221a5ba5856aca42127cb29ee7f50bd480765b5', 'payload': {'value': '233333', 'msg': 'test client'}}}, 'version': 1, 'assignee': 'DNh9fJwqfh8rMgxi2uZ8znCra1xhEYczFfcp6HKii4zu', 'id': 'faeda120b633bb9c828a6981c4ed2047280b993153131278e3bf41915a90a2ce'}
>
> \>>> c1.transfer(c2.public_key, tx['id'], {'value':'33333', 'msg':'test client transder'})
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/usr/local/lib/python3.4/dist-packages/bigchaindb/client.py", line 91, in transfer
>     tx, private_key=self.private_key)
>   File "/usr/local/lib/python3.4/dist-packages/bigchaindb/consensus.py", line 229, in sign_transaction
>     return util.sign_tx(transaction, private_key)
>   File "/usr/local/lib/python3.4/dist-packages/bigchaindb/util.py", line 335, in sign_tx
>     input_condition = get_input_condition(bigchain, fulfillment)
>   File "/usr/local/lib/python3.4/dist-packages/bigchaindb/util.py", line 512, in get_input_condition
>     previous_tx = bigchain.get_transaction(input_tx['txid'])
> TypeError: string indices must be integers

I try to figure out the reason. It seems the second arguement of `c1.transfer` should not be `tx['id']`, and it should be `{'cid':'****', 'txid':'*****'}`.

When I test `c1.transfer` with `b.get_owned_ids(c1.public_key)`, it works well.

> \>>> b.get_owned_ids(c1.public_key)
> [{'cid': 0, 'txid': 'faeda120b633bb9c828a6981c4ed2047280b993153131278e3bf41915a90a2ce'}]
> \>>> c1.transfer(c2.public_key, b.get_owned_ids(c1.public_key), {'value':'33333', 'msg':'test client transder'})
> {'transaction': {'conditions': [{'new_owners': ['DEZ7xyTvwGHzDVHzehZgftqzNVSooYFE1WbTskgava7Q'], 'cid': 0, 'condition': {'uri': 'cc:4:20:tcUcp54xZ2I9ZOXigp6ai0UvHU3sPgotoIgYZdUmI48:96', 'details': {'type': 'fulfillment', 'signature': None, 'type_id': 4, 'bitmask': 32, 'public_key': 'DEZ7xyTvwGHzDVHzehZgftqzNVSooYFE1WbTskgava7Q'}}}], 'operation': 'TRANSFER', 'fulfillments': [{'fid': 0, 'input': {'cid': 0, 'txid': 'faeda120b633bb9c828a6981c4ed2047280b993153131278e3bf41915a90a2ce'}, 'current_owners': ['Ghve9ecC9gekwWh7LHMdrTDthVcD5LUiA3uLHcsHcRdG'], 'fulfillment': 'cf:4:6VswEYH3o-jW8AkaY_-SiCEibRQGDkFdeGF9ZzvdPw-rIjPgTP_SR9vY4pq_-WQOXTu1uaOolAZ_amJVWv1dkfA3AFs_ZeMHc5Xhejjru9JUw-twuXDXvy-yPrQzl-EE'}], 'timestamp': '1466667692.027563', 'data': {'hash': 'ff9ccdb976ac39fd8d3a9dcf9d8d2884f0a7e622183d5141dc665f2f9d4613d2', 'payload': {'value': '33333', 'msg': 'test client transder'}}}, 'version': 1, 'assignee': 'DNh9fJwqfh8rMgxi2uZ8znCra1xhEYczFfcp6HKii4zu', 'id': 'b0e9dd71173814e7a3245079e06a3cae62889f0ec1b8dfe69644952da02a3d91'}

**Comment by r-marques** [comment]
> I try to figure out the reason. It seems the second arguement of c1.transfer should not be tx['id'], and it should be {'cid':'****', 'txid':'*****'}

Its true. Since we added support for multiple inputs and outputs, when specifying an input you also need to pass the condition index.

We will update the docs

**Comment by guozhongxin** [comment]
Cool.
I am a freshman of BigchainDB, thanks so much for your response. 

I have another question about BigchainDB. As you mentioned BigchainDB support multiple inputs and outputs.  If I want to implement a trade system, using BigchainDB, can BigchainDB support the multiple outputs with different users for now. For example, User A owns a transaction with 10 'dollars' as payload, and it wants to transfer 5 dollars to user B, and 5 dollars to user C.

**Comment by ttmc** [comment]
A transfer transaction can transfer several different assets, each with different old and new owners.

Your example is about something different. Right now, an asset can't be split apart into smaller pieces. Right now, BigchainDB only handles indivisible assets. There's an enhancement proposal to support divisible assets.

**Comment by r-marques** [comment]
At this point we do not support divisible assets, its on the roadmap #129 

We also do not support sending different inputs to different owners with the current api. When you used create transaction all of the inputs will go to the same `new_owners`. Maybe we should rethink this and add support for this in the bigchaindb api.

You can however do it by creating custom crypto conditions https://bigchaindb.readthedocs.io/en/latest/nodes/python-server-api-examples.html

**Comment by ttmc** [comment]
Resolved by PR #402
