### ISSUE TITLE
ASL 2.0

### ISSUE THREAD

**Issue by sirinath** [bigchaindb/bigchaindb#405]
Is it possible to license the whole project under ASL 2.0

**Comment by ttmc** [comment]
Most of the core bigchaindb/bigchaindb software is licensed AGPL 3.0, similar to MongoDB and RethinkDB. See [our licenses document](https://github.com/bigchaindb/bigchaindb/blob/master/LICENSES.md) for more details.

If you want to make changes to the core code, keep those changes private (closed source), and use the modified code in a cluster, then please contact us by email and request a commercial license.
