### ISSUE TITLE
Make the required version of rethinkdb more general

### ISSUE THREAD

**Issue by ttmc** [bigchaindb/bigchaindb#41]
Currently, setup.py specifies a very specific version of rethinkdb (Python package):

```
'rethinkdb==2.2.0.post1',
```

That's causing some issues already because when I try to install rethinkdb=2.2.0.post1, I get this message: `Requested rethinkdb==2.2.0.post1, but installing version 2.2.0-1`

Then, when I go to run `bigchaindb start`, it fails because it requires `rethinkdb==2.2.0.post1` but 2.2.0-1 is installed.

@vrde suggested changing the setup.py requirement to something more general:

```shell
'rethinkdb>=2.2,<2.3',
```

I guess that `bigchaindb` should also be changed to have the same, looser requirement.

**Comment by ttmc** [comment]
Note: @Mec-iS created PR #40 in response to the same problem

**Comment by ttmc** [comment]
Here is what happened when I ran `bigchaindb start`:
```shell
ubuntu@ip-172-31-12-118:/usr/local/bin$ bigchaindb start
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 444, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 725, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 632, in resolve
    raise VersionConflict(dist,req) # XXX put more info here
pkg_resources.VersionConflict: (rethinkdb 2.2.0-1 (/usr/local/lib/python3.4/dist-packages), Requirement.parse('rethinkdb==2.2.0.post1'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/bigchaindb", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2749, in <module>
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 446, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 459, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 628, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: rethinkdb==2.2.0.post1
```

If fails because it requires `rethinkdb==2.2.0.post1` but 2.2.0-1 is installed.

**Comment by vrde** [comment]
I'm looking into the problem. There might related to the fact that in the `setup.py` contained in [rethinkdb-2.2.0.post1.tar.gz](https://pypi.python.org/packages/source/r/rethinkdb/rethinkdb-2.2.0.post1.tar.gz#md5=6fa2c80ff5ed2f439b55093a813be39b) the version is defined as:

```python
from setuptools import setup

version_path = 'rethinkdb/version.py'

exec(open(version_path).read())

setup(
    name="rethinkdb",
    zip_safe=True,
    version=version,
   ...
```

If you open the file `rethinkdb/version.py`, it contains:
```python
version = '2.2.0-1'
```

Apparently, this is triggering the error pointed by @Mec-iS:
```
pkg_resources.VersionConflict: (rethinkdb 2.2.0-1 (/usr/local/lib/python3.4/dist-packages), Requirement.parse('rethinkdb==2.2.0.post1'))
```

Upgrading pip `pip install --upgrade pip`  or `pip3 install --upgrade pip` solves the issue. I'm looking now if there is a bug in `pip` related to this.

**Comment by Mec-iS** [comment]
Ok, now the situation is different. 
I updated `pip` (`pip 8.0.2 from /usr/local/lib/python3.4/dist-packages (python 3.4)`), I have a newer version of `rethinkdb` (`rethinkdb 2.2.4~0trusty (GCC 4.8.2)`) but still I get this log while pip installing `bigchaindb`:
```
Requirement already satisfied (use --upgrade to upgrade): rethinkdb==2.2.0.post1 in /usr/local/lib/p
ython3.4/dist-packages (from bigchaindb)
```
I tried `--upgrade` but as said it is already at the latest version. 
`pip` cache is void.

I manually deleted directory and egg in `/usr/local/lib/python3.4/dist-packages` but again while trying `pip`:
```
Collecting rethinkdb==2.2.0.post1 (from bigchaindb)
  Downloading rethinkdb-2.2.0.post1.tar.gz (105kB)
    100% |████████████████████████████████| 106kB 44kB/s
```
even if the newer version is present.

**Comment by vrde** [comment]
The nice devs at RethinkDB fixed the issue and pushed a new version of their package. I'll update you once I upload the new version of our package on PyPI.

**Comment by vrde** [comment]
@Mec-iS: `v0.1.3` is in PyPI, can you give it a try?

**Comment by Mec-iS** [comment]
ok, done. Keys generated and daemon running
