### ISSUE TITLE
Confusing error message for config file.

### ISSUE THREAD

**Issue by nsgeorgi** [bigchaindb/bigchaindb#419]
I manually updated the config file which by default is located at ~/.bigchaindb and I received the below error message after I tried this command in python API "b = Bigchain()". After the help of @vrde I realised that I had some typo in the config file and I got the error cause it was no longer valid json. In the future you could print a better error message.
![screenshot-from-2016-07-05-04_24_32](https://cloud.githubusercontent.com/assets/8840982/16603317/f0f17434-4312-11e6-9fca-91fe36cec34f.png)

**Comment by vrde** [comment]
Thanks for reporting the issue @nsgeorgi!

Maybe we can fix this by reviewing the configuration system and use something more classical than a JSON file. If we use [ConfigObj](http://www.voidspace.org.uk/python/configobj.html) we can even add schema validation. It's a bit old (~6 years) but if someone knows anything newer please tell us.
@sbellem: any thoughts on that?
