### ISSUE TITLE
Handle the Case of the Unlucky Valid Transaction

### ISSUE THREAD

**Issue by ttmc** [bigchaindb/bigchaindb#424]
Moved from Issue #346 

It might happen that an unlucky valid transaction gets included in a sequence of invalid blocks (and so it takes a long time before it's "finalized," i.e. in a valid block).

Maybe we could check valid transactions at block-building time (using a query?) to see how many invalid blocks they've been in before, and if it's greater than three (say), we could just put the unlucky transaction in its own block to ensure that it gets into a valid block ASAP.

**Comment by r-marques** [comment]
I think the way to go is to minimize the number of invalid blocks. If we have a sequence of invalid blocks it means that either we have malicious nodes or the consensus is broken.

If the sequence of invalid blocks is small then the transaction won't take long to be confirmed. 

The proposed solution at this point adds complexity with little benefit

**Comment by ttmc** [comment]
Yeah, I agree: invalid blocks should be rare, and "unlucky valid transactions" even rarer, so adding time-consuming code to deal with them amounts to making the whole system slower and more expensive just because of an edge case that almost never happens (and isn't system-breaking if it does happen).

I will close this issue but I'm glad it was discussed, so we have somewhere to point people if they ask.
