### ISSUE TITLE
Proposal: Make block timeout value configurable

### ISSUE THREAD

**Issue by r-marques** [bigchaindb/bigchaindb#427]
The purpose of the timeout in the block creation routine is for the block creation to wait for new transactions from the validators before creating the block.

We do this because on slower systems transactions are not validated fast enough and without a timeout this causes the block creation routine to create in quick succession blocks with few transactions instead of bundling them to save consensus rounds.

There have been some questions about this value and whether it is configurable and @makevoid forked bigchaindb just to make this change.

Would it make sense for this to be a configurable parameter in the bigchaindb config file?

**Comment by ttmc** [comment]
The block-creation-timeout time is something every node in the federation should agree on (like the keyring), and therefore if it is configurable, it should be included in the set of **federation-level** configuration parameters. Right now, we have nowhere to store federation-level configuration parameters, but see the proposal in issue #187

**Comment by makevoid** [comment]
+1, I am using a fork (that I have to periodically sync) just to change
block time - I am currently putting a value slightly higher than average
ping (latency)

**Comment by ttmc** [comment]
Related issue #123

**Comment by ttmc** [comment]
We decided not to make a fancy cluster configuration management system (issue #436, now closed), so if we _do_ decide to make block timeout value configurable, we can just add it as a new setting in the BigchainDB Server configuration file.
