### ISSUE TITLE
A little mis-discription

### ISSUE THREAD

**Issue by huangpeilong** [bigchaindb/bigchaindb#438]
"is_valid_transaction(transaction)[source]
Check whether a transacion is valid or invalid.
Similar to validate_transaction but does not raise an exception if the transaction is valid."

The description above is from “http://bigchaindb.readthedocs.io/en/latest/appendices/the-Bigchain-class.html”.   And the last letter should be "invalid".

**Comment by r-marques** [comment]
@huangpeilong want to submit a pull request?

**Comment by huangpeilong** [comment]
@r-marques I have just write a script to deploy bigchaindb on a single ubuntu node:
"""
#! /bin/bash

echo begin to prepare bigchaindb on one ubuntu node
apt-get update
apt-get install -y g++ python3-dev
apt-get install -y python-pip

# install rethinkdb
source /etc/lsb-release && echo "deb http://download.rethinkdb.com/apt $DISTRIB_CODENAME main" | sudo tee /etc/apt/sources.list.d/rethinkdb.list
wget -qO- https://download.rethinkdb.com/apt/pubkey.gpg | sudo apt-key add -
sudo apt-get update
sudo apt-get -y install rethinkdb
#rethinkdb --bind all

# install bigchaindb
pip install virtualenv
mkdir /root/bigchaindb
cd /root/bigchaindb
virtualenv -p /usr/bin/python3.4 py34env
source py34env/bin/activate

pip3 install --upgrade bigchaindb
bigchaindb -y configure
"""

**Comment by ttmc** [comment]
I am confused. When I look at the source code of the `is_valid_transaction()` method, I see that if the transaction is valid, it returns the transaction itself, and otherwise (i.e. if the transaction is invalid), it returns `False`. That's consistent with the docstring. I don't see the error.

**Comment by ttmc** [comment]
@r-marques helped me understand. That line can be interpreted in two different ways. I will do a quick pull request to fix this issue.
