### ISSUE TITLE
Connect multiple BigchainDB nodes using Docker

### ISSUE THREAD

**Issue by vrde** [bigchaindb/bigchaindb#439]
Our [`Dockerfile`](https://github.com/bigchaindb/bigchaindb/blob/master/Dockerfile) starts BigchainDB with the flag `--experimental-start-rethinkdb`, that is an experimental flag to start RethinkDB (you don't say?).

Since our `Dockerfile` embeds RethinkDB, we need to expose from the BigchainDB command line at least the `--join` option.

If you are familiar with Docker, this issue should be simple to implement. If you want to give it a try you should:
- read our [guidelines for contributing](https://github.com/bigchaindb/bigchaindb/blob/master/CONTRIBUTING.md)
- understanding how to start a [RethinkDB cluster on multiple machines](https://rethinkdb.com/docs/start-a-server/#a-rethinkdb-cluster-using-multiple-machines)
- add a new parameter (I think a good name is still `--experimental-join`) in the Command line interface, more or less [here](https://github.com/bigchaindb/bigchaindb/blob/master/bigchaindb/commands/bigchain.py#L232)
- pass the parameter to the [`util.start_rethinkdb` function](https://github.com/bigchaindb/bigchaindb/blob/master/bigchaindb/commands/bigchain.py#L159)
- add the parameter, if any, to the list of parameters [here](https://github.com/bigchaindb/bigchaindb/blob/master/bigchaindb/commands/utils.py#L26)
- add a test in [test_commands.py](https://github.com/bigchaindb/bigchaindb/blob/master/tests/test_commands.py) (testing this feature might be a bit tricky because it might need mocks, if you are in trouble with it just comment this issue)

**Comment by krish7919** [comment]
@vrde : We can get this done using etcd, flannel and docker containers for bdb and mongo/rethinkdb. Can be useful for testing and benchmaking, on single or multiple cloud instances.
I can elaborate more on this if this sounds interesting.

**Comment by trentmc** [comment]
What is the problem that this issue is solving? Not sure it's a priority.

**Comment by krish7919** [comment]
It isn't a priority.
Can help people run cluster level tests easily in the face of sharding and other features we are bringing in.
