### ISSUE TITLE
Review number of CPUs option for py.test on travis

### ISSUE THREAD

**Issue by sbellem** [bigchaindb/bigchaindb#455]
We currently use in our [.travis.yml](https://github.com/bigchaindb/bigchaindb/blob/master/.travis.yml#L20) file:

```yml
script: py.test -n8 -v --cov=bigchaindb
```

where the `-n 8` option is to send the tests to multiple CPUs, 8 in that case. But does travis provide 8 CPUs?

As per [travis documentation](https://docs.travis-ci.com/user/ci-environment/#Virtualization-environments), we have **two** cores.

See related github issue at https://github.com/travis-ci/travis-ci/issues/4696.

**Comment by vrde** [comment]
I think the best approach is to use `-n auto`, so it's automatic :)

**Comment by sbellem** [comment]
@vrde #457 :smile:

**Comment by vrde** [comment]
oh that's great :+1:
