### ISSUE TITLE
benchmark test issue

### ISSUE THREAD

**Issue by LyLuo** [bigchaindb/bigchaindb#470]

**Comment by LyLuo** [comment]
environment: 
one server (two Intel Xeon E5-2660 v3 (40 core), 128G memory, raid 6(hard disk))
deployment:
three rethinkdb instances
three bighchain nodes

when i executed run_add_backlog in benchmark_utils.py with parmamter 40000000, i got a error.
 thank you in advance

error:
rethinkdb.errors.ReqlOpFailedError: Cannot perform read: primary replica for shard ["", +inf) not available in:
r.table('backlog').get_all('ff037f7aaacee1f144052d3549876bd13f3fba9883168b0a9bedc62cc1649337').delete(durability='soft')

![error](https://cloud.githubusercontent.com/assets/5416987/16980072/dabac5f0-4e96-11e6-9fe8-d10dbd6cc4b5.png)

**Comment by ttmc** [comment]
How did you set up your server to run three RethinkDB instances and three BigchainDB nodes? How did you set things like the ports they use? Did you run the BigchainDB nodes in virtual machines or Docker containers or what?

Did you do other checks to make sure the RethinkDB instances are all communicating with each other properly? For example, once the RethinkDB instances are running, what shows up on when you visit http://localhost:8080/ ?

**Comment by LyLuo** [comment]
![cluster](https://cloud.githubusercontent.com/assets/5416987/17050661/b57fcd44-5026-11e6-82c2-a5dcf478a4c2.png)
![backlog](https://cloud.githubusercontent.com/assets/5416987/17050846/c29e58dc-5027-11e6-9fe8-1bd3d7c1f862.png)
My rethinkdb cluster works fine. At the begining, tps of write performance of backlog was about 3K  At that time, i didn't configure shard and replicas.
I did benchmark test again with set-shards = 3, I got this error.
![init](https://cloud.githubusercontent.com/assets/5416987/17050834/b648a074-5027-11e6-86cb-845153cbe4e0.png)
![error](https://cloud.githubusercontent.com/assets/5416987/17050922/43564df4-5028-11e6-8115-b99989fe29a9.png)
I guess it caused by disk performance.

**Comment by r-marques** [comment]
That usually happens when one of the primary replicas goes down. Do you get any warnings about about that in the rethinkdb webui?

Also note that the code in the benchmarking-test folder is still a work in progress. We paused the benchmarks in favor of a refactor of our multiprocessing code.

Once that is finished we will resume the benchmarking tests.

**Comment by r-marques** [comment]
Closing this as it relates to outdated code that is no longer in use.
