### ISSUE TITLE
Fix the Python style guide on string formatting

### ISSUE THREAD

**Issue by ttmc** [bigchaindb/bigchaindb#477]
Our current [Python style guide](https://github.com/bigchaindb/bigchaindb/blob/master/PYTHON_STYLE_GUIDE.md) says to use .format() to compose strings with formatted variables inside them, but based on this comment

https://github.com/bigchaindb/bigchaindb/pull/476#issuecomment-234239734

it seems that our Python style guide is wrong. I'm not sure when to use what now, so someone who understands that should update our Python style guide. @vrde I will assign this to you but feel free to assign it to someone else.

**Comment by sbellem** [comment]
Is this specific to `logging` only?

With respect to `logging`, different formatting styles are available. See https://docs.python.org/3/howto/logging-cookbook.html#formatting-styles

and https://docs.python.org/3/library/logging.html#logging.basicConfig

**Comment by sohkai** [comment]
@ttmc I think @vrde's comments were more specific to logging (which has its own set of best practices aside from string composition). [PEP 3101](https://www.python.org/dev/peps/pep-3101/) basically replaces the `%` operator with `.format()` wholesale.

We can add (or link to) some best practices for logging, but that might not fall inside the domain of the style guide.
