### ISSUE TITLE
IPLD support in BigchainDB

### ISSUE THREAD

**Issue by TimDaub** [bigchaindb/bigchaindb#485]
Use this [py-ipld](https://github.com/bigchaindb/py-ipld/issues/1) to hash blocks and transactions.
Make serialization and hashing unopinionated in bigchain-db core though.

There was a PR for this (now closed): #381

**Comment by TimDaub** [comment]
Since #641 was merged, here are some updates to my master plan:

IPLD integration should now be **much** simpler. The requirements for IPLDizing the BigchainDB data models are the following:

- replace all `sha3_256` `id`s with IPLD ids
- Use IPLD paths to links between data

In practice, these are the tasks that need to be done:

- Add a toggable option to BigchainDB to enable IPLD (we can also go straight for it if we want)
- Some minor changes have been made to the IPLD spec, hence [py-ipld](https://github.com/bigchaindb/py-ipld#usage) might not be up to date anymore
- Create a `to_hash` method from [this](https://github.com/bigchaindb/bigchaindb/blob/master/bigchaindb/models.py#L156) and overwrite it in a `IPLDBlock` class with [multihash and marshal](https://github.com/bigchaindb/py-ipld#usage).
- Override/replace [this method](https://github.com/bigchaindb/bigchaindb-common/blob/master/bigchaindb_common/transaction.py#L595) in the `Transaction` class with [multihash and marshal](https://github.com/bigchaindb/py-ipld#usage).

_Either_

- Remove the need for [`TransactionLink`](https://github.com/bigchaindb/bigchaindb-common/blob/master/bigchaindb_common/transaction.py#L79) and simply pass a IPLD path URI

_or_

override `TransactionLink`'s `to_dict` and `from_dict` methods to (de)serialize from a IPLD path URI (definitely the dirty way)

_or_

provide a way for `TransactionLink` to handle IPLD path URIs (`to_ipld`, `from_ipld`?).


### Challenges:

- `payload` (aka `metadata` aka `data`) relies on having a UUID as a hash. At this point, IPLD doesn't know what a UUID is. Eventually it will. This is not a blocker so we can ignore it for now.

- Same goes for a digital assets data. Not a blocker, we can ignore.

//cc @jbenet as he might be interested in this.

**Comment by ttmc** [comment]
If the `id` is removed from the JSON representation of a transaction, then what will the underlying database use for the primary key?

Conceptually, I'm intrigued by the idea of removing all signatures (i.e. all fulfillments) from the transaction: it makes calculating signatures more straightforward. It's asymmetric, since the conditions are inside the transaction, but oh well, it's not like symmetry is a requirement.

**Comment by TimDaub** [comment]
> If the id is removed from the JSON representation of a transaction, then what will the underlying database use for the primary key?

It's not quite like this.
We can still store Transactions and Blocks the way we do currently (in their JSON representation, using `id`s as primary keys for querying). What matters though is how we represent them to users of the HTTP API.
There we'll have to comply to an IPLD-compatible schema (removing the `id` and moving the `fulfillments` signatures) - basically all points I've mentioned in my last comment.

**Comment by TimDaub** [comment]
// @whyrusleeping for the discussion later.

**Comment by whyrusleeping** [comment]
@TimDaub Link from speaking in person: https://github.com/ipfs/specs/tree/master/iprs-interplanetary-record-system

**Comment by TimDaub** [comment]
As was pointed out in #830, IPLD (or rather merkle trees) would help us to verify partial bodies in HTTP JSON responses.

**Comment by ttmc** [comment]
I'm removing the "when: in progress" label on this issue because I'm pretty sure it's not in progress.

**Comment by ttmc** [comment]
I created the issue bigchaindb/BEPs#87 to remind us about this idea, so I'm going to close this issue here.
