### ISSUE TITLE
Write specs for divisible assets

### ISSUE THREAD

**Issue by r-marques** [bigchaindb/bigchaindb#487]
Define data model specs and core consesus protocol to to support divisible assets

**Comment by r-marques** [comment]
Initial specs for divisible asset support on bigchaindb. This is still a work in progress

### Terminology

It would be helpful to come up with a terminology for the terms related to divisible assets. Since this is a blockchain its easy to think in terms of _coins_ and _amounts_, since these are the same terms used in crypto currency ledgers and in protocols that add support for divisible assets on top of currency ledgers e.g. colored coins.

A divisible asset is any asset can can be divided into a fixed amount of shares.
An amount is a subset of all the shares of a specific digital asset.

### Overview

To support divisible assets we need at least two new fields:
 - __amount__: an integer amount to be transfered
 - __asset_id__: possibly an uuid to uniquely identify that asset. Amounts / shares for different assets cannot be combined together

### Creation of a divisible asset

The creation of the divisible asset is similar to the creation of a digital asset, except that we can specify an amount of shares that this divisible asset will have.

### Transfer of a divisible asset

When transferring a divisible asset, besides specifying a new_owner we also need to specify the amount to transfer. The amount will be a new field on the conditions.

We need to perform an extra validation: total amount in the outputs of the transactions should be less then or equal to the total amount in the inputs of the transaction.

### Implementation details

We will start by adding a field in the conditions called __amount__. If amount is different then `0` or `None` the transaction will be treated as a divisible asset transaction and extra validation will need to take place. If __amount__ is `0` or `None` we will treat it as a normal undivisible asset transaction.

### Open questions

Should we allow the replenishment of shares of a divisible asset?
For example if a user creates a divisible asset with 10 shares can he in the future add 10 more shares to that digital asset?

**Comment by diminator** [comment]
> Should we allow the replenishment of shares of a divisible asset?
> For example if a user creates a divisible asset with 10 shares can he in the future add 10 more shares to that digital asset?

I think we should allow minting new coins of a previously defined coin-type. Then there needs to be a reference to the coin type

**Comment by r-marques** [comment]
I agree. We also need term other then coin

**Comment by ttmc** [comment]
Terminology: Isn't the "amount" the _number_ of shares in a subset (of all the shares), i.e. the "len" or "size" or "cardinality" of the subset? The amount is an integer, not a set.

Will it be possible to recombine shares of the same asset? If yes, maybe say a bit about how, and the associated validation logic.

Implementation details: Maybe indivisible assets could just have amount == 1 always? The meaning is more obvious. It wouldn't be possible to subdivide it because a set with one element doesn't have any meaningful subsets. It wouldn't be possible to combine it with other assets because no other assets would have the same asset_id.

**Comment by r-marques** [comment]
> Will it be possible to recombine shares of the same asset? If yes, maybe say a bit about how, and the associated validation logic.

You can divide or sum then at will. We only need to check that `sum(outputs) <= sum(inputs)`

**Comment by TimDaub** [comment]
> Should we allow the replenishment of shares of a divisible asset?
> For example if a user creates a divisible asset with 10 shares can he in the future add 10 more shares to that digital asset?

For the COALA IP protocol, replenishment of shares is not necessary.



> asset_id: possibly an uuid to uniquely identify that asset. Amounts / shares for different assets cannot be combined together

Do we really need this field? Shouldn't it be apparent by following a transaction to its origin?
I'd leave it out.

**Comment by r-marques** [comment]
We may need an `asset_id` if we are to allow replenishment of the shares. I will have a better understanding of what is needed as I implement it.

**Comment by MuzammalRamzan** [comment]
can someone guide me about devisiblity of asset in bigchaindb?

**Comment by ttmc** [comment]
@MuzammalRamzan AFAIK, assets are not divisible in BigchainDB.
