### ISSUE TITLE
Consider removing __init__.py files under tests/ dir

### ISSUE THREAD

**Issue by sbellem** [bigchaindb/bigchaindb#50]
See pyest [Good Integration Practices](http://pytest.org/latest/goodpractices.html#good-integration-practices)

> avoid `__init__.py` files in your test directories. This way your tests can run easily against an installed version of `mypkg`, independently from the installed package if it contains the tests or not.

**Comment by vrde** [comment]
Right now we have some relative imports that would fail without an `__init__` file. Also, I don't fully understand the advantage of removing these files.

Anyway, feel free to work on it and do a pull request :smile_cat: but I'd like to understand more what's going on here.
