### ISSUE TITLE
Remove plugin architecture

### ISSUE THREAD

**Issue by vrde** [bigchaindb/bigchaindb#500]
# Reasons to remove it:
- code difficult to navigate
- we are not using it
- too much abstraction

# Reasons to keep it:
- might be useful in the future to simulate malicious nodes or having different implementation of the consensus
- @thedoctor: are you using the plugin in your fork?

# Conclusion
Isolate and refactor the code for the consensus before abstract it (we need a stable consensus layer)

**Comment by ttmc** [comment]
Just a reminder: there's a page about consensus plugins in the docs: https://bigchaindb.readthedocs.io/en/latest/appendices/consensus.html

**Comment by thedoctor** [comment]
Sorry guys, I just saw this — I'm not actively using bigchain atm and won't have much time to contribute unless there's something specific I can do to make the code more usable for you guys.

**Comment by TimDaub** [comment]
> @sbellem Is this completed now with #641 merged?

Yes, this ticket has been resolved.
