### ISSUE TITLE
Isolate code to access the Database

### ISSUE THREAD

**Issue by vrde** [bigchaindb/bigchaindb#502]
Access to the database is spread around different layers of the architecture.
Would be nice to encapsulate all the database queries in a different module to keep the code more isolated and easy to test.

Consider also:
- https://github.com/bigchaindb/bigchaindb/pull/623/files#r77772779

**Comment by ttmc** [comment]
See pull requests #754 and #788

**Comment by sohkai** [comment]
Closing as #788 was merged.
