### ISSUE TITLE
Ensure durability == 'hard' everywhere

### ISSUE THREAD

**Issue by ttmc** [bigchaindb/bigchaindb#504]
RethinkDB only guarantees linearizability of individual atomic operations on individual documents if `durability` is set to `hard`, which is the default; see:

https://www.rethinkdb.com/docs/consistency/

There are some places in the code where `durability` is changed to `soft` (e.g. the default in `write_block()` in `core.py`). We should revisit that and let the `durability` be `hard` unless we have good reason.

@rhsimplex Would it make sense to add this issue to Issue #199? I'll assign it to you to decide.

**Comment by rhsimplex** [comment]
Sure. Should writes to `backlog` also be `hard`?

**Comment by ttmc** [comment]
It's the RethinkDB default for write durability to be `hard` so I assume it doesn't incur a huge performance penalty. We could do some experiments in the future.

**Comment by sohkai** [comment]
@r-marques I believe we did this a while back? AFAIK all durability settings are set to hard in the RethinkDB queries.

**Comment by r-marques** [comment]
Not all of them need to be. This was somewhat abstracted in the the queries but we will need something similar for mongodb because they also have what they call read and write preferences.

I can create a new issue for this and close this one.

**Comment by sohkai** [comment]
👍 .

I asked @vrde when we did the db abstraction and we came up with making RethinkDB queries always `write == hard` and `read == majority`, but potentially leaving other settings available in the `Connection` class if we needed it in the future.
