### ISSUE TITLE
Add a CHANGELOG.md file to track changes

### ISSUE THREAD

**Issue by SohKai** [bigchaindb/bigchaindb#51]
It'd be nice to have a document where the changes are listed, with attribution as appropriate. It's usually useful to note even small configuration changes, such as https://github.com/bigchaindb/bigchaindb/issues/41, or for version bumps, such as https://github.com/bigchaindb/bigchaindb/pull/42, so people can find out what's changed between versions.

Those same notes made in the CHANGELOG.md file can be copied over for each release that's done as well.

For example, see how React does this:
  * [CHANGELOG.md](https://github.com/facebook/react/blob/master/CHANGELOG.md)
  * [Releases](https://github.com/facebook/react/releases)

**Comment by ttmc** [comment]
We have a "Releases" page at:

https://github.com/bigchaindb/bigchaindb/releases

I gather it's auto-generated by GitHub from the tags and their associated comments. Maybe we can just have that page for now? If so, more comments should be added to the releases so we know what changed with each one.

**Comment by ttmc** [comment]
Here's an interesting discussion of ways to keep a CHANGELOG.md file in sync with the "Releases" (tags):  https://github.com/olivierlacan/keep-a-changelog/issues/1

**Comment by ttmc** [comment]
I found a nice set of guidelines which we could follow for writing the CHANGELOG.md file. It's on the website "Keep a CHANGELOG" at http://keepachangelog.com/ 

I can create and back-fill a `CHANGELOG.md` file using those guidelines, but going forward, everyone making changes (e.g. via pull requests) should consider editing `CHANGELOG.md` as part of their pull request. Then that file (`CHANGELOG.md`) can act as the source for what to put in a new "Release" (tag) on GitHub.

**Comment by ttmc** [comment]
Resolved by PR #117
