### ISSUE TITLE
Make quorum size a configuration parameter?

### ISSUE THREAD

**Issue by ttmc** [bigchaindb/bigchaindb#514]
The size of a "quorum" might vary between federations (e.g. 50% + 1, 2/3 + 1, unanimous, etc.).

Maybe start by adding that as a BigchainDB configuration parameter, and then later, once we have federation-level configuration parameters (see Issue #436), we can move it there.

This issue originated with issue #190.

**Comment by vrde** [comment]
Since #190 is closed, should we close this issue as well?

**Comment by ttmc** [comment]
We decided in #190 that every node must _vote_ but that's not the same as deciding that the size of a quorum should always be 50% + 1. That's a different question.

For example, if there are twelve federation nodes, how many must vote "yes" for the outcome of the election to be "yes"? Seven? Nine? All twelve nodes must vote regardless.

**Comment by vrde** [comment]
Correct, thanks for clarifying :)

**Comment by ttmc** [comment]
Issue #351 is related.

**Comment by libscott** [comment]
Agree with this issue; rather than requiring an `n/2+1` majority, which allows for many faults, we should have a configurable fault tolerance and encourage node operators to decide how many nodes may disagree based on actual reasons.

**Comment by ttmc** [comment]
Some folks may allow for at most one or two nodes to not vote, or vote differently. Some slack is needed because, for example, a node may be listed in the voters list for a block, but it may leave the federation forever before voting.

The validity of a transaction (or block) isn't a matter of opinion, but it does (today) depend on what other blocks are currently in the set of undecided and valid blocks, a set that changes over time.

**Comment by ttmc** [comment]
In BigchainDB 2.0, which is coming out soon, the required number of of voters isn't something BigchainDB Server controls or decides. It's left to the consensus and replication software, which is separate. One can look at the configuration settings of _that_ software, if they want to mess with how it works. This is just not an issue for BigchainDB any more, so I'm closing it.
