### ISSUE TITLE
Revisit how invalid tx get decided invalid and actions taken

### ISSUE THREAD

**Issue by ttmc** [bigchaindb/bigchaindb#524]
Right now, the only point where a transaction can leave the system is in the "block pipeline" (see https://github.com/bigchaindb/bigchaindb/blob/master/bigchaindb/pipelines/block.py ).

Summary of what a node does with a new tx in the backlog changefeed today: "If this tx is assigned to me, delete it from the backlog table, then check its validity. If it's valid, pass it on to get included in a block, otherwise forget it."

In other words, just one node makes the call on whether a tx is invalid and deletes it from the system. Moreover, it doesn't tell anyone it did that, so nobody can find out who removed the tx from the system.

Questions to consider:
1. When _should_ invalid transactions get removed from the system? Maybe when an Election copies transactions from an invalid block to the backlog, it could just not copy the ones it thinks are invalid?
2. Should the client that submitted the tx be informed that it was deemed invalid, and be told which node deemed it invalid? Should that notification be signed by the node which made the determination (so it can't be spoofed)?

**Comment by libscott** [comment]
For 1.0 we do not make a guarantee that even a valid transaction will not be deleted from the backlog before being made part of a valid block. This may come later.

**Comment by ttmc** [comment]
Transactions can still be dropped or deleted by Byzantine nodes in BigchainDB 2.0, but the assumption is that _not all nodes are Byzantine_, the assumption is that 2/3 of them are okay. So if you submit a transaction to almost all nodes, you should be fine. At least one of the non-faulty nodes will get the transactions into the system (regardless of the bad nodes) and that's all you care about.

If more than 1/3 of the nodes are Byzantine, then the network won't be able to come to consensus and all bets are off. The network will probably just halt to stay safe. That's just how these things work. It's not a bug, it's a feature. Stay within the _reasonable assumptions_ and everything should be fine.

I'm closing this issue.
