### ISSUE TITLE
Ensure no same-asset transactions get put in the same block

### ISSUE THREAD

**Issue by ttmc** [bigchaindb/bigchaindb#527]
The transactions in a block should all be "independent", i.e. 
1. a block should never contain a transaction that creates an asset plus another transaction that also transfers the same asset, and
2. a block should never contain two transfer transactions which transfer the same asset.

Remember that a transfer transaction can transfer multiple assets.

When a node builds a block, it starts by making a list of transactions to put in the block. Before it adds a new transaction to that list, it could check to see if that transaction references assets already in the list (i.e. in the transactions in the list). (If so, it should dump the transaction back in the backlog for future consideration.)

This check will be easier to do if every asset has a unique **asset_id**; it seems we will be adding that to help with the implementation of divisible assets; see issue #487 

@rhsimplex I will add this issue to Project Issue #199

**Comment by rhsimplex** [comment]
#629 should prevent this in principle.  After merging, such a transaction will be assumed `invalid` by `pipelines/block.py::Block::validate_tx` and the transaction will be dropped from the backlog.   Here we can simply except `FulfillmentNotInValidBlock` separately and do nothing.  How then can we keep these transactions from remaining in the backlog indefinitely?

**Comment by ttmc** [comment]
I think this issue is now resolved:

1. If a block somehow gets built that includes both an asset-creation-transaction and a transaction that tries to transfer the same asset, then when another node is validating that block, it will see a transfer transaction that's trying to spend an asset in an undecided block, and it will consider that transaction invalid. Hence the whole block will be considered invalid.
2. Resolved by similar logic, except now it's the double-spending check that will catch it, rather than the check to ensure the condition-being-fulfilled is in a valid block.

I will close this issue and check the box on issue #199.
