### ISSUE TITLE
Third-party libraries get installed in repository's root

### ISSUE THREAD

**Issue by Mec-iS** [bigchaindb/bigchaindb#53]
After installation all the libraries' directories and eggs get created in the root of the repository creating some messy environment. 

The libraries should be saved in a proper `lib` directory during installation.

**Comment by r-marques** [comment]
How are you installing bigchaindb?

**Comment by Mec-iS** [comment]
from Pypi:

`python3 -m pip install bigchaindb`

**Comment by r-marques** [comment]
Sorry, maybe I am missing something.

If you install through pip it should install bigchaindb in `site-packages` similar to other modules.

**Comment by r-marques** [comment]
If you are inside the root of the repository and do a `setup.py install` it will create the `egg-info` and `build` directory on the root of the repository before copying the files to `site-packages`. These are safe to delete after the install is completed (`setup.py clean --all` should take care of it).

**Comment by Mec-iS** [comment]
Yeah, sorry. I misinterpreted the outcome from `setup.py test` as been made by `pip`.
