### ISSUE TITLE
Add a documentation page to run a Vagrant based container on Windows or Linux

### ISSUE THREAD

**Issue by Mec-iS** [bigchaindb/bigchaindb#54]
It's quite easy to provision and run a Vagrant VM:

* Install Vagrant in your host system following instructions [here](https://www.vagrantup.com/docs/installation/)
* In your VM-to-be's home directory create the `VagrantFile` and the bash script to provision the machine (`config.sh`)

**VagrantFile**
```
# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.provision "shell", path: "config.sh"
  config.vm.box = "ubuntu/trusty64"
  config.vm.network "forwarded_port", guest: 7000, host: 7000
  config.vm.network "forwarded_port", guest: 5000, host: 5000
end
```
**config.sh**
```
apt-get -qqy update
apt-get -qqy upgrade
apt-get -qqy install build-essential
apt-get -qqy install curl
apt-get -qqy install git
apt-get -qqy install libssl-dev
apt-get -qqy install python3-pip
apt-get -qqy install rethinkdb
python3 -m pip install --upgrade pip
python3 -m pip install bigchaindb
```

* run `vagrant up` to start provisioning (SO and libraries get installed)
* run `vagrant ssh` to log in the newly created machine
* test if working, from VM's command line:
```
$> python3
>>> from bigchaindb.core import Bigchain
>>> bigchain = Bigchain()
>>> print(bigchain.host)
localhost
>>> print(bigchain.me)
<print the public key of the instance>
```

**Comment by ttmc** [comment]
Hi, we don't plan to support Vagrant, but you could maybe post these instructions on your own repository (open source) and we'd be happy to link to it from the documentation; that way it would be clear that we're not the folks writing it, but we do like to give our users options.

Just let us know where you post it.

**Comment by Mec-iS** [comment]
Ok: https://gist.github.com/Mec-iS/b84758397f1b21f21700

I think it can be useful also to solve much of Windows users' problems; being platform/provider/technology agnostic is important for open source.

**Comment by ttmc** [comment]
I added a link to that in the Installation section of the documentation and it will go live when PR #57 gets merged.
