### ISSUE TITLE
Investigate other database / blockchain APIs

### ISSUE THREAD

**Issue by sohkai** [bigchaindb/bigchaindb#541]
Notes on what others are doing / provide us insight with as we proceed with https://github.com/bigchaindb/bigchaindb/issues/362

**Comment by sohkai** [comment]
**To be updated as we go along:**

Mostly looked into Javascript clients, but results:

Mongo High Level Client
-----------------------

* Promise / callback interface
* Connect provides a `db` object instance
    * Can connect to multiple (replica sets, sharded clusters)
    * Can specify authentication scheme for user
* `db` object can:
    * `db.addUser(...)`: Add user
    * `db.collection('name')`: Get collection
    * `collection.insert(...)`, `.insertMany([...])`: Async insert, with success / error callback
    * `collection.find(...)`: Query collection for documents based on key matches
        * Can include projections to limit data returned
    * `collection.createIndex(...)`: Create index on collection
* Provides monitoring hook (APM)
* Uses Mongo wire protocol

Mongo REST
----------

* `mongod` includes simple REST API: only for monitoring, alerts, admin
* [Crest](https://github.com/cordazar/crest):
    * Exposes endpoints as: `<host>:<port>/<table>/<collection>`; e.g. `curl -d '{ "Key" : 42 }' -H "Content-Type: application/json" http://localhost:3500/test/example` adds a document to the `example` collection in the `test` dataase
    * Maps HTTP verbs to actions on the DB (based on the endpoints):
        * `GET` is returning documents,
        * `GET` with `query` query param is query
        * `POST` to create
        * `DELETE` to delete
    * Stores config in `config.json` file; can specify database host, port, username, password

===========

Questions
---------

* Can we provide something similar to [mongos](https://docs.mongodb.com/manual/core/sharded-cluster-query-router/) for query routing to nodes? How to make sure you're not screwed by malicious nodes?
    * Do you talk to a member of a federation or the federation as a whole (e.g. there's a proxy server somewhere)?
       * **Answer**: Right now, I think the plan is to talk to just a member (or you can give a list of members)
    * **Answer**: Super difficult question that's been asked a lot; we've found that we can find all the RethinkDB nodes through an API and BigchainDB should probably provide that as well. It's **really** hard to solve this when the client could potentially have to not trust any server.

**Comment by ttmc** [comment]
This gets at an outstanding issue ( #436 ): how shall nodes agree upon federation-level configuration parameters such as the list of node hostnames (for clients to use), the list of node public keys, etc.

**Comment by sohkai** [comment]
Closing this until we need to revisit this topic (e.g. for API v1.2, etc).
