### ISSUE TITLE
Decide on pattern of driver names for github repos

### ISSUE THREAD

**Issue by sbellem** [bigchaindb/bigchaindb#545]
e.g.:

py-bdb-driver
js-bdb-driver

or

bdb-driver-py,
bdb-driver-js

**Comment by ttmc** [comment]
"Semantics": I do not think it means what you think it means. :princess: 

Your suggested names are all fine. Please don't forget the COBOL driver.

**Comment by sohkai** [comment]
Closing since we've (more or less) picked a name for the Python driver (https://github.com/bigchaindb/bigchaindb-driver).

**Comment by kremalicious** [comment]
yeah, somehow the decided pattern mentioned in here wasn't used. Problems arising from that outlined here: https://github.com/bigchaindb/org/issues/35
