### ISSUE TITLE
Improvement proposal for get_transaction

### ISSUE THREAD

**Issue by r-marques** [bigchaindb/bigchaindb#557]
relates to #555 

Right now `bigchaindb.get_transaction` returns a transaction that exists in the `bigchain` table that is not in an invalid block. However it does not return any information about the status of the transaction.

We could improve the logic of `get_transaction` so that it would return every possible state of a transaction. This would require also querying the `backlog` if the transaction is not on `bigchain`. If the transaction exists instead of returning the transaction we would also return the status of the transaction.

Proposed status:
- UNDECIDED_BACKLOG
- UNDECIDED_BIGCHAIN
- DECIDED
- None (transaction is not in the backlog or bigchain, worst case its only in an invalid block in bigchain)

**Comment by rhsimplex** [comment]
Maybe I can work on this? I've re-written a lot of code for these functions. Should be able to make a PR before vacation.

**Comment by r-marques** [comment]
cc @diminator
