### ISSUE TITLE
Create a BigchainDB Glossary of Terms

### ISSUE THREAD

**Issue by ttmc** [bigchaindb/bigchaindb#59]
Feel free to comment with terms you want included.

**Comment by ttmc** [comment]
I've started writing a Glossary section in the Bigchain Documentation. I will be away on Thursday and Friday, but don't worry, I won't forget about it!

**Comment by Mec-iS** [comment]
Definitely a good idea.
Let's start from the beginning:
- block
- transaction
- vote (voting system)

**Comment by ttmc** [comment]
A first version of the Glossary has been merged via PR #69
