### ISSUE TITLE
Support other database backends?

### ISSUE THREAD

**Issue by ttmc** [bigchaindb/bigchaindb#591]
BigchainDB currently works with RethinkDB as its "database backend." We're investigating and considering having BigchainDB work with other database backends. The goal of this project is to support at least one other database backend.

**Comment by BigBlueHat** [comment]
@ttmc is https://github.com/bigchaindb/bigchaindb/blob/master/bigchaindb/db/utils.py the home of most of the DB related code?

It seems that Apache CouchDB (and it's kin: pouchdb-server, Cloudant, etc) could fit the bill. I'd be happy to chat through a mapping / integration. @tilgovi might also be persuaded / interested in helping out. 😁

**Comment by ttmc** [comment]
@BigBlueHat As noted in our [recent blog post](https://medium.com/the-bigchaindb-blog/what-rethinkdb-shutting-down-means-for-bigchaindb-3e6732caa652#.rkyez5ddz):

> "It’s important to note that we chose RethinkDB as a starting point, but BigchainDB code is designed to be agnostic to the underlying database and portable to other database substrates. One of our main goals has always been to help blockchain-ify other popular databases."

Also, from the [BigchainDB Whitepaper](https://www.bigchaindb.com/whitepaper/):

![blockchainify](https://cloud.githubusercontent.com/assets/1210951/19213182/9442d84e-8d64-11e6-80ed-4a97de8b59ba.png)

There are several things that would have to be done to support another database backend:
* Add one or more new configuration settings to BigchainDB Server
* Change the code to setup the database, its tables, its indexes, etc.
* Change all code that does database queries
* Change all "changefeed" code. This is tricky because other databases do this quite differently, if at all
* Change deployment and operations configurations, scripts, optimizations, etc.

Some of the database-calling code could be abstracted behind a standard interface; some refactoring would be required to support that.

I'm not sure how much I should say about this, because I'm not in marketing or management... Let's just say that *we mean it* when we say we plan to support other database backends, so there should be no surprise if we make some formal announcement along those lines, and code like the above starts to get pushed to this repository. Then it would be easier for you (and others) to see what it would take to support whatever database backend.

**Comment by ttmc** [comment]
Work has begun on this project. For example, see pull request #754.

**Comment by ttmc** [comment]
Even more details: see pull request #788

**Comment by sohkai** [comment]
MongoDB integration is underway, with the merging of #942 and additional implementation steps being documented under [the milestone](https://github.com/bigchaindb/bigchaindb/milestone/7).

**Comment by r-marques** [comment]
Can we close this?

**Comment by trentmc** [comment]
My view: yes

**Comment by sohkai** [comment]
Closing as we now support both MongoDB and RethinkDB, and the necessary infrastructure to support other backends is in place.
