### ISSUE TITLE
Double spend shouldn't be included in a block (block voted invalid)

### ISSUE THREAD

**Issue by TimDaub** [bigchaindb/bigchaindb#592]
See this line: https://github.com/bigchaindb/bigchaindb/blob/master/bigchaindb/consensus.py#L161

So the following scenario:
1. I create a spendable asset `create_transaction('create')`
2. I create a transfer transaction to spend the asset `create_transaction('transfer')`
3. I sign and write them both. They go through and end up in valid blocks
4. Now  I take the transfer-tx from step 2 and post it to the backlog again.

The voters will now run `validate_transaction` or `is_valid_transaction` (same methods in the end), that will see that the transaction posted in step 4 has the same `id` as the one already included in step two.

So in the line mentioned in the beginning:

`if spent and spent['id'] != transaction['id']:`

spent will be the `{'id': <txid of tx in step 2>, ...}`. It evaluates to `True`.
For `spent['id'] != transaction['id']`, `spend['id'] will be the`id`from the transaction of step 2, while`transaction['id']`will be that exact same`id`, which means the above boolean statement will evaluate to`False`meaning a`DoubleSpend` error is not thrown.

This means that a transaction will be included in a block, the voter-logic though will - by checking `validate_transaction` again - see that the transaction has now been spent twice https://github.com/bigchaindb/bigchaindb/blob/master/bigchaindb/core.py#L312 and vote the block `invalid`.

Still, a double spend shouldn't even reach a block as this could be used for DDOSing a BigchainDB network.

**Comment by libscott** [comment]
Superceeded by #1150
