### ISSUE TITLE
Fix functions that have unwanted side effects

### ISSUE THREAD

**Issue by TimDaub** [bigchaindb/bigchaindb#593]
This is a ticket for collecting functions that have unwanted side effects on objects that are being passed as parameters:

- [x] [`write_transaction`](https://github.com/bigchaindb/bigchaindb/blob/master/bigchaindb/core.py#L134) adds `assingee` to a transaction that is being passed

Please add functions to this ticket, so that they can be fixed. Thx.

**Comment by vrde** [comment]
Didn't spend too much time investigating this, but we can consider enforcing this from a *type* point of view using a [`MappingProxyType`](https://docs.python.org/3/library/types.html#types.MappingProxyType).

**Comment by sohkai** [comment]
@vrde big fan of `MappingProxyType`.
