### ISSUE TITLE
Document guarantees for version 1.0 Community (WIP)

### ISSUE THREAD

**Issue by ttmc** [bigchaindb/bigchaindb#595]
Answered Question: What are the guarantees we want to provide? "Works for x conditions, not y"
- Implemented x

Work in Progress.

For clarification, ask Rodolphe or Trent.

**Comment by TimDaub** [comment]
See also #1194.

**Comment by ttmc** [comment]
@TimDaub   We're done all the documenting that we're going to do for 1.0. I think we can close this issue and open more specific issues for future projects.

**Comment by TimDaub** [comment]
:tada: :)
