### ISSUE TITLE
DB admin worked out

### ISSUE THREAD

**Issue by ttmc** [bigchaindb/bigchaindb#598]
Transcript of the sticky note:

DB admin worked out
- initialization
- live
Every action becomes a "request for action"

(I think what this means is that if anyone wants to make a database-admin-level change to the database, they must first do a request to the whole federation and then all the other nodes must vote or whatever.)

This is closely related to cluster configuration management (issue #436) and the wire protocol firewall (issue #594).

**Comment by sohkai** [comment]
@ttmc I believe this is a duplicate of https://github.com/bigchaindb/bigchaindb/issues/598?

**Comment by ttmc** [comment]
Closed as a duplicate of #240
