### ISSUE TITLE
Need an easier way to update example Python code output in the docs

### ISSUE THREAD

**Issue by ttmc** [bigchaindb/bigchaindb#607]
Some of our docs have examples of Python code and the output of those examples:

https://bigchaindb.readthedocs.io/en/latest/drivers-clients/python-server-api-examples.html

https://bigchaindb.readthedocs.io/en/latest/drivers-clients/python-driver-api-examples.html

I'd rather not have to be updating those manually all the time. In principle, it should be possible to get the outputs from a live, running instance of BigchainDB + RethinkDB. I don't think ReadTheDocs can run RethinkDB on their side though. One solution:

Step 1, on our side: run RethinkDB, BigchainDB, and some scripts to auto-generate those outputs and insert them as static text in the relevant Markdown files (in /docs/source/...). This wouldn't have to be done all the time, just when we expect the outputs in examples to be changed.

Step 2, use Sphinx to generate the docs from the contents of the GitHub repo, the same as always. This works locally and on ReadTheDocs.

Maybe Step 1 can be accomplished using an IPython Notebook?
- Start RethinkDB
- Start BigchainDB
- Start IPython
- Run an IPython notebook version of the documentation page (contains the text, the Python commands, and the output of those commands)
- Convert the "finished" IPython notebook to something Sphinx can ingest (.rst or .md or whatever)

A quick Google search reveals that there are several options for that last step.

**Comment by ttmc** [comment]
Sorry I bumped something on my keyboard and created this issue before I was done writing it up. I edited the description and it's better now.

**Comment by ttmc** [comment]
Issue #637 is about the same example code but it's concerned with _testing_ that code.

**Comment by ttmc** [comment]
I discussed the Python Server API examples page at

https://bigchaindb.readthedocs.io/en/latest/drivers-clients/python-server-api-examples.html

with Dimi (who wrote that page). He said that all the Python Server API functionality should (eventually) be exposed via the various client-side APIs, so that page will no longer be necessary. Maybe it can be moved to the Appendices, with some notes added to the top.

As for the Python Driver API examples page at 

https://bigchaindb.readthedocs.io/en/latest/drivers-clients/python-driver-api-examples.html

... the example code is now gone from that page (as of PR #625). Some new example code will be going in the new Python driver documentation at https://bigchaindb-driver.readthedocs.io/en/latest/index.html so this issue isn't going away, it's just moving over there.

Maybe we can use the Sphinx extension named doctest? See http://www.sphinx-doc.org/en/stable/ext/doctest.html

**Comment by sbellem** [comment]
We could [`sphinxcontrib.autorun`](https://bitbucket.org/birkenfeld/sphinx-contrib/src/28c9d4224c27027ab5f443c40561bf8893888eb0/autorun/?at=default) perhaps. 

It needs to be ported to Python 3 though, but the amount of code is fairly small, so it shouldn't be a big effort.

**Comment by sbellem** [comment]
[Cog](http://nedbatchelder.com/code/cog/) by Ned Batchelder

Interesting blog post by Doug Hellmann: https://doughellmann.com/blog/2009/02/02/writing-technical-documentation-with-sphinx-paver-and-cog/

Related stackoverflow post: http://stackoverflow.com/questions/9809434/auto-generate-doctest-output-with-sphinx-extension

**Comment by ttmc** [comment]
@sbellem I think we've found a nice solution for this, which we're already using in the Python Driver docs: the `ipython` directive thing. I think we can close this issue.
