### ISSUE TITLE
Design of a REST API

### ISSUE THREAD

**Issue by Mec-iS** [bigchaindb/bigchaindb#61]
I take here some notes about the REST API.

Taking the first look to the core API I noted down these basic operations to be mapped into endpoints:
- Read Transaction (**R**ead)
    - by id
    - by payload
- Write transaction (**U**pdate)
- ... (add anything to have a complete list)

Next I will write algorithms to accomplish each of these operations. Like:
- _Write Transaction_:
```
bigchaindb.core.create_transaction
bigchaindb.core.sign_transaction
bigchaindb.core.write_transaction
```
- _Read Transaction_:
```
```

And creating a development server:
Is it needed to embed the server in the RethinkDB Web-interface one, or a parallel one has to be started? Is it the first option possible (reading the RDB doc now for the first time) or advisable? If the second, I would suggest [Falcon Framework](http://falconframework.org).

**Comment by r-marques** [comment]
relates to #17

**Comment by Mec-iS** [comment]
Goes into #17
