### ISSUE TITLE
how to transfer $20 to pub_keyB when pub_keyA has an asset($100)

### ISSUE THREAD

**Issue by CsterKuroi** [bigchaindb/bigchaindb#616]
The following scenario:

1. pub_keyA create asset ($100) `create_transaction('create') `  

2. pub_keyA transfer $20 to pub_keyB `create_transaction('transfer')`

How to do this in bigchaindb?

**Comment by ttmc** [comment]
That will be possible once BigchainDB has support for divisible assets; see issue #129.
