### ISSUE TITLE
Ed25519VerifyingKey bug

### ISSUE THREAD

**Issue by LyLuo** [bigchaindb/bigchaindb#617]
![bug](https://cloud.githubusercontent.com/assets/5416987/18200047/93b144f6-7135-11e6-8f17-bd6f141a1d48.png)

**Comment by ttmc** [comment]
We don't test our code on win32 machines, so that's one possibility. Dimi will take a closer look once he has time.

**Comment by LyLuo** [comment]
It's the same on CentOS 6.5 with python3.5
![image](https://cloud.githubusercontent.com/assets/5416987/18201260/bdde8a30-713b-11e6-97aa-8d249690fd77.png)

**Comment by diminator** [comment]
Thanks for reporting LyLuo

At a first glance, the python [ed25519 library](https://github.com/warner/python-ed25519) yields `True` under the following conditions:

```
msg = b'age=33&name=luo&title=architecture'
sig = b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'

vk_s  = b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'

msg  == _ed25519.open(sig + msg, self.vk_s)
```

cc @r-marques 
We might want to examine this closer. I did notice that our `cryptoconditions.crypto` library works internally with `base64` format while pure `bytes` would be better. This wrapper would then only need to expose `base58` versions of the keys and sigs

**Comment by TimDaub** [comment]
Should this ticket go under Cryptoconditions?

**Comment by diminator** [comment]
was filed as https://github.com/bigchaindb/cryptoconditions/issues/22
and resolved by https://github.com/bigchaindb/cryptoconditions/pull/28
Thanks @r-marques !

**Comment by diminator** [comment]
@r-marques does bigchaindb/cryptoconditions#28 has a version bump and is integrated in bdb / bdb-common and bdb-driver?

**Comment by r-marques** [comment]
I still need to test it on bigchaindb to see if everything is working correctly since we changed how the encoding works on cryptoconditions. I will actually take care of this now
