### ISSUE TITLE
Transfer Transaction using Rest API

### ISSUE THREAD

**Issue by SheikhAbdul** [bigchaindb/bigchaindb#622]
Team

Can you please let me know whether we will be able to initiate a TRANSFER operation using the Rest API?
If so, please share me some sample layouts.

regards
Sheikh

**Comment by diminator** [comment]
Hi @SheikhAbdul 

A `TRANSFER` operation is very similar to a `CREATE`:
1. Create the transaction on the client (using the drivers)
2. POST the transaction to the API.

In order to facilitate the creation of the transaction, we are we are working on a `Transaction` model that should be accessible by the drivers: see #586 - #590

**Comment by SheikhAbdul** [comment]
Hi Diminator,

Can you please confirm my below understanding?
1. I can initially create the transaction(Original one) using Rest API.
2. Now I need to Transfer the one created as part of #1.
3. I have to create a transfer transaction using Python Driver then post the same transaction via Rest API?

**Comment by diminator** [comment]
At this point, it is possble to create transfers easily on the server:
https://bigchaindb.readthedocs.io/en/latest/drivers-clients/python-server-api-examples.html

However, as we are migrating some of that code to the client, I'll cc @TimDaub who is actually doing that.

**Comment by SheikhAbdul** [comment]
Thanks for the update Diminator, I will wait to hear from TimDaub.

**Comment by TimDaub** [comment]
> Thanks for the update Diminator, I will wait to hear from TimDaub.

As @diminator already mentioned, you can use the driver that is currently provided in the bigchaindb repository.
It requires to have bigchaindb running on your machine though.
We're currently working on removing that limitation. For update on our progress, see this PR: https://github.com/bigchaindb/bigchaindb/pull/590

**Comment by TimDaub** [comment]
> For update on our progress, see this PR: #590

@SheikhAbdul We've now made it possible to use the [BDB-Driver](https://github.com/bigchaindb/bigchaindb-driver) with BDB.

Check out our usage examples [here](https://bigchaindb.readthedocs.io/projects/py-driver/en/latest/usage.html).

If it's OK for you @SheikhAbdul, I'll close this issue.

**Comment by SheikhAbdul** [comment]
Thanks for the update TimDaub. Will it be released as a new version? I am still using the version V0.6.0 released on September 1st.

**Comment by ttmc** [comment]
@SheikhAbdul Yes, that will be released in version 0.7, which should arrive in the next week or two.

**Comment by SheikhAbdul** [comment]
Thanks again for the update. Could you please drop a note to this issue, once it's released? so i will get an alert and check out.

**Comment by ttmc** [comment]
@SheikhAbdul We've released BigchainDB Server version 0.7. The change log summarizes what's new and changed:

https://github.com/bigchaindb/bigchaindb/releases/tag/v0.7.0

**Comment by SheikhAbdul** [comment]
Thanks for the update Troy, I am able to get it installed, however I am not able to CREATE a transaction now. I used to access the Rest API using Chrome Extension - Postman, with V0.6 I was able to create it using the same. I can understand that the transaction model has been updated now. The below is what I tried and I getting 
{ "message": "Invalid transaction",
  "status": 400
}

Input Body
{
  "transaction": {
    "operation": "CREATE",
    "asset": {
        "data": {
		"payload": {
        "msg": "Initial Transaction created on 10/31/2016"
        }
	  }
    },
    "metadata": null,
    "fulfillments": [
      {
        "owners_before": [
          "BBeUitPxYmzhs4rSH2V94PPP9nK4kygPXBFMrvpX8BPa"
        ]
      }
    ]
  }
}

Could you please get me a sample working one?

**Comment by ttmc** [comment]
@SheikhAbdul Today, the easiest way to build (and sign) a CREATE transaction is to use the BigchainDB Python Driver. Version 0.0.2 is the latest version; you can get it using `pip install --upgrade bigchaindb_driver`. Here is the documentation about how to use it:

https://docs.bigchaindb.com/projects/py-driver/en/latest/usage.html

In the future, we'll have more documentation about the steps to build and sign a valid CREATE transaction.

**Comment by sohkai** [comment]
@SheikhAbdul We've modified the way transactions should be sent to the server with the new version. 0.7.0 introduces the requirement for the client to sign every transaction they intend to send to the server (previously, this was only true for `TRANSFER` transactions; now this is true for both `CREATE` and `TRANSFER` transactions).

Unfortunately, our current client does the signing internally when you ask it to send a transaction. This means that there's no easy way to dump a signed transaction from the driver and put it into Postman, but we've already started to work on splitting the transaction signing away from the sending in the driver for its next release. We're also building CLI tools to make this easier :). By the next release, we'll be able to provide you with a workflow for use with Postman.

Stay tuned--we're actively focusing on making this part of the experience easier and better for you!

**Comment by SheikhAbdul** [comment]
Thanks for the update. Please keep me posted on this thread once we have an update.

**Comment by ttmc** [comment]
@SheikhAbdul It's now possible to prepare, fulfill (sign), and send a transaction using three separate BigchainDB Python Driver methods. There are examples in the latest driver docs: https://docs.bigchaindb.com/projects/py-driver/en/latest/usage.html

You may have to update to the latest versions of BigchainDB Server (v0.8.0) and BigchainDB Python Driver (v0.1.2).
