### ISSUE TITLE
get_addresses

### ISSUE THREAD

**Issue by MitchK** [bigchaindb/bigchaindb#628]
Hi,

where are the addresses that a node owns stored? Is there an API to retrieve those addresses, analog to `getaddresses` of MultiChain? (http://www.multichain.com/developers/json-rpc-api/)

**Comment by r-marques** [comment]
The only "addresses" a node stores are the public keys of the other nodes in the federation. These are stored in the configuration file under `keyring`. The configuration file is by default located at `$HOME/.bigchaindb`. You can also list the configuration file with `bigchaindb show-config`

**Comment by CsterKuroi** [comment]
The configuration file of rethinkdb contains:
The host:port of a node that RethinkDB will connect to
`join=10.2.1.22:29015`

**Comment by TimDaub** [comment]
@MitchK I think your question was answered by @r-marques.

I'll close this ticket for now. Feel free to reopen if you feel that your concern wasn't addressed properly.
