### ISSUE TITLE
`get_owned_ids` breaks after DoubleSpent

### ISSUE THREAD

**Issue by diminator** [bigchaindb/bigchaindb#633]
How to reproduce:
- do a `DoubleSpent`, you'll see the node putting the transactions back
- try `get_owned_ids`: it will throw an error on `DoubleSpent`

**Comment by rhsimplex** [comment]
Can you include the stacktrace? `DoubleSpend` is raised in both core and consensus

**Comment by rhsimplex** [comment]
I can't reproduce this. I have a PR open for integration tests ( #614).  See `tests/integration/test_double_creation.py::test_get_owned_ids_works_after_double_spend`.
