### ISSUE TITLE
API endpoint `POST transaction` is inconsistent with `CREATE`

### ISSUE THREAD

**Issue by diminator** [bigchaindb/bigchaindb#634]
Posting a `CREATE` transaction, will use `transform_create` and messes up a lot

- It shouldnt use that, needs to be consistent
- it alters the output conditions, so you cannot `CREATE` a hashlock or others
- the `owners_before` and `owners_after` get inverted

**Comment by TimDaub** [comment]
Is already handled in https://github.com/bigchaindb/bigchaindb/pull/590

**Comment by TimDaub** [comment]
@diminator I think this was resolved.

I'll close. Feel free to reopen if there's still smth missing.
