### ISSUE TITLE
No clear instructions on connecting nodes/instances/containers on single host-machine?

### ISSUE THREAD

**Issue by Kentoseth** [bigchaindb/bigchaindb#638]
I don't know if I am not seeing/reading the documentation properly, but I recall previously reading how to connect local instances/nodes/containers of BigchainDB to each other. I can no longer find that.

Here is my scenario:

- I am running x-instances of BigChainDB as LXC-containers, each with a DCHP address
- I would like to connect each node/instance to the other x-instances running locally to build a cluster

The documentation fails to clearly mention this (anywhere).

Can someone help clarify on this? (or link me to the documentation, in case I miss-read)

**Comment by ttmc** [comment]
These docs may be useful: https://bigchaindb.readthedocs.io/en/latest/nodes/setup-run-node.html

The general idea is:
* If you're running all the containers on the same machine, then you will have to give each one a unique intra-cluster communications port (when you launch it, i.e. either in the command line command to run RethinkDB or in the RethinkDB config file using `cluster-port=`). (The default is port 29015.) See https://www.rethinkdb.com/docs/config-file/ 
* Similar remarks for the `driver-port`. (The default is 28015.)
* the RethinkDB config file for each instance of RethinkDB should list all the other machine hostnames in its list of `join=hostname:port` statements.
* the BigchainDB config file for each instance of BigchainDB (usually in ~/.bigchaindb) should have the public keys of all _other_ BigchainDB nodes in its keyring. See https://bigchaindb.readthedocs.io/en/latest/server-reference/configuration.html#keyring
* There may be some other RethinkDB or BigchainDB config settings to consider. Let me know if I missed some.

**Comment by ttmc** [comment]
I'm closing this issue. If you are still having trouble, feel free to reopen this issue, or open a new issue.
