### ISSUE TITLE
BigchainDB installs but won't connect to RethinkDB

### ISSUE THREAD

**Issue by Flaise** [bigchaindb/bigchaindb#642]
I'm using a Vagrant instance to test BigchainDB. I made sure all the dependencies are installed. The `start` command isn't working; it gives me the following output:

```
vagrant@vagrant-ubuntu-trusty-64:~$ rethinkdb --version
rethinkdb 2.3.5~0trusty (GCC 4.8.2)
vagrant@vagrant-ubuntu-trusty-64:~$ bigchaindb --version
bigchaindb 0.6.0
vagrant@vagrant-ubuntu-trusty-64:~$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.04
DISTRIB_CODENAME=trusty
DISTRIB_DESCRIPTION="Ubuntu 14.04.5 LTS"


vagrant@vagrant-ubuntu-trusty-64:~$ bigchaindb start
INFO:bigchaindb.commands.bigchain:BigchainDB Version 0.6.0
INFO:bigchaindb.config_utils:Configuration loaded from `/home/vagrant/.bigchaindb`
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/rethinkdb/net.py", line 271, in __init__
    self._socket = socket.create_connection((self.host, self.port), timeout)
  File "/usr/lib/python3.4/socket.py", line 512, in create_connection
    raise err
  File "/usr/lib/python3.4/socket.py", line 503, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/bigchaindb", line 11, in <module>
    load_entry_point('BigchainDB==0.6.0', 'console_scripts', 'bigchaindb')()
  File "/usr/local/lib/python3.4/dist-packages/bigchaindb/commands/bigchain.py", line 305, in main
    utils.start(parser, globals())
  File "/usr/local/lib/python3.4/dist-packages/bigchaindb/commands/utils.py", line 95, in start
    func(args)
  File "/usr/local/lib/python3.4/dist-packages/bigchaindb/commands/bigchain.py", line 165, in run_start
    db.init()
  File "/usr/local/lib/python3.4/dist-packages/bigchaindb/db/utils.py", line 94, in init
    conn = get_conn()
  File "/usr/local/lib/python3.4/dist-packages/bigchaindb/db/utils.py", line 18, in get_conn
    bigchaindb.config['database']['port'])
  File "/usr/local/lib/python3.4/dist-packages/rethinkdb/net.py", line 661, in connect
    return conn.reconnect(timeout=timeout)
  File "/usr/local/lib/python3.4/dist-packages/rethinkdb/net.py", line 572, in reconnect
    return self._instance.connect(timeout)
  File "/usr/local/lib/python3.4/dist-packages/rethinkdb/net.py", line 430, in connect
    self._socket = SocketWrapper(self, timeout)
  File "/usr/local/lib/python3.4/dist-packages/rethinkdb/net.py", line 337, in __init__
    (self.host, self.port, str(ex)))
rethinkdb.errors.ReqlDriverError: Could not connect to localhost:28015. Error: [Errno 111] Connection refused
```

**Comment by r-marques** [comment]
That means that either rethinkdb is not running or is not running on localhost:28015

**Comment by sohkai** [comment]
@Flaise Are you still having issues connecting BigchainDB with RethinkDB on vagrant? It might be worth trying [our docker settings](https://github.com/bigchaindb/bigchaindb/blob/master/docker-compose.yml), checking that those work for you, and then diffing for what's different between the docker config and your vagrant config.

I'm not familiar with provisioning vagrant instances, but it's important to note that on Docker, we need to expose a number of ports from the RethinkDB instance and tell BigchainDB to connect to them (e.g. [here](https://github.com/bigchaindb/bigchaindb/blob/master/docker-compose.yml#L31) and [here](https://github.com/bigchaindb/bigchaindb/blob/master/docker-compose.yml#L6)).

**Comment by Flaise** [comment]
Version 0.6.0 is working fine. I didn't realize at the time that there were extra steps involved in starting RethinkDB (and that there was an explanation in a part of your documentation other than the quick start).

**Comment by sohkai** [comment]
Awesome :).

> I didn't realize at the time that there were extra steps involved in starting RethinkDB

Just curious, was step B on the [quickstart](https://docs.bigchaindb.com/projects/server/en/latest/quickstart.html) page confusing because it wasn't clear that you had to keep the rethinkdb daemon up?

**Comment by jln1989** [comment]
Am still getting this error even though my rethinkDB is up and listening on 28015. Any help would be much appreciated.

**Error:**
_

> File "/usr/local/lib/python3.5/dist-packages/rethinkdb/net.py", line 271, in __init__
>     self._socket = socket.create_connection((self.host, self.port), timeout)
>   File "/usr/lib/python3.5/socket.py", line 711, in create_connection
>     raise err
>   File "/usr/lib/python3.5/socket.py", line 702, in create_connection
>     sock.connect(sa)
> ConnectionRefusedError: [Errno 111] Connection refused
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/usr/local/bin/bigchaindb", line 11, in <module>
>     load_entry_point('BigchainDB==0.7.0', 'console_scripts', 'bigchaindb')()
>   File "/usr/local/lib/python3.5/dist-packages/bigchaindb/commands/bigchain.py", line 332, in main
>     utils.start(create_parser(), sys.argv[1:], globals())
>   File "/usr/local/lib/python3.5/dist-packages/bigchaindb/commands/utils.py", line 96, in start
>     return func(args)
>   File "/usr/local/lib/python3.5/dist-packages/bigchaindb/commands/bigchain.py", line 182, in run_start
>     db.init()
>   File "/usr/local/lib/python3.5/dist-packages/bigchaindb/db/utils.py", line 156, in init
>     conn = get_conn()
>   File "/usr/local/lib/python3.5/dist-packages/bigchaindb/db/utils.py", line 75, in get_conn
>     db=bigchaindb.config['database']['name'])
>   File "/usr/local/lib/python3.5/dist-packages/rethinkdb/net.py", line 661, in connect
>     return conn.reconnect(timeout=timeout)
>   File "/usr/local/lib/python3.5/dist-packages/rethinkdb/net.py", line 572, in reconnect
>     return self._instance.connect(timeout)
>   File "/usr/local/lib/python3.5/dist-packages/rethinkdb/net.py", line 430, in connect
>     self._socket = SocketWrapper(self, timeout)
>   File "/usr/local/lib/python3.5/dist-packages/rethinkdb/net.py", line 337, in __init__
>     (self.host, self.port, str(ex)))
> rethinkdb.errors.ReqlDriverError: Could not connect to localhost:28015. Error: [Errno 111] Connection refused

_



**RethinkDB Terminal**
> Loading data from directory /home/innovationlab/rethinkdb_data
> Listening for intracluster connections on port 29015
> Listening for client driver connections on port 28015
> Listening for administrative HTTP connections on port 8080

**Comment by ttmc** [comment]
I think we've seen this before and I think the solution was to: 

1. update RethinkDB to the latest version (see https://rethinkdb.com/docs/install/ ) and
2. update the `rethinkdb` Python package to the latest version: `pip install --upgrade rethinkdb`

**Comment by r-marques** [comment]
@jln1989 are you running rethinkdb in a virtual machine or container?
And is rethinkdb and bigchaindb running on the same machine? If not you need to change the `~/.bigchaindb` config file with the correct host for the database

**Comment by jln1989** [comment]
@ttmc : I have installed the rethinkDB today morning and version is 

> rethinkdb 2.3.5~0xenial (GCC 5.3.1).

I have run the second command you have given me and it gives me "it has already been updated"

@r-marques : Am running rethinkdb and bigchaindb are running on the same machine only. 

Thanks in advance guys. Am a newbie to rethink/bigchaindb and any help would be great.

**Comment by r-marques** [comment]
I am closing this for now.
@jln1989 if you are still having problems we can re open this.
