### ISSUE TITLE
Will bigchaindb support wallet?

### ISSUE THREAD

**Issue by LyLuo** [bigchaindb/bigchaindb#652]

**Comment by ttmc** [comment]
For a given BigchainDB federation (used for keeping records about some specific class of assets), a developer could write a "wallet" application (client) to manage a user's keypairs, list of unspent assets, and other information of interest to a user.

For example, a BigchainDB federation might be created to keep track of who owns the lawn ornaments in Kentucky. A developer might create a wallet to help Kentucky lawn ornament collectors keep track of their lawn ornaments. It could have lawn-ornament-specific features such as a map showing the current location of each ornament, and whether the lawn ornament was features in an episode of _Antiques Roadshow_.

The BigchainDB core development team may write a demo "wallet" client, as an example.

I'm going to close this issue but feel free to reopen it if you have a follow-up question.
