### ISSUE TITLE
BigChain data truncated after system reboot 

### ISSUE THREAD

**Issue by sekharkumarroy** [bigchaindb/bigchaindb#661]
It might sound weird however I observed after a hard reboot of my box all the existing data got truncated.

After reboot I did the following – 
Start rethinkDB & 
BigChainDB instance using the command “BigChainDB start”.

Have anyone experienced it before ?

**Comment by ttmc** [comment]
Can you provide more details? What do you mean when you say "all the existing data got truncated"?

**Comment by sekharkumarroy** [comment]
whatever payload I have pushed into the BigChain for a owner is no longer available after the reboot.

**Comment by ttmc** [comment]
Is there _some_ data still available (e.g. blocks containing transactions), with parts missing, or is there no data at all?

It would be great if you could provide more details, e.g. how did you build the transactions, what was in the payload, how did you send those transactions to BigchainDB for validation & storage, how did you find out what was stored (or not), etc.?

**Comment by sekharkumarroy** [comment]
We have developed Python based REST services to insert/push the payload into BigChainDB by using the CREATE asset API. Also there is a REST service (NodeJS) exposed to fetch the data directly from RethinkDB BigChain table. It works fine till I did a hard reboot. When I try to fetch data after reboot from RethinkDB it returns empty payload. Do you require more info please feel free to let me know. Please note we are querying rethinkdb directly as that's the only option we have to get the payload back. Please suggest if there are better ways to fetch the payload based on owner/assetid and filter condition.

**Comment by r-marques** [comment]
From bigchaindb side shutting it down before it finished processing transactions and voting can lead to data loss.
From the rethinkdb side a hard shutdown will probably also lead to data loss if there is data that was not yet committed to disk.

When you say payload do you mean the payload of the transactions? and if so did the entire transaction disappeared?
Also is there any error output from the bigchaindb process?

**Comment by sohkai** [comment]
@sekharkumarroy Are you still seeing this and able to reproduce it?

> Please suggest if there are better ways to fetch the payload based on owner/assetid and filter condition.

We're currently working on some features related to assets for this :).

**Comment by sekharkumarroy** [comment]
I haven't seen that lately. I don't also have exact steps to reproduce that as well.

**Comment by sohkai** [comment]
Ok, then I'll close this for now. We can reopen it in the future if we encounter it again :).
