### ISSUE TITLE
Log more

### ISSUE THREAD

**Issue by sbellem** [bigchaindb/bigchaindb#663]
We need to add more logging in various places, as it can greatly help troubleshooting.

- [x] API-level code: log errors before sending the response.(e.g.: before [`return make_error(...)`](https://github.com/bigchaindb/bigchaindb/blob/master/bigchaindb/web/views/transactions.py#L89) or before [`return response`](https://github.com/bigchaindb/bigchaindb/blob/master/bigchaindb/web/views/base.py#L17) within [`def make_error(...)`](https://github.com/bigchaindb/bigchaindb/blob/master/bigchaindb/web/views/base.py#L8))

More generally, following Python's docs, we should log at least for the following:

* to report events that occur during normal operation of a program (e.g. for status monitoring or fault investigation);
* to report suppression of an error without raising an exception (e.g. error handler in a long-running server process).

ref: https://docs.python.org/3.6/howto/logging.html#when-to-use-logging

**Comment by TimDaub** [comment]
@sbellem Please elaborate actions that should be logged in this ticket.
Otherwise the scope of this ticket is to broad.

**Comment by sbellem** [comment]
@TimDaub well, I will document the "various places" mentioned above, as soon as I can.

**Comment by sohkai** [comment]
I think that the broadness of this ticket exemplifies how problematic this is. We should have at least a debug flag that outputs a lot more about what the nodes are doing.

**Comment by r-marques** [comment]
We could use this ticket to discuss how logging should be done on bigchaindb.
Correctly using the python logging module would already put us in a good shape.
Setting that up correctly with flags to control the verbosity and where to log (console, file) would be enough for this ticket

**Comment by sbellem** [comment]
Sorry to have not provided more details yet. This ticket was created as I was troubleshooting an issue and thought that logging information could have helped. I will add details as soon as possible.

**Comment by krish7919** [comment]
Include log-rotate configs on logging.

**Comment by r-marques** [comment]
Since the _Log More_ we have added logging to BigchainDB and have been improving what is logged.
We already have a lot better scoped tickets to improve bigchaindb logging.
I think we should close this ticket.
@TimDaub @sbellem?

**Comment by TimDaub** [comment]
> We already have a lot better scoped tickets to improve bigchaindb logging.
> I think we should close this ticket.

Agreed.
