### ISSUE TITLE
[HTTP API] be more precise about the cause of an error

### ISSUE THREAD

**Issue by sbellem** [bigchaindb/bigchaindb#664]
Currently, it is possible to get `400` errors for various reasons (input transaction not found, double spend, invalid signature, etc), but an API user, will only receive an `'Inavlid transaction'` message. 

This issue proposes to pass on the exact reason for an invalid transaction as part of the response.

**Comment by ttmc** [comment]
@sbellem Do you think that pull request #916 resolved this issue, or is there still more to do?

**Comment by sbellem** [comment]
@ttmc there could perhaps be more to do but we can close the issue and re-open as needed.
