### ISSUE TITLE
util.py: do we need it

### ISSUE THREAD

**Issue by rhsimplex** [bigchaindb/bigchaindb#672]
https://github.com/bigchaindb/bigchaindb/blob/master/bigchaindb/util.py

Is there any reason for this file to exist anymore?  I think everything has been replaced with the transaction/block models and pipelines.

@vrde @TimDaub

**Comment by TimDaub** [comment]
Ideally we move the left over methods to "where they belong" (which might not exist already).
So to answer:

> util.py: do we need it

No.

**Comment by rhsimplex** [comment]
Thanks for the update
