### ISSUE TITLE
Rename variable "validity" to more descriptive name, such as "block_statuses"

### ISSUE THREAD

**Issue by sbellem** [bigchaindb/bigchaindb#679]
Some parts of the code have this variable `validity` which stores a dictionary of block ids, and their statuses. The word `validity` is somewhat nebulous once one knows what it actually holds.

See https://github.com/bigchaindb/bigchaindb/blob/master/bigchaindb/core.py#L215 for instance.

**Comment by ketanbhatt** [comment]
@sbellem can I take this up?

**Comment by sbellem** [comment]
Yes!

**Comment by ketanbhatt** [comment]
@sbellem have submitted a PR. Sorry for the delay, got caught up. Thank you
