### ISSUE TITLE
[HTTP API] Implement "get_owned_ids"

### ISSUE THREAD

**Issue by sbellem** [bigchaindb/bigchaindb#682]
This includes the support of query parameters, such as `owner`, etc

One example for which this could be useful:

```python
>>> # Retrieve the transaction with condition id
>>> b.get_owned_ids(testuser1_pub).pop()
{
    "cid":0,
    "txid":"933cd83a419d2735822a2154c84176a2f419cbd449a74b94e592ab807af23861"
}
```

see https://github.com/bigchaindb/bigchaindb/blob/master/docs/source/drivers-clients/python-server-api-examples.md#transfer-the-digital-asset

**Comment by TimDaub** [comment]
This is already handled in #601.

It's even already implemented in this PR #624 

I'll close this issue, further discussion in the issues linked.
