### ISSUE TITLE
Asset creation uuid should always be done server side

### ISSUE THREAD

**Issue by r-marques** [bigchaindb/bigchaindb#686]
In order for an asset to be uniquely identifiable in the blockchain there are 2 solutions to generate an id:
1. Use the hash of the asset payload.
2. Use a uuid.

The problem with 1. is that if two users create an asset with the same payload (e.g. empty payload) they will end up with the same id.

Right now we use solution 2.
The problem here is that we cannot trust client generated uuid's because a client could just forge this uuid to for instance mint more shares of an existing token.
So its important that when a user creates an asset for the server to disregard the uuid provided by the client and generate a random one server side.

TODO:
- [ ] check that uuids are actually generated server side (whatever uuid is provided by the client is disregarded and a new uuid is generated).
- [ ] write unit tests to test this scenario.

**Comment by ttmc** [comment]
A third idea is to use the id of the CREATE transaction as the id of the asset. For a discussion of that idea,  see issue #697

**Comment by r-marques** [comment]
Solution 2 no longer works because CREATE transactions are now signed by the clients. The server cannot change or assign a new asset id.

Closing this in favor of #697
