### ISSUE TITLE
Node should sign the JSON doc it returns as response to a root HTTP API request

### ISSUE THREAD

**Issue by ttmc** [bigchaindb/bigchaindb#692]
When you send an HTTP GET request to the root HTTP API endpoint (e.g. `http://joesbigchaindbcluster.net:9984/api/v1/`), the node at that endpoint responds with a JSON document, as implemented in

[bigchaindb/bigchaindb/web/views/info.py](https://github.com/bigchaindb/bigchaindb/blob/master/bigchaindb/web/views/info.py)

That JSON document should be signed by the sending node, i.e. there should be a new key/field added to the response: the signature of the document (after being serialized). That way the client can have more trust that the JSON document wasn't tampered-with en route, and came from the node in question. (The node's verifying key is already in the JSON document.)

**Comment by r-marques** [comment]
I feel like this is solved with HTTPS or am I missing something?

**Comment by krish7919** [comment]
@r-marques @ttmc and I just had a chat over this, and I think we can rely on HTTPS to say that the JSON was returned from the specific node.
