### ISSUE TITLE
Node should check on validity of UUID's schema

### ISSUE THREAD

**Issue by TimDaub** [bigchaindb/bigchaindb#693]
See: [How to check if a UUIDv4 is compliant to it's schema](https://gist.github.com/ShawnMilo/7777304).

I think this can be done in `Transaction.validate` or `Asset.validate`.

//cc @r-marques

**Comment by sohkai** [comment]
This should be handled by the schema validation in https://github.com/bigchaindb/bigchaindb/pull/798.
