### ISSUE TITLE
Use transaction ID as asset ID

### ISSUE THREAD

**Issue by libscott** [bigchaindb/bigchaindb#697]
When an asset is created, it needs to be identifiable with a unique ID, which can identify the set of transactions of this asset.

This ID can't be a hash of the asset, as the asset may have no distinguishing properties to give it a unique hash. The client may be trusted to generate a random asset ID, but this is also a potential attack vector and makes it more complicated to validate a block.

Using the ID of the transaction that created the asset has some nice properties:
- Client can still generate valid transactions
- No extra validation step is required
- No potential to create a duplicate (without privkey compromise), because the transaction ID depends on ~~a signature of the person creating  the asset~~ the public keys of the people creating the asset, verified by the signatures.

Thoughts?

**Comment by ttmc** [comment]
This is a nice idea.

One concern I had:  A client could make two CREATE transactions with the same hash/id at substantially different times (e.g. by lying about the timestamp in the second one, setting it equal to the timestamp of the first one). I just checked with Ryan about what would happen in that situation. Answer: The second transaction would be checked to see if there's already a transaction with the same ID in an undecided or valid block, and if there is, it would be deleted from the backlog. Good!

**Comment by sbellem** [comment]
I thought that the ID of the transaction was the hash of the transaction content. Has this changed?

**Comment by ttmc** [comment]
@sbellem That is also my understanding (where "the transaction content" doesn't include the signatures [fulfillments]). Why do you ask?

**Comment by libscott** [comment]
@sbellem I think you may be referring to the chicken / egg problem, how to record the asset ID inside the transaction, which then changes the transaction ID... The answer is that the asset definition inside the CREATE tx doesn't need to include the transaction ID, only subsequent transactions do.

**Comment by sbellem** [comment]
@libscott ok then

**Comment by ttmc** [comment]
Actually, it might not even be possible for a client to generate two transactions with the same hash/id, even if they try (e.g. by lying about the timestamp), because of the UUID in the `transaction.metadata.id`. I guess it depends on who generates _that_ UUID.

It doesn't matter though. Even if a tricksy client somehow manages to generate two CREATE transactions with the same id/hash, BigchainDB server will nuke the second one.

**Comment by libscott** [comment]
@ttmc: to be clear, the dummy fulfillment in the signed CREATE tx is critically important because it allows the creator to control their address space (only the controller of that privkey can generate a tx with that hash).

I also suspect that the UUID in metadata.id may be problematic, for the same reasons as the asset ID, ie, attack vector, verification overhead, is there any reason not to use the TX id to refer to it also?

**Comment by r-marques** [comment]
I agree with the solution in https://github.com/bigchaindb/bigchaindb/issues/697#issue-183622586

My only concern is that although the solution makes sense from a blockchain point of view it is a bad practice from a database point of view because we are using the same index to index different things and we have no control over the index since its the hash of the transaction.

This ties our hands if in the future we want to provide more custom ways for clients to index their assets. For instance its normal for databases to allow you to construct your indexes to address specific use cases like data clustering so that you can optimize read performance. Some examples are time series where you include time information on the index and cluster your data by day, hour, minute; geo data where you cluster your data by region or even uses cases where you want increasing ids.

But maybe this is just an early optimization.

**Comment by sbellem** [comment]
Perhaps I am missing something, but as of now my understanding of the transaction `id` was that it results from hashing its payload. 

Now, the `timestamp` and asset `id` played a role in making hashes unique, and consequently transaction `id`s unique.

If the above is correct, how do we plan to deal with possibly colliding transaction `id`s?

This situation has occurred in tests, in which rapidly created transactions, in a loop, would have identical `id`s. There was a time in which it was possible to have no asset `id`. Asset `id`s were re-introduced and the problem would not occur any more.

**Comment by r-marques** [comment]
@sbellem https://github.com/bigchaindb/bigchaindb/issues/697#issuecomment-254454929

That is a problem, although the consensus protocol would not allow two valid transactions with the same id.

Anyway since now the clients sign the CREATE transaction there is no way for the server to change the asset uuid.
The only other way would be for the consensus to make sure that the uuid does not exist yet. Basically do the same validation we already do on the transaction id

**Comment by libscott** [comment]
@sbellem @r-marques, as I said above, for this to work the hash of the `CREATE` transaction must include a signature by the person submitting it. That way, they will be not able to generate collisions with transactions that are not their own. This will probably necessitate an extra change.

**Comment by r-marques** [comment]
If we do include the signature in the hash of the transaction we need to be careful not to introduce transaction malleability. That was exactly the problem of bitcoin

**Comment by libscott** [comment]
> My only concern is that although the solution makes sense from a blockchain point of view it is a bad practice from a database point of view because we are using the same index to index different things and we have no control over the index since its the hash of the transaction.

We could have multiple indexes using the txid as the key, I would have thought. One could be a partial index of asset definitions, for example. Perhaps this depends on the database?

**Comment by libscott** [comment]
Talking with @ttmc, seems I was wrong and we don't need to include any extra signatures inside the CREATE tx, because it already contains public keys of the creators and those are verified by the signatures. Yay!

**Comment by sbellem** [comment]
What if we left it up to the user to provide the asset id? Many things do have unique identifiers, and could perhaps be used as the asset id.

As an example, the automotive industry uses [VIN](https://en.wikipedia.org/wiki/Vehicle_identification_number).

Manufactured goods have serial numbers, etc.

So could it make sense to develop an asset data model that allows the usage of the already existing unique id of the asset as the id of the asset, that can then be looked up in the DB?

**Comment by libscott** [comment]
I'm also wondering if we shouldn't enforce a `name` field on the assets. It could make sense when creating lists of assets, that each of them have a name. Any company performing analysis on assets will appreciate it. It could simultaneously serve as a `nonce`, ie, if the asset ID was `hash(pubkeys + name)`.

**Comment by TimDaub** [comment]
The relation of asset to transaction is 1:Many, meaning that for an asset a user for example would like to know:


- Which transactions are related to an asset?
- Which transactions are related to a group/type/cohort of assets?
- Which transaction is related to the creation of a particular asset?
- Which transaction caused some "state transition" of the asset?

What is clear is that by addressing the asset by transaction id, these questions cannot be answered.
I'd like to see the following properties represented in the asset id:

- it's unique within the system
- it helps verify the asset itself on retrieval, without involving the corresponding transaction's payload

Additionally, asset_id creation should be really dead simple and not cause any unforeseen restrictions (like: one asset of a kind for particular private keys (#851).

I hope these requirements help the discussion. I'll think of solutions myself a little.

**Comment by libscott** [comment]
It was decided to use the transaction ID to refer to the asset, and the implementation ticket is #926.

**Comment by sohkai** [comment]
@libscott and I had a conversation about ensuring unique `CREATE` tx IDs for assets which may be the same. We came to the (perhaps limiting?) conclusion that you'll either need to provide a unique asset or metadata payload as the nonce, to generate the unique tx ID. I think that enforcing the user to provide a unique asset (if you don't want to use the metadata) is quite elegant with respect to divisible assets: if you want to create the same asset more than once, you should probably be using a divisible asset.

**Comment by libscott** [comment]
> @diminator 
> [10:40 AM]  
> agreed
> 
> [10:40]  
> the driver could abstract that actually by inserting a nonce/UUID automatically

**Comment by diminator** [comment]
> conclusion that you'll either need to provide a unique asset or metadata payload as the nonce, to generate the unique tx ID. I think that enforcing the user to provide a unique asset (if you don't want to use the metadata) is quite elegant with respect to divisible assets: if you want to create the same asset more than once, you should probably be using a divisible asset.

agreed. The driver could help the user by inserting a nonce or UUID automagically
