### ISSUE TITLE
Unified place to set the version number

### ISSUE THREAD

**Issue by ttmc** [bigchaindb/bigchaindb#70]
Right now, the BigchainDB version number is stored in at least two places:

1. /setup.py inside the setup(), there is e.g. `version='0.1.3'`
2. /docs/source/conf.py in the variables named version (e.g. "0.1") and release (e.g. "0.1.3-rc4").

Maybe there will be more places in the future.

It would be nice if there was one central place (file?) where the long version name could be stored, and then a script could read that central place to modify conf.py and setup.py accordingly, so the version number stays in sync across all files.

**Comment by sbellem** [comment]
see http://python-packaging-user-guide.readthedocs.org/en/latest/single_source_version/
