### ISSUE TITLE
MongoDB support tasks

### ISSUE THREAD

**Issue by rhsimplex** [bigchaindb/bigchaindb#704]
Bookkeeping tasks for MongoDB support, to be expanded by more issues
- BigchainDB init with MongoDB
- Connection object with MongoDB
- Writes/Queries
- Configuration setting for backend
- Docker container
- Set up indexes

**Comment by sohkai** [comment]
Closing for our initial MongoDB implementation milestone: https://github.com/bigchaindb/bigchaindb/milestone/7
