### ISSUE TITLE
Merge bigchaindb-common repo into the bigchaindb repo

### ISSUE THREAD

**Issue by r-marques** [bigchaindb/bigchaindb#706]
TODO:
- [x] merge the code inside a subfolder of bigchaindb `bigchaindb/common` -- see PR https://github.com/bigchaindb/bigchaindb/pull/731 -- see PR https://github.com/bigchaindb/bigchaindb/pull/732
- [x] merge the tests inside a subfolder of tests `tests/common`
- [x] fix all the tests and problems with the merge
- [x] move all issues from bigchaindb-common into bigchaindb
- [x] ~~move the docs to ?~~

**Comment by r-marques** [comment]
Assigned the label `common` to all imported issues so its easier for us to track what was imported from bigchaindb-common

**Comment by ttmc** [comment]
I don't think we need to bring the docs from the bigchaindb-common repo. AFAIK they were just auto-generated by cookiecutter. I did add a **← Back to All BigchainDB Docs** link, but I think that's the only change I made. You can see the rendered bigchaindb-common docs at:

https://bigchaindb-common.readthedocs.io/en/latest/

The [intro page](https://bigchaindb-common.readthedocs.io/en/latest/readme.html) (imported from the README) has a short list of features that Tim probably wrote but we don't need that either.

**Comment by sohkai** [comment]
@sbellem I believe this is finished now?

**Comment by sbellem** [comment]
@sohkai indeed

**Comment by sbellem** [comment]
Some notes on how this merge was done, especially regarding:

* merge the code inside a subfolder of bigchaindb `bigchaindb/common`
* merge the tests inside a subfolder of tests `tests/common`

We'll assume the following directory structure:

```bash
$ ls
bigchaindb           common-implementation     common-tests
```

Cloning the repos to yield the above:

```bash
$ git clone git@github.com:bigchaindb/bigchaindb
$ git clone git@github.com:bigchaindb/bigchaindb-common common-implementation
$ git clone git@github.com:bigchaindb/bigchaindb-common common-tests
```

Have three shells, one for each repo:

##### shell 1: `bigchaindb`
```bash
$ cd bigchaindb/
```

##### shell 2: `common-implementation (bigchaindb-common)`
```bash
$ cd common-implementation/
```

##### shell 3: `common-tests (bigchaindb-common)`
```bash
$ cd common-tests/
```

##### shell 2: `common-implementation (bigchaindb-common)`
```bash
$ git filter-branch -f --subdirectory-filter bigchaindb_common/ -- --all
$ ls
crypto.py  exceptions.py  __init__.py  transaction.py  util.py
$ mkdir -p bigchaindb/common
$ git mv *.py bigchaindb/common/
$ git commit -am 'Extract common lib implementation'
```

##### shell 1: `bigchaindb`
```bash
$ git remote add common-implementation ../common-implementation/
$ git fetch common-implementation 
remote: Counting objects: 6, done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 6 (delta 1), reused 1 (delta 1)
Unpacking objects: 100% (6/6), done.
From ../common-implementation
 * [new branch]      master     -> common-implementation/master
$ git checkout -b extract-common-implementation master
$ git pull common-implementation master
$ git rebase master
```

##### shell 3: `common-tests (bigchaindb-common)`
```bash
$ git filter-branch -f --subdirectory-filter tests -- --all
$ git filter-branch -f --index-filter 'git rm -f --cached --ignore-unmatch conftest.py bigchaindb/transaction.py __init__.py'
$ mkdir -p tests/common
$ git mv *.py tests/common/
$ git commit -am 'Extract common lib tests'
```

##### shell 1: `bigchaindb`
```bash
$ git remote add common-tests ../common-tests/
$ git fetch common-tests
$ git pull common-tests master
$ git rebase -i master
# fixup duplicate Planning release commit
```

**Comment by ttmc** [comment]
Wow, that was non-trivial. Kudos
