### ISSUE TITLE
Sanitize naming/positioning of fulfillments, conditions, inputs, outputs

### ISSUE THREAD

**Issue by r-marques** [bigchaindb/bigchaindb#709]
_From @TimDaub on October 17, 2016 14:41_

I just had a talk with @vrde and @rhsimplex about the complex naming regarding fulfillments, conditions, inputs and outputs. In the last couple of weeks I had quite a few people that were confused by this. Things that came up:
- How is a `fulfillment` in a `CREATE` transaction generated. Why is `input == None`?

> This is usually referred to as the `implicit condition`. A condition is generated, immediately a fulfillment is derived from it, signed and its URI is put as `fulfillments[x].fulfillment`.
- What's `input` (and `output`) in regard to `fulfillment` and `condition`?

> If you think of a door then `fulfillment` is the key to a lock (a `condition`). `input`s and `output`s define the relationship between doors (e.g. _can a certain key open a certain lock_).

A few thoughts from myself:
- Could `conditions` and `fulfillments` be renamed/simplified to `inputs` and `outputs` in the transaction model? Would that still be compliant with the Interledger spec?

_or_
- Could we remove all notion of `inputs` and `outputs` and comply to some other language that is used within Interledger?
- What is `fulfillment[x].fulfillment` and why is a transaction not signed?

> `fulfillment[x].fulfillment` is the signature of a transaction.

A few thoughts from myself:
- Ideally, a fulfillment (meaning the URI part) should be stored outside of the transaction's body (compare to the Block model) so that validation doesn't have to rearrange/delete/ certain keys.

@vrde @rhsimplex Please add more if you can.

The goal of this ticket is to have a discussion around simplifying the language (only fulfillments, conditions, inputs, outputs) in a transaction, to make it easier for newcomers to understand.
There are already threads for other concepts:
- [Rename 'owners_after' to 'fulfillers'](https://github.com/bigchaindb/bigchaindb/issues/626)

//cc @r-marques and @ttmc as it might be interesting for them as well

_Copied from original issue: bigchaindb/bigchaindb-common#57_

**Comment by r-marques** [comment]
_From @ttmc on October 17, 2016 16:13_

Fulfillments and conditions make sense in TRANSFER transactions, but it's easy to understand why fulfillments in a CREATE transaction might be confusing to a newcomer. Fulfilling what conditions? Are there implicit conditions? If so, what are they? The problem isn't so much a problem of language as a problem of documenting the implicit conditions.

I think that the words "fulfillments" and "conditions" are more precise than "inputs" and "outputs." They're also the words used within the Interldeger Protocol. Also, "[conditionals](https://en.wikipedia.org/wiki/Conditional_(computer_programming))" are a common concept in the computer science world, i.e. `if <condition> then <do something>`.

Fulfillments is an odd word. One normally hears it in reference to orders, e.g. [fulfilling an order](https://en.wikipedia.org/wiki/Order_fulfillment) for a basket of turnips by delivering it to Aunt Millie's doorstep.

I like the analogy with locks and keys. The conditions are like locks (e.g. hashlocks) and the fulfillments are like the keys that unlock those locks, enabling a transfer. It's interesting that the transfer doesn't happen automatically. One must use the fulfillments to build a transaction, and then one must submit the transaction to a BigchainDB node.

While locks and keys are a useful _analogy_, I'm not going to advocate switching to that terminology, because there are good reasons to stick with conditions and fulfillments (listed above).

**Comment by r-marques** [comment]
_From @ttmc on October 18, 2016 16:51_

Another thought: a fulfillment (JSON document or Python dict) contains a `fulfillment` (a crypto-conditions URI). Surely we can think of a different name for one of those things. Maybe the latter could be called a `uri`?

I generally prefer more descriptive names, but in this case `uri` isn't any worse than `fid`. Moreover, a condition already contains a `uri`.

**Comment by sohkai** [comment]
@libscott Some of these questions and concerns have been addressed lately (or will be later?). Is this still useful to keep open?

**Comment by libscott** [comment]
Fixed in #925
