### ISSUE TITLE
Metadata object should be created outside of the transaction

### ISSUE THREAD

**Issue by r-marques** [bigchaindb/bigchaindb#719]
_From @r-marques on October 5, 2016 14:26_

Looking at how the asset is implemented and to maintain consistency the metadata object should be created and then passed to `Transaction`, `Transaction.create`, `Transaction.transfer`

_Copied from original issue: bigchaindb/bigchaindb-common#36_

**Comment by sohkai** [comment]
Closing, as the `Metadata` class has been removed.
