### ISSUE TITLE
Review, and possibly implement class hierarchy for exceptions

### ISSUE THREAD

**Issue by r-marques** [bigchaindb/bigchaindb#721]
_From @sbellem on September 28, 2016 12:17_

The current exceptions all inherit from Python's `Exception` class. This ticket wishes to review the current design, and to consider having some "key" parent classes wherever it makes sense.

From https://github.com/bigchaindb/bigchaindb/pull/641#discussion_r80899205:

> ... if a certain group of exceptions share certain characteristics, and for this reason are often caught together (as above), then it may make sense to have a parent class from which these classes inherit. One advantage of doing so would be that in some cases the parent class can be caught if all children are involved.

``` python
try:
    something_may_go_wrong()
except (ValueError, OperationError, TransactionError):
    handle_what_went_wrong()
```

instead of 

``` python
try:
    something_may_go_wrong()
except (ValueError, OperationError, TransactionDoesNotExist, TransactionOwnerError,
        DoubleSpend, InvalidHash, InvalidSignature):
    handle_what_went_wrong()
```

The simpler version would require something like:

``` python
class TransactionError(Exception):
    """Base class for all transaction related exceptions.""""

class TransactionDoesNotExist(TransactionError):
    """Raised if the transaction is not in the database"""

class TransactionOwnerError(TransactionError):
    """Raised if a user tries to transfer a transaction they don't own"""

class DoubleSpend(TransactionError):
    """Raised if a double spend is found"""

class InvalidHash(TransactionError):
    """Raised if there was an error checking the hash for a particular operation"""
```

**Please note that is is just the idea, and the grouping may be done differently.**

_Copied from original issue: bigchaindb/bigchaindb-common#30_

**Comment by r-marques** [comment]
_From @sohkai on September 30, 2016 12:55_

An option we could take is have `bigchaindb-common` expose a base `BigchaindbError` exception that all python BigchainDB projects (i.e. server, driver, as well as this project itself) could use. However, this is somewhat messy in it coupling the exceptions across different packages and may make it harder in the future to create new drivers.

@sbellem and I had a short conversation about this, and I'm at least convinced the server should be using the same base exception as `bigchaindb-common`, but ¯\_(ツ)_/¯.

We should discuss @sbellem @diminator @r-marques @TimDaub (and anyone else interested).

**Comment by sbellem** [comment]
# Proposal for BigchainDB Exception Hierarchy

```bash
Exception
 +-- BigchainDBError
      +-- ConfigurationError
      +-- DatabaseError
           +-- DatabaseAlreadyExists
           +-- DatabaseDoesNotExist
      +-- OperationError
      +-- StartupError
      +-- TransactionError
           +-- DoubleSpend
           +-- KeypairMismatchException
           +-- KeypairNotFoundException
           +-- TransactionDoesNotExist
           +-- TransactionNotInValidBlock
           +-- TransactionOwnerError
           +-- ValidationError
                +-- InvalidHash
                +-- SchemaValidationError
                +-- InvalidSignature
                +-- AssetIdMismatch
                +-- AmountError
      +-- VoteError
           +-- ImproperVoteError
           +-- MultipleVotesError
      +-- BlockError
           +-- CyclicBlockchainError
           +-- GenesisBlockAlreadyExistsError
```
