### ISSUE TITLE
`owners_before` and `owners_after` should be derived from Cryptoconditions

### ISSUE THREAD

**Issue by r-marques** [bigchaindb/bigchaindb#728]
_From @TimDaub on September 21, 2016 9:19_

@diminator gave a hint here: https://github.com/bigchaindb/bigchaindb-common/pull/4#r76391859

_Copied from original issue: bigchaindb/bigchaindb-common#15_

**Comment by r-marques** [comment]
_From @diminator on September 29, 2016 15:40_

this will be troublesome/impossible for `Thresholdconditions` as the internals are masked, can only be done for `Fulfillments`

note that `owners_before` and `owners_after` are required mainly for:
- indexing
- `get_owned_ids`

**Comment by libscott** [comment]
This SHOULD be part of 1.0 guarantees IMO.
