### ISSUE TITLE
Signing of transaction should be possible with partial set of keys

### ISSUE THREAD

**Issue by r-marques** [bigchaindb/bigchaindb#729]
_From @TimDaub on September 21, 2016 9:15_

This method: https://github.com/bigchaindb/bigchaindb-common/blob/master/bigchaindb_common/transaction.py#L435

Currently, a transaction can just be signed using all the corresponding private keys.
In a real-life scenario this is often unpractical. Hence, `Transaction.sign` should accept a partial set of keys to sign a transaction (while still be (de)serializable `to_dict`, `from_dict`).

_Copied from original issue: bigchaindb/bigchaindb-common#13_

**Comment by r-marques** [comment]
_From @TimDaub on September 23, 2016 9:17_

We'll also have to make adjustments to cryptoconditions: https://github.com/bigchaindb/cryptoconditions/pull/25

**Comment by r-marques** [comment]
@TimDaub This is also related to the driver. Core does not need to sign transactions.

**Comment by Chuseuiti** [comment]
I didnt see this feature in the documentation https://docs.bigchaindb.com/projects/py-driver/en/latest/advanced-usage.html.  I wonder if it has already been developed and if there is a example?
