### ISSUE TITLE
Please document that libffi-dev is a recommended package

### ISSUE THREAD

**Issue by ticosax** [bigchaindb/bigchaindb#73]
## Debian, Ubuntu
```
apt-get install libffi-dev
```

**Comment by ttmc** [comment]
`libffi-dev` is one of the packages installed by the line
```text
$ sudo apt-get install libffi-dev g++ libssl-dev python3-dev
```
in [Section 2.3](http://bigchaindb.readthedocs.org/en/develop/installing.html#install-bigchaindb) of the documentation. Should it be somewhere else as well?

**Comment by ticosax** [comment]
oops :smile: 

I was just following the instructions on README.md.

**Comment by ttmc** [comment]
Ah, okay. I plan to change the README.md into more of an overview + Table of Contents in the coming days, so it will just point to the documentation, the whitepaper, the website, etc.

**Comment by ticosax** [comment]
:+1: thanks
