### ISSUE TITLE
Why the default branch is called `develop` and not `master` ?

### ISSUE THREAD

**Issue by ticosax** [bigchaindb/bigchaindb#74]
Knowing that `master` doesn't exists, and you claim following [github flow](https://guides.github.com/introduction/flow/), which assumes the default branch to be named `master`.

**Comment by ttmc** [comment]
Heh, good question @ticosax ! We were originally thinking of using Gitflow (not the same as the GitHub flow), and it uses `develop` as the default branch. Then we decided Gitflow is too heavy for our purposes right now, so we switched to the GitHub flow... except we still call the working branch `develop`.

**Comment by ttmc** [comment]
@ticosax We decided to switch to using `master` as the default branch. See PR #170
