### ISSUE TITLE
Revisit separation of pipeline nodes for performance

### ISSUE THREAD

**Issue by sohkai** [bigchaindb/bigchaindb#744]
Some nodes to consider merging with other nodes:
- [ ] `pipelines.block.delete_tx`

And maybe more?

**Note**: Some nodes may be separated because they contain blocking calls, rather than waiting for a certain event (e.g. block creation waits for 1000 tx or timeout). The implications of this are important to realize when investigating.

**Comment by ttmc** [comment]
Pipelines are no longer being used in BigchainDB 2.0, which is coming out very soon, so I'm closing this issue.
