### ISSUE TITLE
Naming convention: public/private keys versus verifying/signing keys?

### ISSUE THREAD

**Issue by ttmc** [bigchaindb/bigchaindb#746]
In issue #603, @sbellem [wrote](https://github.com/bigchaindb/bigchaindb/issues/603#issuecomment-256032321):

> ### Naming convention: public/private keys versus verifying/signing keys
> 
> This question could perhaps have its own issue, but I'll ask here, and we can create an issue if needed.
> 
> I simply wonder whether we should stick to one rather than using both interchangeably. It may help make the code simpler, especially for new comers.

@r-marques [responded](https://github.com/bigchaindb/bigchaindb/issues/603#issuecomment-256038312):

> Looking at the literature they seem to be used interchangeably.
> 
> In asymmetric cryptography algorithms that provide both signing and encryption they use the terms public/private key.
> For asymmetric cryptography algorithms that only provide signing like ed25519 they sometimes refer to the keys as signing/verifying key.
> 
> It seems that public/private keys is a more universal term. But at the same time is always advisable to use different keys for signing and encryption and in that case a distinction between public/private and signing/verifying would be desirable.
> 
> At this point we only use the keys for signing and verifying maybe we could switch to using public/private everywhere since its the most used term

**Comment by r-marques** [comment]
##### Proposal

The above being said I propose to just simplify and go with what everyone is familiar with:
- [ ] Replace all occurrences of signing/verifying with private/public in the code
- [ ] Replace all occurrences of signing/verifying with private/public in the documentation
- [ ] Open an issue on cryptoconditions to check the naming conventions (it should follow the naming conventions of the spec)

**Comment by ttmc** [comment]
Yes, and don't just grep for "signing" and "verifying". Look also for shorthand such as "vk" and "sk" (for verifying key and signing key). "pubkey" and "privkey" are already used in some places.

:+1:

**Comment by r-marques** [comment]
Since @sbellem, @ttmc, @sohkai agreed this proposal is frozen from this point on and ready for implementation
