### ISSUE TITLE
Redo? Move "version" inside transaction body and include it in what gets hashed

### ISSUE THREAD

**Issue by ttmc** [bigchaindb/bigchaindb#755]
Issue #341 was to **Move "version" inside transaction body and include it in what gets hashed**

Pull request #518 did just that, and it was merged on August 5.

Today, October 27, the "version" somehow snuck outside the transaction body again, so it's at the same level in the hierarchy as `transaction` and `id`.

Was there a reason for this? I may have missed it. Some relevant code is the `to_dict()` method of the `Transaction` class in https://github.com/bigchaindb/bigchaindb/blob/master/bigchaindb/common/transaction.py

``` python
        tx_body = {
            'fulfillments': [fulfillment.to_dict(fid) for fid, fulfillment
                             in enumerate(self.fulfillments)],
            'conditions': [condition.to_dict(cid) for cid, condition
                           in enumerate(self.conditions)],
            'operation': str(self.operation),
            'timestamp': self.timestamp,
            'metadata': metadata,
            'asset': asset,
        }
        tx = {
            'version': self.version,
            'transaction': tx_body,
        }
```

**Comment by sohkai** [comment]
I imagine it was probably because that got merged after @TimDaub started working off the fork for bdb-common. Surprised no tests were failing because of it, honestly...

**Comment by r-marques** [comment]
As long as transactions get hashed the same way throughout the code don't see why the tests should have failed

**Comment by ttmc** [comment]
I assigned this to @TimDaub because he probably knows why this change was made.

**Comment by sohkai** [comment]
@r-marques If this was unintended, I think our tests should have caught something like this; these sorts of things shouldn't be falling through the cracks until someone manually discovers them.

**Comment by TimDaub** [comment]
I think this was a mistake of mine, but in essence I agree with this statement:

> As long as transactions get hashed the same way throughout the code don't see why the tests should have failed

**Comment by ttmc** [comment]
@TimDaub Is the "version" still included in the message gets hashed and signed? If so, then it's probably okay to keep it outside the inner "transaction" field, and you may close this issue.

**Comment by TimDaub** [comment]
Everything is being hashed except for the fulfillment to be created itself.

**Comment by ttmc** [comment]
Yep. I did a quick look at the code to be sure. The Transaction `sign()` method definitely includes the version in the message used to calculate the signature. I will close this issue.
