### ISSUE TITLE
Secure node-to-node communications

### ISSUE THREAD

**Issue by ttmc** [bigchaindb/bigchaindb#77]
Some BigchainDB federations will want secure node-to-node communications, e.g. with encryption or two-way authentication or both.

Right now, the nodes only communicate with each other via RethinkDB, using a RethinkDB wire protocol (quite powerful: it can do all sorts of database operations). Can those communications be secured? See "Using SSH tunneling" on this page:

https://www.rethinkdb.com/docs/security/

**Comment by r-marques** [comment]
RethinkDB will support intra-cluster communication in the upcoming 2.3.0 release.
- Issue is here https://github.com/rethinkdb/rethinkdb/issues/4953
- Setup guide here https://gist.github.com/jlhawn/43f84f86579012470dc9

**Comment by ttmc** [comment]
In BigchainDB 2.0, all node-to-node communications are secure. There is no more using MongoDB or RethinkDB wire protocols. Read what is used instead:  https://tendermint.readthedocs.io/en/master/specification/secure-p2p.html
