### ISSUE TITLE
Rename benchmarking-tests/benchmark_utils.py to benchmarking-tests/utils.py

### ISSUE THREAD

**Issue by sbellem** [bigchaindb/bigchaindb#772]
Simply to remove the redundancy.

**Comment by r-marques** [comment]
This code hasn't been changed in a couple of months. Not sure how much of it still makes sense to keep around

**Comment by sbellem** [comment]
Oh really. Ok. I created this issue simply because I was reviewing #762 and notice the possibility to simply the module name.

**Comment by sbellem** [comment]
Well, kinda funny timing, since @ttmc and myself were discussing benchmarking today.

**Comment by r-marques** [comment]
done in #1359
