### ISSUE TITLE
Remove pytz

### ISSUE THREAD

**Issue by sbellem** [bigchaindb/bigchaindb#775]
```bash
$ grep -rn pytz *
setup.py:62:    'pytz>=2015.7',
setup.py:113:        'pytz==2015.7',
```

**Comment by ttmc** [comment]
I will do this once #695 (created by @MinchinWeb) is resolved and merged.

The reason is that we're not using `pytz` any more, as shown by the grep output.

**Comment by ttmc** [comment]
For the record, pull request #695 removed `pytz` (and did many other things too).
