### ISSUE TITLE
Cleanup of old "consensus" stuff

### ISSUE THREAD

**Issue by ttmc** [bigchaindb/bigchaindb#778]
This is a low-priority cleanup chore. Just search this repo for `consensus` (case-insensitive) and use the results to help you remove the vestigial remains of the old consensus plugin stuff, including the un-needed:

* `BaseConsensusRules` class and `bigchaindb/consensus.py`. You'll have to change all the calls to the three methods defined in that class.
* **Consensus** page in the docs (Appendices) derived from that class. Don't forget to remove it from the index as well (in `docs/server/source/appendices/index.rst`)

**Comment by TimDaub** [comment]
@ttmc I believe we've completed this ticket in various pull-requests in the past.
If that's correct, can you please close this ticket?

**Comment by ttmc** [comment]
@TimDaub The "pluggable consensus" stuff was brought back (by an external PR, which we merged), so I guess it's still with us. Anyway, it _does_ make this issue moot, so I will close it.

**Comment by TimDaub** [comment]
> The "pluggable consensus" stuff was brought back (by an external PR, which we merged)

Pst, let's keep it our secret :D

(Stranger from the interwebz: There is nothing to see here, move on)
