### ISSUE TITLE
IPDB User Authorization, Monitoring and User Dashboard

### ISSUE THREAD

**Issue by ttmc** [bigchaindb/bigchaindb#779]
IPDB wants to be able to:

* ignore HTTP requests from unknown users
* revoke HTTP API access by known users (e.g. if they behave badly, or they reach their quota)
* measure who is making the HTTP requests (e.g. for monitoring and billing)

Moreover, IPDB users need a way to:

* get or set authorization credentials/tokens
* see how they are doing, e.g. how many HTTP API requests they've made in the past day, week, month, etc.
* do more in the future

Some kind of IPDB User Dashboard would be nice.

### Notes

* this is independent of BigchainDB Server. We shouldn't be modifying BigchainDB Server to accomplish any of the above.
* BigchainDB drivers may require some new extra methods or plugins to make it easier to work with IPDB.

**Comment by TimDaub** [comment]
> Modify the BigchainDB Server HTTP API to only act on requests containing a valid OAuth token.

> Modify the BigchainDB Python Driver to send requests with the OAuth token in all HTTP request headers.

I guess this will be part of that meeting we'll soon have, but in my opinon we shouldn't be building any Authentication into bigchaindb/bigchaindb, but rather in a proxy on top.

**Comment by ttmc** [comment]
@TimDaub Yes, I agree. My initial comments on this issue were assuming that we'd be modifying BigchainDB Server, but based on the discussion in the planning meeting on Monday, it seems clear that all of this should be separate from BigchainDB Server. I changed this issue's opening comments and title to reflect my improved understanding of the issue.

**Comment by ttmc** [comment]
Because this issue isn't really about BigchainDB Server at all, I moved it over to the bigchaindb/org repo and closed it here. Go to:

https://github.com/bigchaindb/org/issues/26
