### ISSUE TITLE
How can we release the higher memory bigchaindb used or leak?

### ISSUE THREAD

**Issue by wxcsdb88** [bigchaindb/bigchaindb#781]
With the bigchaindb older **0.6.0**, run  `bigchiandb load -m 10` may produce the timeout exception.
Now, the **0.8.0.dev** solves it. But we find the memory is run higher when run `bigchaindb load -m 50` .
When stop the load,it will go higher before the backlog is empty or the memory is running out.And it will keep that until kill the bigchaindb processes.

**MayBe it`s trouble by memory leak or else ?**

Now we can release it by stop the bigchaindb. How can we solve that ？

**Thks for replying.**
The partial `top` results as follow:

[bigchaindb 0.8.0.dev]
![screenshot from 2016-11-01 20 23 57](https://cloud.githubusercontent.com/assets/8437861/19913602/2083f0a8-a0df-11e6-8d1f-e445e1a97ad9.png)

**Comment by r-marques** [comment]
This seams related to #124

**Comment by wxcsdb88** [comment]
Maybe the RethinkDB`s changefeed can`t deal the mass change feedback for backlog and the total txs in backlog will become more.
If the changes for backlog can`t deal in time, it will increase the memory.
The query ReQL for the backlog will use more time and memory. Repeat that(continuously write the backlog and query the backlog ), the memory will be run out .
In my opinion, limit the amount of backlog and improve the capacity of the changefeed maybe better for that.

**Comment by vrde** [comment]
> This seems related to #124
> @vrde do you have any thoughts on this?

yes IMO it's related, I can push a quick fix in a branch in a couple of days and test it. Will keep this issue updated.

**Comment by krish7919** [comment]
@wxcsdb88 : This should be fixed now. Can you please give it a spin and update us? :)

**Comment by wxcsdb88** [comment]
@krish7919 
Now, with the limit, the Mem increase slowly and can decrease without continuous txs write(changefeed).
But the limit can\`t limit the backlog changfeed size, with the quick and mass txs insert, it may be increase quickly. 
Three base pipelines for `bigchain`, `votes`, `backlog`, the `backlog` `s change so frequently.  
With the limit, if the changes count is greater than the maxsize, the pipe queue may be full all time, and the changes from rethinkdb may be lose ? Thus,  we can replace the method to get the backlog data, use filter with timestamp order, and add the limit [dynamic-low-val,1000 or more], this also can reduce the press. The interval [open,open] may avoid the lose data in the same timestamp, but need special deal.
Above is my idea about the issue.
Thanks a lot.

**Comment by ttmc** [comment]
@wxcsdb88 If a transaction waits in the backlog table too long, it gets reassigned to a different node for consideration (and this change to the transaction shows up in the backlog table's changefeed, so all nodes are notified).

In case you're curious, the amount of time before a transaction gets "stale" is now configurable, using the BigchainDB configuration setting `backlog_reassign_delay`. The default is 120 seconds (2 minutes).

https://docs.bigchaindb.com/projects/server/en/latest/server-reference/configuration.html#backlog-reassign-delay
