### ISSUE TITLE
get_all_assets_in(address)

### ISSUE THREAD

**Issue by ttmc** [bigchaindb/bigchaindb#790]
@roderik [wrote on Gitter](https://gitter.im/bigchaindb/bigchaindb?at=581cd085e097df75756ee5e1):

> I would love some simple and fast asset/wallet methods. GetAllAssetsIn(address) which return the metadata and ownedids content

> Getownedids does 3 things at the moment (and is painfully slow), and then you need to take the txid and walk through all transactions related to the asset to compile the payload aka, the actual information you want to store. (Or you send the latest payload with every transfer so you have it handy)

> To make something useful and fast, you very often need to use rethink directly, which will be a pain when mongo is in the mix

Note: The slowness of get_owned_ids is another issue: #787

**Comment by TimDaub** [comment]
I just had a chat with @gkapkowski. They'd also like to have an endpoint with the return for.
I saw this coming up on gitter multiple times as well.

If we can design an endpoint that doesn't break the HTTP API or any common methods, we could theoretically ship this with a patch release of 0.10.

```
GET XXXXXX?public_key=ABC

Returns:

{
  'asset_id_0': 123,
  'asset_id_0': 234,
  ...
}

```

**Comment by r-marques** [comment]
So you want an endpoint that returns all the assets (and only the assets) somewhat related to a public key.

And this somewhat should be all assets created by this public key or all assets currently owned by this public key?
