### ISSUE TITLE
[common] support tuples as well as lists in function/method arguments

### ISSUE THREAD

**Issue by sbellem** [bigchaindb/bigchaindb#797]
In multiple places under `common/transaction.py` arguments are required to be `list` instances. Why so? Why not allow for `tuple` instances as well.

It seems to be overly restrictive, especially considering that optional positional arguments are packed into a `tuple`, and that lists are less memory efficient than tuples.

To give a concrete example:

```python
In [47]: def foo(owners_before, *owners_after):
    ...:     print('owners_after is a {}'.format(type(owners_after)))
    ...:     Transaction.create(owners_before, owners_after)
    ...:     

In [48]: foo(['5WqCkKx9Fem9pEpoFi18QC3JPGYjWt4ZAF44gVC6RUnF'], 'A1BiHksR1WadS82hD8y521KDvfBg382XKTPQNTmjDhyw')
owners_after is a <class 'tuple'>
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-48-5ef957648d53> in <module>()
----> 1 foo(['5WqCkKx9Fem9pEpoFi18QC3JPGYjWt4ZAF44gVC6RUnF'], 'A1BiHksR1WadS82hD8y521KDvfBg382XKTPQNTmjDhyw')

<ipython-input-47-44a529ca3f9c> in foo(owners_before, *owners_after)
      1 def foo(owners_before, *owners_after):
      2     print('owners_after is a {}'.format(type(owners_after)))
----> 3     Transaction.create(owners_before, owners_after)
      4 

/usr/local/lib/python3.5/site-packages/bigchaindb/common/transaction.py in create(cls, owners_before, owners_after, metadata, asset, secret, time_expire)
    675             raise TypeError('`owners_before` must be a list instance')
    676         if not isinstance(owners_after, list):
--> 677             raise TypeError('`owners_after` must be a list instance')
    678 
    679         metadata = Metadata(metadata)

TypeError: `owners_after` must be a list instance
```

Another limitation of the restriction to use lists, is that one cannot pass tuples as in:

```python
In [51]: foo(('5WqCkKx9Fem9pEpoFi18QC3JPGYjWt4ZAF44gVC6RUnF',), ['A1BiHksR1WadS82hD8y521KDvfBg382XKTPQNTmjDhyw'])
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-51-68d270e11318> in <module>()
----> 1 foo(('5WqCkKx9Fem9pEpoFi18QC3JPGYjWt4ZAF44gVC6RUnF',), ['A1BiHksR1WadS82hD8y521KDvfBg382XKTPQNTmjDhyw'])

<ipython-input-50-98ca2570c2ca> in foo(owners_before, *owners_after)
      1 def foo(owners_before, *owners_after):
----> 2     Transaction.create(owners_before, owners_after)
      3 

/usr/local/lib/python3.5/site-packages/bigchaindb/common/transaction.py in create(cls, owners_before, owners_after, metadata, asset, secret, time_expire)
    673         """
    674         if not isinstance(owners_before, list):
--> 675             raise TypeError('`owners_before` must be a list instance')
    676         if not isinstance(owners_after, list):
    677             raise TypeError('`owners_after` must be a list instance')

TypeError: `owners_before` must be a list instance
```

### A case for the paranoids
Moreover, especially in the case of cryptographic keys, a user of an API passing a list of keys does not expect the API to append to that list or remove from it. In this case, using an immutable sequence, although obviously not an absolute protection, is most certainly a better starting point than using a mutable data structure, which allows deletions and appends.

### A case for using the appropriate data structure
And in any case, if the interface is not going to need to "delete from", or "append to", the sequence why use a mutable sequence at all? So, if we were to be so strict on the type, a tuple would perhaps be more appropriate on some cases at least. But at the very least we should allow for both lists and tuples.

The changes are trivial:

```python
   if not isinstance(owners_before, (tuple, list)):
     raise TypeError('`owners_before` must be a tuple or list instance')
```

**Comment by vrde** [comment]
My personal preference is to use duck typing, so try to iterate and fail if I cannot. In this case I might use also the [`collections.abc.Iterable`](https://docs.python.org/3.5/library/collections.abc.html#collections.abc.Iterable) interface like:

```python
if isinstance(owners_before, collections.abc.Iterable):
    # iterable
else:
    # not iterable
```

This would actually be really really nice so we can make full usage of the Python3 lazy evaluation for `map`, `filter`, and more.

The only problem I see here is if the argument passed is a `str` that is an iterable as well (this might happen because keys are strings, and a developer might forget to put it inside a list).
```python
>>> isinstance('troll', collections.abc.Iterable)
True
```

But we can mitigate the problem doing this **before** checking if `owners_before` is iterable:
```python
if isinstance(owners_before, str):
    owners_before = [owners_before]
```

(Don't want to reopen closed discussions, but I really don't remember why we avoid that).

Anyway, I'm happy with the **trivial change** asked by @sbellem.

**Comment by sbellem** [comment]
> My personal preference is to use duck typing

:+1: :+1:

**Comment by sbellem** [comment]
> But we can mitigate the problem doing this before checking if owners_before is iterable:
> 
> ```python
> if isinstance(owners_before, str):
>     owners_before = [owners_before]
> ```

:+1:
