### ISSUE TITLE
Impose a maximum transaction size limit?

### ISSUE THREAD

**Issue by ttmc** [bigchaindb/bigchaindb#805]
Should we impose a limit on the overall size of a transaction, i.e. as part of transaction validation?

There are soft limits imposed by the backend database. For example, [in RethinkDB](https://rethinkdb.com/limitations/):

> While there is no hard limit on the size of a single document, there is a recommended limit of 16MB for memory performance reasons.

Since blocks are documents and a block can contain up to 1000 transactions, that means that the soft limit on a transaction size would be about 16MB / 1000 or about 16kB.

**Comment by TimDaub** [comment]
I don't see a reason to build this in now or any time soon.
I think we should be integrating this retroactively (if a customer demands it).

**Comment by ttmc** [comment]
Note: In MongoDB, there's a similar [limit](https://docs.mongodb.com/manual/reference/limits/):

> The maximum BSON document size is 16 megabytes.

> The maximum document size helps ensure that a single document cannot use excessive amount of RAM or, during transmission, excessive amount of bandwidth. To store documents larger than the maximum size, MongoDB provides the GridFS API. See mongofiles and the documentation for your driver for more information about GridFS.

Note that it's a limit on the BSON document size, so not the same thing as with RethinkDB.
