### ISSUE TITLE
Race condition in test_full_pipeline

### ISSUE THREAD

**Issue by libscott** [bigchaindb/bigchaindb#831]
While running the tests, I get an error sometimes that isn't always reproducible. It happened on my branch `schema-validation`, then as part of my testing also on `master`.

The assertion error is `assert 'aaa' != 'aaa'`, but can also be `assert 'bbb' != 'bbb'`.

    monkeypatch = <_pytest.monkeypatch.MonkeyPatch object at 0x7f18cc10a208>
    user_vk = 'JEAkEJqLbbgDRAtMm8YAjGp759Aq2qTn9eaEHUj2XePE'

    def test_full_pipeline(monkeypatch, user_vk):
        from bigchaindb.models import Transaction
        CONFIG = {
            'database': {
                'name': 'bigchain_test_{}'.format(os.getpid())
            },
            'keypair': {
                'private': '31Lb1ZGKTyHnmVK3LUMrAUrPNfd4sE2YyBt3UA4A25aA',
                'public': '4XYfCbabAWVUCbjTmRTFEu2sc3dFEdkse4r6X498B1s8'
            },
            'keyring': ['aaa', 'bbb'],
            'backlog_reassign_delay': 0.01
        }
        config_utils.set_config(CONFIG)
        b = Bigchain()
        outpipe = Pipe()

        original_txs = {}
        original_txc = []

        monkeypatch.setattr('time.time', lambda: 1)

        for i in range(100):
            tx = Transaction.create([b.me], [([user_vk], 1)])
            tx = tx.sign([b.me_private])
            original_txc.append(tx.to_dict())

            b.write_transaction(tx)
            original_txs[tx.id] = b.connection.run(r.table('backlog').get(tx.id))

        assert b.connection.run(r.table('backlog').count()) == 100

        monkeypatch.undo()

        pipeline = stale.create_pipeline(backlog_reassign_delay=1,
                                         timeout=1)
        pipeline.setup(outdata=outpipe)
        pipeline.start()

        # to terminate
        for _ in range(100):
            outpipe.get()

        pipeline.terminate()

        assert b.connection.run(r.table('backlog').count()) == 100
        reassigned_txs = list(b.connection.run(r.table('backlog')))

        # check that every assignment timestamp has increased, and every tx has a new assignee
        for reassigned_tx in reassigned_txs:
            assert reassigned_tx['assignment_timestamp'] > original_txs[reassigned_tx['id'] ]['assignment_timestamp']
    >       assert reassigned_tx['assignee'] != original_txs[reassigned_tx['id']]['assignee']
    E       assert 'aaa' != 'aaa'

    tests/pipelines/test_stale_monitor.py:116: AssertionError

**Comment by libscott** [comment]
Going to leave it running tests overnight to see if I can determine if it happens on master or only my branch.

**Comment by libscott** [comment]
It does happen on `master` too, only it's the other way around:

    assert 'bbb' != 'bbb'

**Comment by libscott** [comment]
Update: talked with @vrde and we tracked it down to a race condition in the test itself. Fix to follow.

**Comment by rhsimplex** [comment]
This is probably my fault :sweat: so let me know if I can help
