### ISSUE TITLE
Add fast double transfer test to integration tests

### ISSUE THREAD

**Issue by sohkai** [bigchaindb/bigchaindb#832]
From https://github.com/bigchaindb/bigchaindb/pull/614#discussion_r85339190:

Add a test to make sure fast double transfers are handled; something along the lines of:

```
b.write_transaction(create_tx)

time.sleep(2)
b.write_transaction(transfer_tx_1)
b.write_transaction(transfer_tx_2)
```

where `transfer_tx_1` and `transfer_tx_2` may not be the same but need to be spending the `create_tx`. Not sure what would happen here (on a single node, would they just keep getting re-added to the same block and fail?)...

**Comment by TimDaub** [comment]
This might be related to #592.

**Comment by ttmc** [comment]
When a node checks a transaction to check if it's a double-spend transaction, it looks for any other transaction that tries to fulfill the same condition(s). It looks in all undecided blocks, valid blocks, and the backlog. If it finds one, then it considers the transaction invalid.

If the node is checking a transaction in the backlog, it deletes it from the backlog and doesn't put it into a block.

If the node is checking a transaction in a block, it votes that the block is invalid. If a majority of the other nodes also vote the block is invalid, then all its transactions get copied back to the backlog for reconsideration.

If two transfer transactions come in at roughly the same time and they're both trying to fulfill the same condition(s), then I'd expect both to get deleted and never put into blocks. If they're spaced out a bit more, then the first one should end up in a valid block and the second one should get deleted.

But yes, it would be good to have a test for this.
