### ISSUE TITLE
[Discussion] Solutions for trustless asset exchange

### ISSUE THREAD

**Issue by libscott** [bigchaindb/bigchaindb#833]
Let's say Alice paints a painting and wants to sell it to Bob, for some kind of coin. BigchainDB (BDB) has support for divisible and non divisible assets so it should, I suggest, lend itself naturally to this use case.

Providing this mechanism will allow for a BDB ledger to be used as a first class trustless exchange, potentially of great value to customers operating in a federation. Not providing it will necessitate trusted exchanges to operate on top of BDB, to provide transaction atomicity, but as soon as that happens the ownership of assets is abstracted away from the BDB ledger, and the door is wide open for centralization of exchange activity to a trusted third party. Given the "Bigdata" angle of BDB, I'd suggest that we want to support exchange, so that we can provide more functionality "out of the box". An exchange house is a heavyweight application, and avoiding a trusted actor solves a problem for federated nodes.

So how do you allow users to exchange assets without an intermediary?

## Interledger - won't work

There are two separate assets here with no interdependency, we could consider them separate ledgers and try to invoke the Interledger Protocol (ILP), but ILP depends on liquidity of the Connector of all assets being exchanged (impossible with a unique asset like a painting), and furthermore, it is a payment protocol and not an exchange protocol. TODO: verify assumptions?

## Interdependent transactions - could work

Alice can create a transaction to send her painting to Bob, and Bob can create a transaction to send some coins to Alice. These are two independent transactions, but if Alice and Bob don't trust each other the lack of atomicity in the exchange is a problem. So how do you create an interdependency between two transactions? The transaction ID depends on it's contents so you can't make two transactions that depend on each other. What you could do is make a transaction that exists purely for the purpose of sealing the exchange, that is:

1. Either party issues a CREATE tx (TX1), with a fulfillment condition that **both parties must sign** in order to transfer. The asset is a dummy asset, the transaction exists only to provide atomicity in the transfer. The transaction is submitted to BDB.
2. An unsigned TRANSFER transaction (TX2) is created and shared between Alice and Bob.
3. Alice creates and signs a transaction to TRANSFER (TX3) the painting to Bob, with the condition that TX2 must be signed.
4. Bob creates and signs a transaction to TRANSFER (TX4) the coins to Alice, with the condition that TX2 must be signed.
5. Alice and Bob exchange the IDs of TX3 and TX4 so that they can verify the deal.
6. Once both parties are satisfied, they sign and submit TX2, to enable TX3 and TX4 to be spent by the other party.

Currently, our conditions do not support depending on other unrelated transactions. TODO: Can this be done?

## Multi asset transactions - could work

Given multi asset transactions, the entire exchange is done in one transaction, with no need for a dummy-asset. Alice and Bob agree on a transaction that represents their interests, and the fulfullment conditions depend on signatures from both parties. Both parties sign, and all the assets are transferred in one go.

Currently, we have no support for multiple asset transactions. This would entail moving the asset ID into the condition.

## Questions

* Do we agree that an exchange protocol is a Good Thing for BDB?
* What are the implementation costs of multi-asset transactions?
* What are the implementation costs of arbitrary transaction dependency?
* Which is easier?

Open for discussion.

**Comment by diminator** [comment]
## Escrow or hold accounts
This is a typical case of **escrow/hold** accounts: the currency and non-fungible asset(s) are transferred from their respective owner to either:
- a third party account
- a ledger provided hold account

Once that all assets are received by the hold account, ownership exchange transactions are unlocked or triggered. This is called an `execution_condition`. If an expiry time or some other abort scenario occurs before all parties committed, then the currency or non-fungible assets are returned to their respective owner this is called an `abort_condition`. Atomicity is provided in both scenarios.

## ILP protocol

The ILP protocol - when applied to fungible assets - makes extensive use of hold accounts. There are some differences though:
- Each ledger contains a single asset that is fungible
- Each hold account only contains a native fungible asset
- `execute_condition`: A receipt is propagated between ledgers to release the assets

In the case of a multi-asset ledger with possibly non-fungible assets, the following changes need to be introduced:
- multiple parties need to be able to send assets to the hold account
- `execute_condition`: all assets have arrived at the hold account

Some things remain the same:
- The ledger provides the hold account
- `abort_condition`: an expiry time or another checklist of conditional statements

## Interdependent transactions

I would really try to avoid having a bitcoin-like setup for escrow accounts as you suggest by the interdependent transactions [ref1](http://bitcoin.stackexchange.com/questions/13841/how-do-i-use-multisig-transactions-to-handle-escrow-needs) [ref2](https://github.com/starius/bitcoin-escrow-article/blob/master/article_en.md). Typically - in these setups - there is an off-chain exchange of the contracts/transactions and it's unclear how to rollback and provide enough guarantees.

You could try to draft a setting where you have 2 transactions - each transaction containing an `execution_condition` and `abort_condition` that point to the `receiver` and `sender` respectively. Setting up those conditions is a bit involved:
- `execution_conditions` that check whether the other transaction(s) have appeared. Hence the condition needs to be able to query the existence of a transaction in BDB. It's not easy to setup such a query and format is as a condition
- `abort_conditions` need to be in-sync: eg. timeouts need to be the same and validated by the same time-servers on the nodes and so on.
 
## Simple contracts
Ideally you would be able to create a single (simple) contract that:
- has an address space in BDB
- the actors can send their asset to (fungible or non-fungible)
- supports `execution_conditions` and `abort_conditions` which can contain conditional statements

**Comment by ttmc** [comment]
> * Do we agree that an exchange protocol is a Good Thing for BDB?

I agree that it's worth having. We've gotten questions about that. @vrde is collecting user needs and can probably say more.

It's up to the product owner / business people / "customer" (in XP terms) to prioritize what gets added next.

**Comment by libscott** [comment]
Talking with @diminator we came up with a possible way to model escrow using only a transaction. It does require some changes, namely a "query condition" in cryptoconditions and the presence of what I will name a "fulfillment vector", ie, an indication of which branch of a condition was used to generate a fulfillment, so that a transaction can check how another transaction was fulfilled.

TODO: Nice diagrams.

**Comment by yogigolle** [comment]
@libscott, thanks for opening this issue / feature request. I actually posee this question on gitter, and @diminator responded that an issue had not been opened yet, so this is good. My orginal question was 
"What would an asset transfer that requires a corresponding settlement transaction (i.e. payment) look like, such that the asset transfer from owner A to owner B is dependent (i.e. held in escrow) until the settlement transaction is complete (i.e. an asset transfer from owner B to owner A in the form of a value token/currency)"

I like the multi-asset transaction approach with associated execution-condition and abort-condition. 

How would an asset record be identied as belong to a multi-asset group? or is the multi-asset flag be hosted in the transaction record, which then identifies the assets that belong to the asset group?
What about multi-sig transations? Would be possible to work witb multi-asset transactions?

**Comment by libscott** [comment]
Hi @yogigolle,

In your example, would the settlement transaction be done on the same chain as the asset transfer?

In this case, there would be two assets separate assets, there isn't an "asset group" as such. It involves both parties agreeing on the ID of an "escrow transaction", which has a separate, unrelated asset class. Then, they both put their assets "in escrow", which is to say, they spend them into a new transaction, the conditions of which depend on the output of the "escrow transaction". In the case of successful fulfillment, they are able to redeem the asset from the other. In the case of abort, they get their own asset back. So the escrow transaction provides atomicity.

I don't see any reason why multi-sig transactions would not be able to work with escrow transactions, so yes.

If you created an escrow transaction and attached assets to it, potentially you could query for all transaction outputs that depended on that escrow transaction. We do not have an index for that at this moment but it's within the realms of possibility. Same goes for the escrow transaction itself, it doesn't exist yet, but we're not too far off in terms of features.

**Comment by ttmc** [comment]
The interdependent transactions idea seems promising. TX2 would have to be submitted _after_ TX3 and TX4 are already in the network. Otherwise TX3 could be sent to the network but not TX4, or vice versa, and you lose atomicity (i.e. both TX3 and TX4 must be in the system and get unlocked at once). But then how do you have two transactions (TX3 and TX4) just hanging around in the system, waiting for a signed TX2 to show up? The BigchainDB of today will look at them and consider them invalid. If we put some kind of time condition, then it might consider them valid... but before it's time to do so (because TX2 hasn't showed up yet).

We had multi-asset transactions in the past, but they were removed circa the implementation of divisible assets. They could be brought back. Note how there's no need for a timeout condition. The one transaction is either valid or not. It either exchanges control of the assets or not.

A "hold account" is an interesting idea. What it would _be_ in BigchainDB? It can't be some "trusted third party" because blockchains are supposed to remove the need for trusted third parties. Maybe it's some internal "user" (with a keypair) known to all the nodes? One could transfer an asset to that user using a TRANSFER transaction, but there'd have to be some new way to specify the asset it's in exchange _for_, and also the time-until-abort. Who runs the hold-account "user"? Every node?

Note how the transfers from the hold account to the final recipients would, today, have to be done with two separate TRANSFER transactions (one to transfer the painting, one to transfer the currency).

The "hold account" idea would probably be the easiest to extend, e.g. to handling more complicated exchanges, such as an auction, e.g. where there's one painting sent to the hold account, and N bids (of currency), and when the auction ends, the painting gets transferred to the highest bidder, the highest bid currency gets transferred to the old painting owner, and all losing bidders get back control of their bid currency.

**Comment by ttmc** [comment]
It might make sense to start with support for multi-asset transactions, because those would even be useful for a "hold account" --- so that the hold account can transfer all the assets to their final owners/controllers in one transaction.

**Comment by diminator** [comment]
Another workaround is to have query-conditions. Where you could make a transaction available if other transactions already exist. There is a private fork for this. PM me ;-)
