### ISSUE TITLE
Do schema validation only when appropriate

### ISSUE THREAD

**Issue by libscott** [bigchaindb/bigchaindb#834]
#798 addresses schema validation, but it does not address sufficiently the question of when to do schema validation. In some cases it is not necessary, for example:

`Block.from_dict(block_body)`

This ticket is about addressing the questions:

* Should we do schema validation regardless of where a transaction dict is coming from, or only when the source may be unreliable?
* What should that look like? For example, `Block.from_dict` could call `Transaction.from_dict_novalidate`.

**Comment by sohkai** [comment]
Oh boy, `Block.from_dict(block_body)` does use `Transaction.from_dict`. If blocks are supposed to contain 1000 transactions, it'd take 4 seconds to create a block object. This is definitely not good.

Maybe we should hide the transaction validation under a flag for now (e.g. in `Transaction.from_dict`)?

**Comment by ttmc** [comment]
I like idea of adding a do-schema-validation flag to the `Transaction.from_dict` method.

**Comment by sbellem** [comment]
I think an important step like validation should stand on its own, and not be implicit. If it is implicit to a method or function, then the name of that method or function should be such that one may expect that some form of validation may happen.

A method name like `.from_dict()` does not necessarily convey the idea that it may as well validate the given `dict`.

For instance, we could have a method named `.is_valid()` or `.validate()` that needs to be called separately. Users of the API are then responsible to validate the model.

So it would have to be two step process:

1. Instantiate an object, using whatever approach provided by the interface, e.g.: `.__init__()`, `.from_dict()`, etc.
2. Call the validation method on the instance.

Validation, when needed is an important step and should be explicit I think.

Having explicit validation can also help troubleshooting code.

**Comment by ttmc** [comment]
@sbellem makes a good point: it's nicer to work with methods that do just one thing, with no side effects. `Transaction.from_dict()` could do just one thing: convert a dict to a Transaction object. There could be a separate utility function that takes a transaction dict as an input and checks its schema against our JSON schema for transactions.

Note: Currently, `Transaction.from_dict()` also checks the `id` of the incoming dict to make sure it's equal to the transaction hash. I wonder if it would make sense to move that check into a separate method as well.

**Comment by libscott** [comment]
I am quite against removing validation from `from_dict`:

* Increases the possibility of the API consumer running into undefined behavior (possibly exceptions, or getting your transaction rejected with a 400 by the server), because the data structure is in an illegal state.
* You'd never do this in C for example, because you would get segmentation faults. If you were going to do it, you'd put a big fat "UNSAFE" warning on it.

If you want a method that just does the import and no validation, do it the other way around.

**Comment by sohkai** [comment]
> Should we do schema validation regardless of where a transaction dict is coming from, or only when the source may be unreliable?

This is really a question of inputs and when we can be confident in them being structurally correct. A number of places that will likely need this sort of validation:

1. A client driver could be asked to locally validate a transaction's structure, if the user wants to be sure it's OK before sending a request to the HTTP API
1. The HTTP API should validate all incoming transactions' structures
1. The node that picks up a transaction from the backlog (and puts it in a block) should validate its structure
1. All voting nodes should validate a block's transactions against their structures (and in the future, the block structure itself).
1. A client receiving a transaction from the HTTP API could also validate its structure, to be safe.

==========

As for splitting out validation, I'd side with @libscott here. As long as it's properly documented to raise validation errors, I think it's OK. @sbellem notice how in the [link you gave for using `pyyaml.safe_load()`](https://security.openstack.org/guidelines/dg_avoid-dangerous-input-parsing-libraries.html), it notes:

> Many, but not all, of these libraries, offer safe interfaces that disable features that enable code execution. You always want to use the safe functions to load input. **Often the obvious function to use is not the safe one and we should check the documentation for libraries not covered here.**

Make the default, easy to reach function safe and let the user pick when he wants to be unsafe.

**Comment by sbellem** [comment]
I am not sure what we are talking about. My point about separating concerns of validation and instantiation was from the point of view of the server, only that, the server.

Again, I wish to emphasize that we are dealing with a client-server architecture. 

In the above comments, the two (clients and server) seem to be intermingled.

**Comment by sohkai** [comment]
>  the two (clients and server) seem to be intermingled [in concerns]

Because they are, especially in the code. If the two implementations were separated, then yeah, maybe there's a good case for separating out the concerns in the server, but as it stands, we don't have that separation and we shouldn't think about them separately.

**Comment by ttmc** [comment]
I think it would be okay if the `Transaction.from_dict` method is able to do schema validation, as an option (i.e. using a boolean flag in the input arguments), but to implement that it could just call a separately-defined staticmethod for transaction dict schema validation.

**Comment by sbellem** [comment]
> Because they are, especially in the code. If the two implementations were separated, then yeah, maybe there's a good case for separating out the concerns in the server, but as it stands, we don't have that separation and we shouldn't think about them separately.

My understanding was that we were going to separate the two. So why build on unclear foundations? We should first clarify the purpose and intent of the code in question. Otherwise we are building on shaky foundations that are subject to change, and this may cause serious loss of time.

So we should first clarify the purpose of the code in question. Is it meant to be used the server only, or is it meant to be used by both, the server and the python client? 

Clarifying the above could help clarify this issue.

**Comment by libscott** [comment]
It is used by both the server and the python client.

In the case of the python client, I would suggest that the default route to instantiation a Transaction from a dictionary should be safe.

In the case of the server, it should also be safe, but the kwarg `validate=False` suggested by @ttmc can also be passed, for example within the `Block.from_dict` method, in order to save CPU overhead.

The validation method in the common library is called `validate_structure`, in order to differentiate it from the `validate` method in `bigchaindb/models.py`, which performs a full validation, including database calls.

**Comment by sohkai** [comment]
From https://github.com/bigchaindb/bigchaindb/issues/834#issuecomment-261484728, I think it'd be likely that both the client and the server could do validation but for now I'd say it's only important for the server to be doing it (and certainly, this is all that I've thought about 😳). @libscott Maybe we should override `Transaction.from_dict()` in the server model to add the validation only to there for now?

Just for reference: a thought I had about being able to use the validation in both the server and the driver, if we were to move it out of common, was to make it a separate package that lives inside the bigchaindb repo. We could also provide a CLI to validate json blobs in this separate package.

**Comment by libscott** [comment]
> Just for reference: a thought I had about being able to use the validation in both the server and the driver, if we were to move it out of common, was to make it a separate package that lives inside the bigchaindb repo. We could also provide a CLI to validate json blobs in this separate package.

[bdb-transaction-cli](https://github.com/bigchaindb/bdb-transaction-cli) already depends on common, and is also a logical place to put a cli method to validate a transaction.

**Comment by libscott** [comment]
For now, schema validation has been removed from #798, so the scope of this discussion is to add it where appropriate, whether that be as part of `from_dict`, defaulting to `true` or `false` or a separate step.

**Comment by libscott** [comment]
Close by #880
