### ISSUE TITLE
Document how to build a valid tx using only crypto-conditions tools

### ISSUE THREAD

**Issue by ttmc** [bigchaindb/bigchaindb#840]
If someone wants to build a valid BigchainDB transaction, then they should be able to do so if they only have crypto-conditions tools (e.g. the [Java implementation of crypto-conditions](https://github.com/interledger/java-crypto-conditions)).

We should document how to do this. 

This is something any driver-writer will want to know how to do. Telling them to read the Python driver code is crude, because it (currently) uses a lot of the "common" code in the BigchainDB Server repo. Reading and translating all that (and ignoring the irrelevant stuff) might be quite challenging.

@libscott made some nice diagrams when he was writing some docs for the Command Line Transaction Tool; see https://docs.bigchaindb.com/projects/cli/en/latest/usage.html 

Once issue #839 is resolved, we'll also have a JSON Schema file that driver writers can use to do transaction schema validation.

**Comment by sohkai** [comment]
Now that we have the [handcrafting docs](https://docs.bigchaindb.com/projects/py-driver/en/latest/handcraft.html) in the driver, has this been resolved?

cc @sbellem

**Comment by sbellem** [comment]
No.

This needs to be on server side, and not dependent on any client whatsoever.

**Comment by ttmc** [comment]
@sbellem I recently wrote how to build a valid transaction in programming-language-independent terms, i.e. not assuming the use of Python, in the IPDB Protocol specification / docs:

https://the-ipdb-protocol.readthedocs.io/en/latest/transactions/construct-a-tx.html

It assumes they have libraries to do things such as crypto-conditions, JSON serialization, and SHA3-256 hashes.

Therefore I am closing this issue.
