### ISSUE TITLE
Is Metadata.id neccesary?

### ISSUE THREAD

**Issue by libscott** [bigchaindb/bigchaindb#852]
Do we need transaction metadata id? Is there a use case for it that can't be served by using `[txid].metadata`?

**Comment by ttmc** [comment]
What do you mean by `[txid].metadata`?

**Comment by libscott** [comment]
I mean, that you can use the transaction id to refer to the metadata, since they have a 1:1 relationship and the transaction contains the metada. So, `[txid]` gets you the transaction, and `.metadata` deferences the metadata inside the transaction:

```python
def get_metadata_by_txid(bigchain, txid):
    tx = bigchain.get_transaction(txid)
    return tx.metadata
```

**Comment by ttmc** [comment]
I mentioned this in person, but for the record:

What if someone wants to find all transactions with some particular metadata? For example, maybe someone sets the metadata data to "Submitted by Alex P. Goodwin of Beaverton." in every transaction that they submit. Now they want to find all transactions with that particular metadata data.

Admittedly, we don't have that today: the current metadata.id is random per transaction. It's not a hash of the metadata data. Is it possible to index the metadata data? AFAIK we allow arbitrary (nested) JSON in the metadata data so maybe indexing that isn't practical (or is it)?

**Comment by ttmc** [comment]
There's a related question: 

If we do get rid of the metadata id, then what's the point of having "metadata data" --- why not just have "metadata"?

**Comment by libscott** [comment]
Yep, that follows: https://github.com/bigchaindb/bigchaindb/commit/005ad5a93add96da9821c91790b9e13ae40c20c2
