### ISSUE TITLE
Vote's signature is stored in binary

### ISSUE THREAD

**Issue by TimDaub** [bigchaindb/bigchaindb#868]
I found this potential bug on branch: https://github.com/bigchaindb/bigchaindb/tree/docs/601/design-http-api
I don't think it's been solved in master (didn't test though). If so, great.

To reproduce:

- Run `bigchaindb start`
- Post a transaction
- Retrieve the votes table in the rethinkdb web interface:

```
{
    "id":  "b726da5d-0716-4f8e-a580-9e09763434c0" ,
    "node_pubkey":  "ErEeVZt8AfLbMJub25tjNxbpzzTNp3mGidL3GxGdd9bt" ,
    "signature": <binary, 88 bytes, "34 51 45 33 70 75..."> ,
    "vote": {
         "invalid_reason": null ,
        "is_block_valid": true ,
        "previous_block":  "6152fbc7e0f7686512ed6b92c01e8c73ea1e3f51a7b037ac5cc8c860215e7202" ,
        "timestamp":  "1480082692" ,
        "voting_for_block":  "e79204416a2e7490192bf50a827915ee4258680e09d61a19a25c25a44674a1b7"
    }
}
```

I'm not sure if it is supposed to be that signature is stored in binary. I guess not.

**Comment by ttmc** [comment]
Resolved by #869
