### ISSUE TITLE
Having some Difficulty Installing under Docker Windows

### ISSUE THREAD

**Issue by PrutenBoer** [bigchaindb/bigchaindb#88]
After the successful retrieval of:
**$ git clone git@github.com:bigchaindb/bigchaindb.git**

the attempted build gives:

**$ docker-compose build**
Building bigchaindb
Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "C:\projects\compose\compose\cli\main.py", line 55, in main
  File "C:\projects\compose\compose\cli\docopt_command.py", line 23, in sys_dispatch
  File "C:\projects\compose\compose\cli\docopt_command.py", line 26, in dispatch
  File "C:\projects\compose\compose\cli\main.py", line 174, in perform_command
  File "C:\projects\compose\compose\cli\main.py", line 195, in build
  File "C:\projects\compose\compose\project.py", line 246, in build
  File "C:\projects\compose\compose\service.py", line 678, in build
  File "c:\projects\compose\venv\lib\site-packages\docker\api\build.py", line 49, in build
  File "c:\projects\compose\venv\lib\site-packages\docker\utils\utils.py", line 103, in tar
  File "c:\python27-x64\Lib\tarfile.py", line 2021, in add
**IOError: [Errno 13] Permission denied: 'C:\\Users\\whoami\\AppData\\Local\\Google\\Chrome\\User Data\\Default\\Cache\\data_0'
docker-compose returned -1**

**Comment by r-marques** [comment]
Not a windows user, but this seems to be related to your setup of docker on windows.
Are you able to use `docker-compose` with other projects in windows?
Maybe you need admin rights to run `docker-compose`. Are you able to run the build on a terminal with admin rights?

@sbellem do you have any thoughts?

**Comment by sbellem** [comment]
Are you sure you can even use `docker-compose` on Windows, according to the [documentation of Docker](https://docs.docker.com/compose/install/), it isn't supported:

> You can run Compose on OS X and 64-bit Linux. It is currently not supported on the Windows operating system.

**Comment by sbellem** [comment]
But do not despair, since the docker-compose script we currently use is not complicated, and you could perform the same using `docker` by linking the two containers ... I will get back to you shortly with instructions on how to do so.

**Comment by Mec-iS** [comment]
I solved this limitation using Vagrant on Windows and provisioning a VM.
See "Installing on Vagrant" in the documentation. Vagrant provides a
Windows installer that runs ont top of VirtualBox or VMware.

Lorenzo Moriondo, from mobile
https://it.linkedin.com/in/lorenzomoriondo

**Comment by r-marques** [comment]
true @Mec-iS created a guide to install BigchainDB using Vagrant on windows https://bigchaindb.readthedocs.org/en/develop/installing.html#how-to-install-bigchaindb-on-a-vm-with-vagrant

**Comment by Mec-iS** [comment]
It's not a fix to the problem but can be a good turnaround if you need a
testing environment on Win. You can also share a directory between host and
guest filesystems and keep developing with your Win system while running
tests into the Linux machine. Never used in production a Win server though.

Lorenzo Moriondo, from mobile
https://it.linkedin.com/in/lorenzomoriondo

**Comment by PrutenBoer** [comment]
_**Are you able to run the build on a terminal with admin rights?**_

I issued the following in the quickstart bash shell:

**$ docker-machine env default --shell cmd**

which returned the following:

SET DOCKER_TLS_VERIFY=1
SET DOCKER_HOST=tcp://192.168.99.100:2376
SET DOCKER_CERT_PATH=C:\Users\whoami\.docker\machine\machines\default
SET DOCKER_MACHINE_NAME=default
REM Run this command to configure your shell:
REM     FOR /f "tokens=*" %i IN ('"C:\Program Files\Docker Toolbox\docker-machine.exe" env default --shell cmd') DO %i

I copied and pasted the FOR ... DO %i into a windows command prompt which the set those environment variables.

But now running:

**$ docker-compose build**

returns exactly the same error as in the original posting.

I then attempted the same procedure in a Windows 10 Administrative Command:

C:\Windows\system32>FOR /f "tokens=*" %i IN ('"C:\Program Files\Docker Toolbox\docker-machine.exe" env default --shell cmd') DO %i
**Error checking TLS connection: Host is not running**

**Comment by PrutenBoer** [comment]
Abandoned attempt to run under Docker on Windows.
Tried the solution suggested above using Vagrant on Windows.
It too fails following the procedure suggested by r-marques during execution of 'vagrant up'.
Relevant console snippets are:

...
==> default:     File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 1028, in run_setup
==> default:       raise DistutilsError("Setup script exited with %s" % (v.args[0],))
==> default:   distutils.errors.DistutilsError: Setup script exited with error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
==> default:
==> default:   ----------------------------------------
==> default:   Failed cleaning build dir for cryptography
...
==> default:   creating build/temp.linux-x86_64-3.4/c
==> default:   x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -fPIC -DUSE__THREAD -I/usr/include/ffi -I/usr/include/libffi -I/usr/include/python3.4m -c c/_cffi_backend.c -o build/temp.linux-x86_64-3.4/c/_cffi_backend.o
==> default:   c/_cffi_backend.c:15:17: fatal error: ffi.h: No such file or directory
==> default:    #include <ffi.h>
==> default:                    ^
==> default:   compilation terminated.
==> default:   error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
==> default:
==> default:   ----------------------------------------
==> default:   Failed building wheel for cffi
...
==> default: Successfully built bigchaindb rethinkdb pysha3 python-rapidjson logstats base58 bitcoin pycparser
==> default: Failed to build cryptography cffi
==> default: Installing collected packages: rethinkdb, pysha3, pytz, idna, pyasn1, pycparser, cffi, cryptography, statsd, python-rapidjson, logstats, base58, bitcoin, bigchaindb
...
==> default:     x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -fPIC -DUSE__THREAD -I/usr/include/ffi -I/usr/include/libffi -I/usr/include/python3.4m -c c/_cffi_backend.c -o build/temp.linux-x86_64-3.4/c/_cffi_backend.o
==> default:     c/_cffi_backend.c:15:17: fatal error: ffi.h: No such file or directory
==> default:      #include <ffi.h>
==> default:                      ^
==> default:     compilation terminated.
==> default:     error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
...
