### ISSUE TITLE
Plugin or hook architecture e.g. for validate_transaction

### ISSUE THREAD

**Issue by ttmc** [bigchaindb/bigchaindb#90]
In the [bigchaindb/bigchaindb chat room on Gitter](https://gitter.im/bigchaindb/bigchaindb), @thedoctor asked an interesting question: 

> ...the question I was getting at is whether folks thought a plugin or hook architecture would be of general utility? I'm imagining hooks in key places in `Bigchain` – at least `validate_transaction` and `validate_block`. It would be easy for the community to contribute arbitrary consensus plugins. Make sense?

I know there has been some internal discussion about that idea (i.e. at ascribe GmbH) and said as much on Gitter. I wonder how doable it is, or if there are any big gotchas. I said I'd open an issue about it on GitHub (i.e. _this_ issue). Any thoughts @r-marques @diminator @vrde @andreasATascribe ?

@thedoctor replied:

> Cool – I'll wait for some design discussion there [on GitHub] then I'm happy to implement it and PR.

Great!

**Comment by r-marques** [comment]
The consensus protocol will probably be one of the most difficult parts in bigchaindb so it will be important for us to try to decouple it from the rest of the code as much as possible, so that we can improve it or enhance it without interfering with the rest of the code. So in the end ideally we would have a consensus layer that would be a plug able plugin

**Comment by ttmc** [comment]
Maybe @thedoctor could start by writing a different version of `validate_transaction`, with extra bells and whistles for some particular kind of transaction. The idea is that it's easier to generalize from a couple of examples.

**Comment by thedoctor** [comment]
So if this is a good idea, then some things we should probably discuss:
1. What operations are delegated to the consensus plugin?
  * Are there parts of the consensus process that are considered fundamental and should be kept in core?
    * e.g. Is the requirement that secp256k1 is used for signatures just a consensus rule? (I think so) 
    * On the other hand, what about the serialization scheme? (That seems reasonable to standardize)
2. What data is exposed to a plugin? It's probably unwise to expose rethink itself as that would make database optimization difficult.
3. How are plugins invoked? Naively, I would suggest pulling out the existing functionality into a base plugin from which other plugins could inherit and delegating consensus-related functions to that object.
4. Should we provide a mechanism for chaining plugins like middleware or leave it to the developers to compose their functionality?

**Comment by ttmc** [comment]
@thedoctor It's not clear to me what you have in mind. Maybe if you write some code and submit a pull request (including explanations of various decisions), we could have a more concrete understanding. 

We have a [CONTRIBUTING.md file](https://github.com/bigchaindb/bigchaindb/blob/develop/CONTRIBUTING.md) to explain the process to submit a pull request. Feel free to ask questions.

**Comment by thedoctor** [comment]
Sure, I'll put together something demonstrative this week.

**Comment by thedoctor** [comment]
Sample PR referenced above – let me know if it makes sense.

**Comment by ttmc** [comment]
I think this was largely resolved by PR #99. Future changes and improvements to modular consensus can be proposed in new issues so I will close this one.
