### ISSUE TITLE
Remove remaining RethinkDB query in block pipeline

### ISSUE THREAD

**Issue by sohkai** [bigchaindb/bigchaindb#900]
I think we more or less know about this one, but I'm not sure if we have a good abstraction for this.

**Required for database abstraction.**

See https://github.com/bigchaindb/bigchaindb/blob/master/bigchaindb/pipelines/block.py#L143.

**Comment by vrde** [comment]
We don't need to port this! :princess: #876

**Comment by sohkai** [comment]
Fixed with #903.
