### ISSUE TITLE
Improper conftest.py import

### ISSUE THREAD

**Issue by rhsimplex** [bigchaindb/bigchaindb#911]
Per @sbellem's comment in #614:

> A [pytest note](https://pytest.org/dev/plugins.html) about the practice of importing "stuff" from a `conftest.py` module:
> 
> > **Note**
> > 
> > If you have conftest.py files which do not reside in a python package directory (i.e. one containing an `__init__.py`) then “`import conftest`” can be ambiguous because there might be other `conftest.py` files as well on your `PYTHONPATH` or `sys.path`. It is thus good practise for projects to either put `conftest.py` under a package scope or to never import anything from a `conftest.py` file.
> 
> ref: https://pytest.org/dev/plugins.html

See: https://github.com/bigchaindb/bigchaindb/blob/master/tests/integration/conftest.py#L5

**Comment by sbellem** [comment]
Most of it if not all was resolved via #954.

Need to double check if anything has  been missed, and if so should be cleared by #966.

**Comment by sohkai** [comment]
@sbellem AFAIK, all the `import conftest`s have been removed. Can we close this?

**Comment by sbellem** [comment]
yes
