### ISSUE TITLE
bigchain_benchmark.py doesn't load transactions properly in virtualenv

### ISSUE THREAD

**Issue by rhsimplex** [bigchaindb/bigchaindb#92]
the `bigchain-benchmark load` command doesn't seem to respect virtualenv fully.  For instance, after setting everything up (rethinkdb running) the following fails:

```python
(env)ryan@ryan: bigchaindb (develop) $ bigchain-benchmark load
Traceback (most recent call last):
  File "/home/ryan/anaconda/bin/bigchain-benchmark", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/home/ryan/anaconda/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3141, in <module>
    @_call_aside
  File "/home/ryan/anaconda/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3127, in _call_aside
    f(*args, **kwargs)
  File "/home/ryan/anaconda/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3154, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/home/ryan/anaconda/lib/python2.7/site-packages/pkg_resources/__init__.py", line 640, in _build_master
    ws.require(__requires__)
  File "/home/ryan/anaconda/lib/python2.7/site-packages/pkg_resources/__init__.py", line 941, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/home/ryan/anaconda/lib/python2.7/site-packages/pkg_resources/__init__.py", line 828, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'Bigchain' distribution was not found and is required by the application
```

The virtualenv is python 3.4, but the traceback references my Anaconda 2.7 installation.  On the other hand, this works:

```
(env)ryan@ryan: bigchaindb (develop) $ python bigchaindb/commands/bigchain_benchmark.py load
INFO:bigchaindb.config_utils:Configuration loaded from `/home/ryan/.bigchaindb`
INFO:__main__:Starting 1 processes
INFO:logstats.base:transactions: 100, transactions.speed: 100
INFO:logstats.base:transactions: 240, transactions.speed: 140
INFO:logstats.base:transactions: 374, transactions.speed: 134
INFO:logstats.base:transactions: 503, transactions.speed: 129
...
```

**Comment by ttmc** [comment]
Yeah, Conda and virtualenv do not play nicely together. I ran into a similar issue with running pytest. The solution, as you found, is to explicitly call the Python 3.4 interpreter.

Actually, I don't use virtualenv at all. I use Conda virtual environments instead, e.g.
```text
conda update conda
conda create -n bcdb python=3.4
source activate bcdb
```

The second command above creates a Conda virtual environment named `bcdb`, and when that's active, the `python` interpreter is a Python 3.4 interpreter.

**Comment by rhsimplex** [comment]
@vrde any ideas? Does this spawn a process that might ignore virtualenv?

**Comment by vrde** [comment]
@rhsimplex you should use `bigchaindb-benchmark`, not `bigchain-benchmark`. The latter was the old name of the script, but it was changed since `v0.1.0`. You might uninstall the old scripts, namely `bigchain` and `bigchain-benchmark`, with
 - ``rm `which bigchain` ``
 - ``rm `which bigchain-benchmark` ``

**Comment by ttmc** [comment]
Heh, now I'm kicking myself that I didn't notice the "bigchain" rather than "bigchaindb"
