### ISSUE TITLE
In BigchainDB server docs, Data Models->Crypto-Conditions and Fulfillments, there should be a Multiple Current Owner section 

### ISSUE THREAD

**Issue by utarl** [bigchaindb/bigchaindb#921]
In the BigchainDB server docs: https://docs.bigchaindb.com/projects/server/en/latest/data-models/crypto-conditions.html#fulfillments
it should also have a Multiple Current Owner section.

**Comment by utarl** [comment]
I am trying to add it.

**Comment by ttmc** [comment]
I'm really not the right person to add that. Maybe @libscott

**Comment by utarl** [comment]
I wrote some, is it OK? :) @ttmc @libscott @sohkai 
### Multiple Current Owners

If there are Multiple _current owners_, the fulfillment will be a little different from One Current Owner (Suppose it has two current owners).

```json
{
    "owners_before": ["<public key of the first owner before the transaction happened>","<public key of the second owner before the transaction happened>"],
    "fulfillment": "cf:2:AQIBAgEBYwAEYEv6O5HjHGl7OWo2Tu5mWcWQcL_OGrFuUjyej-dK3LM99TbZsRd8c9luQhU30xCH5AdNaupxg-pLHuk8DoSaDA1MHQGXUZ80a_cV-4UaaaCpdey8K0CEcJxre0X96hTHCwABAWMABGBnsuHExhuSj5Mdm-q0KoPgX4nAt0s00k1WTMCzuUpQIp6aStLoTSMlsvS4fmDtOSv9gubekKLuHTMAk-LQFSKF1JdzwaVWAA2UOv0v_OS2gY3A-r0kRq8HtzjYdcmVswUA",
    "input": {
        "cid": 0,
        "txid": "e4805f1bfc999d6409b38e3a4c3b2fafad7c1280eb0d441da7083e945dd89eb8"
    }
}
```

- `owners_before`: A list of public keys of the owners before the transaction; in this case it has two owners, hence two public keys.
- `fulfillment`: A crypto-conditions URI that encodes the cryptographic fulfillments like signatures and others;'cf' indicates this is a fulfillment, '2' indicates the condition type is THRESHOLD-SHA-256 (while '4' in One Current Owner indicates its condition type is ED25519).
- `input`: Pointer to the asset and condition of a previous transaction
    - `cid`: Condition index - the index of the condition in the array of conditions in the previous transaction
    - `txid`: Transaction id

**Comment by libscott** [comment]
Hi @utarl, thanks for this! I will be looking at it very soon and probably use yours as a template.

**Comment by utarl** [comment]
Hi @libscott , I want to be a contributor, but I submit the Contributor License Agreement, but didn't receive any mails, can you give me more guides to be a contributor?

**Comment by sbellem** [comment]
Hi @utarl, sorry for the delays. We'll make sure you can contribute as soon as possible.

**Comment by ttmc** [comment]
Hi @utari - I get the email when someone submits the BigchainDB Contributor License Agreement form. Unfortunately, I was away on vacation at the time and I just returned. I just sent you an email about how to do the last step of agreeing to the CLA.

Once you do that last step, you may want to submit a pull request making the above-proposed change to the BigchainDB documentation. If you prefer for @libscott to do that, then please say so in the comments on this issue (i.e. below).

**Comment by utarl** [comment]
BEGIN BLOCK

This is to confirm that I agreed to and accepted the BigchainDB Individual Contributor Agreement at https://www.bigchaindb.com/cla/ and to represent and warrant that I have authority to do so.

MgFoeuv2DdKVgpSaXEjrEUQJTXbqfC2yFPKUwwyiG8tdk0TYeANjMw6lQNtixtR

END BLOCK

**Comment by ttmc** [comment]
Thanks @utarl 

Would you like to make a pull request to add your suggested text to our BigchainDB server docs, or would you prefer if one of us did it?

**Comment by utarl** [comment]
Hi @ttmc 
I created a pull request about this.
https://github.com/bigchaindb/bigchaindb/pull/1017

Please help to review it. Thank you.
