### ISSUE TITLE
Tools & features to support benchmarking under realistic loads

### ISSUE THREAD

**Issue by ttmc** [bigchaindb/bigchaindb#94]
To test and benchmark BigchainDB under realistic loads, we need some additional tools & features:

- [ ] tools to generate realistic transactions, for various applications
- [ ] tool to read files of test transactions from files
- [ ] tool to deploy a large number of testing _clients_ and have them send requests to a test cluster
- [ ] ? a tool to bulk-upload realistic transactions directly into the backlog table of a test cluster?
- [ ] Integration of the above tools with our existing benchmarking tools and features

**Comment by ttmc** [comment]
Maybe this is too much to put in one issue. 

@r-marques do you think it would be a good idea if i split it apart into a bunch of separate issues, maybe with a common GitHub Label, such as "testing" (doesn't exist yet)?

**Comment by r-marques** [comment]
@ttmc I agree. That would also make it easier to then review the pull requests

**Comment by ttmc** [comment]
Okay I will go ahead and do that now. Once the new issues exist, I will close this one.

**Comment by r-marques** [comment]
great :+1:

**Comment by ttmc** [comment]
Okay I created Issue #111, #112, #113, #114 to replace this issue. I'm closing this issue.
