### ISSUE TITLE
Separate transaction schema into different schemas for different operations

### ISSUE THREAD

**Issue by sohkai** [bigchaindb/bigchaindb#946]
With `oneOf`, we may be able to provide more specific schema definitions for each operation (e.g. `CREATE`, `TRANSFER`, `GENESIS`).

There's a few things to think about as to how to actually achieve this breakdown, and if we'd like to commit to it.

**Comment by r-marques** [comment]
@libscott this was handled in #1257, right?

**Comment by ttmc** [comment]
There _are_ separate JSON Schema files for CREATE/GENESIS and TRANSFER transactions, so I'm closing this issue.
