### ISSUE TITLE
Rename configuration's database.name to database.dbname

### ISSUE THREAD

**Issue by sohkai** [bigchaindb/bigchaindb#949]
`dbname` is a more obvious name than `name` for what this option actually does.

This will also allow us to fix the signature of `backend.connect()` so that `backend.connect()` is equivalent to `backend.connect(**bigchaindb.config['database'])` ([see related comment](https://github.com/bigchaindb/bigchaindb/pull/939#discussion_r92162224)).

**Comment by sohkai** [comment]
As @sbellem  noted, `database.dbname` might not be the best approach in the long-run. We can revisit this when we look at the configuration in more depth.

One option is to rename the `database` and `database.backend` fields:

```js
{
     'backend': {
        'database': 'rethinkdb',
        'dbname': '...',
    }
}

**Comment by sbellem** [comment]
It seems that we are trying to solve different problems, and that the solution may affect different types of users (e.g.; sys admins of BigchainDB, versus core developers of BigchainDB).

1. How the configuration should be, which is something that a sys admin would have to deal with.
2. How convenient it is to read, and pass config values internally to various interfaces, e.g.: `backend.connect()`. This, seems to be a core developer's concern.

It appeared to me as I was going to tackle this issue that the proposed renaming introduces redundancy and makes the config look slightly awkward, from the point of view of a sys admin. 

We currently have something that looks like;

```bash
$ bigchaindb show-config
{
    "database": {
        "backend": "rethinkdb",
        "host": "localhost",
        "name": "bigchain",
        "port": 28015
    },
    # ...
}
```

the renaming will make the config look like

```bash
$ bigchaindb show-config
{
    "database": {
        "backend": "rethinkdb",
        "host": "localhost",
        "dbname": "bigchain",
        "port": 28015
    },
    # ...
}
```

Furthermore, accessing the database name would look like;

```python
config['database']['dbname']
```

instead of:

```python
config['database']['name']
```

**Comment by sbellem** [comment]
I added @krish7919 as he may have useful insights relating to the point of view of sys admins, and system integrators.

**Comment by sbellem** [comment]
Just to be clear, I do not wish to oppose the current renaming. I simply wish to bring a few considerations forward, such that it may help nourish further discussions on the topic.

**Comment by sbellem** [comment]
> dbname is a more obvious name than name for what this option actually does.

I do not understand the point here, since "name" is namespaced under "database".

**Comment by sbellem** [comment]
> This will also allow us to fix the signature of backend.connect() so that backend.connect() is equivalent to backend.connect(**bigchaindb.config['database'])

Why is this so important to be able to do so? But granted it is crucial to be able to pass the config around in this manner, I propose we instead have a config loader that creates a config object the core code internally needs.

In brief, I propose that we decouple the configuration as it appears externally from the configuration as it is represented internally. The two do not need to be identical, as the needs may differ.

**Comment by sbellem** [comment]
Perhaps a bit of terminology review could help with this issue. From wikipedia's entry on **Database**, under the section [Terminology and overview](https://en.wikipedia.org/wiki/Database#Terminology_and_overview):

> Formally, a "database" refers to a set of related data and the way it is organized. Access to this data is usually provided by a "database management system" (DBMS) consisting of an integrated set of computer software that allows users to interact with one or more databases and provides access to all of the data contained in the database (although restrictions may exist that limit access to particular data). The DBMS provides various functions that allow entry, storage and retrieval of large quantities of information and provides ways to manage how that information is organized.

and this sentence is important:

> Because of the close relationship between them, the term "database" is often used casually to refer to both a database and the DBMS used to manipulate it.

So if we take another look at our configuration with the above in mind:

```bash
{
    "database": {
        "backend": "rethinkdb",
        "host": "localhost",
        "name": "bigchain",
        "port": 28015
    },
    # ...
}
```

`"backend"` refers to what the DBMS is, whereas`"name"` is the name of the database as per the terminology above.

With this in mind renaming `"name"` to `"dbname"` is not necessary, and redundant.

**Comment by ttmc** [comment]
Why is the database "name" (or "dbname") in the set of BigchainDB configuration settings anyway? Can't the database always have the same name (i.e. "bigchain")? Do we ever make use of the ability to change the database name, maybe in tests (so we can have two databases running on the same machine at the same time)?

**Comment by r-marques** [comment]
Yes we do use this functionality so that we can run the tests in parallel and yes this would also allow us to run multiple bigchaindb instances in the same database
