### ISSUE TITLE
BigchainDB not found in Node Deployment on Azure

### ISSUE THREAD

**Issue by jln1989** [bigchaindb/bigchaindb#951]
Hi,

I was trying to test bigchain db on azure and i was trying to follow the github link [https://docs.bigchaindb.com/projects/server/en/latest/cloud-deployment-starter-templates/template-azure.html](Bigchain-Azure). I was not able to find BigchainDB in the available list of blockchain DBs.

Can someone help me on th same?

**Comment by ttmc** [comment]
@jln1989 Sorry about that: after BigchainDB v0.8.0 got released, the BigchainDB Azure Quickstart Template got moved to a different directory in that GitHub repository. You can find the new location and the new instructions at https://docs.bigchaindb.com/projects/server/en/master/cloud-deployment-starter-templates/azure-quickstart-template.html  (i.e. the docs from the bleeding-edge `master` branch of bigchaindb).

Unfortunately, that template isn't working fully correctly at the moment, and we're working with Microsoft to figure out why. Therefore, for the time being, my advice would be to deploy AWS instead. We have scripts to deploy an entire BigchainDB cluster on AWS; the documentation for those is at:

https://docs.bigchaindb.com/projects/server/en/master/clusters-feds/aws-testing-cluster.html
