### ISSUE TITLE
Permissioning system in BigchainDB

### ISSUE THREAD

**Issue by iamdebu** [bigchaindb/bigchaindb#956]
Is there any utility to setup group, send email notification or setup permission in transaction level from BigchainDB? or we have to use RethinkDB to do that?

I can't find any documentation regarding that .

**Comment by ttmc** [comment]
Currently there is no utility to setup groups or send email notifications, and there are no plans to do that any time soon. As for permissions, I believe I already answered that question on Gitter; see:

https://gitter.im/bigchaindb/bigchaindb?at=5853af67589f411830efb8b2
