### ISSUE TITLE
Add flush data function(s) to backend schema

### ISSUE THREAD

**Issue by sbellem** [bigchaindb/bigchaindb#967]
e.g.:

```python
# bigchaindb/backend/schema.py file
def flush(connection, dbname);
    """Flushes all data from ``dbname``."""
```

Functionality to cleanup the tables.

Needed by the tests for the teardown.

- [ ] generic function
- [ ] rethinkdb function
- [ ] mongodb function

**Comment by r-marques** [comment]
what is the difference between this and simply deleting the database?

**Comment by sbellem** [comment]
> what is the difference between this and simply deleting the database?

We keep the database, and tables, and just delete the content, so it's faster to run tests.

**Comment by sbellem** [comment]
Putting this aside for now. Tests will use their own functions.
