### ISSUE TITLE
Proposal: Signing of partial tx vs signing of txid

### ISSUE THREAD

**Issue by libscott** [bigchaindb/bigchaindb#970]
Currently, in order to sign each input to a TX we do a little dance whereby for each input, the payload to be signed is a partial transaction is created containing only that input + the other contents of the transaction:

## Option A (current)

```python
for index, input_ in enumerate(self.inputs):                         
    # NOTE: We clone the current transaction but only add the output 
    #       and input we're currently working on plus all            
    #       previously signed ones.                                  
    tx_partial = Transaction(self.operation, self.asset, [input_],   
                             self.outputs, self.metadata,            
                             self.version)                           
                                                                     
    tx_partial_dict = tx_partial.to_dict()                           
    tx_partial_dict = Transaction._remove_signatures(tx_partial_dict)
    payload = Transaction._to_str(tx_partial_dict)             
    self._sign_input(input_, index, payload, key_pairs)        
```

This has the properties:

* ID of the transaction being signed is **not** part of the signature.
* Person signing cannot verify the other inputs to their transaction, since the transaction is malleable in it's inputs.
* "I authorize this transaction with these outputs and this metadata to spend this output" - does not cover the whole transaction.
* Signature for one output cannot be used for another output.

## Option B (proposed, hash then sign)

The other option would be that for each input, the payload to be signed is a tuple of `(txid, fulfills)`:

```python
for index, input_ in enumerate(self.inputs):
    payload = serialize((txid, input_.fulfills))
    self._sign_input(input_, index, payload, key_pairs)
```

Has the properties:

* ID of the transaction being signed **is** part of the signature.
* Person signing can therefore sign given only the `(txid, fulfills)` tuple, if they accept.
* Person signing can also validate the entire transaction body since they must have the txid in order to sign.
* Signature for one output cannot be used for another output.
* Signatures depend on transaction ID and thus nothing can change.

**Comment by diminator** [comment]
I'm in for Option B - as it manages expectations better...

maybe include @TimDaub since he has implemented the common portion?

**Comment by sohkai** [comment]
Also vote for option b, we had a brief discussion about it earlier but couldn't think anything reason to make it not feasible (again, @TimDaub will know best why it was implemented this way...).

A third potential option that @ttmc suggested was to only create the TX's id once you've gathered all the fulfillment signatures, so that the process of signing the fulfillment and obtaining the TX id is simple. This might have a problem with determining what to use to sign the fulfillment though (if it uses everything in the transaction, the order that the fulfillments were signed would matter?).

**Comment by r-marques** [comment]
I am ok with option B assuming that the txid is always correctly validated and that signatures are specific to a single output and cannot be reused.

**Comment by libscott** [comment]
> This might have a problem with determining what to use to sign the fulfillment though (if it uses everything in the transaction, the order that the fulfillments were signed would matter?).

You could take the same approach, collect the signatures separately, once you have them all, apply them all to the TX and hash to get the ID.

## Option C (Sign then hash)

```python
tx_body = self.to_dict()
tx_body.pop('id')
for index in range(len(self.inputs)):
    tx_body['inputs'][i].fulfillment = None

for index, input_ in enumerate(self.inputs):
    payload = serialize((tx_body, input_.fulfills))
    self._sign_input(input_, index, payload, key_pairs)

```

Same as Option B, except signer doesn't have to know txid, potentially until their output is spent and they see which transaction spent it.

I don't know which is better. I prefer Option B... I'd prefer to know the `txid` before signing, maybe it's important in some scenario?

**Comment by r-marques** [comment]
After thinking a bit more about this issue this is what in my opinion will change.

For a technical point of view nothing really changes. Signing a message or signing the hash of the message is basically the same. The difference is that signing only an hash is more efficient.

For a ux point of view there are some important changes. Before we enforced that the client had to have the entire transaction payload in order to fulfill a condition, so the client was signing a message saying "I am transfering this output to this public key.

With this new solution this no longer happens and since the client is not required to have the transaction payload to fulfill a condition what the client is doing is something like "Here is my fulfilled condition, do whatever you want with it."

Instead of enforcing we are now expecting the client to do the right thing and retrieve and check the transaction payload before fulfilling it.

**Comment by libscott** [comment]
> Before we enforced that the client had to have the entire transaction payload in order to fulfill a condition, so the client was signing a message saying "I am transfering this output to this public key.

That's not quite right, the client didn't necessarily see which were the other inputs to a transaction, or the TXID, they just saw their own inputs and the outputs.

I don't think that there's alot of difference in terms of performance between signing a hash and signing a tx payload. Signing the entire TX payload, including the TXID, in this case achieves the same thing and is foolproof, ie it protects the client from signing a TX they have not had the chance to inspect. And it's alot more efficient than generating partial transactions to sign.

**Comment by libscott** [comment]
@TimDaub @r-marques @ttmc 

Revisiting this because it's on the radar for 1.0.

Having slept on it, my preference is any of:

* Sign TXID only
* Sign entire transaction payload including TXID (address the UX issue mentioned by @r-marques)

Thoughts?

**Comment by diminator** [comment]
I might have found a related bug:
when a message to sign is created from a partial transaction,  a new `tx.id` is hashed, whilst in my opinion the partial messages should have the orginal `tx.id`
```python
tx_partial = Transaction(self.operation, self.asset, [input_],   
                             self.outputs, self.metadata,            
                             self.version)     
# <proposed change>
tx_partial.id = self.id
# </proposed change>
tx_partial_dict = tx_partial.to_dict()                           
tx_partial_dict = Transaction._remove_signatures(tx_partial_dict)
```

**Comment by libscott** [comment]
That's not a bug strictly speaking that's just how it works.

**Comment by r-marques** [comment]
Looking at this again I am ok with Option B.
Some notes:

- We need to make sure that the signature/fulfillment for each output is unique. This one is obvious but something to keep in mind.
- The signature validation should happen only after the txid has been validated. The signature of the txid being valid is not enough, we need to validate the txid to make sure the client signed the correct message.

**Comment by diminator** [comment]
> That's not a bug strictly speaking that's just how it works.

It's an undocumented specification (and can be found multiple times duplicated in the code BTW)

Also, it's kinda useless to spend computational resources on a hash that you won't use for integrity checking

**Comment by libscott** [comment]
@diminator ok fair enough. Are you ok with the signer signing `(serialize(tx.to_dict()), fulfills)` as the payload? That way they see everything they are signing.

**Comment by diminator** [comment]
would that then disallow independent input signing? just wondering if that's an issue

**Comment by libscott** [comment]
It doesn't include a change to cryptoconditions, so (provided appropriate library support is there), signing parties will still be able to provide signatures independently of each other given a message to sign (which is the body of the full transaction, and the (txid,output) tuple of the output they are spending.

**Comment by libscott** [comment]
Closing as #1225 has been approved
