### ISSUE TITLE
Refactor the structure of a transaction

### ISSUE THREAD

**Issue by vrde** [bigchaindb/bigchaindb#98]
The current schema of a transaction is the following:
```json
{
    "id": "<sha3 hash>",
    "transaction": {
        "current_owner": "<pub-key>",
        "new_owner": "<pub-key>",
        "input": "<sha3 hash>",
        "operation": "<string>",
        "timestamp": "<timestamp>",
        "data": {
            "hash": "<SHA3-256 hash hexdigest of payload>",
            "payload": { }
        }
    },
    "signature": "<signature of the transaction>"
}
```
(for more information about the fields check out [the docs](https://bigchaindb.readthedocs.org/en/develop/models.html#the-transaction-model))

We can reorganize some keys in the schema to have a simpler structure, like:
```json
{
    "id": "<sha3 hash>",
    "payload_id": "<sha3 hash of transaction.payload>",

    "transaction": {
        "from": "<pub-key>",
        "to": "<pub-key>",
        "input": "<sha3 hash>",
        "operation": "<string>",
        "timestamp": "<timestamp>",
        "payload": { }
    },

    "signature": "<signature of the transaction>"
}
```

The idea is to have an easier to use, less nested dictionary.

The proposed changes are:
 - move `transaction.data.hash` to `payload_id` to make clearer that it is an index
 - move `transaction.data.payload` to `transaction.payload` to keep the structure less nested
 - remove `transaction.data` since it'd be empty
 - rename `transaction.current_owner` to `transaction.from` to keep the name of the field time-agnostic
 - rename `transaction.new_owner` to `transaction.to` to keep the name of the field time-agnostic

**Comment by r-marques** [comment]
seems good to me :+1:

**Comment by ttmc** [comment]
Yes :+1:

**Comment by sbellem** [comment]
:+1:

**Comment by r-marques** [comment]
This needs to be revisited. Since this issue was created we completely changed the structure of the transaction and also added multiple inputs/outputs.

The renaming of `current_owner`, `new_owner` should be handled in #348 

Regarding the payload we will have a clearer idea of what to do in #391 

@vrde should we close this?
