### ISSUE TITLE
Clean up or remove outdated monitoring tools

### ISSUE THREAD

**Issue by sohkai** [bigchaindb/bigchaindb#990]
There's a number of outdated pieces of monitoring code left across the repo.

Questions:

- Do we need it?
- Will we still be using our old monitoring strategy into the future or use a different one?

**Comment by krish7919** [comment]
I have thoughts on how an stats and/or internal metrics exporter module might look like.
WIll discuss with @ttmc and decide on an action plan.

**Comment by ttmc** [comment]
@krish7919 We certainly _want_ monitoring tools, but I think @sohkai created this issue to clean up the old and broken (but how broken?) cluster monitoring system that Ryan wrote and described in:

https://docs.bigchaindb.com/projects/server/en/v0.8.0/clusters-feds/monitoring.html

I honestly don't know how broken that system is. Maybe it's just better to remove it for now and to create one or more new issues about monitoring systems (which _are_ on the roadmap).

**Comment by krish7919** [comment]
@ttmc Yes, sure. The cleanup can be one phase, and adding support for new performance/benchmarking metrics can be the second phase.

**Comment by r-marques** [comment]
Cleanup monitoring related:
- [ ] code
- [ ] configuration (file and envs)
- [ ] documentation
- [ ] docker files
- [ ] dependencies (setup.py)
