### ISSUE TITLE
Revisit mongodb primary key

### ISSUE THREAD

**Issue by r-marques** [bigchaindb/bigchaindb#992]
MongoDB primary key is `_id` while for rethinkdb its `id`

When using rethinkdb we are overriding the `id` field itself while with MongoDB we are not actually using the `_id` field but we create a new one called `id`.
This makes it easier to do schema validation although sometimes we need to pop the `_id` field of mongodb documents. It also forces us to create an additional secondary index of the `id` field.

Can we change the name of the primary key on mongodb?
Can we set the primary key to any value we want?
Do we care about some properties of the primary key of mongodb like incremental ids, ...?

**Comment by sohkai** [comment]
When we were working on the database abstraction, we briefly thought about allowing database representations of transactions (and other data) to be different than what we internally work with (and output to clients).

This originated from some sketches of how we'd work with relational, non-document databases, which would have to model the data differently, but is starting to sound like a useful proposal for dealing with constraints like MongoDB's primary key being an `_id` field ([see also](https://github.com/bigchaindb/bigchaindb/issues/1033#issuecomment-271631509)).

**Comment by libscott** [comment]
> Can we change the name of the primary key on mongodb?

A brief googling suggests that we can't. `_id` is fixed in Mongo.

> Can we set the primary key to any value we want?

Yes, we could override it with our own ID. This would save us the extra secondary index on "id", I suppose?
